object frmLicWiz4: TfrmLicWiz4
  Left = 333
  Top = 113
  HelpContext = 1007
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'CD Licencing Wizard - Step 4 of 5'
  ClientHeight = 635
  ClientWidth = 714
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = True
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
  object Label2: TLabel
    Left = 8
    Top = 3
    Width = 288
    Height = 29
    AutoSize = False
    Caption = 'Optional Modules'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -24
    Font.Name = 'Times New Roman'
    Font.Style = [fsBold, fsItalic]
    ParentFont = False
  end
  object Label3: TLabel
    Left = 8
    Top = 33
    Width = 532
    Height = 18
    AutoSize = False
    Caption = 
      'Specify the optional modules to be made available for installati' +
      'on and their Release Code status.'
    WordWrap = True
  end
  object btnNext: TButton
    Left = 630
    Top = 81
    Width = 80
    Height = 21
    Caption = '&Next >>'
    TabOrder = 2
    OnClick = btnNextClick
  end
  object btnPrevious: TButton
    Left = 630
    Top = 55
    Width = 80
    Height = 21
    Caption = '<< &Previous'
    TabOrder = 1
    OnClick = btnPreviousClick
  end
  object ScrollBox1: TScrollBox
    Left = 7
    Top = 56
    Width = 618
    Height = 572
    VertScrollBar.Visible = False
    PopupMenu = PopupMenu1
    TabOrder = 0
    object lblCISRCTHed: Label8
      Left = 6
      Top = 261
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'CIS/RCT'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object lblASAHed: Label8
      Left = 6
      Top = 3
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Account Stock Analysis'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel1: TBevel
      Left = 4
      Top = 23
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object Label81: Label8
      Left = 6
      Top = 195
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Importer'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel3: TBevel
      Left = 4
      Top = 215
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object Bevel4: TBevel
      Left = 4
      Top = 279
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object Label84: Label8
      Left = 6
      Top = 283
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'ODBC'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel5: TBevel
      Left = 4
      Top = 303
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblReportWriter: Label8
      Left = 6
      Top = 403
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Report Writer'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel6: TBevel
      Left = 4
      Top = 423
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblTeleHed: Label8
      Left = 6
      Top = 454
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Telesales'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel7: TBevel
      Left = 4
      Top = 473
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object Label87: Label8
      Left = 6
      Top = 477
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Toolkit DLL / COM Toolkit'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object lblEBus: Label8
      Left = 6
      Top = 75
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'eBusiness'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel8: TBevel
      Left = 3
      Top = 95
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblOLEHed: Label8
      Left = 6
      Top = 307
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'OLE Save Functions'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel10: TBevel
      Left = 5
      Top = 327
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblPaperHed: Label8
      Left = 6
      Top = 355
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Paperless'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel11: TBevel
      Left = 5
      Top = 375
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblCommitHed: Label8
      Left = 6
      Top = 27
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Commitment Accounting'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel9: TBevel
      Left = 4
      Top = 47
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblTradeHed: Label8
      Left = 6
      Top = 501
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Trade Counter'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel12: TBevel
      Left = 4
      Top = 497
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object Bevel13: TBevel
      Left = 4
      Top = 449
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object Label82: Label8
      Left = 6
      Top = 428
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Sentimail'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel14: TBevel
      Left = 4
      Top = 545
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblWOPHed: Label8
      Left = 6
      Top = 550
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Works Order Processing'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object lblTradeUsers: TLabel
      Left = 510
      Top = 503
      Width = 40
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Users'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object lblEnhSec: Label8
      Left = 6
      Top = 99
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Enhanced Security'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel2: TBevel
      Left = 4
      Top = 119
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblAppValHed: Label8
      Left = 6
      Top = 241
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Applications & Valuations'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      ShowAccelChar = False
      TextId = 0
    end
    object Label83: Label8
      Left = 6
      Top = 219
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Job Costing'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object lblFullStk: Label8
      Left = 6
      Top = 123
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = '(v5.61)  Full Stock Control'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel15: TBevel
      Left = 4
      Top = 143
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object Bevel16: TBevel
      Left = 4
      Top = 521
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object Label86: Label8
      Left = 6
      Top = 526
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = '(v5.61) Visual Report Writer'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object lblGoodsReturns: Label8
      Left = 6
      Top = 171
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = '(v5.70)  Goods Returns'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel17: TBevel
      Left = 4
      Top = 191
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object Bevel18: TBevel
      Left = 3
      Top = 71
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblEBank: Label8
      Left = 6
      Top = 51
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = '(v5.71)  eBanking'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object lblOutlookHed: Label8
      Left = 6
      Top = 331
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = '(v5.71)  Outlook Dashboard'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel19: TBevel
      Left = 5
      Top = 351
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblGDPRHed: Label8
      Left = 6
      Top = 147
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = '(2018-R1)  GDPR'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel20: TBevel
      Left = 4
      Top = 167
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object lblPervEncryptionHed: Label8
      Left = 6
      Top = 379
      Width = 179
      Height = 16
      Alignment = taRightJustify
      AutoSize = False
      Caption = '(2018-R1) P.SQL Encryption'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Bevel21: TBevel
      Left = 4
      Top = 399
      Width = 608
      Height = 7
      Shape = bsTopLine
    end
    object panCISRCTFull: TPanel
      Tag = 2
      Left = 411
      Top = 258
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 25
      OnClick = CISRCTClick
    end
    object panCISRCT30: TPanel
      Tag = 1
      Left = 304
      Top = 258
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 24
      OnClick = CISRCTClick
    end
    object panCISRCTNo: TPanel
      Left = 200
      Top = 258
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 23
      OnClick = CISRCTClick
    end
    object panAccStkNo: TPanel
      Left = 200
      Top = 2
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      OnClick = AccStkAnalClick
    end
    object panAccStkFull: TPanel
      Tag = 2
      Left = 411
      Top = 2
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnClick = AccStkAnalClick
    end
    object panAccStk30: TPanel
      Tag = 1
      Left = 304
      Top = 2
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnClick = AccStkAnalClick
    end
    object panImpModNo: TPanel
      Left = 200
      Top = 194
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 15
      OnClick = ImpModClick
    end
    object panImpModFull: TPanel
      Tag = 2
      Left = 411
      Top = 194
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 16
      OnClick = ImpModClick
    end
    object panODBCNo: TPanel
      Left = 200
      Top = 282
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 26
      OnClick = ODBCClick
    end
    object panODBCFull: TPanel
      Tag = 2
      Left = 411
      Top = 282
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 27
      OnClick = ODBCClick
    end
    object panRepWrtNo: TPanel
      Left = 200
      Top = 402
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 34
      OnClick = RepWrtClick
    end
    object panRepWrtFull: TPanel
      Tag = 2
      Left = 411
      Top = 402
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 36
      OnClick = RepWrtClick
    end
    object panRepWrt30: TPanel
      Tag = 1
      Left = 304
      Top = 402
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 35
      OnClick = RepWrtClick
    end
    object panTeleSaleFull: TPanel
      Tag = 2
      Left = 411
      Top = 453
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 41
      OnClick = TelesalesClick
    end
    object panTeleSale30: TPanel
      Tag = 1
      Left = 304
      Top = 453
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 40
      OnClick = TelesalesClick
    end
    object panTeleSaleNo: TPanel
      Left = 200
      Top = 453
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 39
      OnClick = TelesalesClick
    end
    object panToolDllInfo: TPanel
      Left = 200
      Top = 476
      Width = 301
      Height = 20
      BevelOuter = bvNone
      Caption = '30-day Developer - 0/20 Users'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 42
      OnDblClick = btnToolkitSettingsClick
    end
    object panEBusNo: TPanel
      Left = 200
      Top = 74
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      OnClick = EBusClick
    end
    object panEBusFull: TPanel
      Tag = 2
      Left = 411
      Top = 74
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 8
      OnClick = EBusClick
    end
    object panEBus30: TPanel
      Tag = 1
      Left = 304
      Top = 74
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
      OnClick = EBusClick
    end
    object panOLENo: TPanel
      Left = 200
      Top = 306
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 28
      OnClick = OLEClick
    end
    object panOLEFull: TPanel
      Tag = 2
      Left = 411
      Top = 306
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 30
      OnClick = OLEClick
    end
    object panOLE30: TPanel
      Tag = 1
      Left = 304
      Top = 306
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 29
      OnClick = OLEClick
    end
    object panPaperFull: TPanel
      Tag = 2
      Left = 411
      Top = 354
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 33
      OnClick = PaperClick
    end
    object panPaper30: TPanel
      Tag = 1
      Left = 304
      Top = 354
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 32
      OnClick = PaperClick
    end
    object panPaperNo: TPanel
      Left = 200
      Top = 354
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 31
      OnClick = PaperClick
    end
    object panCommitNo: TPanel
      Left = 200
      Top = 26
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      OnClick = panCommitNoClick
    end
    object panCommitFull: TPanel
      Tag = 2
      Left = 411
      Top = 26
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      OnClick = panCommitNoClick
    end
    object panCommit30: TPanel
      Tag = 1
      Left = 304
      Top = 26
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      OnClick = panCommitNoClick
    end
    object btnToolkitSettings: TButton
      Left = 520
      Top = 476
      Width = 88
      Height = 20
      Caption = 'Settings...'
      TabOrder = 43
      OnClick = btnToolkitSettingsClick
    end
    object panTradeNo: TPanel
      Left = 200
      Top = 501
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 44
      OnClick = TradeClick
    end
    object panTrade30: TPanel
      Tag = 1
      Left = 304
      Top = 501
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 45
      OnClick = TradeClick
    end
    object panTradeFull: TPanel
      Tag = 2
      Left = 411
      Top = 501
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 46
      OnClick = TradeClick
    end
    object lstTradeUsers: TComboBox
      Left = 552
      Top = 499
      Width = 44
      Height = 22
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      ParentFont = False
      TabOrder = 47
      Text = '4'
      Items.Strings = (
        '1'
        '4'
        '8'
        '12'
        '16'
        '20'
        '24'
        '28')
    end
    object btnWOPSettings: TButton
      Left = 520
      Top = 548
      Width = 88
      Height = 20
      Caption = 'Settings...'
      TabOrder = 49
      OnClick = btnWOPSettingsClick
    end
    object panWOPInfo: TPanel
      Left = 200
      Top = 548
      Width = 301
      Height = 20
      BevelOuter = bvNone
      Caption = '30-day Professional'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 50
      OnDblClick = btnWOPSettingsClick
    end
    object panElertInfo: TPanel
      Left = 200
      Top = 427
      Width = 301
      Height = 20
      BevelOuter = bvNone
      Caption = '30-day - 2 Engines - 10 Widgets'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 37
      OnDblClick = btnToolkitSettingsClick
    end
    object btnElertSettings: TButton
      Left = 520
      Top = 427
      Width = 88
      Height = 20
      Caption = 'Settings...'
      TabOrder = 38
      OnClick = btnElertSettingsClick
    end
    object panEnhSecNo: TPanel
      Left = 200
      Top = 98
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 9
      OnClick = EnhSecClick
    end
    object panEnhSec30: TPanel
      Tag = 1
      Left = 304
      Top = 98
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 10
      OnClick = EnhSecClick
    end
    object panEnhSecFull: TPanel
      Tag = 2
      Left = 411
      Top = 98
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 11
      OnClick = EnhSecClick
    end
    object UpDown1: TUpDown
      Left = 596
      Top = 499
      Width = 16
      Height = 22
      Associate = lstTradeUsers
      Min = 0
      Position = 4
      TabOrder = 48
      Wrap = False
    end
    object panAppValNo: TPanel
      Left = 200
      Top = 238
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 20
      OnClick = AppValClick
    end
    object panAppVal30: TPanel
      Tag = 1
      Left = 304
      Top = 238
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 21
      OnClick = AppValClick
    end
    object panAppValFull: TPanel
      Tag = 2
      Left = 411
      Top = 238
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 22
      OnClick = AppValClick
    end
    object panJobCostNo: TPanel
      Left = 200
      Top = 218
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 17
      OnClick = JobCostClick
    end
    object panJobCostFull: TPanel
      Tag = 2
      Left = 411
      Top = 218
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 19
      OnClick = JobCostClick
    end
    object panJobCost30: TPanel
      Tag = 1
      Left = 304
      Top = 218
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 18
      OnClick = JobCostClick
    end
    object panFullStkNo: TPanel
      Left = 200
      Top = 122
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 12
      OnClick = FullStkClick
    end
    object panFullStk30: TPanel
      Tag = 1
      Left = 304
      Top = 122
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 13
      OnClick = FullStkClick
    end
    object panFullStkFull: TPanel
      Tag = 2
      Left = 411
      Top = 122
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 14
      OnClick = FullStkClick
    end
    object panVRWNo: TPanel
      Left = 200
      Top = 525
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 51
      OnClick = VRWClick
    end
    object panVRW30: TPanel
      Tag = 1
      Left = 304
      Top = 524
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 52
      OnClick = VRWClick
    end
    object panVRWFull: TPanel
      Tag = 2
      Left = 411
      Top = 524
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 53
      OnClick = VRWClick
    end
    object panGoodsReturnsNo: TPanel
      Left = 200
      Top = 170
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 54
      OnClick = GoodsReturnsClick
    end
    object panGoodsReturns30: TPanel
      Tag = 1
      Left = 304
      Top = 170
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 55
      OnClick = GoodsReturnsClick
    end
    object panGoodsReturnsFull: TPanel
      Tag = 2
      Left = 411
      Top = 170
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 56
      OnClick = GoodsReturnsClick
    end
    object panEBankFull: TPanel
      Tag = 2
      Left = 411
      Top = 50
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 57
      OnClick = EBankClick
    end
    object panEBank30: TPanel
      Tag = 1
      Left = 304
      Top = 50
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 58
      OnClick = EBankClick
    end
    object panEBankNo: TPanel
      Left = 200
      Top = 50
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 59
      OnClick = EBankClick
    end
    object panOutlookNo: TPanel
      Left = 200
      Top = 330
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 60
      OnClick = OutlookClick
    end
    object panOutlook30: TPanel
      Tag = 1
      Left = 304
      Top = 330
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 61
      OnClick = OutlookClick
    end
    object panOutlookFull: TPanel
      Tag = 2
      Left = 411
      Top = 330
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 62
      OnClick = OutlookClick
    end
    object panImpMod30: TPanel
      Tag = 1
      Left = 304
      Top = 194
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 63
      OnClick = ImpModClick
    end
    object panGDPRNo: TPanel
      Left = 200
      Top = 146
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 64
      OnClick = GDPRClick
    end
    object panGDPR30: TPanel
      Tag = 1
      Left = 304
      Top = 146
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 65
      OnClick = GDPRClick
    end
    object panGDPRFull: TPanel
      Tag = 2
      Left = 411
      Top = 146
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 66
      OnClick = GDPRClick
    end
    object panPervEncryptFull: TPanel
      Tag = 2
      Left = 411
      Top = 378
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'FULL'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 67
      OnClick = PervEncryptClick
    end
    object panPervEncrypt30: TPanel
      Tag = 1
      Left = 304
      Top = 378
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = '30-DAY'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 68
      OnClick = PervEncryptClick
    end
    object panPervEncryptNo: TPanel
      Left = 200
      Top = 378
      Width = 90
      Height = 20
      BevelOuter = bvNone
      Caption = 'NO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 69
      OnClick = PervEncryptClick
    end
  end
  object PopupMenu1: TPopupMenu
    AutoHotkeys = maManual
    Left = 655
    Top = 122
    object Popup_AllNone: TMenuItem
      Caption = 'All Modules To NONE'
      ShortCut = 16462
      OnClick = Popup_SetAllMods
    end
    object N1: TMenuItem
      Caption = '-'
    end
    object Popup_All30: TMenuItem
      Tag = 11
      Caption = 'All Modules To 30-DAY'
      ShortCut = 114
      OnClick = Popup_SetAllMods
    end
    object N2: TMenuItem
      Caption = '-'
    end
    object Popup_AllFull: TMenuItem
      Tag = 12
      Caption = 'All Modules To FULL'
      ShortCut = 16454
      OnClick = Popup_SetAllMods
    end
  end
end
