object frmedUsers: TfrmedUsers
  Left = 0
  Top = 0
  Width = 823
  Height = 753
  VertScrollBar.Position = 64
  Background.Fixed = False
  HandleTabs = False
  SupportedBrowsers = [brIE, brNetscape6]
  OnCreate = IWAppFormCreate
  OnDestroy = IWAppFormDestroy
  DesignLeft = 174
  DesignTop = 14
  object cbParent: TIWComboBox
    Left = 144
    Top = 4
    Width = 226
    Height = 21
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ItemsHaveValues = False
    NoSelectionText = ' '
    RequireSelection = True
    ScriptEvents = <>
    OnChange = cbParentChange
    UseSize = True
    DoSubmitValidation = True
    Editable = True
    TabOrder = 0
    ItemIndex = -1
    Sorted = True
  end
  object lblParent: TIWLabel
    Left = 28
    Top = 8
    Width = 46
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Parent:'
  end
  object lblUserCode: TIWLabel
    Left = 28
    Top = 36
    Width = 74
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'User Code:'
  end
  object capPassword: TIWLabel
    Left = 28
    Top = 148
    Width = 69
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Password:'
  end
  object edUserCode: TIWEdit
    Left = 144
    Top = 32
    Width = 239
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'IWEdit1'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 1
    PasswordPrompt = False
  end
  object cbSuspended: TIWCheckBox
    Left = 144
    Top = 204
    Width = 113
    Height = 21
    ZIndex = 0
    Caption = 'Suspended'
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    DoSubmitValidation = True
    Style = stNormal
    TabOrder = 2
    Checked = False
  end
  object bnSaveChanges: TIWButton
    Left = 583
    Top = 656
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Save Changes'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 3
    OnClick = bnSaveChangesClick
  end
  object bnReturnAdmin: TIWButton
    Left = 583
    Top = 712
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Return to Admin'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 4
    OnClick = bnReturnAdminClick
  end
  object bnReturnMain: TIWButton
    Left = 699
    Top = 712
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Return to Main'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 5
    OnClick = bnReturnMainClick
  end
  object lbPermitFrom: TIWListbox
    Left = 20
    Top = 384
    Width = 355
    Height = 265
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ItemsHaveValues = False
    NoSelectionText = ' '
    RequireSelection = False
    ScriptEvents = <>
    UseSize = True
    DoSubmitValidation = True
    Editable = True
    TabOrder = 6
    ItemIndex = 0
    MultiSelect = True
    Sorted = True
  end
  object lbPermitTo: TIWListbox
    Left = 454
    Top = 384
    Width = 355
    Height = 265
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ItemsHaveValues = False
    NoSelectionText = ' '
    RequireSelection = False
    ScriptEvents = <>
    UseSize = True
    DoSubmitValidation = True
    Editable = True
    TabOrder = 7
    ItemIndex = 0
    Items.Strings = (
      'Run WebRel')
    MultiSelect = True
    Sorted = True
  end
  object bnAdd: TIWButton
    Left = 384
    Top = 412
    Width = 61
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = '>'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 8
    OnClick = bnAddClick
  end
  object bnRemove: TIWButton
    Left = 384
    Top = 585
    Width = 61
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = '<'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 9
    OnClick = bnRemoveClick
  end
  object lblTemplate: TIWLabel
    Left = 24
    Top = 332
    Width = 67
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Template:'
  end
  object cbTemplate: TIWComboBox
    Left = 148
    Top = 328
    Width = 226
    Height = 21
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ItemsHaveValues = False
    NoSelectionText = ' '
    RequireSelection = True
    ScriptEvents = <>
    OnChange = cbTemplateChange
    UseSize = True
    DoSubmitValidation = True
    Editable = True
    TabOrder = 10
    ItemIndex = -1
    Sorted = False
  end
  object lblPermissions: TIWLabel
    Left = 20
    Top = 228
    Width = 93
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = [fsBold]
    Caption = 'Permissions'
  end
  object txtPermissions: TIWText
    Left = 24
    Top = 252
    Width = 469
    Height = 73
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Lines.Strings = (
      'To change user permissions, select a template to begin from, and'
      'use the buttons between the list-boxes to add and remove '
      'permissions. Press the Save Changes button to complete the '
      'changes.')
    RawText = False
    UseFrame = False
    WantReturns = True
  end
  object edUserName: TIWEdit
    Left = 144
    Top = -24
    Width = 239
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edUserName'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 11
    PasswordPrompt = False
  end
  object lblDealerName: TIWLabel
    Left = 28
    Top = -20
    Width = 79
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'User Name:'
  end
  object lblhdrUsers: TIWLabel
    Left = 20
    Top = -52
    Width = 45
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = [fsBold]
    Caption = 'Users'
  end
  object bnCancel: TIWButton
    Left = 699
    Top = 656
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Cancel'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 12
    OnClick = bnCancelClick
  end
  object bnAddAll: TIWButton
    Left = 384
    Top = 384
    Width = 61
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = '>>'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 13
    OnClick = bnAddAllClick
  end
  object bnRemoveAll: TIWButton
    Left = 384
    Top = 613
    Width = 61
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = '<<'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 14
    OnClick = bnRemoveAllClick
  end
  object lblAvailable: TIWLabel
    Left = 24
    Top = 364
    Width = 147
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Permissions Available'
  end
  object lblGranted: TIWLabel
    Left = 460
    Top = 364
    Width = 137
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Permissions Granted'
  end
  object lblEmail: TIWLabel
    Left = 28
    Top = 64
    Width = 100
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Email Address:'
  end
  object edEmail: TIWEdit
    Left = 144
    Top = 60
    Width = 239
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edEmail'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 15
    PasswordPrompt = False
  end
  object lblSMSPhone: TIWLabel
    Left = 28
    Top = 92
    Width = 104
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'SMS Phone No:'
  end
  object edSMSPhone: TIWEdit
    Left = 144
    Top = 88
    Width = 239
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edEmail'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 16
    PasswordPrompt = False
  end
  object lblPassword: TIWLabel
    Left = 148
    Top = 148
    Width = 66
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Password'
  end
  object capExpiryDate: TIWLabel
    Left = 28
    Top = 176
    Width = 79
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Expiry Date:'
  end
  object lblExpiryDate: TIWLabel
    Left = 148
    Top = 176
    Width = 75
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Expiry Date'
  end
  object lblExpiryDays: TIWLabel
    Left = 28
    Top = 120
    Width = 82
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Expiry Days:'
  end
  object edExpiryDays: TIWEdit
    Left = 144
    Top = 116
    Width = 77
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edEmail'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 17
    PasswordPrompt = False
  end
  object bnFilterUser: TIWButton
    Left = 430
    Top = 2
    Width = 55
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Filter'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 18
    OnClick = edFilterUserSubmit
  end
  object edFilterUser: TIWEdit
    Left = 376
    Top = 4
    Width = 32
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edDealerName'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 19
    OnSubmit = edFilterUserSubmit
    PasswordPrompt = False
  end
  object cbContainsUser: TIWCheckBox
    Left = 490
    Top = 6
    Width = 85
    Height = 21
    ZIndex = 0
    Caption = 'Contains'
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    DoSubmitValidation = True
    Style = stNormal
    TabOrder = 20
    Checked = False
  end
end
