object frmedESNs: TfrmedESNs
  Left = 0
  Top = 0
  Width = 409
  Height = 452
  Background.Fixed = False
  HandleTabs = False
  SupportedBrowsers = [brIE, brNetscape6]
  DesignLeft = 290
  DesignTop = 153
  object edESN: TIWEdit
    Left = 148
    Top = 44
    Width = 239
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edESN'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 0
    PasswordPrompt = False
  end
  object lblESN: TIWLabel
    Left = 24
    Top = 48
    Width = 34
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'ESN:'
  end
  object lblCustESNs: TIWLabel
    Left = 20
    Top = 16
    Width = 118
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = [fsBold]
    Caption = 'Customer ESNs'
  end
  object memoESN: TIWMemo
    Left = 25
    Top = 96
    Width = 293
    Height = 150
    ZIndex = 0
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    RawText = False
    ReadOnly = False
    Required = False
    TabOrder = 1
    WantReturns = False
    FriendlyName = 'memoESN'
  end
  object lblESNNotes: TIWLabel
    Left = 24
    Top = 76
    Width = 77
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'ESN Notes:'
  end
  object bnSaveChanges: TIWButton
    Left = 148
    Top = 344
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Save Changes'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 2
    OnClick = bnSaveChangesClick
  end
  object bnCancel: TIWButton
    Left = 264
    Top = 344
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Cancel'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 3
    OnClick = bnCancelClick
  end
  object cbUnspecified: TIWCheckBox
    Left = 148
    Top = 288
    Width = 121
    Height = 21
    ZIndex = 0
    Caption = 'Unspecified'
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    DoSubmitValidation = True
    Style = stNormal
    TabOrder = 4
    Checked = False
  end
  object cbActive: TIWCheckBox
    Left = 148
    Top = 312
    Width = 121
    Height = 21
    ZIndex = 0
    Caption = 'Active'
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    DoSubmitValidation = True
    Style = stNormal
    TabOrder = 5
    Checked = True
  end
  object lblVersion: TIWLabel
    Left = 24
    Top = 256
    Width = 53
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Version:'
  end
  object cbVersion: TIWComboBox
    Left = 148
    Top = 256
    Width = 234
    Height = 21
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ItemsHaveValues = False
    NoSelectionText = ' '
    RequireSelection = True
    ScriptEvents = <>
    UseSize = True
    DoSubmitValidation = True
    Editable = True
    TabOrder = 6
    ItemIndex = -1
    Sorted = True
  end
  object bnReturnAdmin: TIWButton
    Left = 148
    Top = 398
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Return to Admin'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 7
    OnClick = bnReturnAdminClick
  end
  object bnReturnMain: TIWButton
    Left = 264
    Top = 398
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Return to Main'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 8
    OnClick = bnReturnMainClick
  end
end
