object frmSentinelLog: TfrmSentinelLog
  Left = 192
  Top = 107
  Width = 409
  Height = 271
  Caption = 'frmSentinelLog'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Position = poDefault
  Visible = True
  PixelsPerInch = 96
  TextHeight = 13
  object memLog: TMemo
    Left = 0
    Top = 0
    Width = 401
    Height = 244
    Align = alClient
    TabOrder = 0
  end
end
