object frmTestOutput: TfrmTestOutput
  Left = 192
  Top = 107
  BorderStyle = bsDialog
  Caption = 'Sentinel Output'
  ClientHeight = 447
  ClientWidth = 448
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 14
  object Memo1: TMemo
    Left = 8
    Top = 8
    Width = 433
    Height = 401
    ScrollBars = ssBoth
    TabOrder = 0
  end
  object Button1: TButton
    Left = 376
    Top = 416
    Width = 65
    Height = 25
    Caption = '&Close'
    ModalResult = 2
    TabOrder = 1
  end
end
