object Form3: TForm3
  Left = 360
  Top = 226
  Width = 471
  Height = 274
  BorderIcons = [biSystemMenu]
  Caption = 'Form3'
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 14
  object Label10: TLabel
    Left = 280
    Top = 202
    Width = 60
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = '9.10'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
  end
  object Label13: TLabel
    Left = 185
    Top = 202
    Width = 90
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Original NET'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
  end
  object Label1: TLabel
    Left = 64
    Top = 184
    Width = 83
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = #163'2.40'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
  end
  object Label2: TLabel
    Left = 28
    Top = 184
    Width = 29
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Cost'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
  end
  object Label4: TLabel
    Left = 280
    Top = 184
    Width = 60
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = '6.40'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
  end
  object Label5: TLabel
    Left = 185
    Top = 184
    Width = 90
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Discount'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
  end
  object Label14: TLabel
    Left = 280
    Top = 220
    Width = 60
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = '2.70'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
  end
  object Label15: TLabel
    Left = 185
    Top = 220
    Width = 90
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Discounted NET'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
  end
  object ScrollBox1: TScrollBox
    Left = 7
    Top = 6
    Width = 364
    Height = 171
    VertScrollBar.Position = 8
    Ctl3D = False
    ParentCtl3D = False
    TabOrder = 0
    object Label6: TLabel
      Left = 8
      Top = 3
      Width = 322
      Height = 14
      AutoSize = False
      Caption = '8 x WIDGET310 - 10mm Widget Type 3'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label11: TLabel
      Left = 311
      Top = 25
      Width = 21
      Height = 14
      Alignment = taRightJustify
      Caption = '3.90'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label12: TLabel
      Left = 311
      Top = 52
      Width = 21
      Height = 14
      Alignment = taRightJustify
      Caption = '1.30'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label16: TLabel
      Left = 18
      Top = 25
      Width = 82
      Height = 14
      Alignment = taRightJustify
      Caption = 'Buy 5 Get 3 Free'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label17: TLabel
      Left = 18
      Top = 52
      Width = 82
      Height = 14
      Alignment = taRightJustify
      Caption = 'Buy 2 Get 1 Free'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label18: TLabel
      Left = 147
      Top = 52
      Width = 6
      Height = 14
      Alignment = taRightJustify
      Caption = 'x'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label19: TLabel
      Left = 147
      Top = 25
      Width = 6
      Height = 14
      Alignment = taRightJustify
      Caption = 'x'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label20: TLabel
      Left = 225
      Top = 25
      Width = 45
      Height = 14
      Alignment = taRightJustify
      Caption = 'Discount:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label21: TLabel
      Left = 225
      Top = 52
      Width = 45
      Height = 14
      Alignment = taRightJustify
      Caption = 'Discount:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 8
      Top = 83
      Width = 322
      Height = 14
      AutoSize = False
      Caption = '12 x IFS10 - 10mm Inverse Flange Sprocket'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label7: TLabel
      Left = 311
      Top = 105
      Width = 21
      Height = 14
      Alignment = taRightJustify
      Caption = '1.20'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label8: TLabel
      Left = 311
      Top = 132
      Width = 21
      Height = 14
      Alignment = taRightJustify
      Caption = '0.00'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label9: TLabel
      Left = 18
      Top = 105
      Width = 82
      Height = 14
      Alignment = taRightJustify
      Caption = 'Buy 6 Get 3 Free'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label22: TLabel
      Left = 18
      Top = 132
      Width = 82
      Height = 14
      Alignment = taRightJustify
      Caption = 'Buy 3 Get 1 Free'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label23: TLabel
      Left = 147
      Top = 132
      Width = 6
      Height = 14
      Alignment = taRightJustify
      Caption = 'x'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label24: TLabel
      Left = 147
      Top = 105
      Width = 6
      Height = 14
      Alignment = taRightJustify
      Caption = 'x'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label25: TLabel
      Left = 225
      Top = 105
      Width = 45
      Height = 14
      Alignment = taRightJustify
      Caption = 'Discount:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label26: TLabel
      Left = 225
      Top = 132
      Width = 45
      Height = 14
      Alignment = taRightJustify
      Caption = 'Discount:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object EditValue1: TEditValue
      Left = 161
      Top = 22
      Width = 30
      Height = 20
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = '1'
      FloatValue = 1
      FormatMask = '###,###,##0 ;###,###,##0-'
      NDecimals = 0
    end
    object EditValue2: TEditValue
      Left = 161
      Top = 49
      Width = 30
      Height = 20
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = '1'
      FloatValue = 1
      FormatMask = '###,###,##0 ;###,###,##0-'
      NDecimals = 0
    end
    object UpDown2: TUpDown
      Left = 191
      Top = 49
      Width = 16
      Height = 20
      Associate = EditValue2
      Min = 0
      Position = 1
      TabOrder = 2
      Wrap = False
    end
    object UpDown1: TUpDown
      Left = 191
      Top = 22
      Width = 16
      Height = 20
      Associate = EditValue1
      Min = 0
      Position = 1
      TabOrder = 3
      Wrap = False
    end
    object EditValue3: TEditValue
      Left = 161
      Top = 102
      Width = 30
      Height = 20
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      Text = '2'
      FloatValue = 2
      FormatMask = '###,###,##0 ;###,###,##0-'
      NDecimals = 0
    end
    object EditValue4: TEditValue
      Left = 161
      Top = 129
      Width = 30
      Height = 20
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      Text = '0'
      FormatMask = '###,###,##0 ;###,###,##0-'
      NDecimals = 0
    end
    object UpDown3: TUpDown
      Left = 191
      Top = 129
      Width = 16
      Height = 20
      Associate = EditValue4
      Min = 0
      Position = 0
      TabOrder = 6
      Wrap = False
    end
    object UpDown4: TUpDown
      Left = 191
      Top = 102
      Width = 16
      Height = 20
      Associate = EditValue3
      Min = 0
      Position = 2
      TabOrder = 7
      Wrap = False
    end
    object BorCheckEx1: TBorCheckEx
      Left = 25
      Top = 195
      Width = 98
      Height = 20
      Caption = 'BorCheckEx1'
      Color = clBtnFace
      ParentColor = False
      TabOrder = 8
      TextId = 0
    end
  end
  object Button1: TButton
    Left = 376
    Top = 8
    Width = 80
    Height = 21
    Caption = '&Apply'
    TabOrder = 1
  end
  object Button2: TButton
    Left = 376
    Top = 36
    Width = 80
    Height = 21
    Cancel = True
    Caption = '&Cancel'
    TabOrder = 2
  end
  object Panel1: TPanel
    Left = 375
    Top = 76
    Width = 78
    Height = 107
    BevelOuter = bvNone
    BorderWidth = 1
    BorderStyle = bsSingle
    Caption = 'Panel1'
    TabOrder = 3
  end
end
