object Form5: TForm5
  Left = 339
  Top = 157
  Width = 658
  Height = 409
  Caption = 'Form5'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object PageControl1: TPageControl
    Left = 1
    Top = 1
    Width = 646
    Height = 371
    ActivePage = DE3Page
    TabIndex = 2
    TabOrder = 0
    object DE1Page: TTabSheet
      Caption = 'Data Entry'
      object Id1Panel: TSBSPanel
        Left = 0
        Top = 2
        Width = 401
        Height = 135
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 0
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object Id1ItemLab: Label8
          Left = 10
          Top = 15
          Width = 19
          Height = 14
          Caption = 'Item'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id1UPLab: Label8
          Left = 260
          Top = 42
          Width = 34
          Height = 14
          Caption = 'U/Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id1DiscLab: Label8
          Left = 252
          Top = 75
          Width = 42
          Height = 14
          Caption = 'Discount'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id1LTotLab: Label8
          Left = 269
          Top = 107
          Width = 23
          Height = 14
          Caption = 'Total'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id1QtyLab: Label8
          Left = 87
          Top = 14
          Width = 17
          Height = 14
          Caption = 'Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object Id1ItemF: Text8Pt
        Tag = 1
        Left = 34
        Top = 13
        Width = 39
        Height = 22
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 1
        TextId = 0
        ViaSBtn = False
      end
      object Id1QtyF: TCurrencyEdit
        Tag = 1
        Left = 108
        Top = 14
        Width = 88
        Height = 22
        HelpContext = 247
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id1SBox: TScrollBox
        Left = 8
        Top = 42
        Width = 238
        Height = 88
        HorzScrollBar.Visible = False
        Ctl3D = False
        ParentCtl3D = False
        TabOrder = 3
        object Id1Desc1F: Text8Pt
          Tag = 1
          Left = 1
          Top = 1
          Width = 218
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          Text = '12345678901234567890123456789012345'
          TextId = 0
          ViaSBtn = False
        end
        object Id1Desc2F: Text8Pt
          Tag = 1
          Left = 1
          Top = 22
          Width = 218
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 1
          TextId = 0
          ViaSBtn = False
        end
        object Id1Desc3F: Text8Pt
          Tag = 1
          Left = 1
          Top = 43
          Width = 218
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 2
          TextId = 0
          ViaSBtn = False
        end
        object Id1Desc4F: Text8Pt
          Tag = 1
          Left = 1
          Top = 64
          Width = 218
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          TextId = 0
          ViaSBtn = False
        end
        object Id1Desc5F: Text8Pt
          Tag = 1
          Left = 1
          Top = 85
          Width = 218
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 4
          TextId = 0
          ViaSBtn = False
        end
        object Id1Desc6F: Text8Pt
          Tag = 1
          Left = 1
          Top = 106
          Width = 218
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 5
          TextId = 0
          ViaSBtn = False
        end
      end
      object Id1UPriceF: TCurrencyEdit
        Tag = 1
        Left = 296
        Top = 42
        Width = 100
        Height = 22
        HelpContext = 268
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 4
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id1LTotF: TCurrencyEdit
        Tag = 2
        Left = 296
        Top = 105
        Width = 100
        Height = 22
        HelpContext = 248
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 6
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id1DiscF: Text8Pt
        Tag = 1
        Left = 296
        Top = 74
        Width = 100
        Height = 22
        HelpContext = 269
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 5
        TextId = 0
        ViaSBtn = False
      end
      object OkCP1Btn: TButton
        Tag = 1
        Left = 441
        Top = 166
        Width = 80
        Height = 21
        HelpContext = 278
        Caption = '&OK'
        ModalResult = 1
        TabOrder = 7
      end
      object CanCP1Btn: TButton
        Tag = 1
        Left = 526
        Top = 166
        Width = 80
        Height = 21
        HelpContext = 279
        Cancel = True
        Caption = '&Cancel'
        ModalResult = 2
        TabOrder = 8
      end
    end
    object De2Page: TTabSheet
      Caption = 'Data Entry'
    end
    object DE3Page: TTabSheet
      Caption = 'Data Entry'
      object Id3Panel2: TSBSPanel
        Left = 255
        Top = 2
        Width = 181
        Height = 181
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 9
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object Id3PQLab: Label8
          Left = 4
          Top = 11
          Width = 69
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Pack Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3QtyLab: Label8
          Left = 4
          Top = 36
          Width = 69
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3UPLab: Label8
          Left = 4
          Top = 60
          Width = 69
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'U/Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3DiscLab: Label8
          Left = 4
          Top = 84
          Width = 69
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Line Disc'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3LTotLab: Label8
          Left = 4
          Top = 156
          Width = 69
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Total'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label87: Label8
          Left = 4
          Top = 109
          Width = 69
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Multi-Buy Disc'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label88: Label8
          Left = 4
          Top = 132
          Width = 69
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Trans Disc'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object Id3Panel: TSBSPanel
        Left = 0
        Top = 2
        Width = 252
        Height = 181
        BevelInner = bvRaised
        BevelOuter = bvLowered
        Caption = 'Id3Panel'
        TabOrder = 0
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object Id3SCodeLab: Label8
          Left = 7
          Top = 12
          Width = 43
          Height = 14
          Caption = 'Stk Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object id3LocLab: Label8
          Left = 183
          Top = 11
          Width = 27
          Height = 14
          Alignment = taRightJustify
          Caption = 'Locn '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object Id3SCodeF: Text8Pt
        Tag = 1
        Left = 52
        Top = 10
        Width = 127
        Height = 22
        Hint = 
          'Double click to drill down|Double clicking or using the down but' +
          'ton will drill down to the record for this field. The up button ' +
          'will search for the nearest match.'
        HelpContext = 256
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 1
        TextId = 0
        ViaSBtn = False
        ShowHilight = True
      end
      object Id3SBox: TScrollBox
        Left = 8
        Top = 44
        Width = 238
        Height = 130
        HorzScrollBar.Visible = False
        Ctl3D = False
        ParentCtl3D = False
        TabOrder = 3
        object Id3Desc1F: Text8Pt
          Tag = 1
          Left = 1
          Top = 1
          Width = 234
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          Text = '12345678901234567890123456789012345'
          TextId = 0
          ViaSBtn = False
        end
        object Id3Desc2F: Text8Pt
          Tag = 1
          Left = 1
          Top = 22
          Width = 234
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 1
          TextId = 0
          ViaSBtn = False
        end
        object Id3Desc3F: Text8Pt
          Tag = 1
          Left = 1
          Top = 43
          Width = 234
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 2
          TextId = 0
          ViaSBtn = False
        end
        object Id3Desc4F: Text8Pt
          Tag = 1
          Left = 1
          Top = 64
          Width = 234
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          TextId = 0
          ViaSBtn = False
        end
        object Id3Desc5F: Text8Pt
          Tag = 1
          Left = 1
          Top = 85
          Width = 234
          Height = 21
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 4
          TextId = 0
          ViaSBtn = False
        end
        object Id3Desc6F: Text8Pt
          Tag = 1
          Left = 1
          Top = 107
          Width = 234
          Height = 20
          HelpContext = 235
          BorderStyle = bsNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 5
          TextId = 0
          ViaSBtn = False
        end
      end
      object Id3PQtyF: TCurrencyEdit
        Tag = 1
        Left = 331
        Top = 9
        Width = 76
        Height = 22
        HelpContext = 267
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 4
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id3QtyF: TCurrencyEdit
        Tag = 1
        Left = 331
        Top = 33
        Width = 76
        Height = 22
        HelpContext = 247
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 5
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id3UPriceF: TCurrencyEdit
        Tag = 1
        Left = 331
        Top = 57
        Width = 97
        Height = 22
        HelpContext = 268
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 6
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id3LTotF: TCurrencyEdit
        Tag = 2
        Left = 331
        Top = 154
        Width = 97
        Height = 22
        HelpContext = 248
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 8
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id3LocF: Text8Pt
        Tag = 1
        Left = 207
        Top = 11
        Width = 38
        Height = 22
        HelpContext = 274
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 2
        TextId = 0
        ViaSBtn = False
      end
      object Id3DiscF: Text8Pt
        Tag = 1
        Left = 331
        Top = 81
        Width = 97
        Height = 22
        HelpContext = 269
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 7
        TextId = 0
        ViaSBtn = False
      end
      object Id3Panel3: TSBSPanel
        Left = 0
        Top = 187
        Width = 436
        Height = 69
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 14
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object UDF1L: Label8
          Left = 6
          Top = 14
          Width = 48
          Height = 14
          Caption = 'UD Field 1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF3L: Label8
          Left = 220
          Top = 15
          Width = 48
          Height = 14
          Caption = 'UD Field 3'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF2L: Label8
          Left = 5
          Top = 42
          Width = 48
          Height = 14
          Caption = 'UD Field 2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF4L: Label8
          Left = 220
          Top = 43
          Width = 48
          Height = 14
          Caption = 'UD Field 4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object LUD1F: Text8Pt
        Tag = 1
        Left = 58
        Top = 198
        Width = 155
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 10
        TextId = 0
        ViaSBtn = False
      end
      object LUD3F: Text8Pt
        Tag = 1
        Left = 273
        Top = 198
        Width = 155
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 12
        TextId = 0
        ViaSBtn = False
      end
      object LUD4F: Text8Pt
        Tag = 1
        Left = 273
        Top = 227
        Width = 156
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 13
        TextId = 0
        ViaSBtn = False
      end
      object LUD2F: Text8Pt
        Tag = 1
        Left = 58
        Top = 227
        Width = 155
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 11
        TextId = 0
        ViaSBtn = False
      end
      object SBSPanel1: TSBSPanel
        Left = 0
        Top = 260
        Width = 436
        Height = 81
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 15
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object Label5: TLabel
          Left = 6
          Top = 6
          Width = 233
          Height = 14
          Caption = 'The following Multi-Buy discounts are available:-'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object ScrollBox1: TScrollBox
          Left = 8
          Top = 23
          Width = 422
          Height = 53
          BorderStyle = bsNone
          TabOrder = 0
          object Label3: TLabel
            Left = 266
            Top = 5
            Width = 76
            Height = 14
            Alignment = taRightJustify
            Caption = 'Discount Value:'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object Label11: TLabel
            Left = 363
            Top = 5
            Width = 21
            Height = 14
            Alignment = taRightJustify
            Caption = '3.90'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object Label2: TLabel
            Left = 266
            Top = 32
            Width = 76
            Height = 14
            Alignment = taRightJustify
            Caption = 'Discount Value:'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object Label4: TLabel
            Left = 363
            Top = 32
            Width = 21
            Height = 14
            Alignment = taRightJustify
            Caption = '1.30'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object Label6: TLabel
            Left = 177
            Top = 5
            Width = 6
            Height = 14
            Alignment = taRightJustify
            Caption = 'x'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object Label8: TLabel
            Left = 177
            Top = 32
            Width = 6
            Height = 14
            Alignment = taRightJustify
            Caption = 'x'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object Label1: TLabel
            Left = 12
            Top = 5
            Width = 82
            Height = 14
            Alignment = taRightJustify
            Caption = 'Buy 5 Get 3 Free'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object Label7: TLabel
            Left = 12
            Top = 32
            Width = 82
            Height = 14
            Alignment = taRightJustify
            Caption = 'Buy 2 Get 1 Free'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object EditValue1: TEditValue
            Left = 191
            Top = 2
            Width = 30
            Height = 22
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TabOrder = 0
            Text = '0'
            FormatMask = '###,###,##0.00 ;###,###,##0.00-'
            NDecimals = 2
          end
          object UpDown1: TUpDown
            Left = 221
            Top = 2
            Width = 16
            Height = 22
            Associate = EditValue1
            Min = 0
            Position = 0
            TabOrder = 1
            Wrap = False
          end
          object EditValue2: TEditValue
            Left = 191
            Top = 29
            Width = 30
            Height = 22
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TabOrder = 2
            Text = '0'
            FormatMask = '###,###,##0.00 ;###,###,##0.00-'
            NDecimals = 2
          end
          object UpDown2: TUpDown
            Left = 221
            Top = 29
            Width = 16
            Height = 22
            Associate = EditValue2
            Min = 0
            Position = 0
            TabOrder = 3
            Wrap = False
          end
        end
      end
      object Button1: TButton
        Tag = 1
        Left = 457
        Top = 227
        Width = 80
        Height = 21
        HelpContext = 278
        Caption = '&OK'
        ModalResult = 1
        TabOrder = 16
      end
      object Button2: TButton
        Tag = 1
        Left = 542
        Top = 227
        Width = 80
        Height = 21
        HelpContext = 279
        Cancel = True
        Caption = '&Cancel'
        ModalResult = 2
        TabOrder = 17
      end
      object ext8Pt1: Text8Pt
        Tag = 1
        Left = 331
        Top = 105
        Width = 97
        Height = 22
        HelpContext = 269
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 18
        TextId = 0
        ViaSBtn = False
      end
      object ext8Pt2: Text8Pt
        Tag = 1
        Left = 331
        Top = 129
        Width = 97
        Height = 22
        HelpContext = 269
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 19
        TextId = 0
        ViaSBtn = False
      end
      object SBSPanel2: TSBSPanel
        Left = 439
        Top = 2
        Width = 197
        Height = 215
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 20
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object Label89: Label8
          Left = 18
          Top = 9
          Width = 45
          Height = 14
          Caption = 'Job Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label810: Label8
          Left = 21
          Top = 35
          Width = 42
          Height = 14
          Caption = 'Analysis'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label811: Label8
          Left = 2
          Top = 59
          Width = 61
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = '/CC/Dep'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label812: Label8
          Left = 21
          Top = 86
          Width = 42
          Height = 14
          Caption = 'GL Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label813: Label8
          Left = 24
          Top = 133
          Width = 34
          Height = 14
          Alignment = taRightJustify
          Caption = 'Cost__'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label814: Label8
          Left = 18
          Top = 159
          Width = 44
          Height = 14
          Caption = 'Line type'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label815: Label8
          Left = 11
          Top = 188
          Width = 51
          Height = 14
          Alignment = taRightJustify
          Caption = 'Deliv. Date'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label816: Label8
          Left = 130
          Top = 155
          Width = 42
          Height = 14
          Alignment = taRightJustify
          Caption = 'Override'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label817: Label8
          Left = 132
          Top = 166
          Width = 39
          Height = 14
          Alignment = taRightJustify
          Caption = 'Intrastat'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object ext8Pt3: Text8Pt
          Tag = 1
          Left = 64
          Top = 4
          Width = 123
          Height = 22
          Hint = 
            'Double click to drill down|Double clicking or using the down but' +
            'ton will drill down to the record for this field. The up button ' +
            'will search for the nearest match.'
          HelpContext = 465
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          TextId = 0
          ViaSBtn = False
          Link_to_Job = True
          ShowHilight = True
        end
        object ext8Pt4: Text8Pt
          Tag = 1
          Left = 64
          Top = 29
          Width = 123
          Height = 22
          HelpContext = 466
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 1
          TextId = 0
          ViaSBtn = False
        end
        object SBSComboBox1: TSBSComboBox
          Tag = 1
          Left = 64
          Top = 54
          Width = 41
          Height = 22
          HelpContext = 249
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ItemHeight = 14
          MaxLength = 1
          ParentFont = False
          TabOrder = 2
          AllowChangeInExit = True
          ExtendedList = True
          MaxListWidth = 75
          ReadOnly = True
          Validate = True
        end
        object ext8Pt5: Text8Pt
          Tag = 1
          Left = 107
          Top = 54
          Width = 39
          Height = 22
          HelpContext = 272
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          TextId = 0
          ViaSBtn = False
        end
        object ext8Pt6: Text8Pt
          Tag = 1
          Left = 148
          Top = 54
          Width = 39
          Height = 22
          HelpContext = 272
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 4
          TextId = 0
          ViaSBtn = False
        end
        object ext8Pt7: Text8Pt
          Tag = 1
          Left = 64
          Top = 80
          Width = 82
          Height = 22
          HelpContext = 275
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 5
          TextId = 0
          ViaSBtn = False
        end
        object ext8Pt8: Text8Pt
          Left = 6
          Top = 105
          Width = 183
          Height = 22
          HelpContext = 275
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 6
          TextId = 0
          ViaSBtn = False
        end
        object EditDate1: TEditDate
          Tag = 1
          Left = 64
          Top = 182
          Width = 77
          Height = 22
          HelpContext = 273
          AutoSelect = False
          EditMask = '00/00/0000;0;'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          ReadOnly = True
          TabOrder = 7
          Placement = cpAbove
        end
        object SBSComboBox2: TSBSComboBox
          Tag = 1
          Left = 64
          Top = 156
          Width = 57
          Height = 22
          HelpContext = 276
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ItemHeight = 14
          MaxLength = 40
          ParentFont = False
          TabOrder = 8
          ExtendedList = True
          MaxListWidth = 75
          ReadOnly = True
          Validate = True
        end
        object CurrencyEdit3: TCurrencyEdit
          Tag = 1
          Left = 64
          Top = 131
          Width = 123
          Height = 22
          HelpContext = 277
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 9
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object BorCheck1: TBorCheck
          Tag = 1
          Left = 171
          Top = 152
          Width = 16
          Height = 20
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentColor = False
          ParentFont = False
          TabOrder = 10
          TabStop = True
          TextId = 0
        end
        object BitBtn1: TBitBtn
          Left = 174
          Top = 171
          Width = 13
          Height = 13
          HelpContext = 207
          Enabled = False
          TabOrder = 11
          Glyph.Data = {
            C6000000424DC60000000000000076000000280000000A0000000A0000000100
            0400000000005000000000000000000000001000000000000000000000000000
            80000080000000808000800000008000800080800000C0C0C000808080000000
            FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFFFF00FFFFFFFFFF00
            0000FFFFFFFFFF000000FFFFFFFFFF000000FFFF0FFFFF000000FFF000FFFF00
            0000FF00000FFF000000F0000000FF000000FFFFFFFFFF000000FFFFFFFFFF00
            0000FFFFFFFFFF000000}
        end
      end
    end
    object DE4Page: TTabSheet
      HelpContext = 494
      Caption = 'Qty/Pick'
      object SBSPanel7: TSBSPanel
        Left = 254
        Top = 4
        Width = 351
        Height = 61
        Caption = 'Total Quantities To Date'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        AllowReSize = False
        IsGroupBox = True
        TextId = 0
        object Label831: Label8
          Left = 42
          Top = 18
          Width = 43
          Height = 14
          Caption = ' Ordered'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label833: Label8
          Left = 125
          Top = 18
          Width = 45
          Height = 14
          Caption = 'Delivered'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label834: Label8
          Left = 200
          Top = 18
          Width = 55
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Written Off'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label835: Label8
          Left = 282
          Top = 18
          Width = 58
          Height = 14
          Caption = 'Outstanding'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object SBSPanel8: TSBSPanel
        Left = 284
        Top = 75
        Width = 321
        Height = 51
        Caption = 'Pick/Write Off - This Time'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        AllowReSize = False
        IsGroupBox = True
        TextId = 0
        object Label836: Label8
          Left = 183
          Top = 28
          Width = 47
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Write Off'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object PickLab: Label8
          Left = 18
          Top = 27
          Width = 41
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Pick'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object Id4QOF: TCurrencyEdit
        Tag = 2
        Left = 263
        Top = 36
        Width = 80
        Height = 22
        HelpContext = 479
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id4QDF: TCurrencyEdit
        Tag = 2
        Left = 348
        Top = 36
        Width = 80
        Height = 22
        HelpContext = 479
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 3
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id4QWF: TCurrencyEdit
        Tag = 2
        Left = 433
        Top = 36
        Width = 80
        Height = 22
        HelpContext = 479
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 4
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id4QOSF: TCurrencyEdit
        Tag = 2
        Left = 518
        Top = 36
        Width = 80
        Height = 22
        HelpContext = 479
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 5
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object ID4QPTF: TCurrencyEdit
        Tag = 1
        Left = 348
        Top = 98
        Width = 80
        Height = 22
        HelpContext = 480
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 6
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id4QWTF: TCurrencyEdit
        Tag = 1
        Left = 518
        Top = 98
        Width = 80
        Height = 22
        HelpContext = 480
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 7
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
    end
  end
end
