"Torry''s Delphi Pages" files/links uploads form


Filename (xxxxxxxx.xxx): temail2.zip

Component/Application/Tool/Link name: TEmail

Version: 2.10.0

File size:  115 KB

Delphi version and C++ Builder compatibility (check all that apply):
                [x] Delphi 1.x
                [x] Delphi 2.x
                [x] Delphi 3.x
                [x] Delphi 4.x
                [x] C++ Builder 1.x
                [x] C++ Builder 3.x

If application or tool please indicate targeted OS (check all that apply):
                [x] W3.X
                [x] W95
                [x] W98
                [x] NT

Type:
                [x] Freeware
                [ ] Shareware
                [ ] Commercial

Price: 

Source Availability:
                [x] Included 
                [ ] Purchase/Registration 
                [ ] On request 
                [ ] None
                [ ] N/A 

Status:
                [x] Fully Functional 
                [ ] Trial (Works when IDE is running) 
                [ ] Evaluation (Time Limit) 
                [ ] Demo only 
                [ ] N/A 

Author Name: Stefan Hoffmeister

Company Name: Econos

EMail: Stefan.Hoffmeister@Econos.de

Web page: http://www.econos.de/

Description: TEmail is a MAPI component with source. It allows for 
             easy but powerful distribution of MAPI email (<b>not</b> 
             native SMTP !!), faxes and other data through MAPI clients 
             like MS Exchange.

File Location:
                [ ] Uploaded or soon will be 
                [ ] Please download it 
                [ ] Link 
                [x] Sent/sending via EMail 
                [ ] Just additional info 

For link to your file, enter exact URL to the file:

If you want us to download the file, enter permanent URL to the file: 

URL for on-line registration (if any): 

Version this file replaces (if any) that should be removed from our site: 

Notes: temail2.zip
            
Do you want to recieve information about your files download (only for files that located on "Torry's Delphi Pages")?
                [ ] Yes
                [x] No

Do you allow to place your files on "Torry's Delphi Pages" CD?
                [x] Yes
                [ ] No

