object Form1: TForm1
  Left = 218
  Top = 127
  Width = 510
  Height = 477
  Caption = 'Form1'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object ListBox1: TListBox
    Left = 13
    Top = 12
    Width = 481
    Height = 429
    ItemHeight = 13
    TabOrder = 0
    TabWidth = 120
  end
end
