{*********************************************************}
{* ABBREVIA: AbDlgPwd.pas 3.02                           *}
{* Copyright (c) TurboPower Software Co 1997, 2002       *}
{* All rights reserved.                                  *}
{*********************************************************}
{* ABBREVIA: Dialog - Password (VCL)                     *}
{*   See AbQDgPwd.pas for the CLX header                 *}
{*********************************************************}

{$UNDEF UsingClx}

unit AbDlgPwd;

{$R *.dfm}

{$I AbDlgPwd.inc}


