{*********************************************************}
{* ABBREVIA: AbPePass.pas 3.02                           *}
{* Copyright (c) TurboPower Software Co 1997, 2002       *}
{* All rights reserved.                                  *}
{*********************************************************}
{* ABBREVIA: Password property editor (VCL)              *}
{*   See AbQPePas.pas for the CLX header                 *}
{*********************************************************}

{$UNDEF UsingClx}

unit AbPePass;

{$I AbPePass.inc}


