{*********************************************************}
{* ABBREVIA: AbQPeCol.pas 3.02                           *}
{* Copyright (c) TurboPower Software Co 1997, 2002       *}
{* All rights reserved.                                  *}
{*********************************************************}
{* ABBREVIA: Property Editor - ZipView column headings   *}
{* (CLX)                                                 *}
{*   See AbPeCol.pas for the VCL header                  *}
{*********************************************************}

{$DEFINE UsingClx}

unit AbQPeCol;

{$R *.xfm}

{$I AbPeCol.inc}



