{*********************************************************}
{* ABBREVIA: AbQView.pas 3.02                            *}
{* Copyright (c) TurboPower Software Co 1997, 2002       *}
{* All rights reserved.                                  *}
{*********************************************************}
{* ABBREVIA: Base archive viewer component (CLX)         *}
{*   See AbView.pas for the VCL header                   *}
{*********************************************************}

{$DEFINE UsingCLX}

unit AbQView;

{$I AbView.inc}

