{*********************************************************}
{* ABBREVIA: AbZipOut.pas 3.02                           *}
{* Copyright (c) TurboPower Software Co 1997, 2002       *}
{* All rights reserved.                                  *}
{*********************************************************}
{* ABBREVIA: Visual Component with Zip and unzip support *}
{* (VCL)                                                 *}
{*   See AbQZpOut.pas for the CLX header                 *}
{*********************************************************}

unit AbZipOut;

{$UNDEF UsingCLX}

{$I AbZipOut.inc}


