#if !defined(AFX_DEVICEDESC_H__BCC8CD43_C77B_11D2_B2D9_0000F87AE18C__INCLUDED_)
#define AFX_DEVICEDESC_H__BCC8CD43_C77B_11D2_B2D9_0000F87AE18C__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDeviceDesc wrapper class

class CDeviceDesc : public COleDispatchDriver
{
public:
	CDeviceDesc() {}		// Calls COleDispatchDriver default constructor
	CDeviceDesc(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDeviceDesc(const CDeviceDesc& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	short GetPort();
	long GetBClass1();
	long GetBClass2();
	long GetBClass20();
	long GetBClass21();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DEVICEDESC_H__BCC8CD43_C77B_11D2_B2D9_0000F87AE18C__INCLUDED_)
