#if !defined(AFX_FAXFINDER_H__BCC8CD42_C77B_11D2_B2D9_0000F87AE18C__INCLUDED_)
#define AFX_FAXFINDER_H__BCC8CD42_C77B_11D2_B2D9_0000F87AE18C__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDeviceDesc;

/////////////////////////////////////////////////////////////////////////////
// CFaxFinder wrapper class

class CFaxFinder : public CWnd
{
protected:
	DECLARE_DYNCREATE(CFaxFinder)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xa5929ec5, 0x74cf, 0x11d2, { 0xba, 0x5e, 0x0, 0x0, 0x21, 0x49, 0x9, 0x3d } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CDeviceDesc GetItem(short nIndex);
	short GetDeviceCount();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FAXFINDER_H__BCC8CD42_C77B_11D2_B2D9_0000F87AE18C__INCLUDED_)
