// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "faxfinder.h"

// Dispatch interfaces referenced by this interface
#include "DeviceDesc.h"

/////////////////////////////////////////////////////////////////////////////
// CFaxFinder

IMPLEMENT_DYNCREATE(CFaxFinder, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CFaxFinder properties

/////////////////////////////////////////////////////////////////////////////
// CFaxFinder operations

CDeviceDesc CFaxFinder::GetItem(short nIndex)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		nIndex);
	return CDeviceDesc(pDispatch);
}

short CFaxFinder::GetDeviceCount()
{
	short result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}
