// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CFaxStatusObj;

/////////////////////////////////////////////////////////////////////////////
// CFaxManJr wrapper class

class CFaxManJr : public CWnd
{
protected:
	DECLARE_DYNCREATE(CFaxManJr)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7728b50, 0x6223, 0x11d2, { 0xba, 0x57, 0x0, 0x0, 0x21, 0x49, 0x9, 0x3d } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetFaxNumber();
	void SetFaxNumber(LPCTSTR lpszNewValue);
	CString GetFaxName();
	void SetFaxName(LPCTSTR lpszNewValue);
	CString GetFaxSubject();
	void SetFaxSubject(LPCTSTR lpszNewValue);
	CString GetUserName_();
	void SetUserName(LPCTSTR lpszNewValue);
	CString GetFaxBanner();
	void SetFaxBanner(LPCTSTR lpszNewValue);
	CString GetFaxCoverPage();
	void SetFaxCoverPage(LPCTSTR lpszNewValue);
	CString GetFaxComments();
	void SetFaxComments(LPCTSTR lpszNewValue);
	CString GetUserCompany();
	void SetUserCompany(LPCTSTR lpszNewValue);
	CString GetFaxCompany();
	void SetFaxCompany(LPCTSTR lpszNewValue);
	CString GetUserFaxNumber();
	void SetUserFaxNumber(LPCTSTR lpszNewValue);
	CString GetUserVoiceNumber();
	void SetUserVoiceNumber(LPCTSTR lpszNewValue);
	CString GetFaxUserData();
	void SetFaxUserData(LPCTSTR lpszNewValue);
	CString GetLocalID();
	void SetLocalID(LPCTSTR lpszNewValue);
	CString GetFaxFiles();
	void SetFaxFiles(LPCTSTR lpszNewValue);
	short GetPort();
	void SetPort(short nNewValue);
	void SendFax();
	long GetClass();
	void SetClass(long nNewValue);
	CString GetDeviceReset();
	void SetDeviceReset(LPCTSTR lpszNewValue);
	CString GetDeviceInit();
	void SetDeviceInit(LPCTSTR lpszNewValue);
	long GetFaxResolution();
	void SetFaxResolution(long nNewValue);
	void CancelFax();
	CString GetReceiveDir();
	void SetReceiveDir(LPCTSTR lpszNewValue);
	void Receive(short nRingCnt);
	void ImportFiles(LPCTSTR pszOutFile, LPCTSTR pszInFiles);
	void Listen();
	long GetStatus();
	void WaitForEvent(long lWaitTime);
	CFaxStatusObj GetStatusObject();
};
