// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CFaxStatusObj wrapper class

class CFaxStatusObj : public COleDispatchDriver
{
public:
	CFaxStatusObj() {}		// Calls COleDispatchDriver default constructor
	CFaxStatusObj(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFaxStatusObj(const CFaxStatusObj& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetRemoteID();
	long GetConnectSpeed();
	short GetLastEventType();
	short GetNegotiatedResolution();
	long GetCurrentStatus();
	long GetStartTime();
	long GetEndTime();
	CString GetReceiveFileName();
	short GetPages();
	long GetErrorCode();
	CString GetErrorDesc();
	short GetPagesCompleted();
	CString GetCurrentStatusDesc();
	void SetCurrentStatusDesc(LPCTSTR lpszNewValue);
};
