// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CFmPrint wrapper class

class CFmPrint : public CWnd
{
protected:
	DECLARE_DYNCREATE(CFmPrint)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xe3bdb1c4, 0x49aa, 0x11d2, { 0xb9, 0x6b, 0x0, 0xa0, 0x24, 0x3d, 0x54, 0xa2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetAppID();
	void SetAppID(LPCTSTR lpszNewValue);
	long GetPaperOrientation();
	void SetPaperOrientation(long nNewValue);
	long GetPaperSize();
	void SetPaperSize(long nNewValue);
	long GetPrinterResolution();
	void SetPrinterResolution(long nNewValue);
	void About();
};
