object frmSOPLine: TfrmSOPLine
  Left = 327
  Top = 144
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'frmSOPLine'
  ClientHeight = 249
  ClientWidth = 632
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poDefault
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object PageControl1: TPageControl
    Left = 1
    Top = 1
    Width = 630
    Height = 244
    ActivePage = DE3Page
    TabIndex = 0
    TabOrder = 0
    object DE3Page: TTabSheet
      Caption = 'Data Entry'
      object Id3Panel3: TSBSPanel
        Left = 0
        Top = 142
        Width = 432
        Height = 69
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 5
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object UDF1L: Label8
          Left = 6
          Top = 14
          Width = 48
          Height = 14
          Caption = 'UD Field 1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF3L: Label8
          Left = 216
          Top = 15
          Width = 48
          Height = 14
          Caption = 'UD Field 3'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF2L: Label8
          Left = 5
          Top = 42
          Width = 48
          Height = 14
          Caption = 'UD Field 2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF4L: Label8
          Left = 216
          Top = 43
          Width = 48
          Height = 14
          Caption = 'UD Field 4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object LineExtF1: TSBSExtendedForm
        Left = 408
        Top = 2
        Width = 213
        Height = 134
        HelpContext = 1170
        HorzScrollBar.Visible = False
        TabOrder = 0
        ArrowPos = alNone
        ArrowX = -10
        ArrowY = -25
        OrigHeight = 134
        OrigWidth = 213
        ExpandedWidth = 209
        ExpandedHeight = 212
        OrigTabOrder = 10
        ShowHorzSB = False
        ShowVertSB = False
        OrigParent = DE3Page
        NewParent = Owner
        FocusFirst = Id5JCodeF
        FocusLast = Id3DelF
        TabNext = LUD1F
        object Label85: Label8
          Left = 21
          Top = 86
          Width = 42
          Height = 14
          Caption = 'GL Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object VATCCLab3: Label8
          Left = 2
          Top = 59
          Width = 61
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = '/CC/Dep'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object DelDateLab: Label8
          Left = 11
          Top = 188
          Width = 51
          Height = 14
          Alignment = taRightJustify
          Caption = 'Deliv. Date'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label83: Label8
          Left = 18
          Top = 159
          Width = 44
          Height = 14
          Caption = 'Line type'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3CostLab: Label8
          Left = 24
          Top = 133
          Width = 34
          Height = 14
          Alignment = taRightJustify
          Caption = 'Cost__'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label84: Label8
          Left = 130
          Top = 155
          Width = 42
          Height = 14
          Alignment = taRightJustify
          Caption = 'Override'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label86: Label8
          Left = 132
          Top = 166
          Width = 39
          Height = 14
          Alignment = taRightJustify
          Caption = 'Intrastat'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label81: Label8
          Left = 19
          Top = 9
          Width = 45
          Height = 14
          Caption = 'Job Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label82: Label8
          Left = 21
          Top = 35
          Width = 42
          Height = 14
          Caption = 'Analysis'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3VATF: TSBSComboBox
          Tag = 1
          Left = 64
          Top = 54
          Width = 41
          Height = 22
          HelpContext = 249
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ItemHeight = 14
          MaxLength = 1
          ParentFont = False
          TabOrder = 2
          AllowChangeInExit = True
          ExtendedList = True
          MaxListWidth = 75
          ReadOnly = True
          Validate = True
        end
        object Id3DepF: Text8Pt
          Tag = 1
          Left = 148
          Top = 54
          Width = 39
          Height = 22
          HelpContext = 272
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 4
          TextId = 0
          ViaSBtn = False
        end
        object Id3DelF: TEditDate
          Tag = 1
          Left = 64
          Top = 182
          Width = 77
          Height = 22
          HelpContext = 273
          AutoSelect = False
          EditMask = '00/00/0000;0;'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          ReadOnly = True
          TabOrder = 11
          Placement = cpAbove
        end
        object Id3LTF: TSBSComboBox
          Tag = 1
          Left = 64
          Top = 156
          Width = 57
          Height = 22
          HelpContext = 276
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ItemHeight = 14
          MaxLength = 40
          ParentFont = False
          TabOrder = 8
          ExtendedList = True
          MaxListWidth = 75
          ReadOnly = True
          Validate = True
        end
        object Id3CostF: TCurrencyEdit
          Tag = 1
          Left = 64
          Top = 131
          Width = 123
          Height = 22
          HelpContext = 277
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 7
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object UseISCB: TBorCheck
          Tag = 1
          Left = 171
          Top = 156
          Width = 16
          Height = 20
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentColor = False
          ParentFont = False
          TabOrder = 9
          TabStop = True
          TextId = 0
        end
        object IntBtn: TBitBtn
          Left = 189
          Top = 160
          Width = 13
          Height = 13
          HelpContext = 207
          Enabled = False
          TabOrder = 10
          Glyph.Data = {
            C6000000424DC60000000000000076000000280000000A0000000A0000000100
            0400000000005000000000000000000000001000000000000000000000000000
            80000080000000808000800000008000800080800000C0C0C000808080000000
            FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFFFF00FFFFFFFFFF00
            0000FFFFFFFFFF000000FFFFFFFFFF000000FFFF0FFFFF000000FFF000FFFF00
            0000FF00000FFF000000F0000000FF000000FFFFFFFFFF000000FFFFFFFFFF00
            0000FFFFFFFFFF000000}
        end
        object Id5JCodeF: Text8Pt
          Tag = 1
          Left = 64
          Top = 4
          Width = 123
          Height = 22
          Hint = 
            'Double click to drill down|Double clicking or using the down but' +
            'ton will drill down to the record for this field. The up button ' +
            'will search for the nearest match.'
          HelpContext = 465
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          TextId = 0
          ViaSBtn = False
          Link_to_Job = True
          ShowHilight = True
        end
        object Id5JAnalF: Text8Pt
          Tag = 1
          Left = 64
          Top = 29
          Width = 123
          Height = 22
          HelpContext = 466
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 1
          TextId = 0
          ViaSBtn = False
        end
        object GLDescF: Text8Pt
          Left = 4
          Top = 105
          Width = 183
          Height = 22
          HelpContext = 275
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 6
          TextId = 0
          ViaSBtn = False
        end
        object Id3CCF: Text8Pt
          Tag = 1
          Left = 107
          Top = 54
          Width = 39
          Height = 22
          HelpContext = 272
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          TextId = 0
          ViaSBtn = False
        end
        object Id3NomF: Text8Pt
          Tag = 1
          Left = 64
          Top = 80
          Width = 82
          Height = 22
          HelpContext = 275
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 5
          TextId = 0
          ViaSBtn = False
        end
      end
      object LUD1F: Text8Pt
        Tag = 1
        Left = 58
        Top = 152
        Width = 150
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 1
        TextId = 0
        ViaSBtn = False
      end
      object LUD3F: Text8Pt
        Tag = 1
        Left = 274
        Top = 152
        Width = 150
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 3
        TextId = 0
        ViaSBtn = False
      end
      object LUD4F: Text8Pt
        Tag = 1
        Left = 274
        Top = 181
        Width = 150
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 4
        TextId = 0
        ViaSBtn = False
      end
      object LUD2F: Text8Pt
        Tag = 1
        Left = 58
        Top = 181
        Width = 150
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 2
        TextId = 0
        ViaSBtn = False
      end
      object btnClose: TButton
        Tag = 1
        Left = 540
        Top = 143
        Width = 80
        Height = 21
        HelpContext = 279
        Cancel = True
        Caption = '&Close'
        ModalResult = 2
        TabOrder = 6
        OnClick = btnCloseClick
      end
      object Notebook1: TNotebook
        Left = 0
        Top = -1
        Width = 408
        Height = 139
        PageIndex = 1
        TabOrder = 7
        object TPage
          Left = 0
          Top = 0
          Caption = 'NonStock'
          object Id1Panel: TSBSPanel
            Left = 1
            Top = 3
            Width = 401
            Height = 135
            BevelInner = bvRaised
            BevelOuter = bvLowered
            TabOrder = 0
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            object Id1ItemLab: Label8
              Left = 10
              Top = 15
              Width = 19
              Height = 14
              Caption = 'Item'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
            object Id1UPLab: Label8
              Left = 260
              Top = 42
              Width = 34
              Height = 14
              Caption = 'U/Price'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
            object Id1DiscLab: Label8
              Left = 252
              Top = 75
              Width = 42
              Height = 14
              Caption = 'Discount'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
            object Id1LTotLab: Label8
              Left = 269
              Top = 107
              Width = 23
              Height = 14
              Caption = 'Total'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
            object Id1QtyLab: Label8
              Left = 87
              Top = 14
              Width = 17
              Height = 14
              Caption = 'Qty'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
          end
          object Id1ItemF: Text8Pt
            Tag = 1
            Left = 35
            Top = 12
            Width = 39
            Height = 22
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 1
            TextId = 0
            ViaSBtn = False
          end
          object Id1QtyF: TCurrencyEdit
            Tag = 1
            Left = 109
            Top = 13
            Width = 88
            Height = 22
            HelpContext = 247
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            Lines.Strings = (
              '0.67-')
            ParentFont = False
            ReadOnly = True
            TabOrder = 2
            WantReturns = False
            WordWrap = False
            AutoSize = False
            BlankOnZero = False
            DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
            ShowCurrency = False
            TextId = 0
            Value = -0.666666
          end
          object Id1SBox: TScrollBox
            Left = 11
            Top = 43
            Width = 238
            Height = 88
            HorzScrollBar.Visible = False
            Ctl3D = False
            ParentCtl3D = False
            TabOrder = 3
            object Id1Desc1F: Text8Pt
              Tag = 1
              Left = 1
              Top = 1
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 0
              Text = '12345678901234567890123456789012345'
              TextId = 0
              ViaSBtn = False
            end
            object Id1Desc2F: Text8Pt
              Tag = 1
              Left = 1
              Top = 22
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 1
              TextId = 0
              ViaSBtn = False
            end
            object Id1Desc3F: Text8Pt
              Tag = 1
              Left = 1
              Top = 43
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 2
              TextId = 0
              ViaSBtn = False
            end
            object Id1Desc4F: Text8Pt
              Tag = 1
              Left = 1
              Top = 64
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 3
              TextId = 0
              ViaSBtn = False
            end
            object Id1Desc5F: Text8Pt
              Tag = 1
              Left = 1
              Top = 85
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 4
              TextId = 0
              ViaSBtn = False
            end
            object Id1Desc6F: Text8Pt
              Tag = 1
              Left = 1
              Top = 106
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 5
              TextId = 0
              ViaSBtn = False
            end
          end
          object Id1UPriceF: TCurrencyEdit
            Tag = 1
            Left = 297
            Top = 41
            Width = 100
            Height = 22
            HelpContext = 268
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            Lines.Strings = (
              '0.67-')
            ParentFont = False
            ReadOnly = True
            TabOrder = 4
            WantReturns = False
            WordWrap = False
            AutoSize = False
            BlankOnZero = False
            DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
            ShowCurrency = False
            TextId = 0
            Value = -0.666666
          end
          object Id1DiscF: Text8Pt
            Tag = 1
            Left = 297
            Top = 73
            Width = 100
            Height = 22
            HelpContext = 269
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 5
            TextId = 0
            ViaSBtn = False
          end
          object Id1LTotF: TCurrencyEdit
            Tag = 2
            Left = 297
            Top = 104
            Width = 100
            Height = 22
            HelpContext = 248
            TabStop = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            Lines.Strings = (
              '0.67-')
            ParentFont = False
            ReadOnly = True
            TabOrder = 6
            WantReturns = False
            WordWrap = False
            AutoSize = False
            BlankOnZero = False
            DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
            ShowCurrency = False
            TextId = 0
            Value = -0.666666
          end
        end
        object TPage
          Left = 0
          Top = 0
          Caption = 'Stock'
          object Id3Panel: TSBSPanel
            Left = 1
            Top = 3
            Width = 252
            Height = 134
            BevelInner = bvRaised
            BevelOuter = bvLowered
            Caption = 'Id3Panel'
            TabOrder = 0
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            object Id3SCodeLab: Label8
              Left = 7
              Top = 12
              Width = 43
              Height = 14
              Caption = 'Stk Code'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
            object id3LocLab: Label8
              Left = 183
              Top = 11
              Width = 27
              Height = 14
              Alignment = taRightJustify
              Caption = 'Locn '
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
          end
          object Id3Panel2: TSBSPanel
            Left = 255
            Top = 3
            Width = 151
            Height = 134
            BevelInner = bvRaised
            BevelOuter = bvLowered
            TabOrder = 4
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            object Id3PQLab: Label8
              Left = 4
              Top = 14
              Width = 43
              Height = 14
              Caption = 'Pack Qty'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
            object Id3QtyLab: Label8
              Left = 30
              Top = 39
              Width = 17
              Height = 14
              Caption = 'Qty'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
            object Id3UPLab: Label8
              Left = 13
              Top = 63
              Width = 34
              Height = 14
              Caption = 'U/Price'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
            object Id3DiscLab: Label8
              Left = 5
              Top = 88
              Width = 42
              Height = 14
              Caption = 'Discount'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
            object Id3LTotLab: Label8
              Left = 24
              Top = 112
              Width = 23
              Height = 14
              Caption = 'Total'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              ParentFont = False
              TextId = 0
            end
          end
          object Id3SCodeF: Text8Pt
            Tag = 1
            Left = 53
            Top = 11
            Width = 127
            Height = 22
            Hint = 
              'Double click to drill down|Double clicking or using the down but' +
              'ton will drill down to the record for this field. The up button ' +
              'will search for the nearest match.'
            HelpContext = 256
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 1
            TextId = 0
            ViaSBtn = False
            ShowHilight = True
          end
          object Id3LocF: Text8Pt
            Tag = 1
            Left = 208
            Top = 12
            Width = 38
            Height = 22
            HelpContext = 274
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 2
            TextId = 0
            ViaSBtn = False
          end
          object Id3SBox: TScrollBox
            Left = 9
            Top = 43
            Width = 238
            Height = 88
            HorzScrollBar.Visible = False
            Ctl3D = False
            ParentCtl3D = False
            TabOrder = 3
            object Id3Desc1F: Text8Pt
              Tag = 1
              Left = 1
              Top = 1
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 0
              Text = '12345678901234567890123456789012345'
              TextId = 0
              ViaSBtn = False
            end
            object Id3Desc2F: Text8Pt
              Tag = 1
              Left = 1
              Top = 22
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 1
              TextId = 0
              ViaSBtn = False
            end
            object Id3Desc3F: Text8Pt
              Tag = 1
              Left = 1
              Top = 43
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 2
              TextId = 0
              ViaSBtn = False
            end
            object Id3Desc4F: Text8Pt
              Tag = 1
              Left = 1
              Top = 64
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 3
              TextId = 0
              ViaSBtn = False
            end
            object Id3Desc5F: Text8Pt
              Tag = 1
              Left = 1
              Top = 85
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 4
              TextId = 0
              ViaSBtn = False
            end
            object Id3Desc6F: Text8Pt
              Tag = 1
              Left = 1
              Top = 106
              Width = 218
              Height = 20
              HelpContext = 235
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = []
              MaxLength = 50
              ParentFont = False
              ParentShowHint = False
              ReadOnly = True
              ShowHint = True
              TabOrder = 5
              TextId = 0
              ViaSBtn = False
            end
          end
          object Id3PQtyF: TCurrencyEdit
            Tag = 1
            Left = 304
            Top = 10
            Width = 76
            Height = 22
            HelpContext = 267
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            Lines.Strings = (
              '0.67-')
            ParentFont = False
            ReadOnly = True
            TabOrder = 5
            WantReturns = False
            WordWrap = False
            AutoSize = False
            BlankOnZero = False
            DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
            ShowCurrency = False
            TextId = 0
            Value = -0.666666
          end
          object Id3QtyF: TCurrencyEdit
            Tag = 1
            Left = 304
            Top = 35
            Width = 76
            Height = 22
            HelpContext = 247
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            Lines.Strings = (
              '0.67-')
            ParentFont = False
            ReadOnly = True
            TabOrder = 6
            WantReturns = False
            WordWrap = False
            AutoSize = False
            BlankOnZero = False
            DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
            ShowCurrency = False
            TextId = 0
            Value = -0.666666
          end
          object Id3UPriceF: TCurrencyEdit
            Tag = 1
            Left = 304
            Top = 60
            Width = 97
            Height = 22
            HelpContext = 268
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            Lines.Strings = (
              '0.67-')
            ParentFont = False
            ReadOnly = True
            TabOrder = 7
            WantReturns = False
            WordWrap = False
            AutoSize = False
            BlankOnZero = False
            DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
            ShowCurrency = False
            TextId = 0
            Value = -0.666666
          end
          object Id3DiscF: Text8Pt
            Tag = 1
            Left = 304
            Top = 85
            Width = 97
            Height = 22
            HelpContext = 269
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 8
            TextId = 0
            ViaSBtn = False
          end
          object Id3LTotF: TCurrencyEdit
            Tag = 2
            Left = 304
            Top = 110
            Width = 97
            Height = 22
            HelpContext = 248
            TabStop = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            Lines.Strings = (
              '0.67-')
            ParentFont = False
            ReadOnly = True
            TabOrder = 9
            WantReturns = False
            WordWrap = False
            AutoSize = False
            BlankOnZero = False
            DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
            ShowCurrency = False
            TextId = 0
            Value = -0.666666
          end
        end
      end
    end
  end
end
