object SetModRec: TSetModRec
  Left = -661
  Top = 67
  Width = 503
  Height = 518
  HelpContext = 14
  BorderIcons = [biSystemMenu, biMinimize]
  Caption = 'Module Licences and User Counts'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = True
  Position = poScreenCenter
  Scaled = False
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  OnResize = FormResize
  DesignSize = (
    487
    479)
  PixelsPerInch = 96
  TextHeight = 13
  object Label830: Label8
    Left = 5
    Top = 5
    Width = 113
    Height = 14
    Caption = 'Exchequer Site Number'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object lblESN: Label8
    Left = 129
    Top = 5
    Width = 318
    Height = 14
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    OnDblClick = lblESNDblClick
    TextId = 0
  end
  object PageControl1: TPageControl
    Left = 5
    Top = 24
    Width = 477
    Height = 451
    ActivePage = tabshModules
    Anchors = [akLeft, akTop, akRight, akBottom]
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TabIndex = 0
    TabOrder = 0
    object tabshModules: TTabSheet
      Caption = 'Release Codes'
      DesignSize = (
        469
        422)
      object Label82: Label8
        Left = 30
        Top = 0
        Width = 141
        Height = 19
        AutoSize = False
        Caption = 'Module'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label83: Label8
        Left = 180
        Top = 2
        Width = 84
        Height = 14
        AutoSize = False
        Caption = 'Security'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label85: Label8
        Left = 271
        Top = 2
        Width = 80
        Height = 14
        AutoSize = False
        Caption = 'Release'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label86: Label8
        Left = 359
        Top = 2
        Width = 79
        Height = 14
        AutoSize = False
        Caption = 'Status'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object ScrollBox1: TScrollBox
        Left = 4
        Top = 17
        Width = 461
        Height = 375
        Anchors = [akLeft, akTop, akBottom]
        TabOrder = 0
        object Label81: Label8
          Left = 3
          Top = 5
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label87: Label8
          Left = 3
          Top = 29
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label88: Label8
          Left = 3
          Top = 77
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label89: Label8
          Left = 3
          Top = 53
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '3'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label814: Label8
          Left = 3
          Top = 101
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '5'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label815: Label8
          Left = 3
          Top = 125
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '6'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label816: Label8
          Left = 3
          Top = 149
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '7'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label817: Label8
          Left = 3
          Top = 173
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '8'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label818: Label8
          Left = 3
          Top = 293
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '13'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label819: Label8
          Left = 3
          Top = 317
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '14'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label820: Label8
          Left = 2
          Top = 341
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '15'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label821: Label8
          Left = 3
          Top = 365
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '16'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label822: Label8
          Left = 3
          Top = 269
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '12'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label823: Label8
          Left = 3
          Top = 245
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '11'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label824: Label8
          Left = 3
          Top = 221
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '10'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label825: Label8
          Left = 3
          Top = 196
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '9'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label833: Label8
          Left = 3
          Top = 581
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '25'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label834: Label8
          Left = 3
          Top = 557
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '24'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label835: Label8
          Left = 3
          Top = 534
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '23'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          Visible = False
          TextId = 0
        end
        object Label836: Label8
          Left = 3
          Top = 511
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '22'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          Visible = False
          TextId = 0
        end
        object Label837: Label8
          Left = 3
          Top = 486
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '21'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          Visible = False
          TextId = 0
        end
        object Label838: Label8
          Left = 3
          Top = 461
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '20'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label839: Label8
          Left = 3
          Top = 437
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '19'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label840: Label8
          Left = 3
          Top = 413
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '18'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label841: Label8
          Left = 3
          Top = 389
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '17'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label831: Label8
          Left = 3
          Top = 485
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '21'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label832: Label8
          Left = 3
          Top = 509
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '22'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label842: Label8
          Left = 3
          Top = 533
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '23'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object CDesc1: Text8Pt
          Left = 21
          Top = 2
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          Text = 'Full Multi Currency'
          TextId = 0
          ViaSBtn = False
        end
        object CSS1: Text8Pt
          Tag = 1
          Left = 170
          Top = 2
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 1
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS1: Text8Pt
          Tag = 1001
          Left = 262
          Top = 2
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 2
          OnClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST1: Text8Pt
          Left = 350
          Top = 2
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          TextId = 0
          ViaSBtn = False
        end
        object CDesc2: Text8Pt
          Left = 21
          Top = 26
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 4
          Text = 'Job Costing'
          TextId = 0
          ViaSBtn = False
        end
        object RS2: Text8Pt
          Tag = 1002
          Left = 262
          Top = 26
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 6
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST2: Text8Pt
          Left = 350
          Top = 26
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 7
          TextId = 0
          ViaSBtn = False
        end
        object CDesc3: Text8Pt
          Left = 21
          Top = 50
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 8
          Text = 'Report Writer'
          TextId = 0
          ViaSBtn = False
        end
        object CSS3: Text8Pt
          Tag = 3
          Left = 170
          Top = 50
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 9
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS3: Text8Pt
          Tag = 1003
          Left = 262
          Top = 50
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 10
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST3: Text8Pt
          Left = 350
          Top = 50
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 11
          TextId = 0
          ViaSBtn = False
        end
        object CSS2: Text8Pt
          Tag = 2
          Left = 170
          Top = 26
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 5
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object Cdesc4: Text8Pt
          Left = 21
          Top = 74
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 12
          Text = 'DLL Toolkit'
          TextId = 0
          ViaSBtn = False
        end
        object CSS4: Text8Pt
          Tag = 4
          Left = 170
          Top = 74
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 13
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS4: Text8Pt
          Tag = 1004
          Left = 262
          Top = 74
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 14
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST4: Text8Pt
          Left = 350
          Top = 74
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 15
          TextId = 0
          ViaSBtn = False
        end
        object Cdesc5: Text8Pt
          Left = 21
          Top = 98
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 16
          Text = 'TeleSales'
          TextId = 0
          ViaSBtn = False
        end
        object CSS5: Text8Pt
          Tag = 5
          Left = 170
          Top = 98
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 17
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS5: Text8Pt
          Tag = 1005
          Left = 262
          Top = 98
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 18
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST5: Text8Pt
          Left = 350
          Top = 98
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 19
          TextId = 0
          ViaSBtn = False
        end
        object CDesc6: Text8Pt
          Left = 21
          Top = 122
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 20
          Text = 'Account Stock Analysis'
          TextId = 0
          ViaSBtn = False
        end
        object CSS6: Text8Pt
          Tag = 8
          Left = 170
          Top = 122
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 21
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS6: Text8Pt
          Tag = 1008
          Left = 262
          Top = 122
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 22
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST6: Text8Pt
          Left = 350
          Top = 122
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 23
          TextId = 0
          ViaSBtn = False
        end
        object CDesc7: Text8Pt
          Left = 21
          Top = 146
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 24
          Text = 'E-Business'
          TextId = 0
          ViaSBtn = False
        end
        object CSS7: Text8Pt
          Tag = 7
          Left = 170
          Top = 146
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 25
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS7: Text8Pt
          Tag = 1007
          Left = 262
          Top = 146
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 26
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST7: Text8Pt
          Left = 350
          Top = 146
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 27
          TextId = 0
          ViaSBtn = False
        end
        object CDesc8: Text8Pt
          Left = 21
          Top = 170
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 28
          Text = 'Paperless'
          TextId = 0
          ViaSBtn = False
        end
        object CSS8: Text8Pt
          Tag = 8
          Left = 170
          Top = 170
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 29
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS8: Text8Pt
          Tag = 1008
          Left = 262
          Top = 170
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 30
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST8: Text8Pt
          Left = 350
          Top = 170
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 31
          TextId = 0
          ViaSBtn = False
        end
        object CDesc9: Text8Pt
          Left = 21
          Top = 194
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 32
          Text = 'OLE Save Functions'
          TextId = 0
          ViaSBtn = False
        end
        object CSS9: Text8Pt
          Tag = 9
          Left = 170
          Top = 194
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 33
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS9: Text8Pt
          Tag = 1009
          Left = 262
          Top = 194
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 34
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST9: Text8Pt
          Left = 350
          Top = 194
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 35
          TextId = 0
          ViaSBtn = False
        end
        object CDesc10: Text8Pt
          Left = 21
          Top = 218
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 36
          Text = 'Commitment Accounting'
          TextId = 0
          ViaSBtn = False
        end
        object CSS10: Text8Pt
          Tag = 10
          Left = 170
          Top = 218
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 37
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS10: Text8Pt
          Tag = 1010
          Left = 262
          Top = 218
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 38
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST10: Text8Pt
          Left = 350
          Top = 218
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 39
          TextId = 0
          ViaSBtn = False
        end
        object CDesc11: Text8Pt
          Left = 21
          Top = 242
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 40
          Text = 'Trade Counter'
          TextId = 0
          ViaSBtn = False
        end
        object CSS11: Text8Pt
          Tag = 11
          Left = 170
          Top = 242
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 41
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS11: Text8Pt
          Tag = 1011
          Left = 262
          Top = 241
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 42
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST11: Text8Pt
          Left = 350
          Top = 242
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 43
          TextId = 0
          ViaSBtn = False
        end
        object CDesc12: Text8Pt
          Left = 21
          Top = 266
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 44
          Text = 'Std Works Order Processing'
          TextId = 0
          ViaSBtn = False
        end
        object CSS12: Text8Pt
          Tag = 12
          Left = 170
          Top = 266
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 45
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS12: Text8Pt
          Tag = 1012
          Left = 263
          Top = 266
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 46
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST12: Text8Pt
          Left = 350
          Top = 266
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 47
          TextId = 0
          ViaSBtn = False
        end
        object Cdesc13: Text8Pt
          Left = 21
          Top = 290
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 48
          Text = 'Pro Works Order Processing'
          TextId = 0
          ViaSBtn = False
        end
        object CSS13: Text8Pt
          Tag = 13
          Left = 170
          Top = 290
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 49
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS13: Text8Pt
          Tag = 1013
          Left = 262
          Top = 290
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 50
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST13: Text8Pt
          Left = 350
          Top = 290
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 51
          TextId = 0
          ViaSBtn = False
        end
        object Cdesc14: Text8Pt
          Left = 21
          Top = 314
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 52
          Text = 'Sentimail'
          TextId = 0
          ViaSBtn = False
        end
        object CSS14: Text8Pt
          Tag = 14
          Left = 169
          Top = 314
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 53
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS14: Text8Pt
          Tag = 1014
          Left = 262
          Top = 314
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 54
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST14: Text8Pt
          Left = 350
          Top = 314
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 55
          TextId = 0
          ViaSBtn = False
        end
        object Cdesc15: Text8Pt
          Left = 21
          Top = 338
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 56
          Text = 'Enhanced Security'
          TextId = 0
          ViaSBtn = False
        end
        object CSS15: Text8Pt
          Tag = 15
          Left = 170
          Top = 338
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 57
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS15: Text8Pt
          Tag = 1015
          Left = 262
          Top = 338
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 58
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST15: Text8Pt
          Left = 350
          Top = 338
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 59
          TextId = 0
          ViaSBtn = False
        end
        object Cdesc16: Text8Pt
          Left = 21
          Top = 362
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 60
          Text = 'CIS/RCT'
          TextId = 0
          ViaSBtn = False
        end
        object CSS16: Text8Pt
          Tag = 15
          Left = 170
          Top = 362
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 61
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS16: Text8Pt
          Tag = 1015
          Left = 262
          Top = 362
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 62
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST16: Text8Pt
          Left = 350
          Top = 362
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 63
          TextId = 0
          ViaSBtn = False
        end
        object Cdesc17: Text8Pt
          Left = 21
          Top = 386
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 64
          Text = 'Applications & Valuations'
          TextId = 0
          ViaSBtn = False
        end
        object CSS17: Text8Pt
          Tag = 15
          Left = 170
          Top = 386
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 65
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS17: Text8Pt
          Tag = 1015
          Left = 262
          Top = 386
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 66
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST17: Text8Pt
          Left = 350
          Top = 386
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 67
          TextId = 0
          ViaSBtn = False
        end
        object Cdesc18: Text8Pt
          Left = 21
          Top = 410
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 68
          Text = 'Full Stock Control'
          TextId = 0
          ViaSBtn = False
        end
        object CSS18: Text8Pt
          Tag = 15
          Left = 170
          Top = 410
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 69
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS18: Text8Pt
          Tag = 1015
          Left = 262
          Top = 410
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 70
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST18: Text8Pt
          Left = 350
          Top = 410
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 71
          TextId = 0
          ViaSBtn = False
        end
        object Cdesc19: Text8Pt
          Left = 21
          Top = 434
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 72
          Text = 'Visual Report Writer'
          TextId = 0
          ViaSBtn = False
        end
        object CSS19: Text8Pt
          Tag = 15
          Left = 170
          Top = 434
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 73
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS19: Text8Pt
          Tag = 1015
          Left = 262
          Top = 434
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 74
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST19: Text8Pt
          Left = 350
          Top = 434
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 75
          TextId = 0
          ViaSBtn = False
        end
        object CDesc20: Text8Pt
          Left = 21
          Top = 458
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 76
          Text = 'Goods Returns'
          TextId = 0
          ViaSBtn = False
        end
        object CSS20: Text8Pt
          Tag = 15
          Left = 170
          Top = 458
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 77
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS20: Text8Pt
          Tag = 1015
          Left = 262
          Top = 458
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 78
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST20: Text8Pt
          Left = 350
          Top = 458
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 79
          TextId = 0
          ViaSBtn = False
        end
        object CDesc21: Text8Pt
          Left = 21
          Top = 482
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 80
          Text = 'eBanking'
          TextId = 0
          ViaSBtn = False
        end
        object CSS21: Text8Pt
          Tag = 15
          Left = 170
          Top = 482
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 81
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS21: Text8Pt
          Tag = 1015
          Left = 262
          Top = 482
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 82
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST21: Text8Pt
          Left = 350
          Top = 482
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 83
          TextId = 0
          ViaSBtn = False
        end
        object CDesc22: Text8Pt
          Left = 21
          Top = 506
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 84
          Text = 'Outlook Dynamic Dashboard'
          TextId = 0
          ViaSBtn = False
        end
        object CSS22: Text8Pt
          Tag = 15
          Left = 170
          Top = 506
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 85
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS22: Text8Pt
          Tag = 1015
          Left = 262
          Top = 506
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 86
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST22: Text8Pt
          Left = 350
          Top = 506
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 87
          TextId = 0
          ViaSBtn = False
        end
        object CDesc23: Text8Pt
          Left = 21
          Top = 530
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 88
          Text = 'Importer'
          TextId = 0
          ViaSBtn = False
        end
        object CSS23: Text8Pt
          Tag = 15
          Left = 170
          Top = 530
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 89
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS23: Text8Pt
          Tag = 1015
          Left = 262
          Top = 530
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 90
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST23: Text8Pt
          Left = 350
          Top = 530
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 91
          TextId = 0
          ViaSBtn = False
        end
        object CDesc24: Text8Pt
          Left = 21
          Top = 554
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 92
          Text = 'GDPR'
          TextId = 0
          ViaSBtn = False
        end
        object CSS24: Text8Pt
          Tag = 15
          Left = 170
          Top = 554
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 93
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS24: Text8Pt
          Tag = 1015
          Left = 262
          Top = 554
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 94
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST24: Text8Pt
          Left = 350
          Top = 554
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 95
          TextId = 0
          ViaSBtn = False
        end
        object CDesc25: Text8Pt
          Left = 21
          Top = 578
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 96
          Text = 'Pervasive File Encryption'
          TextId = 0
          ViaSBtn = False
        end
        object CSS25: Text8Pt
          Tag = 15
          Left = 170
          Top = 578
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 97
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object RS25: Text8Pt
          Tag = 1015
          Left = 262
          Top = 578
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 98
          OnDblClick = DispPhoneticRelCode
          OnExit = RS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object ST25: Text8Pt
          Left = 350
          Top = 578
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 99
          TextId = 0
          ViaSBtn = False
        end
      end
      object RBtn1: TButton
        Tag = 1
        Left = 29
        Top = 397
        Width = 80
        Height = 21
        Anchors = [akLeft, akBottom]
        Caption = '&Reset'
        Enabled = False
        TabOrder = 1
        OnClick = RBtn1Click
      end
      object OkCP1Btn: TButton
        Tag = 1
        Left = 274
        Top = 398
        Width = 80
        Height = 21
        Anchors = [akLeft, akBottom]
        Caption = '&OK'
        ModalResult = 1
        TabOrder = 2
        OnClick = OkCP1BtnClick
      end
      object CanCP1Btn: TButton
        Tag = 1
        Left = 361
        Top = 398
        Width = 80
        Height = 21
        Anchors = [akLeft, akBottom]
        Cancel = True
        Caption = '&Cancel'
        ModalResult = 2
        TabOrder = 3
        OnClick = OkCP1BtnClick
      end
    end
    object tabshUsers: TTabSheet
      Caption = 'User Counts'
      ImageIndex = 1
      DesignSize = (
        469
        422)
      object Label84: Label8
        Left = 30
        Top = 0
        Width = 141
        Height = 19
        AutoSize = False
        Caption = 'Module Count'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label810: Label8
        Left = 180
        Top = 2
        Width = 84
        Height = 14
        AutoSize = False
        Caption = 'Security'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label811: Label8
        Left = 271
        Top = 2
        Width = 80
        Height = 14
        AutoSize = False
        Caption = 'Release'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label812: Label8
        Left = 359
        Top = 2
        Width = 79
        Height = 14
        AutoSize = False
        Caption = 'User Licence'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object ScrollBox2: TScrollBox
        Left = 4
        Top = 17
        Width = 461
        Height = 375
        Anchors = [akLeft, akTop, akBottom]
        TabOrder = 0
        object Label813: Label8
          Left = 3
          Top = 4
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label826: Label8
          Left = 3
          Top = 29
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label827: Label8
          Left = 3
          Top = 77
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label828: Label8
          Left = 3
          Top = 52
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '3'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object Label829: Label8
          Left = 3
          Top = 101
          Width = 16
          Height = 19
          Alignment = taRightJustify
          AutoSize = False
          Caption = '5'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TextId = 0
        end
        object UCDesc1: Text8Pt
          Left = 21
          Top = 2
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          Text = 'MCM Companies'
          TextId = 0
          ViaSBtn = False
        end
        object UCSS1: Text8Pt
          Tag = 101
          Left = 170
          Top = 2
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 1
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object URS1: Text8Pt
          Tag = 1101
          Left = 262
          Top = 2
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 2
          OnDblClick = DispPhoneticRelCode
          OnExit = URS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object UST1: Text8Pt
          Left = 350
          Top = 2
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          TextId = 0
          ViaSBtn = False
        end
        object UCDesc2: Text8Pt
          Left = 21
          Top = 26
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 4
          Text = 'SDK Toolkits 30-Day'
          TextId = 0
          ViaSBtn = False
        end
        object URS2: Text8Pt
          Tag = 1102
          Left = 262
          Top = 26
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 5
          OnDblClick = DispPhoneticRelCode
          OnExit = URS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object UST2: Text8Pt
          Left = 350
          Top = 26
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 6
          TextId = 0
          ViaSBtn = False
        end
        object UCDesc3: Text8Pt
          Left = 21
          Top = 50
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 7
          Text = 'SDK Toolkits Full'
          TextId = 0
          ViaSBtn = False
        end
        object UCSS3: Text8Pt
          Tag = 103
          Left = 170
          Top = 50
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 8
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object URS3: Text8Pt
          Tag = 1103
          Left = 262
          Top = 50
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 9
          OnDblClick = DispPhoneticRelCode
          OnExit = URS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object UST3: Text8Pt
          Left = 350
          Top = 50
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 10
          TextId = 0
          ViaSBtn = False
        end
        object UCSS2: Text8Pt
          Tag = 102
          Left = 170
          Top = 26
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 11
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object UCDesc4: Text8Pt
          Left = 21
          Top = 74
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 12
          Text = 'Trade Counter'
          TextId = 0
          ViaSBtn = False
        end
        object UCSS4: Text8Pt
          Tag = 104
          Left = 170
          Top = 74
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 13
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object URS4: Text8Pt
          Tag = 1104
          Left = 263
          Top = 74
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 14
          OnDblClick = DispPhoneticRelCode
          OnExit = URS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object UST4: Text8Pt
          Left = 350
          Top = 74
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 15
          TextId = 0
          ViaSBtn = False
        end
        object UCDesc5: Text8Pt
          Left = 21
          Top = 98
          Width = 147
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 16
          Text = 'Sentimail Sentinels'
          TextId = 0
          ViaSBtn = False
        end
        object UCSS5: Text8Pt
          Tag = 105
          Left = 170
          Top = 98
          Width = 90
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 17
          OnDblClick = DispPhoneticSecCode
          TextId = 0
          ViaSBtn = False
        end
        object URS5: Text8Pt
          Tag = 1105
          Left = 262
          Top = 98
          Width = 86
          Height = 22
          CharCase = ecUpperCase
          Color = clTeal
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 18
          OnDblClick = DispPhoneticRelCode
          OnExit = URS1Exit
          TextId = 0
          ViaSBtn = False
        end
        object UST5: Text8Pt
          Left = 350
          Top = 98
          Width = 85
          Height = 22
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 11
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 19
          TextId = 0
          ViaSBtn = False
        end
      end
      object Button1: TButton
        Tag = 1
        Left = 29
        Top = 397
        Width = 80
        Height = 21
        Anchors = [akLeft, akBottom]
        Caption = '&Reset'
        TabOrder = 1
        OnClick = RBtn1Click
      end
      object Button2: TButton
        Tag = 1
        Left = 274
        Top = 398
        Width = 80
        Height = 21
        Anchors = [akLeft, akBottom]
        Caption = '&OK'
        ModalResult = 1
        TabOrder = 2
        OnClick = OkCP1BtnClick
      end
      object Button3: TButton
        Tag = 1
        Left = 361
        Top = 398
        Width = 80
        Height = 21
        Anchors = [akLeft, akBottom]
        Cancel = True
        Caption = '&Cancel'
        ModalResult = 2
        TabOrder = 3
        OnClick = OkCP1BtnClick
      end
    end
    object tabshPlugIn: TTabSheet
      Caption = 'Plug-Ins && Utilities'
      ImageIndex = 2
      DesignSize = (
        469
        422)
      object scrlPlugIns: TScrollBox
        Left = 4
        Top = 4
        Width = 461
        Height = 388
        Anchors = [akLeft, akTop, akBottom]
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object Button4: TButton
        Tag = 1
        Left = 29
        Top = 397
        Width = 80
        Height = 21
        Anchors = [akLeft, akBottom]
        Caption = '&Reset'
        TabOrder = 1
        OnClick = RBtn1Click
      end
      object Button5: TButton
        Tag = 1
        Left = 274
        Top = 398
        Width = 80
        Height = 21
        Anchors = [akLeft, akBottom]
        Caption = '&OK'
        ModalResult = 1
        TabOrder = 2
        OnClick = OkCP1BtnClick
      end
      object Button6: TButton
        Tag = 1
        Left = 361
        Top = 398
        Width = 80
        Height = 21
        Anchors = [akLeft, akBottom]
        Cancel = True
        Caption = '&Cancel'
        ModalResult = 2
        TabOrder = 3
        OnClick = OkCP1BtnClick
      end
    end
  end
end
