object frmCustHistory: TfrmCustHistory
  Left = 355
  Top = 190
  Width = 924
  Height = 386
  Caption = 'Customer History'
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  OldCreateOrder = False
  Position = poDefault
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnResize = FormResize
  PixelsPerInch = 96
  TextHeight = 14
  object PageControl: TPageControl
    Left = 4
    Top = 4
    Width = 901
    Height = 341
    ActivePage = LedgerPage
    TabIndex = 0
    TabOrder = 0
    object LedgerPage: TTabSheet
      Caption = 'Ledger'
      object BtListBox: TScrollBox
        Left = 1
        Top = 2
        Width = 771
        Height = 307
        VertScrollBar.Tracking = True
        VertScrollBar.Visible = False
        TabOrder = 0
        object BtListHeaderPanel: TSBSPanel
          Left = 1
          Top = 3
          Width = 763
          Height = 19
          BevelInner = bvLowered
          BevelOuter = bvNone
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumnHeader
          object CLORefLab: TSBSPanel
            Left = 2
            Top = 2
            Width = 67
            Height = 14
            BevelOuter = bvNone
            Caption = 'Our Ref'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 0
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLDateLab: TSBSPanel
            Left = 72
            Top = 2
            Width = 67
            Height = 14
            BevelOuter = bvNone
            Caption = 'Date'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 1
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLAmtLab: TSBSPanel
            Left = 142
            Top = 2
            Width = 100
            Height = 14
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Amount Settled'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 2
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLOSLab: TSBSPanel
            Left = 244
            Top = 2
            Width = 98
            Height = 14
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Outstanding'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 3
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLTotLab: TSBSPanel
            Left = 344
            Top = 2
            Width = 98
            Height = 14
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Total Value'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 4
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLYRefLab: TSBSPanel
            Left = 542
            Top = 2
            Width = 68
            Height = 14
            BevelOuter = bvNone
            Caption = 'Your Ref'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 5
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLDueLab: TSBSPanel
            Left = 614
            Top = 2
            Width = 68
            Height = 14
            BevelOuter = bvNone
            Caption = 'Date Due'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 6
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLOrigLab: TSBSPanel
            Left = 449
            Top = 3
            Width = 97
            Height = 14
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Original Value  '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 7
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLStatLab: TSBSPanel
            Left = 689
            Top = 2
            Width = 71
            Height = 14
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Status  '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 8
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
        end
        object CLDatePanel: TSBSPanel
          Left = 73
          Top = 25
          Width = 69
          Height = 261
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLAMTPanel: TSBSPanel
          Left = 145
          Top = 25
          Width = 98
          Height = 261
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLOSPAnel: TSBSPanel
          Left = 246
          Top = 25
          Width = 98
          Height = 261
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLTotPanel: TSBSPanel
          Left = 347
          Top = 25
          Width = 98
          Height = 261
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLYRefPanel: TSBSPanel
          Left = 549
          Top = 25
          Width = 69
          Height = 261
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 5
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLDuePanel: TSBSPanel
          Left = 621
          Top = 25
          Width = 69
          Height = 261
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 6
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLOrigPanel: TSBSPanel
          Left = 448
          Top = 25
          Width = 98
          Height = 261
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 7
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLStatPanel: TSBSPanel
          Left = 693
          Top = 25
          Width = 69
          Height = 261
          HelpContext = 617
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 8
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLORefPanel: TSBSPanel
          Left = 1
          Top = 25
          Width = 69
          Height = 261
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 9
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
      end
      object BtListBtnPanel: TSBSPanel
        Left = 776
        Top = 28
        Width = 18
        Height = 262
        BevelOuter = bvLowered
        TabOrder = 1
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
      end
    end
  end
  object BtnPanel: TSBSPanel
    Left = 808
    Top = 32
    Width = 91
    Height = 309
    BevelOuter = bvLowered
    TabOrder = 1
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    object I1BSBox: TScrollBox
      Left = 1
      Top = 3
      Width = 88
      Height = 187
      HorzScrollBar.Visible = False
      BorderStyle = bsNone
      TabOrder = 0
      object btnViewLine: TButton
        Left = 4
        Top = 32
        Width = 80
        Height = 21
        Hint = 
          'Find Stock Code|Choosing this option allows you to move to the n' +
          'ext line containing a specified Stock Code.'
        HelpContext = 264
        Caption = '&View'
        TabOrder = 0
        OnClick = btnViewLineClick
      end
      object btnClose: TButton
        Left = 4
        Top = 1
        Width = 80
        Height = 21
        HelpContext = 259
        Cancel = True
        Caption = 'C&lose'
        ModalResult = 2
        TabOrder = 1
        OnClick = btnCloseClick
      end
    end
  end
  object PopupMenu: TPopupMenu
    Left = 15
    Top = 62
    object ViewTransaction: TMenuItem
      Caption = '&View Transaction'
      OnClick = ViewTransactionClick
    end
    object N2: TMenuItem
      Caption = '-'
    end
    object PropFlg: TMenuItem
      Caption = '&Properties'
      Hint = 'Access Colour & Font settings'
      Visible = False
    end
    object N1: TMenuItem
      Caption = '-'
      Visible = False
    end
    object StoreCoordFlg: TMenuItem
      AutoCheck = True
      Caption = '&Save Coordinates'
      OnClick = StoreCoordFlgClick
    end
    object ResetCoordinates1: TMenuItem
      AutoCheck = True
      Caption = '&Reset Coordinates'
      OnClick = ResetCoordinates1Click
    end
  end
end
