object frmStkAdj: TfrmStkAdj
  Left = 404
  Top = 218
  Width = 644
  Height = 389
  Caption = 'frmStkAdj'
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poDefault
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  OnResize = FormResize
  PixelsPerInch = 96
  TextHeight = 14
  object PageControl: TPageControl
    Left = 4
    Top = 4
    Width = 621
    Height = 345
    ActivePage = MainPage
    TabIndex = 0
    TabOrder = 0
    TabStop = False
    object MainPage: TTabSheet
      Caption = 'Data Entry'
      object I1ListBtnPanel: TSBSPanel
        Left = 501
        Top = 92
        Width = 18
        Height = 187
        BevelOuter = bvLowered
        TabOrder = 0
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
      end
      object A1FPanel: TSBSPanel
        Left = 2
        Top = 4
        Width = 517
        Height = 61
        BevelOuter = bvNone
        TabOrder = 1
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object Label817: Label8
          Left = 186
          Top = 5
          Width = 38
          Height = 14
          Caption = 'Our Ref'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label87: Label8
          Left = 14
          Top = 5
          Width = 25
          Height = 14
          Caption = 'Desc'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label816: Label8
          Left = 338
          Top = 5
          Width = 68
          Height = 14
          Caption = 'Last edited by'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object LTxfrLab: Label8
          Left = 324
          Top = 43
          Width = 82
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'In Loc Transfer '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object A1OrefF: Text8Pt
          Left = 229
          Top = 1
          Width = 79
          Height = 22
          HelpContext = 142
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          TextId = 0
          ViaSBtn = False
        end
        object A1OpoF: Text8Pt
          Left = 409
          Top = 1
          Width = 86
          Height = 22
          HelpContext = 241
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 4
          TextId = 0
          ViaSBtn = False
        end
        object A1YRefF: Text8Pt
          Tag = 1
          Left = 42
          Top = 0
          Width = 139
          Height = 22
          HelpContext = 441
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 1
          TextId = 0
          ViaSBtn = False
        end
        object A1LocTxF: Text8Pt
          Tag = 1
          Left = 409
          Top = 38
          Width = 86
          Height = 22
          Hint = 
            'In Location Transfer|Use this box to specify the In (receiving) ' +
            'location against any lines added to the body of the stock adjust' +
            'ment.'
          HelpContext = 373
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          TextId = 0
          ViaSBtn = False
        end
        object TransExtForm1: TSBSExtendedForm
          Left = 6
          Top = 23
          Width = 319
          Height = 37
          HelpContext = 1169
          HorzScrollBar.Visible = False
          VertScrollBar.Visible = False
          AutoScroll = False
          BorderStyle = bsNone
          TabOrder = 2
          ArrowPos = alTop
          ArrowX = 148
          ArrowY = 13
          OrigHeight = 37
          OrigWidth = 319
          ExpandedWidth = 319
          ExpandedHeight = 170
          OrigTabOrder = 2
          ShowHorzSB = True
          ShowVertSB = True
          OrigParent = A1FPanel
          NewParent = Owner
          FocusFirst = A1YRef2F
          FocusLast = THUD4F
          TabPrev = A1YRefF
          TabNext = A1LocTxF
          object UDF1L: Label8
            Left = 7
            Top = 50
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 1'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF3L: Label8
            Left = 7
            Top = 74
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 3'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF2L: Label8
            Left = 151
            Top = 50
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 2'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF4L: Label8
            Left = 151
            Top = 74
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 4'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label84: Label8
            Left = 131
            Top = 1
            Width = 22
            Height = 14
            Caption = 'Date'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label88: Label8
            Left = 222
            Top = 1
            Width = 31
            Height = 14
            Caption = 'Per/Yr'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label89: Label8
            Left = 38
            Top = 1
            Width = 43
            Height = 14
            Caption = 'Your Ref'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF5L: Label8
            Left = 7
            Top = 98
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 5'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF7L: Label8
            Left = 7
            Top = 122
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 7'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF9L: Label8
            Left = 7
            Top = 146
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 9'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF6L: Label8
            Left = 151
            Top = 98
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 6'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF8L: Label8
            Left = 151
            Top = 122
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 8'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF10L: Label8
            Left = 151
            Top = 146
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 10'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object THUD1F: Text8Pt
            Tag = 1
            Left = 65
            Top = 46
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 3
            TextId = 0
            ViaSBtn = False
          end
          object THUD3F: Text8Pt
            Tag = 1
            Left = 65
            Top = 70
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 5
            TextId = 0
            ViaSBtn = False
          end
          object THUD4F: Text8Pt
            Tag = 1
            Left = 210
            Top = 70
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 6
            TextId = 0
            ViaSBtn = False
          end
          object THUD2F: Text8Pt
            Tag = 1
            Left = 210
            Top = 46
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 4
            TextId = 0
            ViaSBtn = False
          end
          object A1TDateF: TEditDate
            Tag = 1
            Left = 130
            Top = 15
            Width = 79
            Height = 22
            HelpContext = 143
            AutoSelect = False
            EditMask = '00/00/0000;0;'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 10
            ParentFont = False
            ReadOnly = True
            TabOrder = 1
            Placement = cpAbove
          end
          object A1TPerF: TEditPeriod
            Tag = 1
            Left = 222
            Top = 15
            Width = 78
            Height = 22
            HelpContext = 239
            AutoSelect = False
            EditMask = '00/0000;0;'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 7
            ParentFont = False
            ReadOnly = True
            TabOrder = 2
            Text = 'mmyyyy'
            Placement = cpAbove
            EPeriod = 1
            EYear = 1996
            ViewMask = '000/0000;0;'
          end
          object A1YRef2F: Text8Pt
            Tag = 1
            Left = 36
            Top = 15
            Width = 84
            Height = 22
            HelpContext = 441
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 0
            TextId = 0
            ViaSBtn = False
          end
          object THUD5F: Text8Pt
            Tag = 1
            Left = 65
            Top = 94
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 7
            TextId = 0
            ViaSBtn = False
          end
          object THUD7F: Text8Pt
            Tag = 1
            Left = 65
            Top = 118
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 9
            TextId = 0
            ViaSBtn = False
          end
          object THUD9F: Text8Pt
            Tag = 1
            Left = 65
            Top = 142
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 11
            TextId = 0
            ViaSBtn = False
          end
          object THUD6F: Text8Pt
            Tag = 1
            Left = 210
            Top = 94
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 8
            TextId = 0
            ViaSBtn = False
          end
          object THUD8F: Text8Pt
            Tag = 1
            Left = 210
            Top = 118
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 10
            TextId = 0
            ViaSBtn = False
          end
          object THUD10F: Text8Pt
            Tag = 1
            Left = 210
            Top = 142
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 12
            TextId = 0
            ViaSBtn = False
          end
        end
      end
      object A1BtmPanel: TSBSPanel
        Left = 0
        Top = 296
        Width = 613
        Height = 20
        Align = alBottom
        BevelOuter = bvNone
        TabOrder = 2
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object CCPanel: TSBSPanel
          Left = 0
          Top = 3
          Width = 118
          Height = 17
          HelpContext = 433
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object CCTit: Label8
            Left = 3
            Top = 2
            Width = 17
            Height = 14
            Caption = 'CC:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object DepTit: Label8
            Left = 57
            Top = 2
            Width = 22
            Height = 14
            Caption = 'Dep:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object CCLab: Label8
            Left = 23
            Top = 2
            Width = 30
            Height = 14
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
          object DepLab: Label8
            Left = 81
            Top = 2
            Width = 30
            Height = 14
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
        end
        object SBSPanel5: TSBSPanel
          Left = 121
          Top = 3
          Width = 136
          Height = 17
          HelpContext = 442
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 1
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object DrReqdTit: Label8
            Left = 4
            Top = 2
            Width = 46
            Height = 14
            Caption = 'Unit Cost:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object CostLab: Label8
            Left = 53
            Top = 2
            Width = 80
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
        end
        object SBSPanel4: TSBSPanel
          Left = 260
          Top = 3
          Width = 253
          Height = 17
          HelpContext = 443
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 2
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object CrReqdTit: Label8
            Left = 4
            Top = 2
            Width = 42
            Height = 14
            Caption = 'G/L Acc:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object GLLab: Label8
            Left = 55
            Top = 2
            Width = 194
            Height = 14
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
        end
      end
      object A1SBox: TScrollBox
        Left = 0
        Top = 68
        Width = 500
        Height = 229
        HorzScrollBar.Tracking = True
        VertScrollBar.Tracking = True
        VertScrollBar.Visible = False
        TabOrder = 3
        object A1HedPanel: TSBSPanel
          Left = 2
          Top = 2
          Width = 661
          Height = 17
          BevelInner = bvLowered
          BevelOuter = bvNone
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumnHeader
          object A1CLab: TSBSPanel
            Left = 2
            Top = 2
            Width = 94
            Height = 13
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = '  Stock Code'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 0
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object A1GLab: TSBSPanel
            Left = 507
            Top = 2
            Width = 59
            Height = 13
            BevelOuter = bvNone
            Caption = 'G/L Code'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 1
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object A1OLab: TSBSPanel
            Left = 267
            Top = 2
            Width = 69
            Height = 13
            BevelOuter = bvNone
            Caption = 'Out (-)'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 2
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object A1DLab: TSBSPanel
            Left = 99
            Top = 2
            Width = 99
            Height = 13
            BevelOuter = bvNone
            Caption = 'Description'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 3
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object A1ILab: TSBSPanel
            Left = 198
            Top = 2
            Width = 68
            Height = 13
            BevelOuter = bvNone
            Caption = 'In (+)'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 4
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object A1CCLab: TSBSPanel
            Left = 568
            Top = 2
            Width = 35
            Height = 13
            BevelOuter = bvNone
            Caption = 'CC'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 5
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object A1DpLab: TSBSPanel
            Left = 605
            Top = 2
            Width = 34
            Height = 13
            BevelOuter = bvNone
            Caption = 'Dept'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 6
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object A1BLab: TSBSPanel
            Left = 338
            Top = 2
            Width = 34
            Height = 13
            BevelOuter = bvNone
            Caption = 'Build'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 7
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object A1ULab: TSBSPanel
            Left = 375
            Top = 2
            Width = 80
            Height = 13
            BevelOuter = bvNone
            Caption = 'Unit Cost'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 8
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object A1LocLab: TSBSPanel
            Left = 455
            Top = 2
            Width = 52
            Height = 13
            BevelOuter = bvNone
            Caption = 'Location'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 9
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
        end
        object A1CPanel: TSBSPanel
          Left = 3
          Top = 22
          Width = 97
          Height = 187
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
        end
        object A1IPanel: TSBSPanel
          Left = 201
          Top = 22
          Width = 68
          Height = 187
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
        end
        object A1GPanel: TSBSPanel
          Left = 511
          Top = 22
          Width = 59
          Height = 187
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
        end
        object A1DPanel: TSBSPanel
          Left = 102
          Top = 22
          Width = 97
          Height = 187
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
        end
        object A1OPanel: TSBSPanel
          Left = 271
          Top = 22
          Width = 68
          Height = 187
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 5
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
        end
        object A1CCPanel: TSBSPanel
          Left = 572
          Top = 22
          Width = 35
          Height = 187
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 6
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
        end
        object A1DpPanel: TSBSPanel
          Left = 609
          Top = 22
          Width = 35
          Height = 187
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 7
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
        end
        object A1BPanel: TSBSPanel
          Left = 341
          Top = 22
          Width = 35
          Height = 187
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 8
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
        end
        object A1UPanel: TSBSPanel
          Left = 378
          Top = 22
          Width = 79
          Height = 187
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 9
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
        end
        object A1LocPanel: TSBSPanel
          Left = 459
          Top = 22
          Width = 50
          Height = 187
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 10
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
        end
      end
    end
  end
  object BtnPanel: TSBSPanel
    Left = 529
    Top = 28
    Width = 91
    Height = 317
    BevelOuter = bvLowered
    TabOrder = 1
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    object I1StatLab: Label8
      Left = 4
      Top = 3
      Width = 85
      Height = 36
      Alignment = taCenter
      AutoSize = False
      Caption = 'I1StatLab'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object I1BSBox: TScrollBox
      Left = 1
      Top = 43
      Width = 88
      Height = 187
      HorzScrollBar.Visible = False
      BorderStyle = bsNone
      PopupMenu = PopupMenu
      TabOrder = 0
      object btnViewLine: TButton
        Left = 4
        Top = 32
        Width = 80
        Height = 21
        Hint = 
          'Find Stock Code|Choosing this option allows you to move to the n' +
          'ext line containing a specified Stock Code.'
        HelpContext = 264
        Caption = '&View'
        TabOrder = 0
        OnClick = btnViewLineClick
      end
      object btnClose: TButton
        Left = 4
        Top = 1
        Width = 80
        Height = 21
        HelpContext = 259
        Cancel = True
        Caption = 'C&lose'
        ModalResult = 2
        TabOrder = 1
        OnClick = btnCloseClick
      end
    end
  end
  object PopupMenu: TPopupMenu
    Left = 9
    Top = 55
    object View1: TMenuItem
      Caption = '&View'
      OnClick = btnViewLineClick
    end
    object N3: TMenuItem
      Caption = '-'
      Enabled = False
      Visible = False
    end
    object PropFlg: TMenuItem
      Caption = '&Properties'
      HelpContext = 65
      Hint = 'Access Colour & Font settings'
      Visible = False
      OnClick = PropFlgClick
    end
    object N1: TMenuItem
      Caption = '-'
    end
    object StoreCoordFlg: TMenuItem
      AutoCheck = True
      Caption = '&Save Coordinates'
      HelpContext = 177
      Hint = 'Make the current window settings permanent'
      OnClick = StoreCoordFlgClick
    end
    object ResetCoordinates1: TMenuItem
      Caption = '&Reset Coordinates'
      OnClick = ResetCoordinates1Click
    end
  end
end
