object frmStock: TfrmStock
  Left = 372
  Top = 200
  Width = 734
  Height = 394
  BorderIcons = [biSystemMenu]
  Caption = 'Stock History'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  OldCreateOrder = False
  PopupMenu = PopupMenu
  Position = poDefault
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnResize = FormResize
  PixelsPerInch = 96
  TextHeight = 14
  object PageControl: TPageControl
    Left = 4
    Top = 4
    Width = 708
    Height = 348
    ActivePage = LedgerPage
    TabIndex = 3
    TabOrder = 0
    OnChange = PageControlChange
    object MainPage: TTabSheet
      Caption = 'Main'
      ImageIndex = 1
      object TCMScrollBox: TScrollBox
        Left = -2
        Top = 0
        Width = 471
        Height = 319
        VertScrollBar.Visible = False
        BorderStyle = bsNone
        TabOrder = 0
        object SBSBackGroup1: TSBSBackGroup
          Left = 5
          Top = 4
          Width = 289
          Height = 156
          Caption = 'Stock Code/Description'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          TextId = 0
        end
        object Label85: Label8
          Left = 187
          Top = 29
          Width = 23
          Height = 14
          Caption = 'Type'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object SBSBackGroup2: TSBSBackGroup
          Left = 5
          Top = 160
          Width = 289
          Height = 154
          TextId = 0
        end
        object Label828: Label8
          Left = 29
          Top = 209
          Width = 27
          Height = 14
          Caption = 'Sales'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label829: Label8
          Left = 34
          Top = 236
          Width = 22
          Height = 14
          Caption = 'Cost'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label830: Label8
          Left = 13
          Top = 261
          Width = 43
          Height = 14
          Caption = 'Re-order'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object SBSBackGroup3: TSBSBackGroup
          Left = 299
          Top = 264
          Width = 154
          Height = 50
          TextId = 0
        end
        object ValLab: Label8
          Left = 11
          Top = 281
          Width = 44
          Height = 14
          Caption = 'Valuation'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object ValLab2: Label8
          Left = 21
          Top = 295
          Width = 35
          Height = 14
          Caption = 'Method'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object SBSBackGroup4: TSBSBackGroup
          Left = 299
          Top = 4
          Width = 154
          Height = 260
          TextId = 0
        end
        object Label836: Label8
          Left = 327
          Top = 97
          Width = 26
          Height = 14
          Caption = 'In Stk'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label837: Label8
          Left = 308
          Top = 159
          Width = 45
          Height = 14
          Caption = 'Allocated'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label838: Label8
          Left = 301
          Top = 190
          Width = 52
          Height = 15
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Free Stk'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label834: Label8
          Left = 308
          Top = 233
          Width = 45
          Height = 14
          Caption = 'On Order'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label835: Label8
          Left = 312
          Top = 128
          Width = 41
          Height = 14
          Caption = '(Posted)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label827: Label8
          Left = 319
          Top = 23
          Width = 34
          Height = 14
          Caption = 'Min Stk'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label831: Label8
          Left = 315
          Top = 55
          Width = 38
          Height = 14
          Caption = 'Max Stk'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Bevel1: TBevel
          Left = 312
          Top = 82
          Width = 132
          Height = 2
        end
        object Bevel2: TBevel
          Left = 310
          Top = 218
          Width = 133
          Height = 2
        end
        object Label832: Label8
          Left = 11
          Top = 180
          Width = 45
          Height = 14
          Caption = 'Priced by'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label1: TLabel
          Left = 310
          Top = 277
          Width = 107
          Height = 28
          Alignment = taRightJustify
          Caption = 'Show stock levels as sales units (packs)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          WordWrap = True
        end
        object SROOF: TCurrencyEdit
          Left = 358
          Top = 227
          Width = 86
          Height = 24
          HelpContext = 195
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 12
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object SRCF: Text8Pt
          Tag = 1
          Left = 14
          Top = 25
          Width = 165
          Height = 22
          HelpContext = 188
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          TextId = 0
          ViaSBtn = False
        end
        object SRISF: TCurrencyEdit
          Left = 358
          Top = 92
          Width = 86
          Height = 23
          HelpContext = 195
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 8
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object SRPOF: TCurrencyEdit
          Left = 358
          Top = 123
          Width = 86
          Height = 23
          HelpContext = 195
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 9
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object SRALF: TCurrencyEdit
          Left = 358
          Top = 154
          Width = 86
          Height = 24
          HelpContext = 195
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 10
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object SRFRF: TCurrencyEdit
          Left = 358
          Top = 184
          Width = 86
          Height = 24
          HelpContext = 195
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 11
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object SRCPF: TCurrencyEdit
          Tag = 1
          Left = 115
          Top = 232
          Width = 103
          Height = 23
          HelpContext = 191
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 2
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object SRRPF: TCurrencyEdit
          Tag = 1
          Left = 115
          Top = 258
          Width = 103
          Height = 24
          HelpContext = 192
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 4
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object SRRPCF: TSBSComboBox
          Tag = 1
          Left = 61
          Top = 258
          Width = 52
          Height = 22
          HelpContext = 192
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ItemHeight = 0
          MaxLength = 3
          ParentFont = False
          TabOrder = 3
          ExtendedList = True
          MaxListWidth = 115
          ReadOnly = True
          Validate = True
        end
        object SRMIF: TCurrencyEdit
          Tag = 1
          Left = 358
          Top = 19
          Width = 86
          Height = 24
          HelpContext = 194
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 6
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object SRMXF: TCurrencyEdit
          Tag = 1
          Left = 358
          Top = 51
          Width = 86
          Height = 23
          HelpContext = 194
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 7
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object SRSPF: TBorCheck
          Tag = 1
          Left = 424
          Top = 281
          Width = 18
          Height = 22
          HelpContext = 544
          Align = alRight
          Color = clBtnFace
          Enabled = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentColor = False
          ParentFont = False
          TabOrder = 13
          TabStop = True
          TextId = 0
        end
        object SRSP1F: TCurrencyEdit
          Tag = 1
          Left = 61
          Top = 205
          Width = 103
          Height = 23
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 1
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = True
          TextId = 0
          Value = 1E-10
        end
        object SRGP1: TCurrencyEdit
          Tag = 1
          Left = 165
          Top = 205
          Width = 53
          Height = 23
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '1.0 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 14
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.0 ;###,###,##0.0-'
          DecPlaces = 1
          ShowCurrency = False
          TextId = 0
          Value = 1
        end
        object SRMBF: TBorCheck
          Tag = 1
          Left = 191
          Top = 284
          Width = 98
          Height = 22
          HelpContext = 1459
          Caption = 'Use Multi Bins'
          Color = clBtnFace
          Enabled = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentColor = False
          ParentFont = False
          TabOrder = 5
          TabStop = True
          TextId = 0
        end
        object SRSBox1: TScrollBox
          Left = 14
          Top = 53
          Width = 271
          Height = 102
          HelpContext = 162
          HorzScrollBar.Visible = False
          VertScrollBar.Position = 40
          Ctl3D = True
          ParentCtl3D = False
          TabOrder = 15
          object Label812: Label8
            Left = 239
            Top = -34
            Width = 6
            Height = 14
            Caption = '1'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label813: Label8
            Left = 239
            Top = -10
            Width = 6
            Height = 14
            Caption = '2'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label814: Label8
            Left = 239
            Top = 16
            Width = 6
            Height = 14
            Caption = '3'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label815: Label8
            Left = 239
            Top = 41
            Width = 6
            Height = 14
            Caption = '4'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label816: Label8
            Left = 239
            Top = 66
            Width = 6
            Height = 14
            Caption = '5'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label817: Label8
            Left = 239
            Top = 89
            Width = 6
            Height = 14
            Caption = '6'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object SRD1F: Text8Pt
            Tag = 1
            Left = 2
            Top = -38
            Width = 235
            Height = 24
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 0
            TextId = 0
            ViaSBtn = False
          end
          object SRD2F: Text8Pt
            Tag = 1
            Left = 2
            Top = -13
            Width = 235
            Height = 24
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 1
            TextId = 0
            ViaSBtn = False
          end
          object SRD3F: Text8Pt
            Tag = 1
            Left = 2
            Top = 12
            Width = 235
            Height = 23
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 2
            TextId = 0
            ViaSBtn = False
          end
          object SRD4F: Text8Pt
            Tag = 1
            Left = 2
            Top = 36
            Width = 235
            Height = 24
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 3
            TextId = 0
            ViaSBtn = False
          end
          object SRD5F: Text8Pt
            Tag = 1
            Left = 2
            Top = 61
            Width = 235
            Height = 24
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 4
            TextId = 0
            ViaSBtn = False
          end
          object SRD6F: Text8Pt
            Tag = 1
            Left = 2
            Top = 86
            Width = 235
            Height = 24
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 5
            TextId = 0
            ViaSBtn = False
          end
        end
        object SRTF: TEdit
          Left = 215
          Top = 25
          Width = 70
          Height = 22
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 16
        end
        object txtStockPricing: Text8Pt
          Left = 61
          Top = 177
          Width = 225
          Height = 22
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 17
          TextId = 0
          ViaSBtn = False
        end
        object SRCPCF: Text8Pt
          Left = 61
          Top = 232
          Width = 52
          Height = 22
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ShowHint = True
          TabOrder = 18
          TextId = 0
          ViaSBtn = False
        end
        object SRVMF: Text8Pt
          Left = 61
          Top = 284
          Width = 130
          Height = 22
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 19
          TextId = 0
          ViaSBtn = False
        end
      end
    end
    object WOPPage: TTabSheet
      Caption = 'WOP'
      ImageIndex = 2
      object SBSBackGroup11: TSBSBackGroup
        Left = 2
        Top = 4
        Width = 449
        Height = 113
        TextId = 0
      end
      object SBSBackGroup10: TSBSBackGroup
        Left = 2
        Top = 120
        Width = 236
        Height = 119
        TextId = 0
      end
      object Label854: Label8
        Left = 8
        Top = 211
        Width = 107
        Height = 15
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Picked on WOR'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label845: Label8
        Left = 9
        Top = 169
        Width = 106
        Height = 15
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Issued to WOR'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label846: Label8
        Left = 5
        Top = 140
        Width = 110
        Height = 15
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Allocated to WOR'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label855: Label8
        Left = 42
        Top = 88
        Width = 73
        Height = 14
        Alignment = taRightJustify
        Caption = 'Issued WIP G/L'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label856: Label8
        Left = 6
        Top = 32
        Width = 109
        Height = 15
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Prod./Assembly Time'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Bevel10: TBevel
        Left = 19
        Top = 196
        Width = 210
        Height = 2
      end
      object Label857: Label8
        Left = 11
        Top = 61
        Width = 104
        Height = 15
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Re-order Lead Time'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label858: Label8
        Left = 165
        Top = 60
        Width = 27
        Height = 14
        Caption = ' days'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label859: Label8
        Left = 121
        Top = 13
        Width = 27
        Height = 14
        Caption = ' days'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label860: Label8
        Left = 167
        Top = 13
        Width = 19
        Height = 14
        Caption = ' hrs'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label861: Label8
        Left = 202
        Top = 13
        Width = 22
        Height = 14
        Caption = 'mins'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label862: Label8
        Left = 249
        Top = 60
        Width = 111
        Height = 14
        Alignment = taRightJustify
        Caption = 'Min. economic build qty'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object SRPWF: TCurrencyEdit
        Left = 120
        Top = 206
        Width = 109
        Height = 23
        HelpContext = 1270
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object SRIWF: TCurrencyEdit
        Left = 120
        Top = 164
        Width = 109
        Height = 23
        HelpContext = 1270
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object SRAWF: TCurrencyEdit
        Left = 120
        Top = 136
        Width = 109
        Height = 23
        HelpContext = 1270
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object SRGIF: Text8Pt
        Tag = 1
        Left = 120
        Top = 83
        Width = 109
        Height = 24
        HelpContext = 1222
        AutoSize = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 3
        TextId = 0
        ViaSBtn = False
      end
      object FGLIF: Text8Pt
        Left = 234
        Top = 83
        Width = 211
        Height = 24
        HelpContext = 1222
        TabStop = False
        AutoSize = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 4
        TextId = 0
        ViaSBtn = False
      end
      object SRROLTF: TCurrencyEdit
        Tag = 1
        Left = 120
        Top = 56
        Width = 40
        Height = 24
        HelpContext = 1268
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0 ')
        MaxLength = 3
        ParentFont = False
        ReadOnly = True
        TabOrder = 5
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0 ;###,###,##0-'
        DecPlaces = 0
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object SRASSDF: TCurrencyEdit
        Tag = 1
        Left = 120
        Top = 28
        Width = 40
        Height = 24
        HelpContext = 1265
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '1 ')
        MaxLength = 3
        ParentFont = False
        ReadOnly = True
        TabOrder = 6
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0 ;###,###,##0-'
        DecPlaces = 0
        ShowCurrency = False
        TextId = 0
        Value = 1
      end
      object SRASSHF: TCurrencyEdit
        Tag = 1
        Left = 166
        Top = 28
        Width = 30
        Height = 24
        HelpContext = 1265
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '1 ')
        MaxLength = 2
        ParentFont = False
        ReadOnly = True
        TabOrder = 7
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0 ;###,###,##0-'
        DecPlaces = 0
        ShowCurrency = False
        TextId = 0
        Value = 1
      end
      object SRASSMF: TCurrencyEdit
        Tag = 1
        Left = 201
        Top = 28
        Width = 31
        Height = 24
        HelpContext = 1265
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '1 ')
        MaxLength = 2
        ParentFont = False
        ReadOnly = True
        TabOrder = 8
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0 ;###,###,##0-'
        DecPlaces = 0
        ShowCurrency = False
        TextId = 0
        Value = 1
      end
      object CBCalcProdT: TBorCheck
        Tag = 1
        Left = 284
        Top = 29
        Width = 158
        Height = 22
        HelpContext = 1266
        Caption = 'Auto Calculate Prod. Time'
        Color = clBtnFace
        Enabled = False
        ParentColor = False
        TabOrder = 9
        TextId = 0
      end
      object SRMEBQF: TCurrencyEdit
        Tag = 1
        Left = 363
        Top = 56
        Width = 81
        Height = 24
        HelpContext = 1269
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.0000 ')
        ParentFont = False
        ReadOnly = True
        TabOrder = 10
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.0000 ;###,###,##0.0000-'
        DecPlaces = 4
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
    end
    object ReturnsPage: TTabSheet
      Caption = 'Returns'
      ImageIndex = 3
      object SBSBackGroup12: TSBSBackGroup
        Left = 2
        Top = 4
        Width = 449
        Height = 138
        Caption = 'Warranty && G/L'
        TextId = 0
      end
      object SBSBackGroup13: TSBSBackGroup
        Left = 2
        Top = 200
        Width = 236
        Height = 80
        TextId = 0
      end
      object Label820: Label8
        Left = 9
        Top = 250
        Width = 106
        Height = 15
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Purchase Returned'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label821: Label8
        Left = 5
        Top = 221
        Width = 110
        Height = 15
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Sales Returned'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label822: Label8
        Left = 33
        Top = 88
        Width = 82
        Height = 14
        Alignment = taRightJustify
        Caption = 'Sales Return G/L'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label823: Label8
        Left = 6
        Top = 33
        Width = 109
        Height = 15
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Sales Warranty'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label824: Label8
        Left = 6
        Top = 60
        Width = 109
        Height = 15
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Manufact. Warranty'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object SBSBackGroup14: TSBSBackGroup
        Left = 2
        Top = 145
        Width = 449
        Height = 52
        Caption = 'Restock'
        TextId = 0
      end
      object Label825: Label8
        Left = 38
        Top = 163
        Width = 77
        Height = 14
        Caption = 'Restock Charge'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label864: Label8
        Left = 14
        Top = 116
        Width = 101
        Height = 14
        Alignment = taRightJustify
        Caption = 'Purchase Return G/L'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object SRRPRF: TCurrencyEdit
        Left = 120
        Top = 244
        Width = 109
        Height = 24
        HelpContext = 1590
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object SRRSRF: TCurrencyEdit
        Left = 120
        Top = 216
        Width = 109
        Height = 24
        HelpContext = 1590
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object SRRGLF: Text8Pt
        Tag = 1
        Left = 120
        Top = 83
        Width = 109
        Height = 24
        HelpContext = 1587
        AutoSize = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 2
        TextId = 0
        ViaSBtn = False
      end
      object SRRGLDF: Text8Pt
        Left = 235
        Top = 83
        Width = 211
        Height = 24
        HelpContext = 1587
        TabStop = False
        AutoSize = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 3
        TextId = 0
        ViaSBtn = False
      end
      object SRRSWDF: TCurrencyEdit
        Tag = 1
        Left = 120
        Top = 28
        Width = 40
        Height = 24
        HelpContext = 1585
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '1 ')
        MaxLength = 2
        ParentFont = False
        ReadOnly = True
        TabOrder = 4
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0 ;###,###,##0-'
        DecPlaces = 0
        ShowCurrency = False
        TextId = 0
        Value = 1
      end
      object SRRMWDF: TCurrencyEdit
        Tag = 1
        Left = 120
        Top = 56
        Width = 40
        Height = 24
        HelpContext = 1585
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '1 ')
        MaxLength = 2
        ParentFont = False
        ReadOnly = True
        TabOrder = 5
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0 ;###,###,##0-'
        DecPlaces = 0
        ShowCurrency = False
        TextId = 0
        Value = 1
      end
      object SRRSWMF: TSBSComboBox
        Tag = 1
        Left = 168
        Top = 28
        Width = 73
        Height = 22
        HelpContext = 1585
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        ItemIndex = 0
        MaxLength = 40
        ParentFont = False
        TabOrder = 6
        Text = 'Days'
        Items.Strings = (
          'Days'
          'Weeks'
          'Months'
          'Years')
        MaxListWidth = 75
        ReadOnly = True
        Validate = True
      end
      object SRRSMMF: TSBSComboBox
        Tag = 1
        Left = 168
        Top = 56
        Width = 73
        Height = 22
        HelpContext = 1585
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        ItemIndex = 0
        MaxLength = 40
        ParentFont = False
        TabOrder = 7
        Text = 'Days'
        Items.Strings = (
          'Days'
          'Weeks'
          'Months'
          'Years')
        MaxListWidth = 75
        ReadOnly = True
        Validate = True
      end
      object SRRPGLF: Text8Pt
        Tag = 1
        Left = 120
        Top = 111
        Width = 109
        Height = 24
        HelpContext = 1588
        AutoSize = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 8
        TextId = 0
        ViaSBtn = False
      end
      object SRRGLPDF: Text8Pt
        Left = 235
        Top = 111
        Width = 211
        Height = 24
        HelpContext = 1588
        TabStop = False
        AutoSize = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 9
        TextId = 0
        ViaSBtn = False
      end
      object SRRRCF: Text8Pt
        Tag = 1
        Left = 120
        Top = 159
        Width = 109
        Height = 24
        HelpContext = 1589
        AutoSize = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 10
        TextId = 0
        ViaSBtn = False
      end
    end
    object LedgerPage: TTabSheet
      Caption = 'Ledger'
      object BtListBox: TScrollBox
        Left = 3
        Top = 3
        Width = 569
        Height = 311
        VertScrollBar.Tracking = True
        VertScrollBar.Visible = False
        TabOrder = 0
        object BtListHeaderPanel: TSBSPanel
          Left = 2
          Top = 3
          Width = 805
          Height = 21
          BevelInner = bvLowered
          BevelOuter = bvNone
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumnHeader
          object CLORefLab: TSBSPanel
            Left = 2
            Top = 2
            Width = 34
            Height = 15
            BevelOuter = bvNone
            Caption = 'Ref'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 0
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLDateLab: TSBSPanel
            Left = 75
            Top = 2
            Width = 73
            Height = 15
            BevelOuter = bvNone
            Caption = 'Date'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 1
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLUPLab: TSBSPanel
            Left = 708
            Top = 2
            Width = 86
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Unit Price  '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 2
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLOOLab: TSBSPanel
            Left = 410
            Top = 2
            Width = 64
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'On Order '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 3
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLQOLab: TSBSPanel
            Left = 278
            Top = 2
            Width = 63
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Qty Out  '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 4
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLALLab: TSBSPanel
            Left = 344
            Top = 2
            Width = 64
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Allocated '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 5
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLQILab: TSBSPanel
            Left = 211
            Top = 2
            Width = 64
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Qty In  '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 6
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLACLab: TSBSPanel
            Left = 152
            Top = 2
            Width = 56
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'A/C Code '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 7
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLAWLab: TSBSPanel
            Left = 479
            Top = 2
            Width = 65
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = ' Alloc WOR '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 8
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLIWLab: TSBSPanel
            Left = 546
            Top = 2
            Width = 64
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Issud WOR'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 9
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLSRLab: TSBSPanel
            Left = 696
            Top = 2
            Width = 24
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Sales Ret. '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 10
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLPRLab: TSBSPanel
            Left = 706
            Top = 2
            Width = 27
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Purch Ret. '
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 11
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLPWLab: TSBSPanel
            Left = 611
            Top = 2
            Width = 63
            Height = 15
            Alignment = taRightJustify
            BevelOuter = bvNone
            Caption = 'Pickd WOR'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 12
            OnMouseDown = BtListLabMouseDown
            OnMouseMove = BtListLabMouseMove
            OnMouseUp = BtListPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
        end
        object CLORefPanel: TSBSPanel
          Left = 2
          Top = 27
          Width = 72
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLDatePanel: TSBSPanel
          Left = 76
          Top = 27
          Width = 75
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLUPPanel: TSBSPanel
          Left = 737
          Top = 27
          Width = 63
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLOOPanel: TSBSPanel
          Left = 414
          Top = 27
          Width = 64
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLQOPanel: TSBSPanel
          Left = 280
          Top = 27
          Width = 65
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 5
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLALPanel: TSBSPanel
          Left = 347
          Top = 27
          Width = 64
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 6
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLQIPanel: TSBSPanel
          Left = 213
          Top = 27
          Width = 65
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 7
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLAcPanel: TSBSPanel
          Left = 153
          Top = 27
          Width = 58
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 8
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLAWPanel: TSBSPanel
          Left = 480
          Top = 27
          Width = 65
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 9
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLIWPanel: TSBSPanel
          Left = 547
          Top = 27
          Width = 65
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 10
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLSRPanel: TSBSPanel
          Left = 698
          Top = 27
          Width = 18
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 11
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLPRPanel: TSBSPanel
          Left = 719
          Top = 27
          Width = 15
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 12
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLPWPanel: TSBSPanel
          Left = 614
          Top = 27
          Width = 64
          Height = 260
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 13
          OnMouseUp = BtListPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
      end
      object BtListBtnPanel: TSBSPanel
        Left = 574
        Top = 31
        Width = 19
        Height = 262
        BevelOuter = bvLowered
        TabOrder = 1
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
      end
    end
  end
  object BtnPanel: TSBSPanel
    Left = 606
    Top = 32
    Width = 99
    Height = 311
    BevelOuter = bvLowered
    TabOrder = 1
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    object I1BSBox: TScrollBox
      Left = 1
      Top = 3
      Width = 95
      Height = 202
      HorzScrollBar.Visible = False
      BorderStyle = bsNone
      TabOrder = 0
      object btnViewLine: TButton
        Left = 4
        Top = 34
        Width = 86
        Height = 23
        Hint = 
          'Find Stock Code|Choosing this option allows you to move to the n' +
          'ext line containing a specified Stock Code.'
        HelpContext = 264
        Caption = '&View'
        TabOrder = 0
        OnClick = btnViewLineClick
      end
      object btnClose: TButton
        Left = 4
        Top = 1
        Width = 86
        Height = 23
        HelpContext = 259
        Cancel = True
        Caption = 'C&lose'
        ModalResult = 2
        TabOrder = 1
        OnClick = btnCloseClick
      end
    end
  end
  object PopupMenu: TPopupMenu
    Left = 37
    Top = 86
    object ViewTransaction: TMenuItem
      Caption = '&View Transaction'
      OnClick = ViewTransactionClick
    end
    object N2: TMenuItem
      Caption = '-'
    end
    object PropFlg: TMenuItem
      Caption = '&Properties'
      Hint = 'Access Colour & Font settings'
      Visible = False
      OnClick = PropFlgClick
    end
    object N1: TMenuItem
      Caption = '-'
      Visible = False
    end
    object StoreCoordFlg: TMenuItem
      AutoCheck = True
      Caption = '&Save Coordinates'
      Hint = 'Make the current window settings permanent'
      OnClick = StoreCoordFlgClick
    end
    object ResetCoordinates1: TMenuItem
      AutoCheck = True
      Caption = '&Reset Coordinates'
      OnClick = ResetCoordinates1Click
    end
  end
end
