object frmTimeSheet: TfrmTimeSheet
  Left = 495
  Top = 141
  Width = 645
  Height = 376
  HelpContext = 930
  Caption = 'Timesheet Record'
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  ShowHint = True
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  OnResize = FormResize
  PixelsPerInch = 96
  TextHeight = 14
  object PageControl: TPageControl
    Left = 4
    Top = 4
    Width = 621
    Height = 330
    ActivePage = RecepPage
    TabIndex = 0
    TabOrder = 0
    object RecepPage: TTabSheet
      Caption = 'Timesheet'
      object BtListBox: TScrollBox
        Left = 0
        Top = 68
        Width = 500
        Height = 211
        HelpContext = 425
        HorzScrollBar.Tracking = True
        VertScrollBar.Tracking = True
        VertScrollBar.Visible = False
        TabOrder = 0
        object N1HedPanel: TSBSPanel
          Left = 2
          Top = 2
          Width = 487
          Height = 17
          BevelInner = bvLowered
          BevelOuter = bvNone
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumnHeader
          object N1DLab: TSBSPanel
            Left = 2
            Top = 2
            Width = 71
            Height = 13
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'Job Code'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 0
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1NomLab: TSBSPanel
            Left = 77
            Top = 2
            Width = 64
            Height = 13
            BevelOuter = bvNone
            Caption = 'Rate Code'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 1
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1CrLab: TSBSPanel
            Left = 408
            Top = 2
            Width = 77
            Height = 13
            BevelOuter = bvNone
            Caption = 'Total'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 2
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1DrLab: TSBSPanel
            Left = 289
            Top = 2
            Width = 42
            Height = 13
            BevelOuter = bvNone
            Caption = 'Hours'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 3
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1TCLab: TSBSPanel
            Left = 332
            Top = 2
            Width = 77
            Height = 13
            BevelOuter = bvNone
            Caption = 'Time Cost'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 4
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1CCLab: TSBSPanel
            Left = 216
            Top = 2
            Width = 35
            Height = 13
            BevelOuter = bvNone
            Caption = 'CC'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 5
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1DepLab: TSBSPanel
            Left = 252
            Top = 2
            Width = 34
            Height = 13
            BevelOuter = bvNone
            Caption = 'Dept'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 6
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1ALab: TSBSPanel
            Left = 154
            Top = 2
            Width = 59
            Height = 13
            BevelOuter = bvNone
            Caption = 'Analysis'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 7
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
        end
        object N1DPanel: TSBSPanel
          Left = 2
          Top = 22
          Width = 73
          Height = 168
          HelpContext = 1019
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1DrPanel: TSBSPanel
          Left = 289
          Top = 22
          Width = 45
          Height = 168
          HelpContext = 1021
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1NomPanel: TSBSPanel
          Left = 77
          Top = 22
          Width = 76
          Height = 168
          HelpContext = 1020
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1CrPanel: TSBSPanel
          Left = 412
          Top = 22
          Width = 76
          Height = 168
          HelpContext = 1023
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1CCPanel: TSBSPanel
          Left = 217
          Top = 22
          Width = 35
          Height = 168
          HelpContext = 272
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 5
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1DepPanel: TSBSPanel
          Left = 253
          Top = 22
          Width = 35
          Height = 168
          HelpContext = 272
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 6
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1APanel: TSBSPanel
          Left = 155
          Top = 22
          Width = 61
          Height = 168
          HelpContext = 976
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 7
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1TCPanel: TSBSPanel
          Left = 335
          Top = 22
          Width = 76
          Height = 168
          HelpContext = 1022
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 8
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
      end
      object N1BtmPanel: TSBSPanel
        Left = 0
        Top = 281
        Width = 613
        Height = 20
        Align = alBottom
        BevelOuter = bvNone
        PopupMenu = PopupMenu
        TabOrder = 1
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object SBSPanel5: TSBSPanel
          Left = 2
          Top = 2
          Width = 225
          Height = 17
          HelpContext = 426
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object DrReqdTit: Label8
            Left = 4
            Top = 2
            Width = 49
            Height = 14
            Caption = 'Pay Desc:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object PayDescF: Label8
            Left = 64
            Top = 2
            Width = 158
            Height = 14
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
        end
        object SBSPanel1: TSBSPanel
          Left = 357
          Top = 2
          Width = 143
          Height = 17
          HelpContext = 426
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 1
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object Label83: Label8
            Left = 4
            Top = 2
            Width = 25
            Height = 14
            Caption = 'Total:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object CrReqdLab: Label8
            Left = 33
            Top = 2
            Width = 96
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
        end
        object SBSPanel2: TSBSPanel
          Left = 229
          Top = 2
          Width = 124
          Height = 17
          HelpContext = 426
          BevelOuter = bvLowered
          Caption = 'SBSPanel2'
          ParentColor = True
          TabOrder = 2
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object Label86: Label8
            Left = 4
            Top = 2
            Width = 20
            Height = 14
            Caption = 'Hrs:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object DrReqdLab: Label8
            Left = 33
            Top = 2
            Width = 88
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
        end
      end
      object BtListBtnPanel: TSBSPanel
        Left = 502
        Top = 92
        Width = 18
        Height = 168
        BevelOuter = bvLowered
        TabOrder = 2
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
      end
      object BtnPanel: TSBSPanel
        Left = 522
        Top = 0
        Width = 91
        Height = 281
        Align = alRight
        BevelOuter = bvLowered
        TabOrder = 3
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object lblStatus: Label8
          Left = 4
          Top = 3
          Width = 85
          Height = 36
          Alignment = taCenter
          AutoSize = False
          Caption = 'lblStatus'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object I1BSBox: TScrollBox
          Left = 1
          Top = 43
          Width = 88
          Height = 187
          HorzScrollBar.Visible = False
          BorderStyle = bsNone
          PopupMenu = PopupMenu
          TabOrder = 0
          object btnViewLine: TButton
            Left = 4
            Top = 32
            Width = 80
            Height = 21
            Hint = 
              'Find Stock Code|Choosing this option allows you to move to the n' +
              'ext line containing a specified Stock Code.'
            HelpContext = 264
            Caption = '&View'
            TabOrder = 0
            OnClick = btnViewLineClick
          end
          object btnClose: TButton
            Left = 4
            Top = 1
            Width = 80
            Height = 21
            HelpContext = 259
            Cancel = True
            Caption = 'C&lose'
            ModalResult = 2
            TabOrder = 1
            OnClick = btnCloseClick
          end
        end
      end
      object N1FPanel: TSBSPanel
        Left = 0
        Top = 0
        Width = 505
        Height = 68
        BevelOuter = bvNone
        PopupMenu = PopupMenu
        TabOrder = 4
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object Label817: Label8
          Left = 323
          Top = 14
          Width = 38
          Height = 14
          Caption = 'Our Ref'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label84: Label8
          Left = 199
          Top = 14
          Width = 22
          Height = 14
          Caption = 'Date'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label81: Label8
          Left = 313
          Top = 41
          Width = 50
          Height = 14
          Caption = ' Wk/Month'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label82: Label8
          Left = 6
          Top = 15
          Width = 46
          Height = 14
          Caption = 'Employee'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object N1OrefF: Text8Pt
          Left = 365
          Top = 10
          Width = 79
          Height = 22
          HelpContext = 1009
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 4
          TextId = 0
          ViaSBtn = False
        end
        object N1OpoF: Text8Pt
          Left = 447
          Top = 10
          Width = 50
          Height = 22
          HelpContext = 1009
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 5
          TextId = 0
          ViaSBtn = False
        end
        object N1TDateF: TEditDate
          Tag = 1
          Left = 224
          Top = 10
          Width = 78
          Height = 22
          HelpContext = 1010
          AutoSelect = False
          Color = clWhite
          EditMask = '00/00/0000;0;'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          ReadOnly = True
          TabOrder = 1
          Placement = cpAbove
        end
        object EmpAc: Text8Pt
          Tag = 1
          Left = 54
          Top = 11
          Width = 69
          Height = 22
          HelpContext = 830
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          TextId = 0
          ViaSBtn = False
        end
        object N1TSWkF: TCurrencyEdit
          Tag = 1
          Left = 365
          Top = 37
          Width = 79
          Height = 22
          HelpContext = 1011
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0 ')
          MaxLength = 4
          ParentFont = False
          ReadOnly = True
          TabOrder = 3
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0 ;###,###,##0-'
          DecPlaces = 0
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object TransExtForm1: TSBSExtendedForm
          Left = 2
          Top = 36
          Width = 313
          Height = 30
          HelpContext = 1169
          HorzScrollBar.Visible = False
          VertScrollBar.Visible = False
          AutoScroll = False
          BorderStyle = bsNone
          TabOrder = 2
          ArrowPos = alTop
          ArrowX = 150
          ArrowY = 6
          OrigHeight = 30
          OrigWidth = 313
          ExpandedWidth = 318
          ExpandedHeight = 159
          OrigTabOrder = 2
          ShowHorzSB = True
          ShowVertSB = True
          OrigParent = N1FPanel
          NewParent = Owner
          FocusFirst = N1YRefF
          FocusLast = THUD10F
          TabPrev = N1TDateF
          TabNext = N1TSWkF
          object UDF1L: Label8
            Left = 7
            Top = 41
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 1'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF3L: Label8
            Left = 7
            Top = 65
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 3'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF2L: Label8
            Left = 156
            Top = 41
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 2'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF4L: Label8
            Left = 156
            Top = 65
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 4'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label87: Label8
            Left = 25
            Top = 10
            Width = 25
            Height = 14
            Caption = 'Desc'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label88: Label8
            Left = 190
            Top = 10
            Width = 31
            Height = 14
            Caption = 'Per/Yr'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF5L: Label8
            Left = 7
            Top = 89
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 5'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF6L: Label8
            Left = 156
            Top = 89
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 6'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF8L: Label8
            Left = 156
            Top = 113
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 8'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF7L: Label8
            Left = 7
            Top = 113
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 7'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF9L: Label8
            Left = 7
            Top = 137
            Width = 58
            Height = 14
            AutoSize = False
            Caption = 'UD Field 9'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF10L: Label8
            Left = 156
            Top = 137
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 10'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object THUD1F: Text8Pt
            Tag = 1
            Left = 66
            Top = 37
            Width = 87
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 2
            TextId = 0
            ViaSBtn = False
          end
          object THUD3F: Text8Pt
            Tag = 1
            Left = 66
            Top = 61
            Width = 87
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 4
            TextId = 0
            ViaSBtn = False
          end
          object THUD4F: Text8Pt
            Tag = 1
            Left = 223
            Top = 61
            Width = 88
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 5
            TextId = 0
            ViaSBtn = False
          end
          object THUD2F: Text8Pt
            Tag = 1
            Left = 223
            Top = 37
            Width = 88
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 3
            TextId = 0
            ViaSBtn = False
          end
          object N1YRefF: Text8Pt
            Tag = 1
            Left = 52
            Top = 6
            Width = 131
            Height = 22
            HelpContext = 830
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ReadOnly = True
            TabOrder = 0
            TextId = 0
            ViaSBtn = False
          end
          object N1TPerF: TEditPeriod
            Tag = 1
            Left = 224
            Top = 6
            Width = 78
            Height = 22
            HelpContext = 1010
            AutoSelect = False
            Color = clWhite
            EditMask = '00/0000;0;'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 7
            ParentFont = False
            ReadOnly = True
            TabOrder = 1
            Text = 'mmyyyy'
            Placement = cpAbove
            EPeriod = 1
            EYear = 1996
            ViewMask = '000/0000;0;'
            OnConvDate = N1TPerFConvDate
            OnShowPeriod = N1TPerFShowPeriod
          end
          object THUD5F: Text8Pt
            Tag = 1
            Left = 66
            Top = 85
            Width = 87
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 6
            TextId = 0
            ViaSBtn = False
          end
          object THUD6F: Text8Pt
            Tag = 1
            Left = 223
            Top = 85
            Width = 88
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 7
            TextId = 0
            ViaSBtn = False
          end
          object THUD8F: Text8Pt
            Tag = 1
            Left = 223
            Top = 109
            Width = 88
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 9
            TextId = 0
            ViaSBtn = False
          end
          object THUD7F: Text8Pt
            Tag = 1
            Left = 66
            Top = 109
            Width = 87
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 8
            TextId = 0
            ViaSBtn = False
          end
          object THUD9F: Text8Pt
            Tag = 1
            Left = 66
            Top = 133
            Width = 87
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 10
            TextId = 0
            ViaSBtn = False
          end
          object THUD10F: Text8Pt
            Tag = 1
            Left = 223
            Top = 133
            Width = 88
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 11
            TextId = 0
            ViaSBtn = False
          end
        end
      end
    end
  end
  object PopupMenu: TPopupMenu
    OnPopup = PopupMenuPopup
    Left = 106
    Top = 230
    object ViewTransaction1: TMenuItem
      Caption = 'View Transaction'
      OnClick = ViewTransaction1Click
    end
    object N2: TMenuItem
      Caption = '-'
      Visible = False
    end
    object PropFlg: TMenuItem
      Caption = '&Properties'
      HelpContext = 65
      Hint = 'Access Colour & Font settings'
      Visible = False
    end
    object N1: TMenuItem
      Caption = '-'
    end
    object StoreCoordFlg: TMenuItem
      AutoCheck = True
      Caption = '&Save Coordinates'
      HelpContext = 177
      Hint = 'Make the current window settings permanent'
      OnClick = StoreCoordFlgClick
    end
    object ResetCoordinates1: TMenuItem
      AutoCheck = True
      Caption = '&Reset Coordinates'
      OnClick = ResetCoordinates1Click
    end
  end
end
