object NTxfrForm: TNTxfrForm
  Left = 542
  Top = 248
  Width = 650
  Height = 391
  HelpContext = 420
  Caption = 'Nominal Journal'
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  KeyPreview = True
  OldCreateOrder = True
  PopupMenu = PopupMenu1
  Position = poDefault
  Scaled = False
  ShowHint = True
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  OnResize = FormResize
  PixelsPerInch = 96
  TextHeight = 14
  object PageControl1: TPageControl
    Left = 0
    Top = 0
    Width = 630
    Height = 351
    ActivePage = RecepPage
    TabIndex = 0
    TabOrder = 0
    OnChanging = PageControl1Changing
    object RecepPage: TTabSheet
      Caption = 'Journal'
      object N1SBox: TScrollBox
        Left = 0
        Top = 90
        Width = 494
        Height = 211
        HelpContext = 425
        HorzScrollBar.Tracking = True
        VertScrollBar.Tracking = True
        VertScrollBar.Visible = False
        TabOrder = 0
        object N1HedPanel: TSBSPanel
          Left = 2
          Top = 2
          Width = 602
          Height = 17
          BevelInner = bvLowered
          BevelOuter = bvNone
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumnHeader
          object N1DLab: TSBSPanel
            Left = 2
            Top = 2
            Width = 98
            Height = 13
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = '  Description'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 0
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1NomLab: TSBSPanel
            Left = 101
            Top = 2
            Width = 59
            Height = 13
            BevelOuter = bvNone
            Caption = 'G/L Code'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 1
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1CrLab: TSBSPanel
            Left = 351
            Top = 2
            Width = 87
            Height = 13
            BevelOuter = bvNone
            Caption = 'Credit (-)'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 2
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1NDLab: TSBSPanel
            Left = 160
            Top = 2
            Width = 102
            Height = 13
            BevelOuter = bvNone
            Caption = 'G/L Description'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 3
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1DrLab: TSBSPanel
            Left = 262
            Top = 2
            Width = 87
            Height = 13
            BevelOuter = bvNone
            Caption = 'Debit (+)'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 4
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1VCLab: TSBSPanel
            Left = 440
            Top = 2
            Width = 22
            Height = 13
            BevelOuter = bvNone
            Caption = 'TC'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 5
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1VAmtLab: TSBSPanel
            Left = 462
            Top = 2
            Width = 61
            Height = 13
            BevelOuter = bvNone
            Caption = ' Amt'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 6
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1CCLab: TSBSPanel
            Left = 522
            Top = 2
            Width = 35
            Height = 13
            BevelOuter = bvNone
            Caption = 'CC'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 7
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object N1DepLab: TSBSPanel
            Left = 558
            Top = 2
            Width = 34
            Height = 13
            BevelOuter = bvNone
            Caption = 'Dept'
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 8
            OnMouseDown = N1DLabMouseDown
            OnMouseMove = N1DLabMouseMove
            OnMouseUp = N1DPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
        end
        object N1DPanel: TSBSPanel
          Left = 2
          Top = 22
          Width = 100
          Height = 168
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1DrPanel: TSBSPanel
          Left = 264
          Top = 22
          Width = 88
          Height = 168
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1NomPanel: TSBSPanel
          Left = 103
          Top = 22
          Width = 59
          Height = 168
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1NDPanel: TSBSPanel
          Left = 163
          Top = 22
          Width = 100
          Height = 168
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1CrPanel: TSBSPanel
          Left = 353
          Top = 22
          Width = 89
          Height = 168
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 5
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1VCPanel: TSBSPanel
          Left = 443
          Top = 22
          Width = 22
          Height = 168
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 6
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1VAmtPanel: TSBSPanel
          Left = 466
          Top = 22
          Width = 61
          Height = 168
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 7
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1CCPanel: TSBSPanel
          Left = 528
          Top = 22
          Width = 35
          Height = 168
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 8
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object N1DepPanel: TSBSPanel
          Left = 564
          Top = 22
          Width = 35
          Height = 168
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 9
          OnMouseUp = N1DPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
      end
      object N1BtmPanel: TSBSPanel
        Left = 0
        Top = 302
        Width = 622
        Height = 20
        Align = alBottom
        BevelOuter = bvNone
        PopupMenu = PopupMenu1
        TabOrder = 1
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object CCPanel: TSBSPanel
          Left = 0
          Top = 3
          Width = 118
          Height = 17
          HelpContext = 433
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object CCTit: Label8
            Left = 3
            Top = 2
            Width = 17
            Height = 14
            Caption = 'CC:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object DepTit: Label8
            Left = 57
            Top = 2
            Width = 22
            Height = 14
            Caption = 'Dep:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object CCLab: Label8
            Left = 23
            Top = 2
            Width = 30
            Height = 14
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
          object DepLab: Label8
            Left = 81
            Top = 2
            Width = 30
            Height = 14
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
        end
        object SBSPanel5: TSBSPanel
          Left = 121
          Top = 3
          Width = 175
          Height = 17
          HelpContext = 426
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 1
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object DrReqdTit: Label8
            Left = 4
            Top = 2
            Width = 42
            Height = 14
            Caption = 'Dr Reqd:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object DrReqdLab: Label8
            Left = 51
            Top = 2
            Width = 120
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
        end
        object SBSPanel4: TSBSPanel
          Left = 299
          Top = 3
          Width = 175
          Height = 17
          HelpContext = 426
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 2
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object CrReqdTit: Label8
            Left = 4
            Top = 2
            Width = 42
            Height = 14
            Caption = 'Cr Reqd:'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object CrReqdLab: Label8
            Left = 51
            Top = 2
            Width = 119
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
        end
        object SBSPanel1: TSBSPanel
          Left = 477
          Top = 3
          Width = 143
          Height = 17
          HelpContext = 426
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 3
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object VATTit: Label8
            Left = 4
            Top = 2
            Width = 3
            Height = 14
            Caption = ':'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object VATTotLab: Label8
            Left = 51
            Top = 2
            Width = 86
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TextId = 0
          end
        end
      end
      object N1ListBtnPanel: TSBSPanel
        Left = 498
        Top = 113
        Width = 18
        Height = 168
        BevelOuter = bvLowered
        TabOrder = 2
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
      end
      object N1FPanel: TSBSPanel
        Left = -2
        Top = 0
        Width = 517
        Height = 90
        BevelOuter = bvNone
        PopupMenu = PopupMenu1
        TabOrder = 3
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object Label817: Label8
          Left = 202
          Top = 14
          Width = 38
          Height = 14
          Caption = 'Our Ref'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label84: Label8
          Left = 17
          Top = 41
          Width = 22
          Height = 14
          Caption = 'Date'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label87: Label8
          Left = 14
          Top = 14
          Width = 25
          Height = 14
          Caption = 'Desc'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object N1BLab: Label8
          Left = 346
          Top = 68
          Width = 56
          Height = 14
          Caption = 'Base Equiv.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label816: Label8
          Left = 338
          Top = 14
          Width = 68
          Height = 14
          Caption = 'Last edited by'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label81: Label8
          Left = 146
          Top = 68
          Width = 95
          Height = 14
          Caption = 'Balancing G/L Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object N1OrefF: Text8Pt
          Left = 245
          Top = 10
          Width = 79
          Height = 22
          HelpContext = 142
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Text = 'SRC000080'
          TextId = 0
          ViaSBtn = False
        end
        object N1OpoF: Text8Pt
          Left = 409
          Top = 10
          Width = 86
          Height = 22
          HelpContext = 241
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 5
          Text = 'Sally'
          TextId = 0
          ViaSBtn = False
        end
        object N1TDateF: TEditDate
          Tag = 1
          Left = 42
          Top = 37
          Width = 79
          Height = 22
          HelpContext = 143
          AutoSelect = False
          EditMask = '00/00/0000;0;'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          ReadOnly = True
          TabOrder = 2
          Placement = cpAbove
        end
        object N1YRefF: Text8Pt
          Tag = 1
          Left = 42
          Top = 9
          Width = 130
          Height = 22
          HelpContext = 240
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 1
          TextId = 0
          ViaSBtn = False
        end
        object N1SelBalF: Text8Pt
          Tag = 1
          Left = 244
          Top = 64
          Width = 87
          Height = 22
          HelpContext = 423
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 4
          TextId = 0
          ViaSBtn = False
        end
        object N1BaseF: TCurrencyEdit
          Left = 409
          Top = 64
          Width = 87
          Height = 22
          HelpContext = 424
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.00 ')
          ParentFont = False
          ReadOnly = True
          TabOrder = 6
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = 1E-10
        end
        object N1SelBalQF: TBorCheck
          Tag = 1
          Left = 166
          Top = 39
          Width = 92
          Height = 20
          HelpContext = 422
          Caption = 'Self Balancing'
          CheckColor = clTeal
          Color = clBtnFace
          Enabled = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentColor = False
          ParentFont = False
          TabOrder = 7
          TabStop = True
          TextId = 0
        end
        object N1AutoRevF: TBorCheck
          Tag = 1
          Left = 265
          Top = 39
          Width = 102
          Height = 20
          HelpContext = 619
          Caption = 'Auto Reversing'
          CheckColor = clTeal
          Color = clBtnFace
          Enabled = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentColor = False
          ParentFont = False
          TabOrder = 8
          TabStop = True
          TextId = 0
        end
        object TransExtForm1: TSBSExtendedForm
          Left = 4
          Top = 57
          Width = 135
          Height = 30
          HelpContext = 1169
          HorzScrollBar.Visible = False
          VertScrollBar.Visible = False
          AutoScroll = False
          BorderStyle = bsNone
          TabOrder = 3
          ArrowPos = alTop
          ArrowX = 57
          ArrowY = 6
          OrigHeight = 30
          OrigWidth = 135
          ExpandedWidth = 302
          ExpandedHeight = 160
          OrigTabOrder = 3
          ShowHorzSB = True
          ShowVertSB = True
          OrigParent = N1FPanel
          NewParent = Owner
          FocusFirst = N1TPerF
          FocusLast = THUD4F
          TabPrev = N1TDateF
          TabNext = N1SelBalQF
          object UDF1L: Label8
            Left = 7
            Top = 41
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 1'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF3L: Label8
            Left = 7
            Top = 65
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 3'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF2L: Label8
            Left = 151
            Top = 41
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 2'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF4L: Label8
            Left = 151
            Top = 65
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 4'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label88: Label8
            Left = 4
            Top = 11
            Width = 31
            Height = 14
            Caption = 'Per/Yr'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label82: Label8
            Left = 157
            Top = 12
            Width = 40
            Height = 14
            Caption = 'YourRef'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF5L: Label8
            Left = 7
            Top = 89
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 5'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF7L: Label8
            Left = 7
            Top = 113
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 7'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF9L: Label8
            Left = 7
            Top = 137
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 9'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF6L: Label8
            Left = 151
            Top = 89
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 6'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF8L: Label8
            Left = 151
            Top = 113
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 8'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UDF10L: Label8
            Left = 151
            Top = 137
            Width = 66
            Height = 14
            AutoSize = False
            Caption = 'UD Field 10'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object THUD1F: Text8Pt
            Tag = 1
            Left = 66
            Top = 37
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 2
            TextId = 0
            ViaSBtn = False
          end
          object THUD3F: Text8Pt
            Tag = 1
            Left = 66
            Top = 61
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 4
            TextId = 0
            ViaSBtn = False
          end
          object THUD4F: Text8Pt
            Tag = 1
            Left = 211
            Top = 61
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 5
            TextId = 0
            ViaSBtn = False
          end
          object THUD2F: Text8Pt
            Tag = 1
            Left = 211
            Top = 37
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 3
            TextId = 0
            ViaSBtn = False
          end
          object N1TPerF: TEditPeriod
            Tag = 1
            Left = 38
            Top = 8
            Width = 78
            Height = 22
            HelpContext = 239
            AutoSelect = False
            EditMask = '00/0000;0;'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 7
            ParentFont = False
            ReadOnly = True
            TabOrder = 0
            Text = 'mmyyyy'
            Placement = cpAbove
            EPeriod = 1
            EYear = 1996
            ViewMask = '000/0000;0;'
            OnShowPeriod = N1TPerFShowPeriod
          end
          object N1YRef2F: Text8Pt
            Tag = 1
            Left = 201
            Top = 8
            Width = 90
            Height = 22
            HelpContext = 240
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ReadOnly = True
            TabOrder = 1
            TextId = 0
            ViaSBtn = False
          end
          object THUD6F: Text8Pt
            Tag = 1
            Left = 211
            Top = 85
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 7
            TextId = 0
            ViaSBtn = False
          end
          object THUD8F: Text8Pt
            Tag = 1
            Left = 211
            Top = 109
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 9
            TextId = 0
            ViaSBtn = False
          end
          object THUD10F: Text8Pt
            Tag = 1
            Left = 211
            Top = 133
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 11
            TextId = 0
            ViaSBtn = False
          end
          object THUD5F: Text8Pt
            Tag = 1
            Left = 66
            Top = 85
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 6
            TextId = 0
            ViaSBtn = False
          end
          object THUD7F: Text8Pt
            Tag = 1
            Left = 66
            Top = 109
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 8
            TextId = 0
            ViaSBtn = False
          end
          object THUD9F: Text8Pt
            Tag = 1
            Left = 66
            Top = 133
            Width = 82
            Height = 22
            HelpContext = 283
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ReadOnly = True
            TabOrder = 10
            TextId = 0
            ViaSBtn = False
          end
        end
      end
    end
    object TabSheet1: TTabSheet
      Caption = 'Footer'
      ImageIndex = 1
      object SBSPanel53: TSBSPanel
        Left = 3
        Top = 7
        Width = 295
        Height = 306
        BevelInner = bvRaised
        BevelOuter = bvLowered
        PopupMenu = PopupMenu1
        TabOrder = 0
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object VATLab: Label8
          Left = 46
          Top = 12
          Width = 28
          Height = 14
          Alignment = taRightJustify
          Caption = 'In/Out'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object SBSPanel54: TSBSPanel
          Left = 8
          Top = 38
          Width = 277
          Height = 17
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'MS Sans Serif'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object I5VATRLab: TLabel
            Left = 3
            Top = 2
            Width = 65
            Height = 13
            AutoSize = False
            Caption = ' Rate'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object Label8: TLabel
            Left = 131
            Top = 2
            Width = 32
            Height = 14
            Caption = 'Goods'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
          object I5VATLab: TLabel
            Left = 174
            Top = 3
            Width = 80
            Height = 13
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'VAT'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
          end
        end
        object NTIOHedCB: TSBSComboBox
          Tag = 1
          Left = 79
          Top = 9
          Width = 98
          Height = 22
          HelpContext = 40016
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ItemHeight = 14
          MaxLength = 1
          ParentFont = False
          TabOrder = 1
          Items.Strings = (
            'N/A'
            'Input'
            'Output')
          AllowChangeInExit = True
          MaxListWidth = 85
          ReadOnly = True
          Validate = True
        end
      end
      object ScrollBox8: TScrollBox
        Left = 10
        Top = 67
        Width = 280
        Height = 243
        HelpContext = 286
        HorzScrollBar.Visible = False
        TabOrder = 1
        object I5VR1F: Text8Pt
          Tag = 2
          Left = 2
          Top = 2
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VR2F: Text8Pt
          Tag = 2
          Left = 2
          Top = 26
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 1
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VR3F: Text8Pt
          Tag = 2
          Left = 2
          Top = 50
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 2
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VR4F: Text8Pt
          Tag = 2
          Left = 2
          Top = 74
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 3
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VR5F: Text8Pt
          Tag = 2
          Left = 2
          Top = 98
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 4
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VR6F: Text8Pt
          Tag = 2
          Left = 2
          Top = 122
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 5
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VR7F: Text8Pt
          Tag = 2
          Left = 2
          Top = 145
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 6
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG1F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 2
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 21
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VG2F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 26
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 22
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VG3F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 50
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 23
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VG4F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 74
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 24
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VG5F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 98
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 25
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VG6F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 122
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 26
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VG7F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 145
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 27
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV1F: TCurrencyEdit
          Left = 171
          Top = 2
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 42
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV2F: TCurrencyEdit
          Left = 171
          Top = 26
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 43
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV3F: TCurrencyEdit
          Left = 171
          Top = 50
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 44
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV4F: TCurrencyEdit
          Left = 171
          Top = 74
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 45
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV5F: TCurrencyEdit
          Left = 171
          Top = 98
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 46
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV6F: TCurrencyEdit
          Left = 171
          Top = 122
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 47
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV7F: TCurrencyEdit
          Left = 171
          Top = 145
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 48
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VR8F: Text8Pt
          Tag = 2
          Left = 2
          Top = 168
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 7
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG8F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 168
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 28
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV8F: TCurrencyEdit
          Left = 171
          Top = 168
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 49
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5Vr9F: Text8Pt
          Tag = 2
          Left = 2
          Top = 192
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 8
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG9F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 192
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 29
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV9F: TCurrencyEdit
          Left = 171
          Top = 192
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 50
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5Vr10F: Text8Pt
          Tag = 2
          Left = 2
          Top = 216
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 9
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG10F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 216
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 30
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV10F: TCurrencyEdit
          Left = 171
          Top = 216
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 51
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5Vr11F: Text8Pt
          Tag = 2
          Left = 2
          Top = 240
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 10
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG11F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 240
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 31
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV11F: TCurrencyEdit
          Left = 171
          Top = 240
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 52
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VR12F: Text8Pt
          Tag = 2
          Left = 2
          Top = 264
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 11
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG12F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 264
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 32
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV12F: TCurrencyEdit
          Left = 171
          Top = 264
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 53
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5Vr13F: Text8Pt
          Tag = 2
          Left = 2
          Top = 288
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 12
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG13F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 288
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 33
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV13F: TCurrencyEdit
          Left = 171
          Top = 288
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 54
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5Vr14F: Text8Pt
          Tag = 2
          Left = 2
          Top = 312
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 13
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG14F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 312
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 34
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV14F: TCurrencyEdit
          Left = 170
          Top = 312
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 55
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5Vr15F: Text8Pt
          Tag = 2
          Left = 2
          Top = 336
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 14
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG15F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 336
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 35
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV15F: TCurrencyEdit
          Left = 170
          Top = 336
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 56
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV16F: TCurrencyEdit
          Left = 170
          Top = 360
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 57
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VG16F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 360
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 36
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5Vr16F: Text8Pt
          Tag = 2
          Left = 2
          Top = 360
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 15
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5Vr17F: Text8Pt
          Tag = 2
          Left = 2
          Top = 384
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 16
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG17F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 384
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 37
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV17F: TCurrencyEdit
          Left = 170
          Top = 384
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 58
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV18F: TCurrencyEdit
          Left = 170
          Top = 408
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 59
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VG18F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 408
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 38
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5Vr18F: Text8Pt
          Tag = 2
          Left = 2
          Top = 408
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 17
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5Vr19F: Text8Pt
          Tag = 2
          Left = 2
          Top = 431
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 18
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG19F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 431
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 39
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV19F: TCurrencyEdit
          Left = 170
          Top = 431
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 60
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5Vr20F: Text8Pt
          Tag = 2
          Left = 2
          Top = 455
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 19
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG20F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 455
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 40
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV20F: TCurrencyEdit
          Left = 170
          Top = 455
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 61
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5Vr21F: Text8Pt
          Tag = 2
          Left = 2
          Top = 478
          Width = 65
          Height = 22
          TabStop = False
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ReadOnly = True
          TabOrder = 20
          Visible = False
          TextId = 0
          ViaSBtn = False
        end
        object I5VG21F: TCurrencyEdit
          Tag = 2
          Left = 69
          Top = 478
          Width = 100
          Height = 22
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 41
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object I5VV21F: TCurrencyEdit
          Left = 170
          Top = 478
          Width = 88
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 62
          Visible = False
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
      end
    end
  end
  object N1BtnPanel: TSBSPanel
    Left = 524
    Top = 28
    Width = 100
    Height = 298
    BevelOuter = bvNone
    BorderStyle = bsSingle
    PopupMenu = PopupMenu1
    TabOrder = 1
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    object N1StatLab: Label8
      Left = 3
      Top = 3
      Width = 95
      Height = 49
      Alignment = taCenter
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object ClsN1Btn: TButton
      Left = 2
      Top = 49
      Width = 80
      Height = 21
      HelpContext = 259
      Cancel = True
      Caption = 'C&lose'
      ModalResult = 2
      TabOrder = 0
      OnClick = ClsN1BtnClick
    end
    object N1BSBox: TScrollBox
      Left = 1
      Top = 99
      Width = 97
      Height = 190
      HorzScrollBar.Tracking = True
      VertScrollBar.Tracking = True
      BorderStyle = bsNone
      Color = clBtnFace
      ParentColor = False
      TabOrder = 1
      object btnViewLine: TButton
        Left = 2
        Top = 9
        Width = 80
        Height = 21
        Hint = 
          'Add new line|Choosing this option allows you to Add a new line w' +
          'hich will be placed at the end of the nominal transfer.'
        HelpContext = 427
        Caption = '&View'
        TabOrder = 0
        OnClick = btnViewLineClick
      end
    end
  end
  object PopupMenu1: TPopupMenu
    OnPopup = PopupMenu1Popup
    Left = 559
    Top = 191
    object View1: TMenuItem
      Caption = '&View'
      Hint = 'Choosing this option allows you to View the selected line'
      OnClick = btnViewLineClick
    end
    object N2: TMenuItem
      Caption = '-'
    end
    object PropFlg: TMenuItem
      Caption = '&Properties'
      HelpContext = 65
      Hint = 'Access Colour & Font settings'
      OnClick = PropFlgClick
    end
    object N1: TMenuItem
      Caption = '-'
    end
    object StoreCoordFlg: TMenuItem
      Caption = '&Save Coordinates'
      HelpContext = 177
      Hint = 'Make the current window settings permanent'
      OnClick = StoreCoordFlgClick
    end
    object N3: TMenuItem
      Caption = '-'
      Enabled = False
      Visible = False
    end
  end
end
