object frmSOPLine: TfrmSOPLine
  Left = 519
  Top = 187
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'frmSOPLine'
  ClientHeight = 482
  ClientWidth = 643
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poDefault
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 14
  object PageControl1: TPageControl
    Left = 2
    Top = 2
    Width = 639
    Height = 499
    ActivePage = DE3Page
    TabIndex = 0
    TabOrder = 0
    TabStop = False
    object DE3Page: TTabSheet
      Caption = 'Data Entry'
      object btnClose: TButton
        Tag = 1
        Left = 542
        Top = 223
        Width = 80
        Height = 21
        HelpContext = 279
        Cancel = True
        Caption = '&Close'
        ModalResult = 2
        TabOrder = 0
        OnClick = btnCloseClick
      end
      object Id3Panel: TSBSPanel
        Left = 0
        Top = 2
        Width = 252
        Height = 214
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 2
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object pnlService: TPanel
          Left = 2
          Top = 178
          Width = 248
          Height = 25
          HelpContext = 8052
          BevelOuter = bvNone
          TabOrder = 1
          object lblServiceTo: TLabel
            Left = 159
            Top = 4
            Width = 9
            Height = 14
            HelpContext = 8052
            Caption = 'to'
          end
          object chkService: TBorCheck
            Tag = 1
            Left = 5
            Top = 1
            Width = 73
            Height = 18
            HelpContext = 8052
            Align = alRight
            Caption = 'EC Service'
            Color = clBtnFace
            ParentColor = False
            TabOrder = 0
            TabStop = True
            TextId = 0
          end
          object dtServiceStart: TEditDate
            Tag = 1
            Left = 84
            Top = 1
            Width = 69
            Height = 22
            HelpContext = 8052
            AutoSelect = False
            EditMask = '00/00/0000;0;'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 10
            ParentFont = False
            TabOrder = 1
            Placement = cpAbove
          end
          object dtServiceEnd: TEditDate
            Tag = 1
            Left = 175
            Top = 1
            Width = 69
            Height = 22
            HelpContext = 8052
            AutoSelect = False
            EditMask = '00/00/0000;0;'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 10
            ParentFont = False
            TabOrder = 2
            Placement = cpAbove
          end
        end
        object Id3SBox: TScrollBox
          Left = 8
          Top = 38
          Width = 241
          Height = 131
          HorzScrollBar.Visible = False
          BorderStyle = bsNone
          Ctl3D = False
          ParentCtl3D = False
          TabOrder = 0
          object Id3Desc1F: Text8Pt
            Tag = 1
            Left = 1
            Top = 1
            Width = 236
            Height = 22
            HelpContext = 235
            Ctl3D = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentCtl3D = False
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 0
            Text = '12345678901234567890123456789012345'
            TextId = 0
            ViaSBtn = False
          end
          object Id3Desc2F: Text8Pt
            Tag = 1
            Left = 1
            Top = 22
            Width = 236
            Height = 22
            HelpContext = 235
            Ctl3D = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentCtl3D = False
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 1
            TextId = 0
            ViaSBtn = False
          end
          object Id3Desc3F: Text8Pt
            Tag = 1
            Left = 1
            Top = 43
            Width = 236
            Height = 22
            HelpContext = 235
            Ctl3D = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentCtl3D = False
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 2
            TextId = 0
            ViaSBtn = False
          end
          object Id3Desc4F: Text8Pt
            Tag = 1
            Left = 1
            Top = 64
            Width = 236
            Height = 22
            HelpContext = 235
            Ctl3D = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentCtl3D = False
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 3
            TextId = 0
            ViaSBtn = False
          end
          object Id3Desc5F: Text8Pt
            Tag = 1
            Left = 1
            Top = 85
            Width = 236
            Height = 22
            HelpContext = 235
            Ctl3D = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentCtl3D = False
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 4
            TextId = 0
            ViaSBtn = False
          end
          object Id3Desc6F: Text8Pt
            Tag = 1
            Left = 1
            Top = 106
            Width = 236
            Height = 22
            HelpContext = 235
            Ctl3D = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 50
            ParentCtl3D = False
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 5
            TextId = 0
            ViaSBtn = False
          end
        end
      end
      object pnlValues: TPanel
        Left = 256
        Top = 2
        Width = 373
        Height = 214
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 3
        object Id3PQLab: Label8
          Left = 11
          Top = 13
          Width = 43
          Height = 14
          Caption = 'Pack Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3QtyLab: Label8
          Left = 37
          Top = 36
          Width = 17
          Height = 14
          Caption = 'Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3UPLab: Label8
          Left = 20
          Top = 62
          Width = 34
          Height = 14
          Caption = 'U/Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3DiscLab: Label8
          Left = 12
          Top = 87
          Width = 42
          Height = 14
          Caption = 'Discount'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3LTotLab: Label8
          Left = 31
          Top = 112
          Width = 22
          Height = 14
          Caption = 'Total'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblOtherDiscounts: Label8
          Left = 13
          Top = 138
          Width = 85
          Height = 14
          Caption = 'Other Discounts:-'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblMBDiscount: Label8
          Left = 10
          Top = 163
          Width = 44
          Height = 14
          Alignment = taRightJustify
          Caption = 'Multi-Buy'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblTransDiscount: Label8
          Left = 26
          Top = 187
          Width = 28
          Height = 14
          Alignment = taRightJustify
          Caption = 'Trans'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label81: Label8
          Left = 194
          Top = 14
          Width = 45
          Height = 14
          Caption = 'Job Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label82: Label8
          Left = 196
          Top = 39
          Width = 42
          Height = 14
          Caption = 'Analysis'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object VATCCLab3: Label8
          Left = 177
          Top = 64
          Width = 61
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = '/CC/Dep'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label85: Label8
          Left = 196
          Top = 88
          Width = 42
          Height = 14
          Caption = 'GL Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3CostLab: Label8
          Left = 199
          Top = 138
          Width = 34
          Height = 14
          Alignment = taRightJustify
          Caption = 'Cost__'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label83: Label8
          Left = 193
          Top = 163
          Width = 44
          Height = 14
          Caption = 'Line type'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object DelDateLab: Label8
          Left = 187
          Top = 188
          Width = 50
          Height = 14
          Alignment = taRightJustify
          Caption = 'Deliv. Date'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label84: Label8
          Left = 304
          Top = 158
          Width = 42
          Height = 14
          Alignment = taRightJustify
          Caption = 'Override'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label86: Label8
          Left = 306
          Top = 169
          Width = 39
          Height = 14
          Alignment = taRightJustify
          Caption = 'Intrastat'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Bevel1: TBevel
          Left = 173
          Top = 10
          Width = 2
          Height = 196
        end
        object Id5JCodeF: Text8Pt
          Tag = 1
          Left = 241
          Top = 9
          Width = 123
          Height = 22
          Hint = 
            'Double click to drill down|Double clicking or using the down but' +
            'ton will drill down to the record for this field. The up button ' +
            'will search for the nearest match.'
          HelpContext = 465
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 6
          TextId = 0
          ViaSBtn = False
          Link_to_Job = True
          ShowHilight = True
        end
        object Id5JAnalF: Text8Pt
          Tag = 1
          Left = 241
          Top = 34
          Width = 123
          Height = 22
          HelpContext = 466
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 7
          TextId = 0
          ViaSBtn = False
        end
        object Id3DepF: Text8Pt
          Tag = 1
          Left = 325
          Top = 59
          Width = 39
          Height = 22
          HelpContext = 272
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 10
          TextId = 0
          ViaSBtn = False
        end
        object Id3CCF: Text8Pt
          Tag = 1
          Left = 284
          Top = 59
          Width = 39
          Height = 22
          HelpContext = 272
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 9
          TextId = 0
          ViaSBtn = False
        end
        object Id3VATF: TSBSComboBox
          Tag = 1
          Left = 241
          Top = 59
          Width = 41
          Height = 22
          HelpContext = 249
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ItemHeight = 14
          MaxLength = 1
          ParentFont = False
          TabOrder = 8
          AllowChangeInExit = True
          ExtendedList = True
          MaxListWidth = 75
          ReadOnly = True
          Validate = True
        end
        object Id3NomF: Text8Pt
          Tag = 1
          Left = 241
          Top = 84
          Width = 82
          Height = 22
          HelpContext = 275
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 11
          TextId = 0
          ViaSBtn = False
        end
        object Id3LTF: TSBSComboBox
          Tag = 1
          Left = 241
          Top = 159
          Width = 57
          Height = 22
          HelpContext = 276
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ItemHeight = 14
          MaxLength = 40
          ParentFont = False
          TabOrder = 15
          ExtendedList = True
          MaxListWidth = 75
          ReadOnly = True
          Validate = True
        end
        object UseISCB: TBorCheck
          Tag = 1
          Left = 348
          Top = 157
          Width = 16
          Height = 20
          Color = clBtnFace
          Enabled = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentColor = False
          ParentFont = False
          TabOrder = 16
          TabStop = True
          TextId = 0
        end
        object IntBtn: TBitBtn
          Left = 351
          Top = 176
          Width = 13
          Height = 13
          HelpContext = 207
          Enabled = False
          TabOrder = 17
          Glyph.Data = {
            C6000000424DC60000000000000076000000280000000A0000000A0000000100
            0400000000005000000000000000000000001000000000000000000000000000
            80000080000000808000800000008000800080800000C0C0C000808080000000
            FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFFFF00FFFFFFFFFF00
            0000FFFFFFFFFF000000FFFFFFFFFF000000FFFF0FFFFF000000FFF000FFFF00
            0000FF00000FFF000000F0000000FF000000FFFFFFFFFF000000FFFFFFFFFF00
            0000FFFFFFFFFF000000}
        end
        object GLDescF: Text8Pt
          Left = 191
          Top = 109
          Width = 173
          Height = 22
          HelpContext = 275
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 12
          TextId = 0
          ViaSBtn = False
        end
        object edtMultiBuy: Text8Pt
          Tag = 1
          Left = 58
          Top = 159
          Width = 97
          Height = 22
          HelpContext = 8004
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 4
          TextId = 0
          ViaSBtn = False
        end
        object edtTransDiscount: Text8Pt
          Tag = 1
          Left = 58
          Top = 184
          Width = 97
          Height = 22
          HelpContext = 8005
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 5
          TextId = 0
          ViaSBtn = False
        end
        object Id3DiscF: Text8Pt
          Tag = 1
          Left = 58
          Top = 84
          Width = 97
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          TextId = 0
          ViaSBtn = False
        end
        object Id3DelF: TEditDate
          Tag = 1
          Left = 241
          Top = 184
          Width = 77
          Height = 22
          HelpContext = 273
          AutoSelect = False
          EditMask = '00/00/0000;0;'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          ReadOnly = True
          TabOrder = 18
          Placement = cpAbove
        end
        object Id3CostF: TCurrencyEdit
          Tag = 1
          Left = 241
          Top = 134
          Width = 123
          Height = 22
          HelpContext = 277
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 13
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object Id3LTotF: TCurrencyEdit
          Tag = 2
          Left = 58
          Top = 109
          Width = 97
          Height = 22
          HelpContext = 248
          TabStop = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 14
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object Id3PQtyF: TCurrencyEdit
          Tag = 1
          Left = 58
          Top = 9
          Width = 76
          Height = 22
          HelpContext = 267
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object Id3QtyF: TCurrencyEdit
          Tag = 1
          Left = 58
          Top = 34
          Width = 76
          Height = 22
          HelpContext = 247
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 1
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object Id3UPriceF: TCurrencyEdit
          Tag = 1
          Left = 58
          Top = 59
          Width = 97
          Height = 22
          HelpContext = 268
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 2
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
      end
      object Id3Panel3: TSBSPanel
        Left = -1
        Top = 220
        Width = 433
        Height = 149
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 4
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object UDF1L: Label8
          Left = 7
          Top = 11
          Width = 48
          Height = 14
          Caption = 'UD Field 1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF3L: Label8
          Left = 218
          Top = 11
          Width = 48
          Height = 14
          Caption = 'UD Field 3'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF2L: Label8
          Left = 7
          Top = 34
          Width = 48
          Height = 14
          Caption = 'UD Field 2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF4L: Label8
          Left = 218
          Top = 34
          Width = 48
          Height = 14
          Caption = 'UD Field 4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF6L: Label8
          Left = 6
          Top = 98
          Width = 48
          Height = 14
          Caption = 'UD Field 6'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF8L: Label8
          Left = 218
          Top = 74
          Width = 48
          Height = 14
          Caption = 'UD Field 8'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF10L: Label8
          Left = 218
          Top = 122
          Width = 54
          Height = 14
          Caption = 'UD Field 10'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF5L: Label8
          Left = 6
          Top = 74
          Width = 48
          Height = 14
          Caption = 'UD Field 5'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF7L: Label8
          Left = 6
          Top = 122
          Width = 48
          Height = 14
          Caption = 'UD Field 7'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF9L: Label8
          Left = 218
          Top = 98
          Width = 48
          Height = 14
          Caption = 'UD Field 9'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Bevel2: TBevel
          Left = 6
          Top = 58
          Width = 418
          Height = 3
        end
      end
      object pnlWebExtensions: TPanel
        Left = 0
        Top = 372
        Width = 432
        Height = 80
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 15
        Visible = False
        object Label4: TLabel
          Left = 5
          Top = 13
          Width = 51
          Height = 14
          Alignment = taRightJustify
          Caption = 'Reference'
        end
        object Label5: TLabel
          Left = 5
          Top = 43
          Width = 52
          Height = 14
          Alignment = taRightJustify
          Caption = 'Receipt No'
        end
        object Label6: TLabel
          Left = 194
          Top = 13
          Width = 73
          Height = 14
          Alignment = taRightJustify
          Caption = 'PostCode From'
        end
        object Label87: Label8
          Left = 207
          Top = 40
          Width = 60
          Height = 14
          Alignment = taRightJustify
          Caption = 'PostCode To'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object edtReference: Text8Pt
          Tag = 1
          Left = 60
          Top = 8
          Width = 121
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 20
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          TextId = 0
          ViaSBtn = False
        end
        object edtFromPostCode: Text8Pt
          Tag = 1
          Left = 274
          Top = 8
          Width = 121
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 15
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 2
          TextId = 0
          ViaSBtn = False
        end
        object edtReceiptNo: Text8Pt
          Tag = 1
          Left = 60
          Top = 40
          Width = 121
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 20
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 1
          TextId = 0
          ViaSBtn = False
        end
        object edtToPostCode: Text8Pt
          Tag = 1
          Left = 274
          Top = 40
          Width = 121
          Height = 22
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 15
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          TextId = 0
          ViaSBtn = False
        end
      end
      object LUD1F: Text8Pt
        Tag = 1
        Left = 72
        Top = 228
        Width = 140
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 5
        TextId = 0
        ViaSBtn = False
      end
      object LUD2F: Text8Pt
        Tag = 1
        Left = 72
        Top = 253
        Width = 140
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 6
        TextId = 0
        ViaSBtn = False
      end
      object LUD3F: Text8Pt
        Tag = 1
        Left = 286
        Top = 225
        Width = 140
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 7
        TextId = 0
        ViaSBtn = False
      end
      object LUD4F: Text8Pt
        Tag = 1
        Left = 286
        Top = 249
        Width = 140
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 8
        TextId = 0
        ViaSBtn = False
      end
      object Notebook1: TNotebook
        Left = 2
        Top = 4
        Width = 248
        Height = 33
        PageIndex = 1
        TabOrder = 1
        object TPage
          Left = 0
          Top = 0
          Caption = 'Stock'
          object id3LocLab: Label8
            Left = 177
            Top = 8
            Width = 27
            Height = 14
            Alignment = taRightJustify
            Caption = 'Locn '
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Id3SCodeLab: Label8
            Left = 5
            Top = 9
            Width = 43
            Height = 14
            Caption = 'Stk Code'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Id3SCodeF: Text8Pt
            Tag = 1
            Left = 48
            Top = 6
            Width = 127
            Height = 22
            Hint = 
              'Double click to drill down|Double clicking or using the down but' +
              'ton will drill down to the record for this field. The up button ' +
              'will search for the nearest match.'
            HelpContext = 256
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 0
            TextId = 0
            ViaSBtn = False
            ShowHilight = True
          end
          object Id3LocF: Text8Pt
            Tag = 1
            Left = 204
            Top = 6
            Width = 38
            Height = 22
            HelpContext = 274
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 1
            TextId = 0
            ViaSBtn = False
          end
        end
        object TPage
          Left = 0
          Top = 0
          Caption = 'NonStock'
          object Id1ItemLab: Label8
            Left = 5
            Top = 9
            Width = 19
            Height = 14
            Caption = 'Item'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Id1QtyLab: Label8
            Left = 87
            Top = 9
            Width = 17
            Height = 14
            Caption = 'Qty'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Id1ItemF: Text8Pt
            Tag = 1
            Left = 35
            Top = 6
            Width = 39
            Height = 22
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 0
            TextId = 0
            ViaSBtn = False
          end
          object Id1QtyF: TCurrencyEdit
            Tag = 1
            Left = 109
            Top = 6
            Width = 88
            Height = 22
            HelpContext = 247
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            Lines.Strings = (
              '0.67-')
            ParentFont = False
            ReadOnly = True
            TabOrder = 1
            WantReturns = False
            WordWrap = False
            AutoSize = False
            BlockNegative = False
            BlankOnZero = False
            DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
            ShowCurrency = False
            TextId = 0
            Value = -0.666666
          end
        end
      end
      object LUD5F: Text8Pt
        Tag = 1
        Left = 72
        Top = 289
        Width = 140
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 9
        TextId = 0
        ViaSBtn = False
      end
      object LUD6F: Text8Pt
        Tag = 1
        Left = 72
        Top = 313
        Width = 140
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 10
        TextId = 0
        ViaSBtn = False
      end
      object LUD7F: Text8Pt
        Tag = 1
        Left = 72
        Top = 337
        Width = 140
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 11
        TextId = 0
        ViaSBtn = False
      end
      object LUD9F: Text8Pt
        Tag = 1
        Left = 286
        Top = 313
        Width = 140
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 13
        TextId = 0
        ViaSBtn = False
      end
      object LUD8F: Text8Pt
        Tag = 1
        Left = 286
        Top = 289
        Width = 140
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 12
        TextId = 0
        ViaSBtn = False
      end
      object LUD10F: Text8Pt
        Tag = 1
        Left = 286
        Top = 337
        Width = 140
        Height = 22
        HelpContext = 466
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 14
        TextId = 0
        ViaSBtn = False
      end
    end
  end
end
