object frmStkLocDetl: TfrmStkLocDetl
  Left = 134
  Top = 159
  Width = 681
  Height = 303
  Caption = 'frmStkLocDetl'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object GroupBox1: TGroupBox
    Left = 6
    Top = 5
    Width = 155
    Height = 236
    TabOrder = 0
    object Label827: TLabel
      Left = 18
      Top = 17
      Width = 46
      Height = 14
      Caption = 'Min Stock'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label831: TLabel
      Left = 13
      Top = 45
      Width = 50
      Height = 14
      Caption = 'Max Stock'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label836: TLabel
      Left = 25
      Top = 73
      Width = 38
      Height = 14
      Caption = 'In Stock'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label835: TLabel
      Left = 22
      Top = 100
      Width = 41
      Height = 14
      Caption = '(Posted)'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label837: TLabel
      Left = 18
      Top = 128
      Width = 45
      Height = 14
      Caption = 'Allocated'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label838: TLabel
      Left = 17
      Top = 155
      Width = 46
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Picked'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label834: TLabel
      Left = 18
      Top = 209
      Width = 45
      Height = 14
      Caption = 'On Order'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label86: TLabel
      Left = 8
      Top = 182
      Width = 55
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Free Stock'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object SRMIF: TEdit
      Tag = 1
      Left = 66
      Top = 14
      Width = 80
      Height = 22
      HelpContext = 194
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object SRMXF: TEdit
      Tag = 1
      Left = 66
      Top = 42
      Width = 80
      Height = 22
      HelpContext = 194
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object SRISF: TEdit
      Left = 66
      Top = 70
      Width = 80
      Height = 22
      HelpContext = 195
      TabStop = False
      AutoSize = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 2
    end
    object SRPOF: TEdit
      Left = 66
      Top = 97
      Width = 80
      Height = 22
      HelpContext = 195
      TabStop = False
      AutoSize = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 3
    end
    object SRALF: TEdit
      Left = 66
      Top = 123
      Width = 80
      Height = 22
      HelpContext = 195
      TabStop = False
      AutoSize = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 4
    end
    object SRFRF: TEdit
      Left = 66
      Top = 177
      Width = 80
      Height = 22
      HelpContext = 195
      TabStop = False
      AutoSize = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 5
    end
    object SROOF: TEdit
      Left = 66
      Top = 204
      Width = 80
      Height = 22
      HelpContext = 195
      TabStop = False
      AutoSize = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 6
    end
    object SRPCK: TEdit
      Left = 66
      Top = 150
      Width = 80
      Height = 22
      HelpContext = 195
      TabStop = False
      AutoSize = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 7
    end
  end
  object GroupBox2: TGroupBox
    Left = 167
    Top = 5
    Width = 401
    Height = 236
    TabOrder = 1
    object Label828: TLabel
      Left = 29
      Top = 209
      Width = 54
      Height = 14
      Caption = 'Sales Price'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label829: TLabel
      Left = 34
      Top = 129
      Width = 49
      Height = 14
      Caption = 'Cost Price'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label81: TLabel
      Left = 292
      Top = 127
      Width = 27
      Height = 14
      Caption = 'Sales'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label82: TLabel
      Left = 254
      Top = 100
      Width = 65
      Height = 14
      Caption = 'Cost of Sales'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label83: TLabel
      Left = 214
      Top = 73
      Width = 106
      Height = 14
      Caption = 'Closing Stk/Write Offs'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label84: TLabel
      Left = 261
      Top = 45
      Width = 58
      Height = 14
      Caption = 'Stock Value'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object WIPLab: TLabel
      Left = 221
      Top = 18
      Width = 99
      Height = 14
      Caption = 'BoM/Finished Goods'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label88: TLabel
      Left = 18
      Top = 18
      Width = 65
      Height = 14
      Caption = 'Pref. Supplier'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label810: TLabel
      Left = 24
      Top = 74
      Width = 59
      Height = 14
      Caption = 'Bin Location'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object CCLab: TLabel
      Left = 47
      Top = 46
      Width = 36
      Height = 14
      Caption = 'CC/Dep'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object Label85: TLabel
      Left = 38
      Top = 157
      Width = 45
      Height = 14
      Caption = 'Re-Order'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object LabCur2: TLabel
      Left = 90
      Top = 182
      Width = 42
      Height = 13
      Caption = 'Currency'
    end
    object Label3: TLabel
      Left = 190
      Top = 182
      Width = 27
      Height = 13
      Caption = 'Value'
    end
    object LabMg: TLabel
      Left = 246
      Top = 182
      Width = 40
      Height = 13
      Caption = 'Margin%'
    end
    object SRCPCF: TComboBox
      Tag = 1
      Left = 87
      Top = 125
      Width = 48
      Height = 22
      HelpContext = 191
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      MaxLength = 3
      ParentFont = False
      TabOrder = 0
    end
    object SRCPF: TEdit
      Tag = 1
      Left = 137
      Top = 125
      Width = 95
      Height = 22
      HelpContext = 191
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object SRRPF: TEdit
      Tag = 1
      Left = 137
      Top = 153
      Width = 95
      Height = 22
      HelpContext = 192
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
    object SRRPCF: TComboBox
      Tag = 1
      Left = 87
      Top = 153
      Width = 48
      Height = 22
      HelpContext = 192
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      MaxLength = 3
      ParentFont = False
      TabOrder = 3
    end
    object SalGL: TEdit
      Tag = 1
      Left = 326
      Top = 125
      Width = 65
      Height = 22
      HelpContext = 201
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 4
    end
    object COSGL: TEdit
      Tag = 1
      Left = 326
      Top = 97
      Width = 65
      Height = 22
      HelpContext = 202
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 5
    end
    object WOGL: TEdit
      Tag = 1
      Left = 326
      Top = 70
      Width = 65
      Height = 22
      HelpContext = 203
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 6
    end
    object SVGL: TEdit
      Tag = 1
      Left = 326
      Top = 42
      Width = 65
      Height = 22
      HelpContext = 204
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 7
    end
    object WIPGL: TEdit
      Tag = 1
      Left = 326
      Top = 14
      Width = 65
      Height = 22
      HelpContext = 205
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 8
    end
    object SRFSF: TEdit
      Tag = 1
      Left = 87
      Top = 14
      Width = 78
      Height = 22
      Hint = 
        'Double click to drill down|Double clicking or using the down but' +
        'ton will drill down to the record for this field. The up button ' +
        'will search for the nearest match.'
      HelpContext = 198
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 9
    end
    object SRBLF: TEdit
      Tag = 1
      Left = 87
      Top = 70
      Width = 66
      Height = 22
      HelpContext = 200
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 10
    end
    object SRCCF: TEdit
      Tag = 1
      Left = 87
      Top = 42
      Width = 47
      Height = 22
      HelpContext = 199
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 11
    end
    object SRDepF: TEdit
      Tag = 1
      Left = 140
      Top = 42
      Width = 47
      Height = 22
      HelpContext = 199
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 12
    end
    object SRSBox2: TScrollBox
      Left = 87
      Top = 197
      Width = 208
      Height = 29
      HelpContext = 190
      HorzScrollBar.Visible = False
      Ctl3D = True
      ParentCtl3D = False
      TabOrder = 13
      object Label818: TLabel
        Left = 144
        Top = 6
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object Label819: TLabel
        Left = 145
        Top = 30
        Width = 7
        Height = 14
        Caption = 'B'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object Label820: TLabel
        Left = 144
        Top = 52
        Width = 7
        Height = 14
        Caption = 'C'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object Label821: TLabel
        Left = 145
        Top = 75
        Width = 7
        Height = 14
        Caption = 'D'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object Label822: TLabel
        Left = 145
        Top = 98
        Width = 6
        Height = 14
        Caption = 'E'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object Label823: TLabel
        Left = 145
        Top = 120
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object Label824: TLabel
        Left = 144
        Top = 144
        Width = 8
        Height = 14
        Caption = 'G'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object Label825: TLabel
        Left = 145
        Top = 167
        Width = 7
        Height = 14
        Caption = 'H'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
      end
      object SRSP1F: TEdit
        Tag = 1
        Left = 48
        Top = 2
        Width = 95
        Height = 22
        HelpContext = 190
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
      end
      object SRSP2F: TEdit
        Tag = 1
        Left = 48
        Top = 26
        Width = 95
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 4
      end
      object SRSP3F: TEdit
        Tag = 1
        Left = 48
        Top = 49
        Width = 95
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 7
      end
      object SRSP4F: TEdit
        Tag = 1
        Left = 48
        Top = 72
        Width = 95
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 10
      end
      object SRSP5F: TEdit
        Tag = 1
        Left = 48
        Top = 95
        Width = 95
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 13
      end
      object SRSP6F: TEdit
        Tag = 1
        Left = 48
        Top = 118
        Width = 95
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 16
      end
      object SRSP7F: TEdit
        Tag = 1
        Left = 48
        Top = 141
        Width = 95
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 19
      end
      object SRSP8F: TEdit
        Tag = 1
        Left = 48
        Top = 164
        Width = 95
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 22
      end
      object SRSPC1F: TComboBox
        Tag = 1
        Left = -2
        Top = 2
        Width = 48
        Height = 22
        HelpContext = 190
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 0
      end
      object SRSPC2F: TComboBox
        Tag = 1
        Left = -2
        Top = 26
        Width = 48
        Height = 22
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 3
      end
      object SRSPC3F: TComboBox
        Tag = 1
        Left = -2
        Top = 49
        Width = 48
        Height = 22
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 6
      end
      object SRSPC4F: TComboBox
        Tag = 1
        Left = -2
        Top = 72
        Width = 48
        Height = 22
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 9
      end
      object SRSPC5F: TComboBox
        Tag = 1
        Left = -2
        Top = 95
        Width = 48
        Height = 22
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 12
      end
      object SRSPC6F: TComboBox
        Tag = 1
        Left = -2
        Top = 118
        Width = 48
        Height = 22
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 15
      end
      object SRSPC8F: TComboBox
        Tag = 1
        Left = -2
        Top = 164
        Width = 48
        Height = 22
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 21
      end
      object SRGP1: TEdit
        Tag = 1
        Left = 152
        Top = 2
        Width = 35
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
      end
      object SRGP2: TEdit
        Tag = 1
        Left = 152
        Top = 26
        Width = 35
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 5
      end
      object SRGP3: TEdit
        Tag = 1
        Left = 152
        Top = 49
        Width = 35
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 8
      end
      object SRGP4: TEdit
        Tag = 1
        Left = 152
        Top = 72
        Width = 35
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 11
      end
      object SRGP5: TEdit
        Tag = 1
        Left = 152
        Top = 95
        Width = 35
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 14
      end
      object SRGP6: TEdit
        Tag = 1
        Left = 152
        Top = 118
        Width = 35
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 17
      end
      object SRGP7: TEdit
        Tag = 1
        Left = 152
        Top = 141
        Width = 35
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 20
      end
      object SRGP8: TEdit
        Tag = 1
        Left = 152
        Top = 164
        Width = 35
        Height = 22
        AutoSize = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 23
      end
      object SRSPC7F: TComboBox
        Tag = 1
        Left = -2
        Top = 141
        Width = 48
        Height = 22
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 18
      end
    end
  end
end
