object frmJobList: TfrmJobList
  Left = 199
  Top = 132
  Width = 391
  Height = 480
  Caption = 'Enterise COM Toolkit - Job Tree'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object lstJobs: TListBox
    Left = 8
    Top = 9
    Width = 354
    Height = 435
    ItemHeight = 13
    TabOrder = 0
  end
end
