library BtrvSQLTK;

uses
  SysUtils,
  Classes,
  Windows,
  SQLCompany in 'SQLCompany.pas',
  BtrvSQLU in 'BtrvSQLU.pas',
  DebugLogU in 'DebugLogU.pas',
  ClientIdU in 'ClientIdU.pas',
  SQLCache in 'SQLCache.pas',
  SQLLockU in 'SQLLockU.pas',
  SQLVariantsU in 'SQLVariantsU.pas',
  SQLStructuresU in 'SQLStructuresU.pas',
  GlobVar in '..\..\ENTRPRSE\R&D\GLOBVAR.PAS',
  SQLRedirectorU in 'SQLRedirectorU.pas',
  UNCCache in 'UNCCache.pas';

{$R *.res}

// MH 30/05/2014 v7.0.10 ABSEXCH-15404: Added PE Flags to force entire component to be loaded into memory
{$SetPEFlags IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP or IMAGE_FILE_NET_RUN_FROM_SWAP}


exports
  BTRCALL,
  BTRCALLID,
  WBTRVINIT,
  WBTRVSTOP,
  UsingSQL,
  OverrideUsingSQL,
  CreateDatabase,
  CreateCompany,
  AttachCompany,
  DetachCompany,
  DeleteCompany,
  GetConnectionString,
  OpenCompany,
  OpenCompanyByCode,
  GetCompanyCode,
  TableExists,
  DeleteTable,
  ValidCompany,
  ValidSystem,
  HasExclusiveAccess,
  ExportDataset,
  ImportDataset,
  GetErrorInformation,
  GetLongErrorInformation,
  CopyTable,
  UpdateTable,
  GetDBColumnName,
  GetDBTableName,
  Initialise,
  CompanyExists,
  CloseClientIdSession,
  SetCacheSize,
  DeleteRows,
  CreateCustomPrefillCache,
  UseCustomPrefillCache,
  DropCustomPrefillCache,
  PostToHistory,
  PostToYearDate,
  UseVariantForNextCall,
  ExecSQL,
  LastSQLError,
  StockFreeze,
  GetCommonConnectionString,
  CheckAllStock,
  GetLineNumberAccounts,
  GetLineNumberStock,
  ResetViewHistory,
  ResetAuditHistory,
  StockLocationFilter,
  UpdateCompanyCache,
  StockAddCustAnal,
  TotalProfitToDateRange,
  FillBudget,
  RemoveLastCommit,
  PartialUnpostHistory,
  RebuildCompanyCache,
  DiscardCachedData,
  UseSQLCacheList,
  CheckExchRnd,
  SetMemCallback,
  SQLFetch,
  EnteringModule,
  LeavingModule;

begin
end.
