object AboutFrm: TAboutFrm
  Left = 541
  Top = 231
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'About...Exchequer'
  ClientHeight = 303
  ClientWidth = 504
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  OldCreateOrder = True
  Position = poScreenCenter
  Scaled = False
  OnActivate = FormActivate
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 14
  object VerF: Label8
    Left = 166
    Top = 12
    Width = 328
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object DLLVer: Label8
    Left = 166
    Top = 26
    Width = 328
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object SBSPanel1: TSBSPanel
    Left = 6
    Top = 42
    Width = 143
    Height = 219
    BevelOuter = bvLowered
    TabOrder = 2
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    Purpose = puFrame
    object Image1: TImage
      Left = 3
      Top = 3
      Width = 136
      Height = 212
    end
  end
  object Memo1: TMemo
    Left = 166
    Top = 42
    Width = 328
    Height = 219
    Color = clBtnFace
    ReadOnly = True
    TabOrder = 1
  end
  object OkI1Btn: TButton
    Tag = 1
    Left = 212
    Top = 275
    Width = 80
    Height = 21
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 0
  end
end
