object SAdjCForm: TSAdjCForm
  Left = 569
  Top = 292
  BorderIcons = []
  BorderStyle = bsNone
  ClientHeight = 75
  ClientWidth = 236
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = True
  Position = poScreenCenter
  Scaled = False
  OnActivate = FormActivate
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object SetPanel: TSBSPanel
    Left = 0
    Top = 0
    Width = 236
    Height = 73
    BevelInner = bvRaised
    BevelOuter = bvLowered
    TabOrder = 0
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    Purpose = puFrame
  end
end
