object AdjLine: TAdjLine
  Left = 465
  Top = 287
  HelpContext = 439
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = 'Adjustment Line'
  ClientHeight = 180
  ClientWidth = 770
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  ShowHint = True
  Visible = True
  OnActivate = FormActivate
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 14
  object Label81: Label8
    Left = 386
    Top = 2
    Width = 40
    Height = 14
    Caption = ' Qty Out'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Id3QtyLab: Label8
    Left = 321
    Top = 2
    Width = 31
    Height = 14
    Caption = ' Qty In'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object PQLab: Label8
    Left = 208
    Top = 2
    Width = 43
    Height = 14
    Caption = 'Pack Qty'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object LocLab: Label8
    Left = 146
    Top = 2
    Width = 27
    Height = 14
    Caption = 'Locn.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label84: Label8
    Left = 480
    Top = 2
    Width = 43
    Height = 14
    Caption = 'Unit Cost'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object GLLab: Label8
    Left = 549
    Top = 2
    Width = 45
    Height = 14
    Caption = 'G/L Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Id3SCodeLab: Label8
    Left = 7
    Top = 2
    Width = 55
    Height = 14
    Caption = 'Stock Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label86: Label8
    Left = 269
    Top = 2
    Width = 23
    Height = 14
    Caption = 'Build'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF1L: Label8
    Left = 7
    Top = 103
    Width = 58
    Height = 14
    AutoSize = False
    Caption = 'UD Field 1'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF6L: Label8
    Left = 7
    Top = 127
    Width = 58
    Height = 14
    AutoSize = False
    Caption = 'UD Field 6'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF2L: Label8
    Left = 158
    Top = 103
    Width = 59
    Height = 14
    AutoSize = False
    Caption = 'UD Field 2'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF7L: Label8
    Left = 158
    Top = 127
    Width = 59
    Height = 14
    AutoSize = False
    Caption = 'UD Field 7'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF3L: Label8
    Left = 311
    Top = 103
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 3'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF8L: Label8
    Left = 311
    Top = 127
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 8'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF4L: Label8
    Left = 462
    Top = 103
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 4'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF9L: Label8
    Left = 462
    Top = 127
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 9'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF5L: Label8
    Left = 614
    Top = 103
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 5'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF10L: Label8
    Left = 614
    Top = 127
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 10'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label85: Label8
    Left = 5
    Top = 43
    Width = 84
    Height = 14
    Caption = 'Stock Description'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object CCLab: Label8
    Left = 187
    Top = 43
    Width = 14
    Height = 14
    Alignment = taCenter
    Caption = 'CC'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object DepLab: Label8
    Left = 232
    Top = 43
    Width = 22
    Height = 14
    Alignment = taCenter
    Caption = 'Dept'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object JCLab: Label8
    Left = 268
    Top = 43
    Width = 45
    Height = 14
    Caption = 'Job Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object JALab: Label8
    Left = 381
    Top = 43
    Width = 61
    Height = 14
    Caption = 'Job Analysis'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object A1SCodef: Text8Pt
    Tag = 1
    Left = 5
    Top = 16
    Width = 126
    Height = 22
    Hint = 
      'Double click to drill down|Double clicking or using the down but' +
      'ton will drill down to the record for this field. The up button ' +
      'will search for the nearest match.'
    HelpContext = 256
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 0
    OnDblClick = A1SCodefDblClick
    OnExit = A1SCodefExit
    TextId = 0
    ViaSBtn = False
    Link_to_Stock = True
    ShowHilight = True
  end
  object A1PQF: TCurrencyEdit
    Tag = 1
    Left = 189
    Top = 16
    Width = 70
    Height = 22
    HelpContext = 267
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 2
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object A1QIF: TCurrencyEdit
    Tag = 1
    Left = 297
    Top = 16
    Width = 70
    Height = 22
    HelpContext = 444
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 4
    WantReturns = False
    WordWrap = False
    OnEnter = A1QIFEnter
    OnExit = A1QIFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object A1LOF: Text8Pt
    Tag = 1
    Left = 133
    Top = 16
    Width = 54
    Height = 22
    HelpContext = 274
    CharCase = ecUpperCase
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 1
    OnEnter = A1LOFEnter
    OnExit = A1LOFExit
    TextId = 0
    ViaSBtn = False
  end
  object A1GLF: Text8Pt
    Tag = 1
    Left = 541
    Top = 16
    Width = 57
    Height = 22
    HelpContext = 275
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 7
    OnEnter = A1GLFEnter
    OnExit = A1GLFExit
    TextId = 0
    ViaSBtn = False
  end
  object A1UCF: TCurrencyEdit
    Tag = 1
    Left = 442
    Top = 16
    Width = 97
    Height = 22
    HelpContext = 277
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 6
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object A1QOF: TCurrencyEdit
    Tag = 1
    Left = 369
    Top = 16
    Width = 70
    Height = 22
    HelpContext = 445
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 5
    WantReturns = False
    WordWrap = False
    OnEnter = A1QIFEnter
    OnExit = A1QIFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object Okdb1Btn: TButton
    Tag = 1
    Left = 591
    Top = 149
    Width = 80
    Height = 21
    HelpContext = 278
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 23
    OnClick = Candb1BtnClick
  end
  object Candb1Btn: TButton
    Tag = 1
    Left = 679
    Top = 149
    Width = 80
    Height = 21
    HelpContext = 279
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 24
    OnClick = Candb1BtnClick
  end
  object A1BUF: TBorCheck
    Left = 264
    Top = 19
    Width = 28
    Height = 17
    Hint = 
      'Adjust components from this Bill of Material|Clicking this check' +
      ' box allows the component element of a BOM to be deducted/credit' +
      'ed according to the stock movement of the BOM.'
    HelpContext = 447
    Caption = '?'
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 3
    TabStop = True
    TextId = 0
    OnClick = A1BUFClick
  end
  object THUD1F: Text8Pt
    Tag = 1
    Left = 63
    Top = 99
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 13
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD6F: Text8Pt
    Tag = 1
    Left = 63
    Top = 123
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 18
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD2F: Text8Pt
    Tag = 1
    Left = 215
    Top = 99
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 14
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD7F: Text8Pt
    Tag = 1
    Left = 215
    Top = 123
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 19
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD3F: Text8Pt
    Tag = 1
    Left = 367
    Top = 99
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 15
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD8F: Text8Pt
    Tag = 1
    Left = 367
    Top = 123
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 20
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD4F: Text8Pt
    Tag = 1
    Left = 519
    Top = 99
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 16
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD9F: Text8Pt
    Tag = 1
    Left = 519
    Top = 123
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 21
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD5F: Text8Pt
    Tag = 1
    Left = 671
    Top = 99
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 17
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD10F: Text8Pt
    Tag = 1
    Left = 671
    Top = 123
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 22
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object A1SDF: Text8Pt
    Left = 4
    Top = 59
    Width = 164
    Height = 22
    HelpContext = 446
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 8
    TextId = 0
    ViaSBtn = False
  end
  object A1CCF: Text8Pt
    Tag = 1
    Left = 170
    Top = 59
    Width = 46
    Height = 22
    HelpContext = 272
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 9
    OnExit = A1CCFExit
    TextId = 0
    ViaSBtn = False
  end
  object A1DpF: Text8Pt
    Tag = 1
    Left = 218
    Top = 59
    Width = 46
    Height = 22
    HelpContext = 272
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 10
    OnExit = A1CCFExit
    TextId = 0
    ViaSBtn = False
  end
  object A1JCF: Text8Pt
    Tag = 1
    Left = 267
    Top = 59
    Width = 111
    Height = 22
    HelpContext = 465
    CharCase = ecUpperCase
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 11
    OnExit = A1JCFExit
    TextId = 0
    ViaSBtn = False
  end
  object A1JAF: Text8Pt
    Tag = 1
    Left = 381
    Top = 59
    Width = 106
    Height = 22
    HelpContext = 466
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 12
    OnExit = A1JAFExit
    TextId = 0
    ViaSBtn = False
  end
end
