object DebugForm: TDebugForm
  Left = 177
  Top = 119
  Width = 435
  Height = 300
  Caption = 'DebugForm'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = True
  PixelsPerInch = 96
  TextHeight = 13
  object DebugBox1: TDebugBox
    Caption = 'Debug Box'
    Visible = False
    Left = 258
    Top = 32
  end
end
