object DiaryNoteFrm: TDiaryNoteFrm
  Left = 313
  Top = 200
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Note Entry'
  ClientHeight = 58
  ClientWidth = 587
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  OnCreate = FormCreate
  OnKeyPress = EnterKeyPressHandler
  PixelsPerInch = 96
  TextHeight = 13
  object MainPnl: TPanel
    Left = 0
    Top = 0
    Width = 587
    Height = 58
    Align = alClient
    BevelInner = bvRaised
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object NoteLineTxt: Text8Pt
      Left = 79
      Top = 28
      Width = 418
      Height = 22
      HelpContext = 113
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 63
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 0
      OnKeyDown = EnterKeyDownHandler
      OnKeyPress = EnterKeyPressHandler
      TextId = 0
      ViaSBtn = False
    end
    object NotePnl: TPanel
      Left = 78
      Top = 4
      Width = 419
      Height = 23
      BevelInner = bvRaised
      BevelOuter = bvLowered
      TabOrder = 4
      object NotesLbl: Label8
        Left = 13
        Top = 4
        Width = 28
        Height = 14
        Caption = 'Notes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object ToLbl: Label8
        Left = 75
        Top = 4
        Width = 14
        Height = 14
        Caption = 'To:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object RepeatLbl: Label8
        Left = 276
        Top = 4
        Width = 71
        Height = 14
        Caption = 'Repeat every :'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object DaysLbl: Label8
        Left = 385
        Top = 4
        Width = 24
        Height = 14
        Caption = 'days'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object NoteAlarmChk: TBorCheck
        Left = 147
        Top = 2
        Width = 50
        Height = 16
        HelpContext = 114
        Caption = 'Alarm'
        CheckColor = clWindowText
        Color = clBtnFace
        Enabled = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 1
        TabStop = True
        TextId = 0
        OnClick = NoteAlarmChkClick
        OnKeyDown = EnterKeyDownHandler
        OnKeyPress = EnterKeyPressHandler
      end
      object NoteAlarmTxt: TEditDate
        Left = 203
        Top = 2
        Width = 67
        Height = 18
        HelpContext = 114
        AutoSelect = False
        AutoSize = False
        Color = clWhite
        EditMask = '00/00/0000;0;'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 10
        ParentFont = False
        TabOrder = 2
        Text = '15031995'
        OnKeyDown = EnterKeyDownHandler
        OnKeyPress = EnterKeyPressHandler
        Placement = cpAbove
      end
      object NoteForTxt: Text8Pt
        Left = 92
        Top = 2
        Width = 52
        Height = 18
        HelpContext = 579
        AutoSize = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 0
        OnExit = NoteForTxtExit
        OnKeyDown = EnterKeyDownHandler
        OnKeyPress = EnterKeyPressHandler
        TextId = 0
        ViaSBtn = False
      end
      object NoteRepeatTxt: TCurrencyEdit
        Left = 348
        Top = 2
        Width = 35
        Height = 18
        HelpContext = 114
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'ARIAL'
        Font.Style = []
        Lines.Strings = (
          '0 ')
        MaxLength = 4
        ParentFont = False
        TabOrder = 3
        WantReturns = False
        WordWrap = False
        OnKeyDown = EnterKeyDownHandler
        OnKeyPress = EnterKeyPressHandler
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0 ;###,###,##0-'
        DecPlaces = 0
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
    end
    object DatePnl: TPanel
      Left = 4
      Top = 4
      Width = 70
      Height = 22
      BevelInner = bvRaised
      BevelOuter = bvLowered
      TabOrder = 3
      object DateChk: TBorCheck
        Left = 3
        Top = 2
        Width = 61
        Height = 16
        HelpContext = 112
        Caption = 'Date'
        CheckColor = clWindowText
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 0
        TabStop = True
        TextId = 0
        OnKeyDown = EnterKeyDownHandler
        OnKeyPress = EnterKeyPressHandler
      end
    end
    object NoteDateTxt: TEditDate
      Left = 4
      Top = 28
      Width = 71
      Height = 21
      HelpContext = 112
      AutoSelect = False
      AutoSize = False
      Color = clWhite
      EditMask = '00/00/0000;0;'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      TabOrder = 5
      Text = '01012010'
      OnKeyDown = EnterKeyDownHandler
      OnKeyPress = EnterKeyPressHandler
      Placement = cpAbove
      AllowBlank = True
    end
    object OkBtn: TButton
      Left = 500
      Top = 5
      Width = 80
      Height = 21
      Caption = '&OK'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ModalResult = 1
      ParentFont = False
      TabOrder = 1
    end
    object CancelBtn: TButton
      Left = 500
      Top = 28
      Width = 80
      Height = 21
      Cancel = True
      Caption = '&Cancel'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ModalResult = 2
      ParentFont = False
      TabOrder = 2
    end
  end
  object SpellCheck4Modal1: TSpellCheck4Modal
    Version = 'TSpellCheck4Modal v5.70.001 for Delphi 6.01'
    Top = 2
  end
end
