object ThreadMsg: TThreadMsg
  Left = 297
  Top = 164
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  ClientHeight = 131
  ClientWidth = 299
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = True
  Position = poScreenCenter
  Scaled = False
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDeactivate = FormDeactivate
  PixelsPerInch = 96
  TextHeight = 13
  object CanCP1Btn: TButton
    Tag = 1
    Left = 112
    Top = 98
    Width = 80
    Height = 22
    Cancel = True
    Caption = '&OK'
    Default = True
    ModalResult = 1
    TabOrder = 0
    OnClick = CanCP1BtnClick
  end
  object SBSPanel3: TSBSPanel
    Left = 5
    Top = 2
    Width = 289
    Height = 86
    BevelInner = bvRaised
    BevelOuter = bvLowered
    TabOrder = 1
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    object Label1: Label8
      Left = 8
      Top = 4
      Width = 273
      Height = 20
      Alignment = taCenter
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label2: Label8
      Left = 8
      Top = 24
      Width = 273
      Height = 20
      Alignment = taCenter
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label3: Label8
      Left = 8
      Top = 40
      Width = 273
      Height = 20
      Alignment = taCenter
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label4: Label8
      Left = 8
      Top = 60
      Width = 273
      Height = 20
      Alignment = taCenter
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
  end
  object NoCP1Btn: TButton
    Tag = 1
    Left = 196
    Top = 98
    Width = 80
    Height = 22
    Caption = '&No'
    Enabled = False
    ModalResult = 2
    TabOrder = 2
    Visible = False
    OnClick = CanCP1BtnClick
  end
end
