Path1    = 'Cust\';
Path2    = 'Trans\';
Path3    = 'Misc\';
Path4    = 'Stock\';
Path5    = 'Reports\';
Path6    = 'Jobs\';
PathSys  = 'ExchqSS.Dat';
PathPrn  = 'ExchqPRN.Dat';
PathDocs = 'Docs\';
PathMaster = 'DocMastr\';
PathEBus = 'Ebus\';
{PathEpos = 'Epos\';}

CustName    = 'CustSupp.Dat';
DocName     = 'Document.Dat';
DetailName  = 'Details.Dat';
HistName    = 'History.Dat';
NomNam      = 'Nominal.Dat';
PassNam     = 'ExchqChk.Dat';
MiscNam     = 'ExStkChk.Dat';
NumNam      = 'ExchqNum.Dat';
StockNam    = 'Stock.Dat';
RepDictNam  = 'Dictnary.Dat';
RepRepNam   = 'Reports.Dat';
JobRecNam   = 'JobHead.Dat';
JobMiscNam  = 'JobMisc.Dat';
JobDetNam   = 'JobDet.Dat';
JobCtrlNam  = 'JobCtrl.Dat';
MLocName    = 'MLocStk.Dat';
MultCompNam = 'Company.Dat';
xoListNam   = 'XOMisc.DAT';
xoGroupNam  = 'XOGroup.Dat';
NVNam       = 'NomView.Dat';
MultiBuyNam = 'MultiBuy.Dat';
QtyBreakNam = 'QtyBreak.dat';


