object JAPLine: TJAPLine
  Left = 416
  Top = 89
  HelpContext = 1555
  ActiveControl = JCode
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = 'Job Application Line Entry'
  ClientHeight = 469
  ClientWidth = 469
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  ShowHint = True
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 14
  object PageControl1: TPageControl
    Left = 0
    Top = 0
    Width = 469
    Height = 469
    ActivePage = TabSheet3
    Align = alClient
    TabIndex = 2
    TabOrder = 1
    object TabSheet1: TTabSheet
      HelpContext = 1568
      Caption = 'Application'
      object Label87: Label8
        Left = 20
        Top = 134
        Width = 64
        Height = 14
        Alignment = taRightJustify
        Caption = 'Qty/Narrative'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label83: Label8
        Left = 115
        Top = 155
        Width = 34
        Height = 14
        Caption = 'Budget'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label88: Label8
        Left = 3
        Top = 227
        Width = 80
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Contract Totals'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label89: Label8
        Left = 223
        Top = 155
        Width = 36
        Height = 14
        Caption = 'Applied'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label810: Label8
        Left = 328
        Top = 155
        Width = 40
        Height = 14
        Caption = 'Certified'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label816: Label8
        Left = 98
        Top = 197
        Width = 80
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Incremental'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label821: Label8
        Left = 98
        Top = 173
        Width = 80
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Gross'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Hrs: TCurrencyEdit
        Tag = 1
        Left = 88
        Top = 131
        Width = 56
        Height = 22
        HelpContext = 1534
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        WantReturns = False
        WordWrap = False
        OnExit = HrsExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object CertF: TCurrencyEdit
        Tag = 1
        Left = 292
        Top = 195
        Width = 90
        Height = 22
        HelpContext = 1536
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 5
        WantReturns = False
        WordWrap = False
        OnEnter = CertFEnter
        OnExit = HrsExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object NarF: Text8Pt
        Tag = 1
        Left = 147
        Top = 131
        Width = 244
        Height = 22
        HelpContext = 1534
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 60
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 1
        TextId = 0
        ViaSBtn = False
      end
      object AppF: TCurrencyEdit
        Tag = 1
        Left = 189
        Top = 195
        Width = 90
        Height = 22
        HelpContext = 1535
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        ReadOnly = True
        TabOrder = 4
        WantReturns = False
        WordWrap = False
        OnExit = HrsExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object YTDBudgetF: TCurrencyEdit
        Tag = 1
        Left = 88
        Top = 221
        Width = 90
        Height = 22
        HelpContext = 1558
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        ReadOnly = True
        TabOrder = 6
        WantReturns = False
        WordWrap = False
        OnExit = HrsExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object YTDAppF: TCurrencyEdit
        Tag = 1
        Left = 189
        Top = 221
        Width = 90
        Height = 22
        HelpContext = 1535
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        ReadOnly = True
        TabOrder = 7
        WantReturns = False
        WordWrap = False
        OnExit = HrsExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object YTDCertF: TCurrencyEdit
        Tag = 1
        Left = 292
        Top = 221
        Width = 90
        Height = 22
        HelpContext = 1536
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        ReadOnly = True
        TabOrder = 8
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object GAppF: TCurrencyEdit
        Tag = 1
        Left = 189
        Top = 169
        Width = 90
        Height = 22
        HelpContext = 1535
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        WantReturns = False
        WordWrap = False
        OnEnter = GAppFEnter
        OnExit = GAppFExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object GCertF: TCurrencyEdit
        Tag = 1
        Left = 292
        Top = 169
        Width = 90
        Height = 22
        HelpContext = 1536
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 3
        WantReturns = False
        WordWrap = False
        OnEnter = GCertFEnter
        OnExit = GCertFExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
    end
    object TabSheet2: TTabSheet
      HelpContext = 1563
      Caption = 'Deductions'
      ImageIndex = 1
      object Label814: Label8
        Left = 242
        Top = 120
        Width = 54
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Deduction  '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label811: Label8
        Left = 8
        Top = 202
        Width = 75
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Narrative '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label813: Label8
        Left = 242
        Top = 176
        Width = 54
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Value   '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object JADedF: TCurrencyEdit
        Tag = 1
        Left = 298
        Top = 117
        Width = 106
        Height = 22
        HelpContext = 1544
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '-0.67%')
        MaxLength = 13
        ParentFont = False
        TabOrder = 1
        WantReturns = False
        WordWrap = False
        OnExit = JARTCBChange
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = ' #0.00%;-#0.00%'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object JACRCB: TBorCheckEx
        Tag = 1
        Left = 10
        Top = 146
        Width = 170
        Height = 20
        HelpContext = 1546
        Align = alRight
        Caption = 'Calculate before Retention'
        CheckColor = clWindowText
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 2
        TabStop = True
        TextId = 0
        OnClick = JARTCBChange
      end
      object JAADCB: TSBSComboBox
        Tag = 1
        Left = 239
        Top = 146
        Width = 167
        Height = 22
        Style = csDropDownList
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 0
        ParentFont = False
        TabOrder = 3
        OnChange = JARTCBChange
        MaxListWidth = 0
      end
      object JADedNF: Text8Pt
        Tag = 1
        Left = 85
        Top = 200
        Width = 244
        Height = 22
        HelpContext = 1534
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 60
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 6
        TextId = 0
        ViaSBtn = False
      end
      object cbov1: TBorCheckEx
        Tag = 1
        Left = 10
        Top = 172
        Width = 106
        Height = 20
        Align = alRight
        Caption = 'Override Value'
        CheckColor = clWindowText
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 4
        TabStop = True
        TextId = 0
        OnClick = cbov1Click
      end
      object DedValF: TCurrencyEdit
        Tag = 1
        Left = 298
        Top = 173
        Width = 106
        Height = 22
        HelpContext = 1409
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 5
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object JACompCB: TSBSComboBox
        Tag = 1
        Left = 10
        Top = 117
        Width = 181
        Height = 22
        HelpContext = 1542
        Style = csDropDownList
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        ItemIndex = 0
        ParentFont = False
        TabOrder = 0
        Text = 'Deduct normally'
        OnChange = JACompCBChange
        Items.Strings = (
          'Deduct normally'
          'Calc. after all other Deductions'
          'Contra Deduction')
        MaxListWidth = 0
      end
    end
    object TabSheet3: TTabSheet
      HelpContext = 1564
      Caption = 'Retention'
      ImageIndex = 2
      object Label817: Label8
        Left = 9
        Top = 118
        Width = 71
        Height = 14
        Caption = 'Retention Type'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label818: Label8
        Left = 242
        Top = 118
        Width = 64
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Retention %  '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label819: Label8
        Left = 9
        Top = 161
        Width = 74
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Expiry Basis  '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label820: Label8
        Left = 214
        Top = 161
        Width = 92
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Expiry Interval  '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label812: Label8
        Left = 5
        Top = 220
        Width = 75
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Narrative '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label815: Label8
        Left = 250
        Top = 193
        Width = 54
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Value   '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object JARTCB: TSBSComboBox
        Tag = 1
        Left = 83
        Top = 115
        Width = 103
        Height = 22
        HelpContext = 1496
        Style = csDropDownList
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        ParentFont = False
        TabOrder = 0
        OnChange = JARTCBChange
        MaxListWidth = 0
      end
      object JARVF: TCurrencyEdit
        Tag = 1
        Left = 307
        Top = 115
        Width = 69
        Height = 22
        HelpContext = 1547
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67%-')
        MaxLength = 13
        ParentFont = False
        TabOrder = 1
        WantReturns = False
        WordWrap = False
        OnExit = JARTCBChange
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object JAECB: TSBSComboBox
        Tag = 1
        Left = 83
        Top = 158
        Width = 124
        Height = 22
        HelpContext = 1548
        Style = csDropDownList
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        ParentFont = False
        TabOrder = 2
        OnChange = JAECBChange
        Items.Strings = (
          'Months'
          'Years'
          'on Practical Application'
          'on Final Application')
        MaxListWidth = 0
      end
      object JAEIF: TCurrencyEdit
        Tag = 1
        Left = 307
        Top = 158
        Width = 69
        Height = 22
        HelpContext = 1549
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0 ')
        MaxLength = 2
        ParentFont = False
        TabOrder = 3
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0 ;###,###,##0-'
        DecPlaces = 0
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object JARetNF: Text8Pt
        Tag = 1
        Left = 83
        Top = 218
        Width = 244
        Height = 22
        HelpContext = 1534
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 60
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 6
        TextId = 0
        ViaSBtn = False
      end
      object cbOv2: TBorCheckEx
        Tag = 1
        Left = 82
        Top = 188
        Width = 113
        Height = 20
        Align = alRight
        Caption = 'Override Value'
        CheckColor = clWindowText
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 4
        TabStop = True
        TextId = 0
        OnClick = cbOv2Click
      end
      object RetValF: TCurrencyEdit
        Tag = 1
        Left = 306
        Top = 188
        Width = 106
        Height = 22
        HelpContext = 1409
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 5
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object cbMaterialsOnly: TBorCheck
        Left = 306
        Top = 139
        Width = 98
        Height = 16
        Align = alRight
        Caption = 'Materials only'
        Color = clBtnFace
        ParentColor = False
        TabOrder = 7
        TextId = 0
      end
    end
  end
  object Okdb1Btn: TButton
    Tag = 1
    Left = 148
    Top = 436
    Width = 80
    Height = 21
    HelpContext = 1029
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 3
    OnClick = Candb1BtnClick
  end
  object Candb1Btn: TButton
    Tag = 1
    Left = 232
    Top = 436
    Width = 80
    Height = 21
    HelpContext = 1030
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 4
    OnClick = Candb1BtnClick
  end
  object SBSPanel1: TSBSPanel
    Left = 2
    Top = 25
    Width = 439
    Height = 114
    BevelOuter = bvNone
    TabOrder = 0
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    object Label81: Label8
      Left = 38
      Top = 12
      Width = 45
      Height = 14
      Caption = 'Job Code'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label84: Label8
      Left = 222
      Top = 12
      Width = 74
      Height = 14
      Caption = 'Job Description'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object CCLab: Label8
      Left = 234
      Top = 68
      Width = 36
      Height = 14
      Caption = 'CC/Dep'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label85: Label8
      Left = 199
      Top = 40
      Width = 99
      Height = 14
      Caption = 'Analysis Description'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label82: Label8
      Left = 33
      Top = 68
      Width = 46
      Height = 14
      Caption = 'Line Type'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label86: Label8
      Left = 13
      Top = 41
      Width = 70
      Height = 14
      Caption = 'Analysis Code'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Bevel1: TBevel
      Left = 45
      Top = 102
      Width = 359
      Height = 2
      Shape = bsTopLine
    end
    object JCode: Text8Pt
      Tag = 1
      Left = 87
      Top = 9
      Width = 90
      Height = 22
      Hint = 
        'Double click to drill down|Double clicking or using the down but' +
        'ton will drill down to the record for this field. The up button ' +
        'will search for the nearest match.'
      HelpContext = 1508
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 0
      OnExit = JCodeExit
      TextId = 0
      ViaSBtn = False
      Link_to_Job = True
      ShowHilight = True
    end
    object JDesc: Text8Pt
      Left = 300
      Top = 9
      Width = 136
      Height = 22
      HelpContext = 1508
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 1
      TextId = 0
      ViaSBtn = False
    end
    object RtDesc: Text8Pt
      Left = 300
      Top = 37
      Width = 136
      Height = 22
      HelpContext = 1532
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 3
      TextId = 0
      ViaSBtn = False
    end
    object Id3VATF: TSBSComboBox
      Tag = 1
      Left = 300
      Top = 64
      Width = 41
      Height = 22
      HelpContext = 1533
      Style = csDropDownList
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      MaxLength = 1
      ParentFont = False
      TabOrder = 5
      OnExit = Id3VATFExit
      AllowChangeInExit = True
      ExtendedList = True
      MaxListWidth = 75
      ReadOnly = True
      Validate = True
    end
    object NTDepF: Text8Pt
      Tag = 1
      Left = 391
      Top = 64
      Width = 47
      Height = 22
      HelpContext = 1533
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 7
      OnExit = NTCCFExit
      TextId = 0
      ViaSBtn = False
    end
    object NTCCF: Text8Pt
      Tag = 1
      Left = 342
      Top = 64
      Width = 47
      Height = 22
      HelpContext = 1533
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 6
      OnExit = NTCCFExit
      TextId = 0
      ViaSBtn = False
    end
    object SRLTF: TSBSComboBox
      Tag = 1
      Left = 87
      Top = 64
      Width = 107
      Height = 22
      HelpContext = 276
      Style = csDropDownList
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      MaxLength = 40
      ParentFont = False
      TabOrder = 4
      MaxListWidth = 75
      Validate = True
    end
    object Anal: Text8Pt
      Tag = 1
      Left = 87
      Top = 37
      Width = 90
      Height = 22
      HelpContext = 1532
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 2
      OnExit = AnalExit
      TextId = 0
      ViaSBtn = False
    end
  end
  object SBSPanel2: TSBSPanel
    Left = 3
    Top = 271
    Width = 433
    Height = 162
    BevelOuter = bvNone
    TabOrder = 2
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    object UDF1L: Label8
      Left = 27
      Top = 16
      Width = 49
      Height = 14
      AutoSize = False
      Caption = 'UD Field 1'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object UDF2L: Label8
      Left = 234
      Top = 16
      Width = 57
      Height = 14
      AutoSize = False
      Caption = 'UD Field 2'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object UDF4L: Label8
      Left = 234
      Top = 44
      Width = 57
      Height = 14
      AutoSize = False
      Caption = 'UD Field 4'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object UDF3L: Label8
      Left = 27
      Top = 44
      Width = 49
      Height = 14
      AutoSize = False
      Caption = 'UD Field 3'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Bevel2: TBevel
      Left = 38
      Top = 4
      Width = 359
      Height = 2
      Shape = bsTopLine
    end
    object Bevel3: TBevel
      Left = 47
      Top = 152
      Width = 359
      Height = 2
    end
    object UDF5L: Label8
      Left = 27
      Top = 72
      Width = 49
      Height = 14
      AutoSize = False
      Caption = 'UD Field 5'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object UDF6L: Label8
      Left = 234
      Top = 72
      Width = 57
      Height = 14
      AutoSize = False
      Caption = 'UD Field 6'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object UDF7L: Label8
      Left = 27
      Top = 98
      Width = 49
      Height = 14
      AutoSize = False
      Caption = 'UD Field 7'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object UDF8L: Label8
      Left = 234
      Top = 98
      Width = 57
      Height = 14
      AutoSize = False
      Caption = 'UD Field 8'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object UDF9L: Label8
      Left = 27
      Top = 124
      Width = 49
      Height = 14
      AutoSize = False
      Caption = 'UD Field 9'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object UDF10L: Label8
      Left = 234
      Top = 124
      Width = 57
      Height = 14
      AutoSize = False
      Caption = 'UD Field 10'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object THUD1F: Text8Pt
      Tag = 1
      Left = 78
      Top = 12
      Width = 120
      Height = 22
      HelpContext = 283
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ReadOnly = True
      TabOrder = 0
      OnExit = THUD1FExit
      TextId = 0
      ViaSBtn = False
      OnEntHookEvent = THUD1FEntHookEvent
    end
    object THUD2F: Text8Pt
      Tag = 1
      Left = 293
      Top = 12
      Width = 120
      Height = 22
      HelpContext = 283
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ReadOnly = True
      TabOrder = 1
      OnExit = THUD1FExit
      TextId = 0
      ViaSBtn = False
      OnEntHookEvent = THUD1FEntHookEvent
    end
    object THUD4F: Text8Pt
      Tag = 1
      Left = 293
      Top = 40
      Width = 120
      Height = 22
      HelpContext = 283
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ReadOnly = True
      TabOrder = 3
      OnExit = THUD1FExit
      TextId = 0
      ViaSBtn = False
      OnEntHookEvent = THUD1FEntHookEvent
    end
    object THUD3F: Text8Pt
      Tag = 1
      Left = 78
      Top = 40
      Width = 120
      Height = 22
      HelpContext = 283
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ReadOnly = True
      TabOrder = 2
      OnExit = THUD1FExit
      TextId = 0
      ViaSBtn = False
      OnEntHookEvent = THUD1FEntHookEvent
    end
    object THUD5F: Text8Pt
      Tag = 1
      Left = 78
      Top = 68
      Width = 120
      Height = 22
      HelpContext = 283
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ReadOnly = True
      TabOrder = 4
      OnExit = THUD1FExit
      TextId = 0
      ViaSBtn = False
      OnEntHookEvent = THUD1FEntHookEvent
    end
    object THUD6F: Text8Pt
      Tag = 1
      Left = 293
      Top = 68
      Width = 120
      Height = 22
      HelpContext = 283
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ReadOnly = True
      TabOrder = 5
      OnExit = THUD1FExit
      TextId = 0
      ViaSBtn = False
      OnEntHookEvent = THUD1FEntHookEvent
    end
    object THUD7F: Text8Pt
      Tag = 1
      Left = 78
      Top = 94
      Width = 120
      Height = 22
      HelpContext = 283
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ReadOnly = True
      TabOrder = 6
      OnExit = THUD1FExit
      TextId = 0
      ViaSBtn = False
      OnEntHookEvent = THUD1FEntHookEvent
    end
    object THUD8F: Text8Pt
      Tag = 1
      Left = 293
      Top = 94
      Width = 120
      Height = 22
      HelpContext = 283
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ReadOnly = True
      TabOrder = 7
      OnExit = THUD1FExit
      TextId = 0
      ViaSBtn = False
      OnEntHookEvent = THUD1FEntHookEvent
    end
    object THUD9F: Text8Pt
      Tag = 1
      Left = 78
      Top = 120
      Width = 120
      Height = 22
      HelpContext = 283
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ReadOnly = True
      TabOrder = 8
      OnExit = THUD1FExit
      TextId = 0
      ViaSBtn = False
      OnEntHookEvent = THUD1FEntHookEvent
    end
    object THUD10F: Text8Pt
      Tag = 1
      Left = 293
      Top = 120
      Width = 120
      Height = 22
      HelpContext = 283
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ReadOnly = True
      TabOrder = 9
      OnExit = THUD1FExit
      TextId = 0
      ViaSBtn = False
      OnEntHookEvent = THUD1FEntHookEvent
    end
  end
end
