object JCEmpP1: TJCEmpP1
  Left = 367
  Top = 248
  HelpContext = 1102
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Time Rate Entry'
  ClientHeight = 178
  ClientWidth = 401
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 14
  object SBSPanel1: TSBSPanel
    Left = 6
    Top = 4
    Width = 387
    Height = 131
    BevelInner = bvRaised
    BevelOuter = bvLowered
    TabOrder = 12
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    object Label84: Label8
      Left = 16
      Top = 73
      Width = 60
      Height = 14
      Caption = 'Payroll Code'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label82: Label8
      Left = 177
      Top = 73
      Width = 47
      Height = 14
      Caption = 'Time Cost'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label81: Label8
      Left = 6
      Top = 42
      Width = 70
      Height = 14
      Caption = 'Analysis Code'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Id3SCodeLab: Label8
      Left = 26
      Top = 12
      Width = 50
      Height = 14
      Caption = 'Rate Code'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label83: Label8
      Left = 177
      Top = 104
      Width = 60
      Height = 14
      Caption = 'Time Charge'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label86: Label8
      Left = 179
      Top = 11
      Width = 25
      Height = 14
      Caption = 'Desc'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label87: Label8
      Left = 180
      Top = 42
      Width = 25
      Height = 14
      Caption = 'Desc'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label85: Label8
      Left = 10
      Top = 102
      Width = 66
      Height = 14
      Caption = 'Payroll Factor'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
  end
  object PRCF: TCurrencyEdit
    Tag = 1
    Left = 293
    Top = 73
    Width = 93
    Height = 23
    HelpContext = 1110
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 13
    ParentFont = False
    TabOrder = 7
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object OkCP1Btn: TButton
    Tag = 1
    Left = 117
    Top = 148
    Width = 80
    Height = 21
    HelpContext = 257
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 10
    OnClick = CanCP1BtnClick
  end
  object CanCP1Btn: TButton
    Tag = 1
    Left = 201
    Top = 148
    Width = 80
    Height = 21
    HelpContext = 258
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 11
    OnClick = CanCP1BtnClick
  end
  object CSStkCode: Text8Pt
    Tag = 1
    Left = 86
    Top = 12
    Width = 93
    Height = 22
    HelpContext = 1106
    CharCase = ecUpperCase
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 0
    OnExit = CSStkCodeExit
    TextId = 0
    ViaSBtn = False
  end
  object CSComp: Text8Pt
    Left = 213
    Top = 42
    Width = 174
    Height = 22
    HelpContext = 1108
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 3
    TextId = 0
    ViaSBtn = False
  end
  object PRHF: TCurrencyEdit
    Tag = 1
    Left = 293
    Top = 104
    Width = 93
    Height = 22
    HelpContext = 1110
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 13
    ParentFont = False
    TabOrder = 9
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object PrDF: Text8Pt
    Tag = 1
    Left = 213
    Top = 12
    Width = 174
    Height = 22
    HelpContext = 1107
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 1
    TextId = 0
    ViaSBtn = False
  end
  object PRAF: Text8Pt
    Tag = 1
    Left = 86
    Top = 42
    Width = 93
    Height = 22
    HelpContext = 976
    CharCase = ecUpperCase
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 2
    OnExit = PRAFExit
    TextId = 0
    ViaSBtn = False
  end
  object ICurrF: TSBSComboBox
    Tag = 1
    Left = 245
    Top = 74
    Width = 48
    Height = 22
    HelpContext = 1110
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 6
    ExtendedList = True
    MaxListWidth = 90
    Validate = True
  end
  object ICurr2F: TSBSComboBox
    Tag = 1
    Left = 245
    Top = 104
    Width = 48
    Height = 22
    HelpContext = 1110
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 8
    ExtendedList = True
    MaxListWidth = 90
    Validate = True
  end
  object PRPF: TCurrencyEdit
    Tag = 1
    Left = 86
    Top = 74
    Width = 40
    Height = 23
    HelpContext = 1109
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    Lines.Strings = (
      '0 ')
    MaxLength = 2
    ParentFont = False
    TabOrder = 4
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0 ;###,###,##0-'
    DecPlaces = 0
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object PRFF: TCurrencyEdit
    Tag = 1
    Left = 86
    Top = 104
    Width = 40
    Height = 23
    HelpContext = 1493
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    Lines.Strings = (
      '0 ')
    MaxLength = 2
    ParentFont = False
    TabOrder = 5
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0 ;###,###,##0-'
    DecPlaces = 0
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
end
