object JEmpRec: TJEmpRec
  Left = 343
  Top = 249
  Width = 746
  Height = 401
  HelpContext = 1082
  Caption = 'Employee/Sub Contract Record'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  ShowHint = True
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  OnResize = FormResize
  PixelsPerInch = 96
  TextHeight = 13
  object PageControl1: TPageControl
    Left = 1
    Top = 0
    Width = 736
    Height = 327
    ActivePage = Ledger
    TabIndex = 2
    TabOrder = 0
    OnChange = PageControl1Change
    OnChanging = PageControl1Changing
    object Main: TTabSheet
      HelpContext = 1082
      Caption = 'Main'
      object TCMScrollBox: TScrollBox
        Left = -2
        Top = 0
        Width = 627
        Height = 319
        VertScrollBar.Visible = False
        BorderStyle = bsNone
        TabOrder = 0
        object SBSPanel8: TSBSPanel
          Left = 4
          Top = 1
          Width = 621
          Height = 33
          BevelInner = bvRaised
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object Label85: Label8
            Left = 8
            Top = 10
            Width = 66
            Height = 14
            Caption = 'Employee A/C'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object Label83: Label8
            Left = 202
            Top = 9
            Width = 72
            Height = 14
            Caption = 'Employee Type'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object lblEmpSatus: Label8
            Left = 476
            Top = 9
            Width = 31
            Height = 14
            Caption = 'Status'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object EmACCF: Text8Pt
            Tag = 1
            Left = 79
            Top = 6
            Width = 79
            Height = 22
            HelpContext = 1083
            Color = clWhite
            EditMask = '>cccccc;0; '
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 6
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 0
            OnExit = EmACCFExit
            TextId = 0
            ViaSBtn = False
          end
          object EmTypF: TSBSComboBox
            Tag = 1
            Left = 280
            Top = 6
            Width = 122
            Height = 22
            HelpContext = 1084
            Style = csDropDownList
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ItemHeight = 0
            ParentFont = False
            TabOrder = 1
            OnChange = EmTypFChange
            MaxListWidth = 0
            ReadOnly = True
          end
          object edEmpStatus: Text8Pt
            Tag = 2
            Left = 511
            Top = 6
            Width = 99
            Height = 22
            HelpContext = 96
            TabStop = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 25
            ParentFont = False
            ReadOnly = True
            TabOrder = 2
            TextId = 0
            ViaSBtn = False
          end
        end
        object SBSPanel2: TSBSPanel
          Left = 4
          Top = 37
          Width = 203
          Height = 262
          BevelInner = bvRaised
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 1
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object Label82: Label8
            Left = 11
            Top = 10
            Width = 59
            Height = 14
            Caption = 'Supplier A/C'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object Label84: Label8
            Left = 12
            Top = 67
            Width = 42
            Height = 14
            Caption = 'Address'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object Label88: Label8
            Left = 12
            Top = 29
            Width = 27
            Height = 14
            Caption = 'Name'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object Label89: Label8
            Left = 11
            Top = 194
            Width = 108
            Height = 14
            Caption = 'Telephone and e-Mail:-'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object SupAcF: Text8Pt
            Tag = 1
            Left = 79
            Top = 6
            Width = 117
            Height = 22
            Hint = 
              'Double click to drill down|Double clicking or using the down but' +
              'ton will drill down to the record for this field. The up button ' +
              'will search for the nearest match.'
            HelpContext = 1085
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 25
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 0
            OnDblClick = SupAcFDblClick
            OnEnter = SupAcFEnter
            OnExit = SupAcFExit
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
            ShowHilight = True
          end
          object EAD1F: Text8Pt
            Tag = 1
            Left = 11
            Top = 81
            Width = 187
            Height = 22
            HelpContext = 1086
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 2
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object EAd2F: Text8Pt
            Tag = 1
            Left = 11
            Top = 103
            Width = 187
            Height = 22
            HelpContext = 1086
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 3
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object EAD3F: Text8Pt
            Tag = 1
            Left = 11
            Top = 125
            Width = 187
            Height = 22
            HelpContext = 1086
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 4
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object EAD4F: Text8Pt
            Tag = 1
            Left = 11
            Top = 147
            Width = 187
            Height = 22
            HelpContext = 1086
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 5
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object EAD5F: Text8Pt
            Tag = 1
            Left = 11
            Top = 169
            Width = 187
            Height = 22
            HelpContext = 1086
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 6
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object ENamF: Text8Pt
            Tag = 1
            Left = 11
            Top = 43
            Width = 187
            Height = 22
            HelpContext = 1086
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 1
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object ETelF: Text8Pt
            Tag = 1
            Left = 11
            Top = 208
            Width = 187
            Height = 22
            HelpContext = 1087
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 20
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 7
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object LinkCF: Text8Pt
            Left = 154
            Top = 1
            Width = 49
            Height = 22
            Hint = 
              'Double click to drill down|Double clicking or using the down but' +
              'ton will drill down to the record for this field. The up button ' +
              'will search for the nearest match.'
            HelpContext = 642
            TabStop = False
            Enabled = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 8
            Visible = False
            TextId = 0
            ViaSBtn = False
            Link_to_Cust = True
            ShowHilight = True
          end
          object edtEmailAddr: Text8Pt
            Tag = 1
            Left = 11
            Top = 233
            Width = 187
            Height = 22
            HelpContext = 8061
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 100
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 9
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
        end
        object SBSPanel3: TSBSPanel
          Left = 210
          Top = 37
          Width = 206
          Height = 262
          BevelInner = bvRaised
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 2
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object Label811: Label8
            Left = 19
            Top = 123
            Width = 75
            Height = 14
            Alignment = taRightJustify
            Caption = 'Certificate Type'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            Visible = False
            TextId = 0
          end
          object Label81: Label8
            Left = 41
            Top = 80
            Width = 51
            Height = 14
            Caption = 'Payroll No.'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object Label86: Label8
            Left = 10
            Top = 9
            Width = 79
            Height = 14
            Caption = 'Fax and Mobile:-'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object Label87: Label8
            Left = 23
            Top = 152
            Width = 72
            Height = 14
            Alignment = taRightJustify
            Caption = 'Certificate Ref.'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object Label810: Label8
            Left = 36
            Top = 178
            Width = 56
            Height = 14
            Caption = 'Cert. Expiry'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object Label813: Label8
            Left = 17
            Top = 219
            Width = 77
            Height = 14
            Alignment = taRightJustify
            Caption = 'Time Rate Rules'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            Visible = False
            TextId = 0
          end
          object Label816: Label8
            Left = 17
            Top = 174
            Width = 77
            Height = 14
            Alignment = taRightJustify
            Caption = 'Contractor Type'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            Visible = False
            TextId = 0
          end
          object EFaxF: Text8Pt
            Tag = 1
            Left = 9
            Top = 25
            Width = 186
            Height = 22
            HelpContext = 1085
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 20
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 0
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object EMobF: Text8Pt
            Tag = 1
            Left = 9
            Top = 50
            Width = 186
            Height = 22
            HelpContext = 1085
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 20
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 1
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object EPayNoF: Text8Pt
            Tag = 1
            Left = 96
            Top = 75
            Width = 99
            Height = 22
            HelpContext = 1088
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 10
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 2
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object ECertF: Text8Pt
            Tag = 1
            Left = 98
            Top = 147
            Width = 99
            Height = 22
            HelpContext = 1089
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 30
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 5
            OnEnter = SupAcFEnter
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object EExpF: TEditDate
            Tag = 1
            Left = 98
            Top = 172
            Width = 99
            Height = 22
            HelpContext = 1089
            AutoSelect = False
            Color = clWhite
            EditMask = '00/00/0000;0;'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 10
            ParentFont = False
            ReadOnly = True
            TabOrder = 7
            OnEnter = SupAcFEnter
            Placement = cpAbove
            AllowBlank = True
          end
          object GrpChkF: TBorCheck
            Tag = 1
            Left = 6
            Top = 98
            Width = 190
            Height = 20
            HelpContext = 1156
            Caption = 'Company Group Certificate'
            CheckColor = clWindowText
            Color = clBtnFace
            Enabled = False
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentColor = False
            ParentFont = False
            TabOrder = 3
            TabStop = True
            TextId = 0
            OnMouseUp = GrpChkFMouseUp
          end
          object GenSBF: TBorCheck
            Tag = 1
            Left = 6
            Top = 238
            Width = 190
            Height = 20
            HelpContext = 1183
            Caption = 'Generate Self Billing Invoice for t/s'
            CheckColor = clWindowText
            Color = clBtnFace
            Enabled = False
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentColor = False
            ParentFont = False
            TabOrder = 10
            TabStop = True
            TextId = 0
          end
          object CBCertType: TSBSComboBox
            Tag = 1
            Left = 98
            Top = 121
            Width = 99
            Height = 22
            HelpContext = 1221
            Style = csDropDownList
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ItemHeight = 14
            ParentFont = False
            TabOrder = 4
            Visible = False
            OnChange = EmTypFChange
            Items.Strings = (
              'N/A'
              'CIS 4T'
              'CIS 4P'
              'CIS 5'
              'CIS 5 Partner'
              'CIS 6 Group')
            MaxListWidth = 0
            ReadOnly = True
          end
          object LabChkF: TBorCheck
            Tag = 1
            Left = 6
            Top = 196
            Width = 190
            Height = 20
            HelpContext = 1440
            Caption = 'Labour costs via Purchase Ledger'
            Color = clBtnFace
            Enabled = False
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentColor = False
            ParentFont = False
            TabOrder = 8
            TabStop = True
            TextId = 0
            Visible = False
            OnClick = LabChkFClick
          end
          object EChkF: TSBSComboBox
            Tag = 1
            Left = 98
            Top = 217
            Width = 99
            Height = 22
            HelpContext = 1221
            Style = csDropDownList
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ItemHeight = 14
            ParentFont = False
            TabOrder = 9
            Visible = False
            Items.Strings = (
              'Global/Own/Job'
              'Own Rates Only'
              'Global/Job/Own'
              'Job Rates Only')
            MaxListWidth = 0
            ReadOnly = True
          end
          object CBSubType: TSBSComboBox
            Tag = 1
            Left = 98
            Top = 172
            Width = 99
            Height = 22
            HelpContext = 2187
            Style = csDropDownList
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ItemHeight = 14
            ParentFont = False
            TabOrder = 6
            Visible = False
            OnChange = EmTypFChange
            Items.Strings = (
              'N/A'
              'Soletrader'
              'Partnership'
              'Trust'
              'Company')
            MaxListWidth = 0
            ReadOnly = True
          end
        end
        object SBSPanel1: TSBSPanel
          Left = 419
          Top = 37
          Width = 206
          Height = 262
          BevelInner = bvRaised
          BevelOuter = bvLowered
          ParentColor = True
          TabOrder = 3
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          object UD1Lab: Label8
            Left = 12
            Top = 119
            Width = 80
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'UD Field 1'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UD2Lab: Label8
            Left = 12
            Top = 145
            Width = 80
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'UD Field 2'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object CCLab: Label8
            Left = 56
            Top = 94
            Width = 36
            Height = 14
            Caption = 'CC/Dep'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UD3Lab: Label8
            Left = 12
            Top = 171
            Width = 80
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'UD Field 3'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object UD4Lab: Label8
            Left = 12
            Top = 197
            Width = 80
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'UD Field 4'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            TextId = 0
          end
          object Label812: Label8
            Left = 23
            Top = 18
            Width = 72
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'N.I. No. '
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object Label814: Label8
            Left = 23
            Top = 43
            Width = 72
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'UTR  '
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object Label815: Label8
            Left = 4
            Top = 69
            Width = 91
            Height = 14
            Alignment = taRightJustify
            AutoSize = False
            Caption = 'Verification. No. '
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            PopupMenu = PopupMenu1
            TextId = 0
          end
          object EUD1F: Text8Pt
            Tag = 1
            Left = 96
            Top = 115
            Width = 100
            Height = 22
            HelpContext = 383
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 5
            OnExit = EUD1FExit
            TextId = 0
            ViaSBtn = False
            OnEntHookEvent = EUD1FEntHookEvent
          end
          object EUD2F: Text8Pt
            Tag = 1
            Left = 96
            Top = 141
            Width = 100
            Height = 22
            HelpContext = 383
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 6
            OnExit = EUD1FExit
            TextId = 0
            ViaSBtn = False
            OnEntHookEvent = EUD1FEntHookEvent
          end
          object ECCF: Text8Pt
            Tag = 1
            Left = 96
            Top = 89
            Width = 47
            Height = 22
            HelpContext = 1094
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 3
            OnExit = ECCFExit
            TextId = 0
            ViaSBtn = False
          end
          object EDepF: Text8Pt
            Tag = 1
            Left = 146
            Top = 89
            Width = 49
            Height = 22
            HelpContext = 1094
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 4
            OnExit = ECCFExit
            TextId = 0
            ViaSBtn = False
          end
          object EUD3F: Text8Pt
            Tag = 1
            Left = 96
            Top = 167
            Width = 100
            Height = 22
            HelpContext = 383
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 7
            OnExit = EUD1FExit
            TextId = 0
            ViaSBtn = False
            OnEntHookEvent = EUD1FEntHookEvent
          end
          object EUD4F: Text8Pt
            Tag = 1
            Left = 96
            Top = 193
            Width = 100
            Height = 22
            HelpContext = 383
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 8
            OnExit = EUD1FExit
            TextId = 0
            ViaSBtn = False
            OnEntHookEvent = EUD1FEntHookEvent
          end
          object ENINOF: Text8Pt
            Tag = 1
            Left = 96
            Top = 13
            Width = 99
            Height = 22
            HelpContext = 1407
            AutoSize = False
            CharCase = ecUpperCase
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 9
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 0
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object EUTRF: Text8Pt
            Tag = 1
            Left = 96
            Top = 38
            Width = 99
            Height = 22
            HelpContext = 2158
            AutoSize = False
            CharCase = ecUpperCase
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 10
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 1
            OnEnter = SupAcFEnter
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object EVERF: Text8Pt
            Tag = 1
            Left = 96
            Top = 64
            Width = 99
            Height = 22
            HelpContext = 2159
            AutoSize = False
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            MaxLength = 13
            ParentFont = False
            ParentShowHint = False
            ReadOnly = True
            ShowHint = True
            TabOrder = 2
            OnEnter = SupAcFEnter
            TextId = 0
            ViaSBtn = False
            GDPREnabled = True
          end
          object ETagF: TBorCheck
            Tag = 1
            Left = 23
            Top = 219
            Width = 87
            Height = 20
            HelpContext = 2100
            Caption = 'Tag Record'
            CheckColor = clWindowText
            Color = clBtnFace
            Enabled = False
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentColor = False
            ParentFont = False
            TabOrder = 9
            TabStop = True
            TextId = 0
          end
        end
      end
    end
    object Notes: TTabSheet
      HelpContext = 844
      Caption = 'Notes'
      object TCNScrollBox: TScrollBox
        Left = 3
        Top = 3
        Width = 583
        Height = 291
        VertScrollBar.Visible = False
        TabOrder = 0
        object TNHedPanel: TSBSPanel
          Left = 2
          Top = 3
          Width = 412
          Height = 19
          BevelInner = bvLowered
          BevelOuter = bvNone
          Color = clWhite
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumnHeader
          object NDateLab: TSBSPanel
            Left = 2
            Top = 2
            Width = 65
            Height = 16
            BevelOuter = bvNone
            Caption = 'Date'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 0
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object NDescLab: TSBSPanel
            Left = 67
            Top = 2
            Width = 266
            Height = 16
            BevelOuter = bvNone
            Caption = 'Notes'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 1
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object NUserLab: TSBSPanel
            Left = 337
            Top = 2
            Width = 66
            Height = 16
            BevelOuter = bvNone
            Caption = 'User'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 2
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
        end
        object NDatePanel: TSBSPanel
          Left = 2
          Top = 26
          Width = 65
          Height = 243
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'MS Sans Serif'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object NDescPanel: TSBSPanel
          Left = 70
          Top = 26
          Width = 265
          Height = 243
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'MS Sans Serif'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object NUserPanel: TSBSPanel
          Left = 338
          Top = 26
          Width = 70
          Height = 243
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'MS Sans Serif'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
      end
      object TCNListBtnPanel: TSBSPanel
        Left = 589
        Top = 30
        Width = 18
        Height = 240
        BevelOuter = bvLowered
        TabOrder = 1
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
      end
    end
    object Ledger: TTabSheet
      HelpContext = 1098
      Caption = 'Ledger'
      object CLSBox: TScrollBox
        Left = 3
        Top = 3
        Width = 583
        Height = 291
        VertScrollBar.Tracking = True
        VertScrollBar.Visible = False
        TabOrder = 0
        object CLHedPanel: TSBSPanel
          Left = 2
          Top = 3
          Width = 511
          Height = 19
          BevelInner = bvLowered
          BevelOuter = bvNone
          Color = clWhite
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumnHeader
          object CLORefLab: TSBSPanel
            Left = 2
            Top = 2
            Width = 75
            Height = 14
            BevelOuter = bvNone
            Caption = 'Job Code'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 0
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLDateLab: TSBSPanel
            Left = 81
            Top = 2
            Width = 60
            Height = 14
            BevelOuter = bvNone
            Caption = 'Rate Code'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 1
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLOOLab: TSBSPanel
            Left = 346
            Top = 2
            Width = 84
            Height = 14
            BevelOuter = bvNone
            Caption = 'Total'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 2
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLQOLab: TSBSPanel
            Left = 231
            Top = 2
            Width = 43
            Height = 14
            BevelOuter = bvNone
            Caption = 'Hours'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 3
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLALLab: TSBSPanel
            Left = 275
            Top = 2
            Width = 69
            Height = 14
            BevelOuter = bvNone
            Caption = 'U/Cost'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 4
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLACLab: TSBSPanel
            Left = 142
            Top = 2
            Width = 88
            Height = 14
            BevelOuter = bvNone
            Caption = 'Analysis'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 5
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLYRefLab: TSBSPanel
            Left = 431
            Top = 3
            Width = 38
            Height = 14
            BevelOuter = bvNone
            Caption = 'CC'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 6
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object CLDueLab: TSBSPanel
            Left = 470
            Top = 3
            Width = 38
            Height = 14
            BevelOuter = bvNone
            Caption = 'Dept'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 7
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
        end
        object CLORefPanel: TSBSPanel
          Left = 3
          Top = 25
          Width = 78
          Height = 245
          HelpContext = 142
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLDatePanel: TSBSPanel
          Left = 83
          Top = 25
          Width = 60
          Height = 245
          HelpContext = 143
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLOOPanel: TSBSPanel
          Left = 349
          Top = 25
          Width = 84
          Height = 245
          HelpContext = 979
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLQOPanel: TSBSPanel
          Left = 234
          Top = 25
          Width = 43
          Height = 245
          HelpContext = 977
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLALPanel: TSBSPanel
          Left = 279
          Top = 25
          Width = 68
          Height = 245
          HelpContext = 978
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 5
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLAcPanel: TSBSPanel
          Left = 145
          Top = 25
          Width = 87
          Height = 245
          HelpContext = 976
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 6
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLYRefPanel: TSBSPanel
          Left = 435
          Top = 25
          Width = 37
          Height = 245
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 7
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object CLDuePanel: TSBSPanel
          Left = 474
          Top = 25
          Width = 37
          Height = 245
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 8
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
      end
      object CListBtnPanel: TSBSPanel
        Left = 589
        Top = 30
        Width = 18
        Height = 240
        BevelOuter = bvLowered
        TabOrder = 1
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
      end
    end
    object PayRates: TTabSheet
      HelpContext = 953
      Caption = 'Time Rates'
      object RTSBox: TScrollBox
        Left = 3
        Top = 3
        Width = 583
        Height = 291
        VertScrollBar.Tracking = True
        VertScrollBar.Visible = False
        TabOrder = 0
        object RTHedPanel: TSBSPanel
          Left = 2
          Top = 3
          Width = 502
          Height = 19
          BevelInner = bvLowered
          BevelOuter = bvNone
          Color = clWhite
          TabOrder = 0
          AllowReSize = False
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumnHeader
          object RTLab: TSBSPanel
            Left = 2
            Top = 2
            Width = 77
            Height = 14
            BevelOuter = bvNone
            Caption = 'Rate Code'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 0
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object DELab: TSBSPanel
            Left = 80
            Top = 2
            Width = 102
            Height = 14
            BevelOuter = bvNone
            Caption = 'Description'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 1
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object THLab: TSBSPanel
            Left = 358
            Top = 2
            Width = 82
            Height = 14
            BevelOuter = bvNone
            Caption = 'Time Charge'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 2
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object TCLab: TSBSPanel
            Left = 274
            Top = 2
            Width = 83
            Height = 14
            BevelOuter = bvNone
            Caption = 'Time Cost'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 3
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object ANLab: TSBSPanel
            Left = 184
            Top = 2
            Width = 88
            Height = 14
            BevelOuter = bvNone
            Caption = 'Analysis'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 4
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
          object PNLab: TSBSPanel
            Left = 446
            Top = 2
            Width = 56
            Height = 14
            BevelOuter = bvNone
            Caption = 'Pay Code'
            Color = clWhite
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Arial'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            TabOrder = 5
            OnMouseDown = CLORefLabMouseDown
            OnMouseMove = CLORefLabMouseMove
            OnMouseUp = CLORefPanelMouseUp
            AllowReSize = False
            IsGroupBox = False
            TextId = 0
            Purpose = puBtrListColumnHeader
          end
        end
        object RTPanel: TSBSPanel
          Left = 3
          Top = 25
          Width = 78
          Height = 245
          HelpContext = 142
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object DEPanel: TSBSPanel
          Left = 83
          Top = 25
          Width = 102
          Height = 245
          HelpContext = 143
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object THPanel: TSBSPanel
          Left = 362
          Top = 25
          Width = 84
          Height = 245
          HelpContext = 979
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object TCPanel: TSBSPanel
          Left = 276
          Top = 25
          Width = 84
          Height = 245
          HelpContext = 978
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object ANPanel: TSBSPanel
          Left = 187
          Top = 25
          Width = 87
          Height = 245
          HelpContext = 976
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 5
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
        object PNPanel: TSBSPanel
          Left = 448
          Top = 25
          Width = 49
          Height = 245
          HelpContext = 979
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TabOrder = 6
          OnMouseUp = CLORefPanelMouseUp
          AllowReSize = True
          IsGroupBox = False
          TextId = 0
          Purpose = puBtrListColumn
        end
      end
    end
    object ContractPage: TTabSheet
      HelpContext = 1519
      Caption = 'Contract Terms'
      ImageIndex = 6
    end
    object AppsTPage: TTabSheet
      HelpContext = 1526
      Caption = 'Applications'
      ImageIndex = 4
    end
    object StatTPage: TTabSheet
      Caption = 'Statutory Diary'
      ImageIndex = 5
    end
  end
  object TCMPanel: TSBSPanel
    Left = 630
    Top = 29
    Width = 102
    Height = 287
    BevelOuter = bvNone
    PopupMenu = PopupMenu1
    TabOrder = 1
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    object I1StatLab: Label8
      Left = 3
      Top = 3
      Width = 95
      Height = 49
      Alignment = taCenter
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object OkCP1Btn: TButton
      Tag = 1
      Left = 2
      Top = 3
      Width = 80
      Height = 21
      HelpContext = 1100
      Caption = '&OK'
      Enabled = False
      ModalResult = 1
      TabOrder = 0
      OnClick = OkCP1BtnClick
    end
    object CanCP1Btn: TButton
      Tag = 1
      Left = 2
      Top = 26
      Width = 80
      Height = 21
      HelpContext = 1101
      Cancel = True
      Caption = '&Cancel'
      Enabled = False
      ModalResult = 2
      TabOrder = 1
      OnClick = OkCP1BtnClick
    end
    object ClsCP1Btn: TButton
      Left = 2
      Top = 49
      Width = 80
      Height = 21
      HelpContext = 728
      Cancel = True
      Caption = 'C&lose'
      ModalResult = 2
      TabOrder = 2
      OnClick = ClsCP1BtnClick
    end
    object TCMBtnScrollBox: TScrollBox
      Left = 0
      Top = 84
      Width = 99
      Height = 199
      HorzScrollBar.Visible = False
      VertScrollBar.Position = 128
      BorderStyle = bsNone
      TabOrder = 3
      object EditCP1Btn: TButton
        Left = 2
        Top = -103
        Width = 80
        Height = 21
        HelpContext = 155
        Caption = '&Edit'
        TabOrder = 1
        OnClick = EditCP1BtnClick
      end
      object DelCP1Btn: TButton
        Left = 2
        Top = -56
        Width = 80
        Height = 21
        HelpContext = 159
        Caption = '&Delete'
        TabOrder = 3
        OnClick = DelCP1BtnClick
      end
      object FindCP1Btn: TButton
        Left = 2
        Top = -32
        Width = 80
        Height = 21
        HelpContext = 165
        Caption = '&Find'
        TabOrder = 4
        OnClick = FindCP1BtnClick
      end
      object HistCP1Btn: TButton
        Left = 2
        Top = -8
        Width = 80
        Height = 21
        HelpContext = 1095
        Caption = '&History'
        TabOrder = 5
        OnClick = HistCP1BtnClick
      end
      object CopyCP1Btn: TButton
        Left = 2
        Top = 86
        Width = 80
        Height = 21
        HelpContext = 186
        Caption = 'Cop&y'
        TabOrder = 9
      end
      object ViewCP1Btn: TButton
        Left = 2
        Top = 63
        Width = 80
        Height = 21
        HelpContext = 154
        Caption = '&View'
        TabOrder = 8
        OnClick = ViewCP1BtnClick
      end
      object PrnCP1Btn: TButton
        Left = 2
        Top = 40
        Width = 80
        Height = 21
        HelpContext = 163
        Caption = '&Print'
        TabOrder = 7
        OnClick = PrnCP1BtnClick
      end
      object InsCP1Btn: TButton
        Left = 2
        Top = -79
        Width = 80
        Height = 21
        HelpContext = 86
        Caption = '&Insert'
        TabOrder = 2
        OnClick = EditCP1BtnClick
      end
      object GenCP3Btn: TButton
        Left = 2
        Top = 16
        Width = 80
        Height = 21
        HelpContext = 90
        Caption = '&Switch'
        TabOrder = 6
        OnClick = GenCP3BtnClick
      end
      object LnkCp1Btn: TButton
        Left = 2
        Top = 109
        Width = 80
        Height = 21
        Hint = 
          'Link to additional information|Displays a list of any additional' +
          ' information attached to this Stock Record.'
        Caption = 'Lin&ks'
        TabOrder = 10
        OnClick = LnkCp1BtnClick
      end
      object NteCP1Btn: TButton
        Left = 2
        Top = 132
        Width = 80
        Height = 21
        Hint = 
          'View CIS/RCT Ledger|Display a list of CIS/RCT items relating to ' +
          'this employee.'
        HelpContext = 1406
        Caption = 'CIS Led&ger'
        TabOrder = 11
        OnClick = NteCP1BtnClick
      end
      object AddCP1Btn: TButton
        Left = 2
        Top = -127
        Width = 80
        Height = 21
        HelpContext = 156
        Caption = '&Add'
        TabOrder = 0
        OnClick = EditCP1BtnClick
      end
      object btnStatus: TButton
        Left = 2
        Top = 155
        Width = 80
        Height = 21
        Hint = 
          'Change current status|Allows the status current record to be cha' +
          'nged.'
        HelpContext = 841
        Caption = 'Stat&us'
        TabOrder = 12
        OnClick = btnStatusClick
      end
      object btnPIITree: TSBSButton
        Left = 2
        Top = 178
        Width = 80
        Height = 21
		HelpContext = 2312
        Caption = 'PII Tree'
        TabOrder = 13
        OnClick = btnPIITreeClick
        TextId = 0
      end
    end
  end
  object pnlAnonymisationStatus: TPanel
    Left = 0
    Top = 328
    Width = 738
    Height = 42
    Alignment = taLeftJustify
    BevelOuter = bvNone
    TabOrder = 2
    Visible = False
    object shpNotifyStatus: TShape
      Left = 5
      Top = 1
      Width = 730
      Height = 38
      Brush.Color = clRed
      Shape = stRoundRect
    end
    object lblAnonStatus: TLabel
      Left = 246
      Top = 8
      Width = 240
      Height = 24
      Alignment = taCenter
      Caption = 'Anonymised 30/09/2017'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      Transparent = True
    end
  end
  object PopupMenu1: TPopupMenu
    OnPopup = PopupMenu1Popup
    Left = 454
    Top = 316
    object Add1: TMenuItem
      Caption = '&Add'
      OnClick = EditCP1BtnClick
    end
    object Edit1: TMenuItem
      Caption = '&Edit'
      OnClick = EditCP1BtnClick
    end
    object Insert1: TMenuItem
      Caption = '&Insert'
      OnClick = EditCP1BtnClick
    end
    object Delete1: TMenuItem
      Caption = '&Delete'
      OnClick = DelCP1BtnClick
    end
    object Find1: TMenuItem
      Caption = '&Find'
      OnClick = FindCP1BtnClick
    end
    object Hist1: TMenuItem
      Caption = '&History'
      OnClick = HistCP1BtnClick
    end
    object Switch1: TMenuItem
      Caption = 'S&witch'
      OnClick = GenCP3BtnClick
    end
    object Print1: TMenuItem
      Caption = '&Print'
      OnClick = PrnCP1BtnClick
    end
    object View1: TMenuItem
      Caption = '&View'
      OnClick = ViewCP1BtnClick
    end
    object Copy1: TMenuItem
      Caption = 'Cop&y'
    end
    object Links1: TMenuItem
      Caption = 'Lin&ks'
      Hint = 
        'Displays a list of any additional information attached to this S' +
        'tock Record.'
      OnClick = LnkCp1BtnClick
    end
    object Notes1: TMenuItem
      Caption = 'CIS Led&ger'
      OnClick = NteCP1BtnClick
    end
    object Status1: TMenuItem
      Caption = 'Stat&us'
    end
    object PIITree1: TMenuItem
      Caption = 'PII Tree'
      OnClick = btnPIITreeClick
    end
    object N2: TMenuItem
      Caption = '-'
    end
    object PropFlg: TMenuItem
      Caption = '&Properties'
      HelpContext = 65
      Hint = 'Access Colour & Font settings'
      OnClick = PropFlgClick
    end
    object N1: TMenuItem
      Caption = '-'
    end
    object StoreCoordFlg: TMenuItem
      Caption = '&Save Coordinates'
      HelpContext = 177
      Hint = 'Make the current window settings permanent'
      OnClick = StoreCoordFlgClick
    end
  end
  object popmnuStatus: TPopupMenu
    Left = 481
    Top = 316
    object mnuItmEmpClosed: TMenuItem
      Tag = 1
      Caption = '&Closed!'
      HelpContext = 83
      Hint = 
        'Set account status as "Closed!". When set, this account will not' +
        ' be available for selection on transscations.'
      OnClick = mnuItmEmpClosedClick
    end
    object mnuItmLine1: TMenuItem
      Caption = '-'
    end
    object mnuItmEmpOpen: TMenuItem
      Caption = '&Open'
      HelpContext = 83
      Hint = 'Set account status as "Open".'
      OnClick = mnuItmEmpClosedClick
    end
  end
  object WindowExport: TWindowExport
    OnEnableExport = WindowExportEnableExport
    OnExecuteCommand = WindowExportExecuteCommand
    OnGetExportDescription = WindowExportGetExportDescription
    Left = 280
    Top = 176
  end
end
