object JobBudget: TJobBudget
  Left = 811
  Top = 367
  HelpContext = 948
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Job Budget Entry'
  ClientHeight = 392
  ClientWidth = 429
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  Visible = True
  OnActivate = FormActivate
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 14
  object PageControl1: TPageControl
    Left = 0
    Top = 0
    Width = 429
    Height = 392
    ActivePage = ValPage
    Align = alClient
    TabIndex = 1
    TabOrder = 1
    OnChange = PageControl1Change
    object Budgetpage: TTabSheet
      Caption = 'Job Budget'
      object Label84: Label8
        Left = 72
        Top = 79
        Width = 69
        Height = 14
        Caption = 'Budget U/Cost'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label85: Label8
        Left = 118
        Top = 106
        Width = 74
        Height = 14
        Caption = 'O/Head Charge'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Bevel2: TBevel
        Left = 10
        Top = 125
        Width = 407
        Height = 2
      end
      object Label813: Label8
        Left = 11
        Top = 134
        Width = 179
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Apply Uplift % to Costs'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object BC1F: TSBSComboBox
        Left = 97
        Top = 76
        Width = 48
        Height = 22
        HelpContext = 988
        Style = csDropDownList
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 0
        TabStop = False
        Visible = False
        ExtendedList = True
        MaxListWidth = 90
        ReadOnly = True
        Validate = True
      end
      object BUCF: TCurrencyEdit
        Tag = 1
        Left = 149
        Top = 76
        Width = 103
        Height = 22
        HelpContext = 988
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'ARIAL'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 1
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object BOHCF: TCurrencyEdit
        Tag = 1
        Left = 196
        Top = 102
        Width = 56
        Height = 22
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          ' 0.00% ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 3
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = ' 0.00% ;-0.00%'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object BUpliftPF: TCurrencyEdit
        Tag = 1
        Left = 196
        Top = 132
        Width = 56
        Height = 22
        HelpContext = 1433
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          ' 0.00% ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 6
        WantReturns = False
        WordWrap = False
        OnEnter = BUpliftPFEnter
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = ' 0.00% ;-0.00%'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object SetPrVBtn: TButton
        Tag = 1
        Left = 275
        Top = 100
        Width = 115
        Height = 21
        Caption = 'Set &Value Budget'
        TabOrder = 5
        Visible = False
        OnClick = SetPrbBtnClick
      end
      object SetPrbBtn: TButton
        Tag = 1
        Left = 275
        Top = 79
        Width = 115
        Height = 21
        Caption = '&Set Qty/Hrs Budget'
        TabOrder = 4
        Visible = False
        OnClick = SetPrbBtnClick
      end
      object BRCF: TBorCheck
        Tag = 1
        Left = 20
        Top = 103
        Width = 90
        Height = 20
        Caption = 'Recharge'
        CheckColor = clWindowText
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        TabOrder = 2
        TabStop = True
        TextId = 0
      end
    end
    object ValPage: TTabSheet
      Caption = 'Valuation'
      ImageIndex = 1
      object Label814: Label8
        Left = 46
        Top = 95
        Width = 97
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Valued - to Date'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label815: Label8
        Left = 272
        Top = 95
        Width = 67
        Height = 14
        AutoSize = False
        Caption = '% of Budget'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object Label86: Label8
        Left = 32
        Top = 125
        Width = 112
        Height = 14
        Alignment = taRightJustify
        AutoSize = False
        Caption = 'Apply next valuation'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TextId = 0
      end
      object BC7F: TSBSComboBox
        Left = 101
        Top = 90
        Width = 48
        Height = 22
        HelpContext = 1554
        Style = csDropDownList
        Color = clBtnFace
        Enabled = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 0
        TabStop = False
        Visible = False
        ExtendedList = True
        MaxListWidth = 90
        ReadOnly = True
        Validate = True
      end
      object BAV7F: TCurrencyEdit
        Tag = 1
        Left = 151
        Top = 90
        Width = 113
        Height = 22
        HelpContext = 1554
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'ARIAL'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 1
        WantReturns = False
        WordWrap = False
        OnExit = BAV7FExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object BAPPF: TCurrencyEdit
        Left = 342
        Top = 90
        Width = 56
        Height = 22
        HelpContext = 1554
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          ' 0.00% ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 2
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = ' 0.00% ;-0.00%'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object BC8F: TSBSComboBox
        Left = 101
        Top = 122
        Width = 48
        Height = 22
        HelpContext = 1555
        Style = csDropDownList
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        MaxLength = 3
        ParentFont = False
        TabOrder = 3
        TabStop = False
        Visible = False
        ExtendedList = True
        MaxListWidth = 90
        ReadOnly = True
        Validate = True
      end
      object BAV8F: TCurrencyEdit
        Tag = 1
        Left = 151
        Top = 122
        Width = 113
        Height = 22
        HelpContext = 1555
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'ARIAL'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 4
        WantReturns = False
        WordWrap = False
        OnExit = P2FV8FExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object BAPP2F: TCurrencyEdit
        Tag = 1
        Left = 342
        Top = 122
        Width = 56
        Height = 22
        HelpContext = 1555
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          ' 0.00% ')
        MaxLength = 13
        ParentFont = False
        TabOrder = 6
        WantReturns = False
        WordWrap = False
        OnEnter = BAPP2FEnter
        OnExit = BAPP2FExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = ' 0.00% ;-0.00%'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object BAVBasisF: TSBSComboBox
        Tag = 1
        Left = 269
        Top = 121
        Width = 69
        Height = 22
        HelpContext = 1556
        Style = csDropDownList
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        ItemIndex = 0
        MaxLength = 3
        ParentFont = False
        TabOrder = 5
        Text = 'Incremental'
        Items.Strings = (
          'Incremental'
          'Gross')
        MaxListWidth = 90
        Validate = True
      end
    end
  end
  object OkCP1Btn: TButton
    Tag = 1
    Left = 132
    Top = 359
    Width = 80
    Height = 21
    HelpContext = 257
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 3
    OnClick = CanCP1BtnClick
  end
  object CanCP1Btn: TButton
    Tag = 1
    Left = 220
    Top = 359
    Width = 80
    Height = 21
    HelpContext = 258
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 4
    OnClick = CanCP1BtnClick
  end
  object Panel1: TPanel
    Left = 2
    Top = 22
    Width = 425
    Height = 73
    BevelInner = bvRaised
    BevelOuter = bvLowered
    TabOrder = 0
    object Label81: Label8
      Left = 35
      Top = 7
      Width = 55
      Height = 14
      Caption = 'Stock Code'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label82: Label8
      Left = 41
      Top = 19
      Width = 49
      Height = 14
      Caption = '/ Pay Rate'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label83: Label8
      Left = 37
      Top = 40
      Width = 53
      Height = 14
      Caption = 'Anal. Code'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object BSDF: Text8Pt
      Left = 200
      Top = 10
      Width = 219
      Height = 22
      HelpContext = 982
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 1
      TextId = 0
      ViaSBtn = False
    end
    object BACF: Text8Pt
      Tag = 1
      Left = 99
      Top = 37
      Width = 97
      Height = 22
      HelpContext = 976
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 2
      OnExit = BACFExit
      TextId = 0
      ViaSBtn = False
    end
    object BSCF: Text8Pt
      Tag = 1
      Left = 99
      Top = 10
      Width = 97
      Height = 22
      HelpContext = 982
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 0
      OnExit = BSCFExit
      TextId = 0
      ViaSBtn = False
    end
    object BADF: Text8Pt
      Left = 200
      Top = 37
      Width = 148
      Height = 22
      HelpContext = 976
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 3
      TextId = 0
      ViaSBtn = False
    end
    object BATF: Text8Pt
      Left = 353
      Top = 37
      Width = 66
      Height = 22
      HelpContext = 987
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 4
      TextId = 0
      ViaSBtn = False
    end
  end
  object Panel2: TPanel
    Left = 2
    Top = 183
    Width = 424
    Height = 171
    BevelInner = bvRaised
    BevelOuter = bvLowered
    TabOrder = 2
    object Label821: Label8
      Left = 23
      Top = 31
      Width = 67
      Height = 14
      Caption = 'Budget - Orig.'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label822: Label8
      Left = 24
      Top = 56
      Width = 65
      Height = 14
      Caption = 'Budget - Rev.'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label823: Label8
      Left = 15
      Top = 90
      Width = 75
      Height = 14
      Caption = 'Actual - to Date'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label824: Label8
      Left = 13
      Top = 115
      Width = 77
      Height = 14
      Caption = 'Actual - this Per'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label825: Label8
      Left = 8
      Top = 140
      Width = 82
      Height = 14
      Caption = 'Actual - this YTD'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label826: Label8
      Left = 110
      Top = 11
      Width = 55
      Height = 14
      Caption = 'Qty / Hours'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label827: Label8
      Left = 297
      Top = 11
      Width = 27
      Height = 14
      Alignment = taCenter
      Caption = 'Value'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object BOHF: TCurrencyEdit
      Tag = 1
      Left = 101
      Top = 27
      Width = 79
      Height = 22
      HelpContext = 989
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'ARIAL'
      Font.Style = []
      Lines.Strings = (
        '0.00 ')
      MaxLength = 13
      ParentFont = False
      TabOrder = 0
      WantReturns = False
      WordWrap = False
      OnExit = BOHFExit
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
      ShowCurrency = False
      TextId = 0
      Value = 1E-10
    end
    object BRHF: TCurrencyEdit
      Tag = 1
      Left = 101
      Top = 52
      Width = 79
      Height = 22
      HelpContext = 989
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'ARIAL'
      Font.Style = []
      Lines.Strings = (
        '0.00 ')
      MaxLength = 13
      ParentFont = False
      TabOrder = 3
      WantReturns = False
      WordWrap = False
      OnExit = BRHFExit
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
      ShowCurrency = False
      TextId = 0
      Value = 1E-10
    end
    object BC3F: TSBSComboBox
      Left = 209
      Top = 52
      Width = 48
      Height = 22
      HelpContext = 1002
      Style = csDropDownList
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      MaxLength = 3
      ParentFont = False
      TabOrder = 4
      TabStop = False
      Visible = False
      ExtendedList = True
      MaxListWidth = 90
      ReadOnly = True
      Validate = True
    end
    object BC2F: TSBSComboBox
      Tag = 1
      Left = 209
      Top = 27
      Width = 48
      Height = 22
      HelpContext = 1002
      Style = csDropDownList
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      MaxLength = 3
      ParentFont = False
      TabOrder = 1
      TabStop = False
      Visible = False
      ExtendedList = True
      MaxListWidth = 90
      ReadOnly = True
      Validate = True
    end
    object BOVF: TCurrencyEdit
      Tag = 1
      Left = 259
      Top = 27
      Width = 113
      Height = 22
      HelpContext = 1002
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'ARIAL'
      Font.Style = []
      Lines.Strings = (
        '0.00 ')
      MaxLength = 13
      ParentFont = False
      TabOrder = 2
      WantReturns = False
      WordWrap = False
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
      ShowCurrency = False
      TextId = 0
      Value = 1E-10
    end
    object BRVF: TCurrencyEdit
      Tag = 1
      Left = 259
      Top = 52
      Width = 113
      Height = 22
      HelpContext = 1002
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'ARIAL'
      Font.Style = []
      Lines.Strings = (
        '0.00 ')
      MaxLength = 13
      ParentFont = False
      TabOrder = 5
      WantReturns = False
      WordWrap = False
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
      ShowCurrency = False
      TextId = 0
      Value = 1E-10
    end
    object BAH1F: TCurrencyEdit
      Left = 101
      Top = 87
      Width = 79
      Height = 22
      HelpContext = 1003
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'ARIAL'
      Font.Style = []
      Lines.Strings = (
        '0.00 ')
      MaxLength = 13
      ParentFont = False
      ReadOnly = True
      TabOrder = 6
      WantReturns = False
      WordWrap = False
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
      ShowCurrency = False
      TextId = 0
      Value = 1E-10
    end
    object BC4F: TSBSComboBox
      Left = 209
      Top = 87
      Width = 48
      Height = 22
      HelpContext = 1003
      Style = csDropDownList
      Color = clBtnFace
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      MaxLength = 3
      ParentFont = False
      TabOrder = 7
      TabStop = False
      Visible = False
      ExtendedList = True
      MaxListWidth = 90
      ReadOnly = True
      Validate = True
    end
    object BAV1F: TCurrencyEdit
      Left = 259
      Top = 87
      Width = 113
      Height = 22
      HelpContext = 1003
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'ARIAL'
      Font.Style = []
      Lines.Strings = (
        '0.00 ')
      MaxLength = 13
      ParentFont = False
      ReadOnly = True
      TabOrder = 8
      WantReturns = False
      WordWrap = False
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
      ShowCurrency = False
      TextId = 0
      Value = 1E-10
    end
    object BAV2F: TCurrencyEdit
      Left = 259
      Top = 112
      Width = 113
      Height = 22
      HelpContext = 1003
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'ARIAL'
      Font.Style = []
      Lines.Strings = (
        '0.00 ')
      MaxLength = 13
      ParentFont = False
      ReadOnly = True
      TabOrder = 11
      WantReturns = False
      WordWrap = False
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
      ShowCurrency = False
      TextId = 0
      Value = 1E-10
    end
    object BC5F: TSBSComboBox
      Left = 209
      Top = 112
      Width = 48
      Height = 22
      HelpContext = 1003
      Style = csDropDownList
      Color = clBtnFace
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      MaxLength = 3
      ParentFont = False
      TabOrder = 10
      TabStop = False
      Visible = False
      ExtendedList = True
      MaxListWidth = 90
      ReadOnly = True
      Validate = True
    end
    object BAH2F: TCurrencyEdit
      Left = 101
      Top = 112
      Width = 79
      Height = 22
      HelpContext = 1003
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'ARIAL'
      Font.Style = []
      Lines.Strings = (
        '0.00 ')
      MaxLength = 13
      ParentFont = False
      ReadOnly = True
      TabOrder = 9
      WantReturns = False
      WordWrap = False
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
      ShowCurrency = False
      TextId = 0
      Value = 1E-10
    end
    object BAH3F: TCurrencyEdit
      Left = 101
      Top = 137
      Width = 79
      Height = 22
      HelpContext = 1003
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'ARIAL'
      Font.Style = []
      Lines.Strings = (
        '0.00 ')
      MaxLength = 13
      ParentFont = False
      ReadOnly = True
      TabOrder = 12
      WantReturns = False
      WordWrap = False
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
      ShowCurrency = False
      TextId = 0
      Value = 1E-10
    end
    object BC6F: TSBSComboBox
      Left = 209
      Top = 137
      Width = 48
      Height = 22
      HelpContext = 1003
      Style = csDropDownList
      Color = clBtnFace
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      MaxLength = 3
      ParentFont = False
      TabOrder = 13
      TabStop = False
      Visible = False
      ExtendedList = True
      MaxListWidth = 90
      ReadOnly = True
      Validate = True
    end
    object BAV3F: TCurrencyEdit
      Left = 259
      Top = 137
      Width = 113
      Height = 22
      HelpContext = 1003
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'ARIAL'
      Font.Style = []
      Lines.Strings = (
        '0.00 ')
      MaxLength = 13
      ParentFont = False
      ReadOnly = True
      TabOrder = 14
      WantReturns = False
      WordWrap = False
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
      ShowCurrency = False
      TextId = 0
      Value = 1E-10
    end
  end
end
