object frmTeleSalesMultiBuy: TfrmTeleSalesMultiBuy
  Left = 612
  Top = 206
  HelpContext = 8018
  BorderStyle = bsDialog
  Caption = 'Available Multi-Buy Discounts'
  ClientHeight = 349
  ClientWidth = 535
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnActivate = FormActivate
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 14
  object scrMultiBuy: TScrollBox
    Left = 8
    Top = 8
    Width = 432
    Height = 241
    HorzScrollBar.Visible = False
    Ctl3D = False
    ParentCtl3D = False
    TabOrder = 0
  end
  object Panel1: TPanel
    Left = 8
    Top = 256
    Width = 433
    Height = 89
    BevelInner = bvRaised
    BevelOuter = bvLowered
    TabOrder = 1
    object lblDiscount: Label8
      Left = 344
      Top = 12
      Width = 52
      Height = 14
      Alignment = taRightJustify
      Caption = 'lblDiscount'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object lblOriginalNet: Label8
      Left = 336
      Top = 36
      Width = 62
      Height = 14
      Alignment = taRightJustify
      Caption = 'lblOriginalNet'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object lblDiscountedNet: Label8
      Left = 318
      Top = 60
      Width = 80
      Height = 14
      Alignment = taRightJustify
      Caption = 'lblDiscountedNet'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label84: Label8
      Left = 281
      Top = 12
      Width = 45
      Height = 14
      Alignment = taRightJustify
      Caption = 'Discount:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label85: Label8
      Left = 268
      Top = 36
      Width = 58
      Height = 14
      Alignment = taRightJustify
      Caption = 'Original Net:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label86: Label8
      Left = 250
      Top = 60
      Width = 76
      Height = 14
      Alignment = taRightJustify
      Caption = 'Discounted Net:'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object lblCost: Label8
      Left = 78
      Top = 12
      Width = 32
      Height = 14
      Alignment = taRightJustify
      Caption = 'lblCost'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object lblCostCaption: Label8
      Left = 22
      Top = 12
      Width = 22
      Height = 14
      Alignment = taRightJustify
      Caption = 'Cost'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
  end
  object btnApply: TSBSButton
    Left = 448
    Top = 16
    Width = 80
    Height = 21
    Caption = '&Apply'
    ModalResult = 1
    TabOrder = 2
    TextId = 0
  end
  object btnCancel: TSBSButton
    Left = 448
    Top = 48
    Width = 80
    Height = 21
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 3
    TextId = 0
  end
end
