object MLocMRec: TMLocMRec
  Left = 380
  Top = 245
  HelpContext = 8060
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Location Record'
  ClientHeight = 412
  ClientWidth = 510
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 14
  object SBSBackGroup2: TSBSBackGroup
    Left = 4
    Top = 182
    Width = 499
    Height = 199
    TextId = 0
  end
  object SBSBackGroup1: TSBSBackGroup
    Left = 4
    Top = 0
    Width = 499
    Height = 182
    TextId = 0
  end
  object Label81: Label8
    Left = 12
    Top = 22
    Width = 52
    Height = 14
    Caption = 'Locn Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label82: Label8
    Left = 22
    Top = 56
    Width = 42
    Height = 14
    Caption = 'Address'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label83: Label8
    Left = 305
    Top = 57
    Width = 37
    Height = 14
    Caption = 'Contact'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label84: Label8
    Left = 292
    Top = 81
    Width = 49
    Height = 14
    Caption = 'Telephone'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label85: Label8
    Left = 324
    Top = 106
    Width = 18
    Height = 14
    Caption = 'Fax'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label86: Label8
    Left = 308
    Top = 131
    Width = 34
    Height = 14
    Caption = 'Modem'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label87: Label8
    Left = 318
    Top = 154
    Width = 24
    Height = 14
    Caption = 'Email'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label88: Label8
    Left = 144
    Top = 22
    Width = 27
    Height = 14
    Caption = 'Name'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label89: Label8
    Left = 65
    Top = 253
    Width = 76
    Height = 14
    Caption = 'Default CC/Dept'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label810: Label8
    Left = 364
    Top = 201
    Width = 47
    Height = 14
    Caption = 'Sales G/L'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label811: Label8
    Left = 326
    Top = 227
    Width = 85
    Height = 14
    Caption = 'Cost of Sales G/L'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label813: Label8
    Left = 286
    Top = 254
    Width = 126
    Height = 14
    Caption = 'Closing Stk/Write Offs G/L'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label812: Label8
    Left = 333
    Top = 280
    Width = 77
    Height = 14
    Caption = 'Stock Value G/L'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label814: Label8
    Left = 292
    Top = 306
    Width = 119
    Height = 14
    Caption = 'BoM/Finished Goods G/L'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label815: Label8
    Left = 279
    Top = 333
    Width = 133
    Height = 14
    Caption = ' WOP/Work in progress G/L'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label816: Label8
    Left = 201
    Top = 359
    Width = 129
    Height = 14
    Caption = 'Sales && Purch. Return  G/L'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object SCodeF: Text8Pt
    Tag = 1
    Left = 68
    Top = 18
    Width = 43
    Height = 22
    HelpContext = 502
    CharCase = ecUpperCase
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 0
    OnExit = SCodeFExit
    TextId = 0
    ViaSBtn = False
  end
  object Ad1F: Text8Pt
    Tag = 1
    Left = 68
    Top = 50
    Width = 211
    Height = 22
    HelpContext = 503
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 2
    TextId = 0
    ViaSBtn = False
  end
  object Ad2F: Text8Pt
    Tag = 1
    Left = 68
    Top = 75
    Width = 211
    Height = 22
    HelpContext = 503
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 3
    TextId = 0
    ViaSBtn = False
  end
  object Ad3F: Text8Pt
    Tag = 1
    Left = 68
    Top = 100
    Width = 211
    Height = 22
    HelpContext = 503
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 4
    TextId = 0
    ViaSBtn = False
  end
  object Ad4F: Text8Pt
    Tag = 1
    Left = 68
    Top = 125
    Width = 211
    Height = 22
    HelpContext = 503
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 5
    TextId = 0
    ViaSBtn = False
  end
  object Ad5F: Text8Pt
    Tag = 1
    Left = 68
    Top = 150
    Width = 211
    Height = 22
    HelpContext = 503
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 6
    TextId = 0
    ViaSBtn = False
  end
  object ConF: Text8Pt
    Tag = 1
    Left = 346
    Top = 50
    Width = 147
    Height = 22
    HelpContext = 503
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 7
    TextId = 0
    ViaSBtn = False
  end
  object TelF: Text8Pt
    Tag = 1
    Left = 346
    Top = 75
    Width = 147
    Height = 22
    HelpContext = 503
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 25
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 8
    TextId = 0
    ViaSBtn = False
  end
  object FaxF: Text8Pt
    Tag = 1
    Left = 346
    Top = 100
    Width = 147
    Height = 22
    HelpContext = 503
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 25
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 9
    TextId = 0
    ViaSBtn = False
  end
  object ModF: Text8Pt
    Tag = 1
    Left = 346
    Top = 125
    Width = 147
    Height = 22
    HelpContext = 503
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 25
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 10
    TextId = 0
    ViaSBtn = False
  end
  object EmailF: Text8Pt
    Tag = 1
    Left = 346
    Top = 150
    Width = 147
    Height = 22
    HelpContext = 503
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 100
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 11
    TextId = 0
    ViaSBtn = False
  end
  object OPF: TBorCheck
    Tag = 1
    Left = 32
    Top = 198
    Width = 126
    Height = 20
    HelpContext = 504
    Caption = 'Override Sales Prices'
    CheckColor = clWindowText
    Color = clBtnFace
    ParentColor = False
    TabOrder = 12
    TabStop = True
    TextId = 0
  end
  object OCF: TBorCheck
    Tag = 1
    Left = 52
    Top = 223
    Width = 106
    Height = 20
    HelpContext = 505
    Caption = 'Override CC/Dept'
    CheckColor = clWindowText
    Color = clBtnFace
    ParentColor = False
    TabOrder = 15
    TabStop = True
    TextId = 0
    OnClick = OCFClick
  end
  object OSF: TBorCheck
    Tag = 1
    Left = 40
    Top = 278
    Width = 118
    Height = 20
    HelpContext = 506
    Caption = 'Override Supplier'
    CheckColor = clWindowText
    Color = clBtnFace
    ParentColor = False
    TabOrder = 18
    TabStop = True
    TextId = 0
  end
  object DefCC: Text8Pt
    Tag = 1
    Left = 145
    Top = 249
    Width = 40
    Height = 22
    HelpContext = 505
    TabStop = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 16
    OnExit = DefCCExit
    TextId = 0
    ViaSBtn = False
  end
  object DefDep: Text8Pt
    Tag = 1
    Left = 189
    Top = 249
    Width = 41
    Height = 22
    HelpContext = 505
    TabStop = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 17
    OnExit = DefCCExit
    TextId = 0
    ViaSBtn = False
  end
  object DescF: Text8Pt
    Tag = 1
    Left = 174
    Top = 18
    Width = 319
    Height = 22
    HelpContext = 63
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 1
    TextId = 0
    ViaSBtn = False
  end
  object OGF: TBorCheck
    Tag = 1
    Left = 28
    Top = 303
    Width = 130
    Height = 20
    HelpContext = 507
    Caption = 'Override GL Accounts'
    CheckColor = clWindowText
    Color = clBtnFace
    ParentColor = False
    TabOrder = 19
    TabStop = True
    TextId = 0
    OnClick = OCFClick
  end
  object SalGL: Text8Pt
    Tag = 1
    Left = 417
    Top = 197
    Width = 76
    Height = 22
    HelpContext = 201
    TabStop = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 20
    OnExit = SalGLExit
    TextId = 0
    ViaSBtn = False
  end
  object COSGL: Text8Pt
    Tag = 1
    Left = 417
    Top = 223
    Width = 76
    Height = 22
    HelpContext = 202
    TabStop = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 21
    OnExit = SalGLExit
    TextId = 0
    ViaSBtn = False
  end
  object WOGL: Text8Pt
    Tag = 1
    Left = 417
    Top = 249
    Width = 76
    Height = 22
    HelpContext = 203
    TabStop = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 22
    OnExit = SalGLExit
    TextId = 0
    ViaSBtn = False
  end
  object SVGL: Text8Pt
    Tag = 1
    Left = 417
    Top = 276
    Width = 76
    Height = 22
    HelpContext = 204
    TabStop = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 23
    OnExit = SalGLExit
    TextId = 0
    ViaSBtn = False
  end
  object WIPGL: Text8Pt
    Tag = 1
    Left = 417
    Top = 302
    Width = 76
    Height = 22
    HelpContext = 205
    TabStop = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 24
    OnExit = SalGLExit
    TextId = 0
    ViaSBtn = False
  end
  object OKCP1Btn: TButton
    Left = 168
    Top = 387
    Width = 80
    Height = 21
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 28
    OnClick = CanCP1BtnClick
  end
  object CanCP1Btn: TButton
    Left = 260
    Top = 387
    Width = 80
    Height = 21
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 29
    OnClick = CanCP1BtnClick
  end
  object OCPF: TBorCheck
    Tag = 1
    Left = 160
    Top = 198
    Width = 69
    Height = 20
    HelpContext = 504
    Caption = 'Cost Price'
    CheckColor = clWindowText
    Color = clBtnFace
    ParentColor = False
    TabOrder = 13
    TabStop = True
    TextId = 0
  end
  object ORPF: TBorCheck
    Tag = 1
    Left = 233
    Top = 198
    Width = 91
    Height = 20
    HelpContext = 504
    Caption = 'Re-order Price'
    CheckColor = clWindowText
    Color = clBtnFace
    ParentColor = False
    TabOrder = 14
    TabStop = True
    TextId = 0
  end
  object WOPGL: Text8Pt
    Tag = 1
    Left = 417
    Top = 329
    Width = 76
    Height = 22
    HelpContext = 1222
    TabStop = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 25
    OnExit = SalGLExit
    TextId = 0
    ViaSBtn = False
  end
  object PRetGL: Text8Pt
    Tag = 1
    Left = 417
    Top = 355
    Width = 76
    Height = 22
    HelpContext = 1222
    TabStop = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 27
    OnExit = SalGLExit
    TextId = 0
    ViaSBtn = False
  end
  object RetGL: Text8Pt
    Tag = 1
    Left = 335
    Top = 355
    Width = 76
    Height = 22
    HelpContext = 1222
    TabStop = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 26
    OnExit = SalGLExit
    TextId = 0
    ViaSBtn = False
  end
end
