object NomRec: TNomRec
  Left = 749
  Top = 352
  HelpContext = 216
  ActiveControl = OkCP1Btn
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Add General Ledger Account'
  ClientHeight = 187
  ClientWidth = 372
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 13
  object SBSPanel1: TSBSBackGroup
    Left = 2
    Top = 1
    Width = 365
    Height = 158
    TextId = 0
  end
  object Label81: Label8
    Left = 14
    Top = 16
    Width = 45
    Height = 14
    Caption = 'G/L Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label82: Label8
    Left = 14
    Top = 57
    Width = 54
    Height = 14
    Caption = 'Description'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label83: Label8
    Left = 306
    Top = 55
    Width = 23
    Height = 14
    Caption = 'Type'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label84: Label8
    Left = 152
    Top = 95
    Width = 47
    Height = 14
    Caption = 'C/Fwd to:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label85: Label8
    Left = 103
    Top = 16
    Width = 118
    Height = 14
    Caption = 'Alternative Search Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label86: Label8
    Left = 13
    Top = 95
    Width = 115
    Height = 14
    Alignment = taCenter
    AutoSize = False
    Caption = 'Currency'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label87: Label8
    Left = 222
    Top = 95
    Width = 83
    Height = 14
    AutoSize = False
    Caption = 'Class'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object NIPF: TBorCheck
    Tag = 1
    Left = 10
    Top = 132
    Width = 78
    Height = 20
    HelpContext = 231
    Caption = 'Page Break'
    CheckColor = clWindowText
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 7
    TabStop = True
    TextId = 0
  end
  object NIDF: Text8Pt
    Tag = 1
    Left = 13
    Top = 71
    Width = 285
    Height = 22
    HelpContext = 222
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 2
    TextId = 0
    ViaSBtn = False
  end
  object NITF: TSBSComboBox
    Tag = 1
    Left = 305
    Top = 70
    Width = 54
    Height = 22
    HelpContext = 229
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    ParentFont = False
    TabOrder = 3
    OnClick = NITFExit
    OnEnter = NITFEnter
    OnExit = NITFExit
    ExtendedList = True
    MaxListWidth = 95
    ReadOnly = True
    Validate = True
  end
  object OkCP1Btn: TButton
    Tag = 1
    Left = 107
    Top = 164
    Width = 80
    Height = 21
    HelpContext = 278
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 11
    OnClick = CanCP1BtnClick
  end
  object CanCP1Btn: TButton
    Left = 192
    Top = 164
    Width = 80
    Height = 21
    HelpContext = 279
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 12
    OnClick = CanCP1BtnClick
  end
  object NIRF: TBorCheck
    Tag = 1
    Left = 183
    Top = 132
    Width = 61
    Height = 20
    HelpContext = 233
    Caption = 'Revalue'
    CheckColor = clWindowText
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 9
    TabStop = True
    TextId = 0
  end
  object NIFF: Text8Pt
    Tag = 1
    Left = 135
    Top = 108
    Width = 83
    Height = 22
    HelpContext = 232
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 5
    OnEnter = NIFFEnter
    OnExit = NIFFExit
    TextId = 0
    ViaSBtn = False
  end
  object NICF: TCurrencyEdit
    Tag = 1
    Left = 14
    Top = 30
    Width = 83
    Height = 22
    HelpContext = 175
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '1-')
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 0
    WantReturns = False
    WordWrap = False
    OnEnter = NICFEnter
    OnExit = NICFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = True
    DisplayFormat = '###,###,##0 ;###,###,##0-'
    DecPlaces = 0
    ShowCurrency = False
    TextId = 0
    Value = -0.666666
  end
  object NIACF: Text8Pt
    Tag = 1
    Left = 102
    Top = 30
    Width = 257
    Height = 22
    HelpContext = 1176
    Color = clWhite
    EditMask = '>cccccccccccccccccccccccccccccccccccccccccccccccccc;0; '
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 50
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 1
    TextId = 0
    ViaSBtn = False
  end
  object CurrF: TSBSComboBox
    Tag = 1
    Left = 13
    Top = 108
    Width = 119
    Height = 22
    HelpContext = 1175
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 4
    OnEnter = CurrFEnter
    ExtendedList = True
    MaxListWidth = 130
    ReadOnly = True
    Validate = True
  end
  object NIFJCF: TBorCheck
    Tag = 1
    Left = 247
    Top = 132
    Width = 65
    Height = 20
    HelpContext = 1353
    Caption = 'Force JC'
    CheckColor = clWindowText
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 10
    TabStop = True
    TextId = 0
  end
  object cbHideGL1: TBorCheck
    Tag = 1
    Left = 100
    Top = 132
    Width = 78
    Height = 20
    HelpContext = 1434
    Caption = 'Inactive A/C'
    CheckColor = clWindowText
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 8
    TabStop = True
    TextId = 0
  end
  object NICLF: TSBSComboBox
    Tag = 1
    Left = 221
    Top = 108
    Width = 88
    Height = 22
    HelpContext = 229
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    ParentFont = False
    TabOrder = 6
    OnEnter = NITFEnter
    OnExit = NITFExit
    MaxListWidth = 95
    ReadOnly = True
    Validate = True
  end
end
