object NomVRec: TNomVRec
  Left = 605
  Top = 249
  HelpContext = 2147
  ActiveControl = OkCP1Btn
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'General Ledger View Account'
  ClientHeight = 272
  ClientWidth = 372
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 14
  object SBSPanel1: TSBSBackGroup
    Left = 2
    Top = 1
    Width = 365
    Height = 236
    TextId = 0
  end
  object Label81: Label8
    Left = 14
    Top = 16
    Width = 54
    Height = 14
    Caption = 'View Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label84: Label8
    Left = 293
    Top = 191
    Width = 47
    Height = 14
    Caption = 'C/Fwd to:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    Visible = False
    TextId = 0
  end
  object Label85: Label8
    Left = 191
    Top = 16
    Width = 147
    Height = 14
    Caption = 'Alternative View Search Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object SBSBackGroup1: TSBSBackGroup
    Left = 8
    Top = 55
    Width = 357
    Height = 136
    Caption = 'Linked To'
    TextId = 0
  end
  object Label86: Label8
    Left = 16
    Top = 72
    Width = 50
    Height = 14
    Caption = 'View Ord.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label87: Label8
    Left = 83
    Top = 72
    Width = 25
    Height = 14
    Caption = 'Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label88: Label8
    Left = 152
    Top = 72
    Width = 54
    Height = 14
    Caption = 'Description'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label89: Label8
    Left = 339
    Top = 72
    Width = 19
    Height = 14
    Caption = 'Use'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object CCLab: Label8
    Left = 48
    Top = 110
    Width = 14
    Height = 14
    Alignment = taCenter
    Caption = 'CC'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object DepLab: Label8
    Left = 93
    Top = 110
    Width = 22
    Height = 14
    Alignment = taCenter
    Caption = 'Dept'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label810: Label8
    Left = 16
    Top = 148
    Width = 83
    Height = 14
    Caption = 'View Description'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label811: Label8
    Left = 306
    Top = 148
    Width = 23
    Height = 14
    Caption = 'Type'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object NIPF: TBorCheck
    Tag = 1
    Left = 117
    Top = 124
    Width = 78
    Height = 20
    HelpContext = 2182
    Caption = 'Inc. Budget'
    CheckColor = clWindowText
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 8
    TabStop = True
    TextId = 0
  end
  object NIDF: Text8Pt
    Tag = 1
    Left = 16
    Top = 164
    Width = 285
    Height = 22
    HelpContext = 2154
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 100
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 11
    TextId = 0
    ViaSBtn = False
  end
  object NITF: TSBSComboBox
    Tag = 1
    Left = 305
    Top = 164
    Width = 54
    Height = 22
    HelpContext = 2155
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    ParentFont = False
    TabOrder = 12
    OnEnter = NITFEnter
    OnExit = NIFJCFClick
    Items.Strings = (
      'Balance'
      'Heading')
    MaxListWidth = 95
    ReadOnly = True
    Validate = True
  end
  object OkCP1Btn: TButton
    Tag = 1
    Left = 107
    Top = 247
    Width = 80
    Height = 21
    HelpContext = 278
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 14
    OnClick = CanCP1BtnClick
  end
  object CanCP1Btn: TButton
    Left = 192
    Top = 247
    Width = 80
    Height = 21
    HelpContext = 279
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 15
    OnClick = CanCP1BtnClick
  end
  object NIFF: Text8Pt
    Tag = 1
    Left = 276
    Top = 205
    Width = 83
    Height = 22
    HelpContext = 232
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 13
    Visible = False
    OnEnter = NIFFEnter
    OnExit = NIFFExit
    TextId = 0
    ViaSBtn = False
  end
  object NIACF: Text8Pt
    Tag = 1
    Left = 189
    Top = 30
    Width = 171
    Height = 22
    HelpContext = 2149
    CharCase = ecUpperCase
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 1
    TextId = 0
    ViaSBtn = False
  end
  object NIFJCF: TBorCheck
    Tag = 1
    Left = 334
    Top = 87
    Width = 23
    Height = 20
    HelpContext = 2152
    CheckColor = clWindowText
    Color = clBtnFace
    Enabled = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 5
    TabStop = True
    TextId = 0
    OnClick = NIFJCFClick
  end
  object NIVNF: TCurrencyEdit
    Tag = 1
    Left = 16
    Top = 86
    Width = 63
    Height = 22
    HelpContext = 2150
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0 ')
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 2
    WantReturns = False
    WordWrap = False
    OnExit = NIVNFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = True
    DisplayFormat = '###,###,##0 ;###,###,##0-'
    DecPlaces = 0
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object NICF: Text8Pt
    Tag = 1
    Left = 16
    Top = 30
    Width = 171
    Height = 22
    HelpContext = 2148
    CharCase = ecUpperCase
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 0
    OnEnter = NICFEnter
    OnExit = NICFExit
    TextId = 0
    ViaSBtn = False
  end
  object A1CCF: Text8Pt
    Tag = 1
    Left = 16
    Top = 123
    Width = 49
    Height = 22
    HelpContext = 2153
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 6
    OnExit = A1CCFExit
    TextId = 0
    ViaSBtn = False
  end
  object A1DpF: Text8Pt
    Tag = 1
    Left = 69
    Top = 123
    Width = 49
    Height = 22
    HelpContext = 2153
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 7
    OnExit = A1CCFExit
    TextId = 0
    ViaSBtn = False
  end
  object NIVDF: Text8Pt
    Left = 149
    Top = 86
    Width = 188
    Height = 22
    HelpContext = 2151
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 100
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 4
    TextId = 0
    ViaSBtn = False
  end
  object NIICF: TBorCheck
    Tag = 1
    Left = 198
    Top = 124
    Width = 89
    Height = 20
    HelpContext = 2183
    Caption = 'Use Committed'
    CheckColor = clWindowText
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    TabOrder = 9
    TabStop = True
    TextId = 0
    OnClick = NIICFClick
  end
  object NIVCF: Text8Pt
    Tag = 1
    Left = 81
    Top = 86
    Width = 64
    Height = 22
    HelpContext = 2151
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 3
    OnExit = NIVCFExit
    TextId = 0
    ViaSBtn = False
  end
  object NIIUF: TSBSComboBox
    Tag = 1
    Left = 291
    Top = 123
    Width = 71
    Height = 22
    HelpContext = 2184
    Style = csDropDownList
    Color = clWhite
    DropDownCount = 3
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 4
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 10
    OnChange = NIIUFChange
    Items.Strings = (
      'Posted Only'
      'Unposted'
      'Psted & Unpstd')
    MaxListWidth = 0
  end
end
