object PayLine: TPayLine
  Left = 257
  Top = 279
  HelpContext = 236
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = ' '
  ClientHeight = 157
  ClientWidth = 769
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clBlack
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 14
  object Label87: Label8
    Left = 80
    Top = 5
    Width = 56
    Height = 14
    Caption = 'Cheque No.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label81: Label8
    Left = 3
    Top = 5
    Width = 45
    Height = 14
    Caption = 'G/L Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label82: Label8
    Left = 433
    Top = 5
    Width = 58
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Amount'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object CCLab: Label8
    Left = 255
    Top = 5
    Width = 14
    Height = 14
    Caption = 'CC'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object DepLab: Label8
    Left = 304
    Top = 5
    Width = 22
    Height = 14
    Caption = 'Dept'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object CurLab: Label8
    Left = 339
    Top = 5
    Width = 45
    Height = 14
    Caption = 'Currency'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object PILab: Label8
    Left = 160
    Top = 5
    Width = 50
    Height = 14
    Caption = 'Pay-In Ref'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object BELab: Label8
    Left = 517
    Top = 5
    Width = 77
    Height = 14
    Caption = 'Base Equivalent'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF1L: Label8
    Left = 7
    Top = 87
    Width = 58
    Height = 14
    AutoSize = False
    Caption = 'UD Field 1'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF6L: Label8
    Left = 7
    Top = 111
    Width = 58
    Height = 14
    AutoSize = False
    Caption = 'UD Field 1'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF2L: Label8
    Left = 158
    Top = 87
    Width = 58
    Height = 14
    AutoSize = False
    Caption = 'UD Field 2'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF7L: Label8
    Left = 158
    Top = 111
    Width = 58
    Height = 14
    AutoSize = False
    Caption = 'UD Field 2'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF3L: Label8
    Left = 310
    Top = 87
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 3'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF8L: Label8
    Left = 310
    Top = 111
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 3'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF10L: Label8
    Left = 612
    Top = 111
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 4'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF5L: Label8
    Left = 612
    Top = 87
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 4'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF9L: Label8
    Left = 461
    Top = 111
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 4'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF4L: Label8
    Left = 461
    Top = 87
    Width = 57
    Height = 14
    AutoSize = False
    Caption = 'UD Field 4'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object JALab: Label8
    Left = 176
    Top = 43
    Width = 61
    Height = 14
    Caption = 'Job Analysis'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object JCLab: Label8
    Left = 300
    Top = 43
    Width = 45
    Height = 14
    Caption = 'Job Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label84: Label8
    Left = 1
    Top = 43
    Width = 132
    Height = 14
    Caption = 'General Ledger Description'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object PICQF: Text8Pt
    Tag = 1
    Left = 77
    Top = 19
    Width = 79
    Height = 22
    HelpContext = 412
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 50
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 1
    TextId = 0
    ViaSBtn = False
  end
  object PINAF: Text8Pt
    Tag = 1
    Left = 3
    Top = 19
    Width = 73
    Height = 22
    HelpContext = 410
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 0
    OnEnter = PICCFEnter
    OnExit = PINAFExit
    TextId = 0
    ViaSBtn = False
  end
  object PICCF: Text8Pt
    Tag = 1
    Left = 237
    Top = 19
    Width = 47
    Height = 22
    HelpContext = 414
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 3
    OnEnter = PICCFEnter
    OnExit = PICCFExit
    TextId = 0
    ViaSBtn = False
  end
  object PIDepF: Text8Pt
    Tag = 1
    Left = 285
    Top = 19
    Width = 47
    Height = 22
    HelpContext = 414
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 4
    OnEnter = PICCFEnter
    OnExit = PICCFExit
    TextId = 0
    ViaSBtn = False
  end
  object Candb1Btn: TButton
    Tag = 1
    Left = 683
    Top = 132
    Width = 80
    Height = 21
    HelpContext = 279
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 22
    OnClick = Okdb1BtnClick
  end
  object Okdb1Btn: TButton
    Tag = 1
    Left = 599
    Top = 132
    Width = 80
    Height = 21
    HelpContext = 278
    Caption = '&OK'
    Enabled = False
    ModalResult = 1
    TabOrder = 21
    OnClick = Okdb1BtnClick
  end
  object PIPIF: Text8Pt
    Tag = 1
    Left = 157
    Top = 19
    Width = 79
    Height = 22
    HelpContext = 413
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 2
    TextId = 0
    ViaSBtn = False
  end
  object PICurrF: TSBSComboBox
    Left = 334
    Top = 19
    Width = 57
    Height = 22
    HelpContext = 415
    Style = csDropDownList
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 5
    TabStop = False
    ExtendedList = True
    MaxListWidth = 90
    ReadOnly = True
  end
  object PIAmtF: TCurrencyEdit
    Tag = 1
    Left = 393
    Top = 19
    Width = 100
    Height = 22
    HelpContext = 416
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 13
    ParentFont = False
    ReadOnly = True
    TabOrder = 6
    WantReturns = False
    WordWrap = False
    OnEnter = PIAmtFEnter
    OnExit = PIAmtFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object PIBEF: TCurrencyEdit
    Left = 494
    Top = 19
    Width = 100
    Height = 22
    HelpContext = 404
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    ParentFont = False
    ReadOnly = True
    TabOrder = 7
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object THUD1F: Text8Pt
    Tag = 1
    Left = 63
    Top = 83
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 11
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD6F: Text8Pt
    Tag = 1
    Left = 63
    Top = 107
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 16
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD2F: Text8Pt
    Tag = 1
    Left = 215
    Top = 83
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 12
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD7F: Text8Pt
    Tag = 1
    Left = 215
    Top = 107
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 17
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD3F: Text8Pt
    Tag = 1
    Left = 366
    Top = 83
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 13
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD8F: Text8Pt
    Tag = 1
    Left = 366
    Top = 107
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 18
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD10F: Text8Pt
    Tag = 1
    Left = 671
    Top = 107
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 20
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD5F: Text8Pt
    Tag = 1
    Left = 671
    Top = 83
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 15
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD9F: Text8Pt
    Tag = 1
    Left = 518
    Top = 107
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 19
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object PIJAF: Text8Pt
    Tag = 1
    Left = 171
    Top = 59
    Width = 120
    Height = 22
    HelpContext = 466
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 9
    OnEnter = PICCFEnter
    OnExit = PIJAFExit
    TextId = 0
    ViaSBtn = False
  end
  object THUD4F: Text8Pt
    Tag = 1
    Left = 518
    Top = 83
    Width = 90
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 14
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object PIJCF: Text8Pt
    Tag = 1
    Left = 297
    Top = 59
    Width = 119
    Height = 22
    HelpContext = 465
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 10
    OnEnter = PICCFEnter
    OnExit = PIJCFsExit
    TextId = 0
    ViaSBtn = False
  end
  object PINDF: Text8Pt
    Left = 2
    Top = 59
    Width = 164
    Height = 22
    HelpContext = 417
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 8
    TextId = 0
    ViaSBtn = False
  end
end
