object RETLine: TRETLine
  Left = 315
  Top = 232
  HelpContext = 1617
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = 'Return Note Line'
  ClientHeight = 301
  ClientWidth = 625
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  ShowHint = True
  Visible = True
  OnActivate = FormActivate
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 13
  object SBSBackGroup2: TSBSBackGroup
    Left = 2
    Top = 2
    Width = 616
    Height = 45
    TextId = 0
  end
  object SBSBackGroup1: TSBSBackGroup
    Left = 248
    Top = 80
    Width = 369
    Height = 53
    TextId = 0
  end
  object Id3QtyLab: Label8
    Left = 190
    Top = 9
    Width = 67
    Height = 13
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Expected Qty'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object PQLab: Label8
    Left = 259
    Top = 9
    Width = 71
    Height = 13
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Qty Returned '
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object LocLab: Label8
    Left = 146
    Top = 9
    Width = 27
    Height = 14
    Caption = 'Locn.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Id3SCodeLab: Label8
    Left = 7
    Top = 9
    Width = 55
    Height = 14
    Caption = 'Stock Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label85: Label8
    Left = 5
    Top = 49
    Width = 84
    Height = 14
    Caption = 'Stock Description'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label84: Label8
    Left = 254
    Top = 49
    Width = 103
    Height = 12
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Unit Price '
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object GLLab: Label8
    Left = 255
    Top = 91
    Width = 45
    Height = 14
    Caption = 'G/L Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object CCLab: Label8
    Left = 522
    Top = 91
    Width = 14
    Height = 14
    Alignment = taCenter
    Caption = 'CC'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object DepLab: Label8
    Left = 567
    Top = 91
    Width = 22
    Height = 14
    Alignment = taCenter
    Caption = 'Dept'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF1L: Label8
    Left = 6
    Top = 180
    Width = 120
    Height = 14
    AutoSize = False
    Caption = 'UD Field 1'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF2L: Label8
    Left = 127
    Top = 180
    Width = 120
    Height = 14
    AutoSize = False
    Caption = 'UD Field 2'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF3L: Label8
    Left = 249
    Top = 180
    Width = 120
    Height = 14
    AutoSize = False
    Caption = 'UD Field 3'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF4L: Label8
    Left = 371
    Top = 180
    Width = 120
    Height = 14
    AutoSize = False
    Caption = 'UD Field 4'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label81: Label8
    Left = 475
    Top = 49
    Width = 106
    Height = 12
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Discount  '
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label86: Label8
    Left = 467
    Top = 91
    Width = 39
    Height = 14
    Alignment = taCenter
    AutoSize = False
    Caption = 'VAT'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label87: Label8
    Left = 482
    Top = 136
    Width = 134
    Height = 12
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Total   '
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label88: Label8
    Left = 250
    Top = 136
    Width = 120
    Height = 12
    Alignment = taCenter
    AutoSize = False
    Caption = 'Reason'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label82: Label8
    Left = 332
    Top = 9
    Width = 68
    Height = 13
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Qty Repaired'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label83: Label8
    Left = 474
    Top = 9
    Width = 67
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Qty W.Off '
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label89: Label8
    Left = 404
    Top = 9
    Width = 68
    Height = 11
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Tot. Repaired'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label810: Label8
    Left = 548
    Top = 9
    Width = 67
    Height = 12
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Tot. W.Off '
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label811: Label8
    Left = 372
    Top = 136
    Width = 106
    Height = 12
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Cost'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label812: Label8
    Left = 363
    Top = 49
    Width = 106
    Height = 12
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Unit Repair Price '
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF6L: Label8
    Left = 6
    Top = 228
    Width = 120
    Height = 14
    AutoSize = False
    Caption = 'UD Field 6'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF7L: Label8
    Left = 127
    Top = 228
    Width = 120
    Height = 14
    AutoSize = False
    Caption = 'UD Field 7'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF8L: Label8
    Left = 249
    Top = 228
    Width = 120
    Height = 14
    AutoSize = False
    Caption = 'UD Field 8'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF9L: Label8
    Left = 371
    Top = 228
    Width = 120
    Height = 14
    AutoSize = False
    Caption = 'UD Field 9'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF10L: Label8
    Left = 494
    Top = 228
    Width = 120
    Height = 14
    AutoSize = False
    Caption = 'UD Field 10'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UDF5L: Label8
    Left = 494
    Top = 180
    Width = 120
    Height = 14
    AutoSize = False
    Caption = 'UD Field 5'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object A1SCodef: Text8Pt
    Tag = 1
    Left = 5
    Top = 22
    Width = 126
    Height = 22
    Hint = 
      'Double click to drill down|Double clicking or using the down but' +
      'ton will drill down to the record for this field. The up button ' +
      'will search for the nearest match.'
    HelpContext = 1634
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 0
    OnDblClick = A1SCodefDblClick
    OnExit = A1SCodefExit
    TextId = 0
    ViaSBtn = False
    ShowHilight = True
  end
  object A1PQF: TCurrencyEdit
    Tag = 1
    Left = 260
    Top = 22
    Width = 70
    Height = 22
    HelpContext = 1624
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 4
    WantReturns = False
    WordWrap = False
    OnEnter = A1SCodefEnter
    OnExit = A1QIFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object A1QIF: TCurrencyEdit
    Tag = 1
    Left = 189
    Top = 22
    Width = 70
    Height = 22
    HelpContext = 1623
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 3
    WantReturns = False
    WordWrap = False
    OnExit = A1QIFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object A1LOF: Text8Pt
    Tag = 1
    Left = 133
    Top = 22
    Width = 54
    Height = 22
    HelpContext = 1613
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 2
    OnEnter = A1LOFEnter
    OnExit = A1LOFExit
    TextId = 0
    ViaSBtn = False
  end
  object Okdb1Btn: TButton
    Tag = 1
    Left = 447
    Top = 272
    Width = 80
    Height = 21
    HelpContext = 278
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 30
    OnClick = Candb1BtnClick
  end
  object Candb1Btn: TButton
    Tag = 1
    Left = 535
    Top = 272
    Width = 80
    Height = 21
    HelpContext = 279
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 31
    OnClick = Candb1BtnClick
  end
  object A1IssF: TCurrencyEdit
    Tag = 1
    Left = 331
    Top = 22
    Width = 70
    Height = 22
    HelpContext = 1625
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 5
    WantReturns = False
    WordWrap = False
    OnExit = A1QIFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object A2IssF: TCurrencyEdit
    Left = 402
    Top = 22
    Width = 70
    Height = 22
    HelpContext = 1620
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 6
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object A1UCF: TCurrencyEdit
    Tag = 1
    Left = 251
    Top = 61
    Width = 108
    Height = 22
    HelpContext = 1629
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 9
    WantReturns = False
    WordWrap = False
    OnEnter = A1UCFEnter
    OnExit = A1QIFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object A1GLF: Text8Pt
    Tag = 1
    Left = 251
    Top = 105
    Width = 57
    Height = 22
    HelpContext = 1633
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 12
    OnExit = A1GLFExit
    TextId = 0
    ViaSBtn = False
  end
  object A1CCF: Text8Pt
    Tag = 1
    Left = 515
    Top = 104
    Width = 49
    Height = 22
    HelpContext = 272
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 15
    OnExit = A1CCFExit
    TextId = 0
    ViaSBtn = False
  end
  object A1DpF: Text8Pt
    Tag = 1
    Left = 565
    Top = 104
    Width = 49
    Height = 22
    HelpContext = 272
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ReadOnly = True
    TabOrder = 16
    OnExit = A1CCFExit
    TextId = 0
    ViaSBtn = False
  end
  object THUD1F: Text8Pt
    Tag = 1
    Left = 5
    Top = 194
    Width = 120
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 20
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD2F: Text8Pt
    Tag = 1
    Left = 127
    Top = 194
    Width = 120
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 21
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD3F: Text8Pt
    Tag = 1
    Left = 249
    Top = 194
    Width = 120
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 22
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD4F: Text8Pt
    Tag = 1
    Left = 371
    Top = 194
    Width = 120
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 23
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object Id3SBox: TScrollBox
    Left = 4
    Top = 62
    Width = 240
    Height = 110
    HorzScrollBar.Visible = False
    Ctl3D = False
    ParentCtl3D = False
    TabOrder = 1
    object Id3Desc1F: Text8Pt
      Tag = 1
      Left = 1
      Top = 1
      Width = 218
      Height = 20
      HelpContext = 235
      BorderStyle = bsNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 50
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 0
      Text = '12345678901234567890123456789012345'
      OnKeyPress = Id3Desc1FKeyPress
      TextId = 0
      ViaSBtn = False
    end
    object Id3Desc2F: Text8Pt
      Tag = 1
      Left = 1
      Top = 22
      Width = 218
      Height = 20
      HelpContext = 235
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 50
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 1
      OnKeyPress = Id3Desc1FKeyPress
      TextId = 0
      ViaSBtn = False
    end
    object Id3Desc3F: Text8Pt
      Tag = 1
      Left = 1
      Top = 43
      Width = 218
      Height = 20
      HelpContext = 235
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 50
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 2
      OnKeyPress = Id3Desc1FKeyPress
      TextId = 0
      ViaSBtn = False
    end
    object Id3Desc4F: Text8Pt
      Tag = 1
      Left = 1
      Top = 64
      Width = 218
      Height = 20
      HelpContext = 235
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 50
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 3
      OnKeyPress = Id3Desc1FKeyPress
      TextId = 0
      ViaSBtn = False
    end
    object Id3Desc5F: Text8Pt
      Tag = 1
      Left = 1
      Top = 85
      Width = 218
      Height = 20
      HelpContext = 235
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 50
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 4
      OnKeyPress = Id3Desc1FKeyPress
      TextId = 0
      ViaSBtn = False
    end
    object Id3Desc6F: Text8Pt
      Tag = 1
      Left = 1
      Top = 106
      Width = 218
      Height = 20
      HelpContext = 235
      BorderStyle = bsNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 50
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 5
      OnKeyPress = Id3Desc1FKeyPress
      TextId = 0
      ViaSBtn = False
    end
  end
  object Id3VATF: TSBSComboBox
    Tag = 1
    Left = 466
    Top = 105
    Width = 46
    Height = 22
    HelpContext = 249
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 1
    ParentFont = False
    TabOrder = 14
    OnExit = Id3VATFExit
    AllowChangeInExit = True
    ExtendedList = True
    MaxListWidth = 75
    ReadOnly = True
    Validate = True
  end
  object Id3DiscF: Text8Pt
    Tag = 1
    Left = 473
    Top = 61
    Width = 108
    Height = 22
    HelpContext = 1638
    AutoSize = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 12
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 11
    OnExit = Id3DiscFExit
    TextId = 0
    ViaSBtn = False
  end
  object Id3LTotF: TCurrencyEdit
    Left = 483
    Top = 150
    Width = 133
    Height = 22
    HelpContext = 1640
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    ParentFont = False
    ReadOnly = True
    TabOrder = 19
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object GLDescF: Text8Pt
    Left = 311
    Top = 105
    Width = 151
    Height = 22
    HelpContext = 1633
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 13
    TextId = 0
    ViaSBtn = False
  end
  object Id3StatCB1: TSBSComboBox
    Tag = 1
    Left = 249
    Top = 150
    Width = 120
    Height = 22
    HelpContext = 1614
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 17
    MaxListWidth = 250
    ReadOnly = True
    Validate = True
  end
  object A1WOffF: TCurrencyEdit
    Tag = 1
    Left = 473
    Top = 22
    Width = 70
    Height = 22
    HelpContext = 1631
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 7
    WantReturns = False
    WordWrap = False
    OnEnter = A1WOffFEnter
    OnExit = A1QIFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object A2WOffF: TCurrencyEdit
    Left = 544
    Top = 22
    Width = 70
    Height = 22
    HelpContext = 1635
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 8
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object Id3LCostF: TCurrencyEdit
    Left = 371
    Top = 150
    Width = 108
    Height = 22
    HelpContext = 1639
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    ParentFont = False
    ReadOnly = True
    TabOrder = 18
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object A1URCF: TCurrencyEdit
    Tag = 1
    Left = 362
    Top = 61
    Width = 108
    Height = 22
    HelpContext = 1637
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 10
    WantReturns = False
    WordWrap = False
    OnEnter = A1UCFEnter
    OnExit = A1QIFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object THUD5F: Text8Pt
    Tag = 1
    Left = 493
    Top = 194
    Width = 120
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 24
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD6F: Text8Pt
    Tag = 1
    Left = 5
    Top = 242
    Width = 120
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 25
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD7F: Text8Pt
    Tag = 1
    Left = 127
    Top = 242
    Width = 120
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 26
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD8F: Text8Pt
    Tag = 1
    Left = 249
    Top = 242
    Width = 120
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 27
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD9F: Text8Pt
    Tag = 1
    Left = 371
    Top = 242
    Width = 120
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 28
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
  object THUD10F: Text8Pt
    Tag = 1
    Left = 493
    Top = 242
    Width = 120
    Height = 22
    HelpContext = 283
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ReadOnly = True
    TabOrder = 29
    OnExit = THUD1FExit
    TextId = 0
    ViaSBtn = False
    OnEntHookEvent = THUD1FEntHookEvent
  end
end
