object SetCISRate: TSetCISRate
  Left = 411
  Top = 134
  HelpContext = 1390
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = 'SetUp'
  ClientHeight = 329
  ClientWidth = 502
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 14
  object SBSBackGroup1: TSBSBackGroup
    Left = 2
    Top = -1
    Width = 498
    Height = 330
    TextId = 0
  end
  object SBSBackGroup2: TSBSBackGroup
    Left = 14
    Top = 8
    Width = 377
    Height = 119
    TextId = 0
  end
  object Label82: Label8
    Left = 26
    Top = 23
    Width = 90
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = '&Last Tax Return'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label83: Label8
    Left = 195
    Top = 23
    Width = 85
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Return every'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label81: Label8
    Left = 18
    Top = 49
    Width = 98
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Current Tax Period'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label816: Label8
    Left = 325
    Top = 23
    Width = 35
    Height = 14
    Caption = 'months'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label89: Label8
    Left = 195
    Top = 49
    Width = 84
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Scheme Ref:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object VATLab: Label8
    Left = 188
    Top = 79
    Width = 91
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = ' Rate'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object SBSBackGroup3: TSBSBackGroup
    Left = 14
    Top = 128
    Width = 377
    Height = 103
    Caption = 'Contractor CIS Details'
    TextId = 0
  end
  object Label865: Label8
    Left = 45
    Top = 144
    Width = 90
    Height = 14
    Alignment = taCenter
    AutoSize = False
    Caption = 'Certificate Type'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    Visible = False
    TextId = 0
  end
  object Label867: Label8
    Left = 148
    Top = 144
    Width = 97
    Height = 14
    Alignment = taCenter
    AutoSize = False
    Caption = 'Certificate Ref.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label868: Label8
    Left = 260
    Top = 144
    Width = 97
    Height = 14
    Alignment = taCenter
    AutoSize = False
    Caption = 'Cert. Expiry'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label810: Label8
    Left = 41
    Top = 183
    Width = 97
    Height = 14
    Alignment = taCenter
    AutoSize = False
    Caption = 'Contractor NINO'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label811: Label8
    Left = 148
    Top = 183
    Width = 97
    Height = 14
    Alignment = taCenter
    AutoSize = False
    Caption = 'UTR'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label817: Label8
    Left = 262
    Top = 183
    Width = 97
    Height = 14
    Alignment = taCenter
    AutoSize = False
    Caption = 'A/C Office Ref'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label818: Label8
    Left = 266
    Top = 144
    Width = 90
    Height = 14
    Alignment = taCenter
    AutoSize = False
    Caption = 'Type of Submitter'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    Visible = False
    TextId = 0
  end
  object lblRCTRVC: Label8
    Left = 252
    Top = 183
    Width = 105
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Reverse VAT Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    Visible = False
    TextId = 0
  end
  object OkCP1Btn: TButton
    Tag = 1
    Left = 399
    Top = 21
    Width = 80
    Height = 21
    Caption = '&OK'
    Enabled = False
    ModalResult = 1
    TabOrder = 18
    OnClick = OkCP1BtnClick
  end
  object CanCP1Btn: TButton
    Tag = 1
    Left = 399
    Top = 45
    Width = 80
    Height = 21
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 19
    OnClick = OkCP1BtnClick
  end
  object CPBtn: TButton
    Tag = 1
    Left = 399
    Top = 76
    Width = 80
    Height = 21
    Caption = 'Close &Period'
    Enabled = False
    TabOrder = 20
    OnClick = CPBtnClick
  end
  object ScrollBox1: TScrollBox
    Left = 11
    Top = 241
    Width = 468
    Height = 80
    TabOrder = 17
    object Label85: Label8
      Left = -7
      Top = 21
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'C'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label86: Label8
      Left = -7
      Top = 44
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'T'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label813: Label8
      Left = -5
      Top = 1
      Width = 32
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Code'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label812: Label8
      Left = 39
      Top = 1
      Width = 66
      Height = 14
      Alignment = taCenter
      AutoSize = False
      Caption = 'Description'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label814: Label8
      Left = 129
      Top = 2
      Width = 44
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Rate '
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label815: Label8
      Left = 193
      Top = 2
      Width = 86
      Height = 14
      AutoSize = False
      Caption = 'G/L Code'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label87: Label8
      Left = 368
      Top = 2
      Width = 44
      Height = 14
      AutoSize = False
      Caption = 'CC'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label88: Label8
      Left = 418
      Top = 2
      Width = 44
      Height = 14
      AutoSize = False
      Caption = 'Dept'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label84: Label8
      Left = 283
      Top = 2
      Width = 79
      Height = 14
      AutoSize = False
      Caption = 'G/L Description'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object DR0: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 18
      Width = 69
      Height = 22
      HelpContext = 1395
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 1
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object CDesc0: Text8Pt
      Tag = 1
      Left = 24
      Top = 18
      Width = 93
      Height = 22
      HelpContext = 1395
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 0
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object CDesc1: Text8Pt
      Tag = 1
      Left = 24
      Top = 42
      Width = 93
      Height = 22
      HelpContext = 1395
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 6
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR1: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 42
      Width = 69
      Height = 22
      HelpContext = 1395
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 7
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GLBank0: Text8Pt
      Tag = 1
      Left = 191
      Top = 18
      Width = 88
      Height = 22
      HelpContext = 1396
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 2
      OnEnter = CDesc0Enter
      OnExit = GLBank0Exit
      TextId = 0
      ViaSBtn = False
    end
    object CC0: Text8Pt
      Tag = 1
      Left = 365
      Top = 18
      Width = 46
      Height = 22
      HelpContext = 1397
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 4
      OnEnter = CDesc0Enter
      OnExit = CC0Exit
      TextId = 0
      ViaSBtn = False
    end
    object Dep0: Text8Pt
      Tag = 1
      Left = 416
      Top = 18
      Width = 46
      Height = 22
      HelpContext = 1397
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 5
      OnEnter = CDesc0Enter
      OnExit = CC0Exit
      TextId = 0
      ViaSBtn = False
    end
    object GLBank1: Text8Pt
      Tag = 1
      Left = 191
      Top = 42
      Width = 88
      Height = 22
      HelpContext = 1396
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 8
      OnEnter = CDesc0Enter
      OnExit = GLBank0Exit
      TextId = 0
      ViaSBtn = False
    end
    object CC1: Text8Pt
      Tag = 1
      Left = 365
      Top = 42
      Width = 46
      Height = 22
      HelpContext = 1397
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 10
      OnEnter = CDesc0Enter
      OnExit = CC0Exit
      TextId = 0
      ViaSBtn = False
    end
    object Dep1: Text8Pt
      Tag = 1
      Left = 414
      Top = 42
      Width = 46
      Height = 22
      HelpContext = 1397
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 11
      OnEnter = CDesc0Enter
      OnExit = CC0Exit
      TextId = 0
      ViaSBtn = False
    end
    object GLDesc0: Text8Pt
      Left = 281
      Top = 18
      Width = 81
      Height = 22
      HelpContext = 1396
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBtnText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 3
      TextId = 0
      ViaSBtn = False
    end
    object GLDesc1: Text8Pt
      Left = 281
      Top = 42
      Width = 81
      Height = 22
      HelpContext = 1396
      TabStop = False
      Color = clBtnFace
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBtnText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 9
      TextId = 0
      ViaSBtn = False
    end
  end
  object EqF: Text8Pt
    Left = 120
    Top = 46
    Width = 68
    Height = 22
    HelpContext = 1391
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 16
    Text = 'Nov/2002'
    TextId = 0
    ViaSBtn = False
  end
  object TRE: TCurrencyEdit
    Tag = 1
    Left = 283
    Top = 19
    Width = 38
    Height = 22
    HelpContext = 1391
    Color = clWhite
    Ctl3D = True
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '1-')
    MaxLength = 2
    ParentCtl3D = False
    ParentFont = False
    ReadOnly = True
    TabOrder = 1
    WantReturns = False
    WordWrap = False
    OnExit = LTRChange
    OnKeyPress = TREKeyPress
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0 ;###,###,##0-'
    DecPlaces = 0
    ShowCurrency = False
    TextId = 0
    Value = -0.666666
  end
  object LTR: TEditDate
    Tag = 1
    Left = 120
    Top = 19
    Width = 68
    Height = 22
    HelpContext = 1391
    AutoSelect = False
    Color = clWhite
    EditMask = '00/00/0000;0;'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 0
    OnExit = LTRChange
    Placement = cpAbove
  end
  object CSRF: Text8Pt
    Tag = 1
    Left = 283
    Top = 46
    Width = 98
    Height = 22
    HelpContext = 1392
    AutoSize = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 20
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 2
    TextId = 0
    ViaSBtn = False
  end
  object cbSetPrF: TBorCheck
    Tag = 1
    Left = 26
    Top = 76
    Width = 161
    Height = 20
    HelpContext = 1393
    Caption = 'Set period from date allocated'
    CheckColor = clWindowText
    Color = clBtnFace
    ParentColor = False
    TabOrder = 3
    TabStop = True
    TextId = 0
  end
  object SRVCF: TSBSComboBox
    Tag = 1
    Left = 283
    Top = 74
    Width = 38
    Height = 22
    HelpContext = 1394
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 1
    ParentFont = False
    TabOrder = 4
    ExtendedList = True
    MaxListWidth = 95
    ReadOnly = True
    Validate = True
  end
  object CBCertType: TSBSComboBox
    Tag = 1
    Left = 39
    Top = 158
    Width = 99
    Height = 22
    HelpContext = 1221
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    ParentFont = False
    TabOrder = 6
    Visible = False
    Items.Strings = (
      'N/A'
      'CIS 4T'
      'CIS 4P'
      'CIS 5'
      'CIS 5 Partner'
      'CIS 6 Group')
    MaxListWidth = 0
    ReadOnly = True
  end
  object ECertF: Text8Pt
    Tag = 1
    Left = 146
    Top = 158
    Width = 99
    Height = 22
    HelpContext = 2185
    AutoSize = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 20
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 7
    TextId = 0
    ViaSBtn = False
  end
  object EExpF: TEditDate
    Tag = 1
    Left = 260
    Top = 158
    Width = 99
    Height = 22
    HelpContext = 1089
    AutoSelect = False
    Color = clTeal
    EditMask = '00/00/0000;0;'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 9
    Placement = cpAbove
    AllowBlank = True
  end
  object ENINOF: Text8Pt
    Tag = 1
    Left = 39
    Top = 197
    Width = 99
    Height = 22
    HelpContext = 2101
    AutoSize = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 9
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 10
    TextId = 0
    ViaSBtn = False
  end
  object EUTRF: Text8Pt
    Tag = 1
    Left = 146
    Top = 197
    Width = 99
    Height = 22
    HelpContext = 2102
    AutoSize = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 11
    TextId = 0
    ViaSBtn = False
  end
  object EACREFF: Text8Pt
    Tag = 1
    Left = 260
    Top = 197
    Width = 99
    Height = 22
    HelpContext = 2103
    AutoSize = False
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 13
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 12
    TextId = 0
    ViaSBtn = False
  end
  object CBSubType: TSBSComboBox
    Tag = 1
    Left = 260
    Top = 158
    Width = 99
    Height = 22
    HelpContext = 2186
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    ParentFont = False
    TabOrder = 8
    Visible = False
    Items.Strings = (
      'Individual'
      'Company'
      'Agent'
      'Bureau'
      'Partnership'
      'Trust'
      'Employer'
      'Government'
      'Acting in Capacity'
      'Other')
    MaxListWidth = 0
    ReadOnly = True
  end
  object cbRCTRV: TBorCheck
    Tag = 1
    Left = 35
    Top = 200
    Width = 133
    Height = 20
    HelpContext = 1393
    Caption = 'Use RCT Reverse VAT'
    CheckColor = clWindowText
    Color = clBtnFace
    ParentColor = False
    TabOrder = 13
    TabStop = True
    TextId = 0
    Visible = False
    OnClick = cbRCTRVClick
  end
  object RCTRVCF1: TSBSComboBox
    Tag = 1
    Left = 274
    Top = 197
    Width = 38
    Height = 22
    HelpContext = 1394
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 1
    ParentFont = False
    TabOrder = 14
    Visible = False
    ExtendedList = True
    MaxListWidth = 95
    ReadOnly = True
    Validate = True
  end
  object RCTRVCF2: TSBSComboBox
    Tag = 1
    Left = 320
    Top = 197
    Width = 38
    Height = 22
    HelpContext = 1394
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 1
    ParentFont = False
    TabOrder = 15
    Visible = False
    ExtendedList = True
    MaxListWidth = 95
    ReadOnly = True
    Validate = True
  end
  object cbCISOnGross: TBorCheck
    Left = 22
    Top = 100
    Width = 217
    Height = 20
    HelpContext = 2188
    Caption = 'CIS Calculated on Gross ONLY for JSA'#39's'
    Color = clBtnFace
    ParentColor = False
    TabOrder = 5
    TabStop = True
    TextId = 0
  end
end
