object SetModRec: TSetModRec
  Left = 453
  Top = 169
  HelpContext = 419
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = 'Module License Details'
  ClientHeight = 263
  ClientWidth = 462
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 13
  object Label810: Label8
    Left = 3
    Top = 74
    Width = 16
    Height = 19
    Alignment = taRightJustify
    AutoSize = False
    Caption = '0'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TextId = 0
  end
  object Label811: Label8
    Left = 3
    Top = 50
    Width = 16
    Height = 19
    Alignment = taRightJustify
    AutoSize = False
    Caption = '0'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TextId = 0
  end
  object Label812: Label8
    Left = 3
    Top = 28
    Width = 16
    Height = 19
    Alignment = taRightJustify
    AutoSize = False
    Caption = '0'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TextId = 0
  end
  object Label813: Label8
    Left = 3
    Top = 4
    Width = 16
    Height = 19
    Alignment = taRightJustify
    AutoSize = False
    Caption = '0'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TextId = 0
  end
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 462
    Height = 223
    Align = alTop
    BevelInner = bvRaised
    BevelOuter = bvLowered
    TabOrder = 0
    object Label82: Label8
      Left = 27
      Top = 15
      Width = 146
      Height = 14
      Alignment = taCenter
      AutoSize = False
      Caption = 'Module'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Label83: Label8
      Left = 174
      Top = 15
      Width = 92
      Height = 14
      Alignment = taCenter
      AutoSize = False
      Caption = 'Security'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Label85: Label8
      Left = 265
      Top = 15
      Width = 88
      Height = 14
      Alignment = taCenter
      AutoSize = False
      Caption = 'Release'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object Label86: Label8
      Left = 352
      Top = 15
      Width = 85
      Height = 14
      Alignment = taCenter
      AutoSize = False
      Caption = 'Status'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TextId = 0
    end
    object ScrollBox1: TScrollBox
      Left = 2
      Top = 36
      Width = 458
      Height = 185
      HorzScrollBar.Visible = False
      Align = alBottom
      TabOrder = 0
      object Label81: Label8
        Left = 3
        Top = 4
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '1'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label87: Label8
        Left = 3
        Top = 29
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '2'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label88: Label8
        Left = 3
        Top = 77
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '4'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label89: Label8
        Left = 3
        Top = 52
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '3'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label814: Label8
        Left = 3
        Top = 101
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '5'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label815: Label8
        Left = 3
        Top = 126
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '6'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label816: Label8
        Left = 3
        Top = 149
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '7'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label817: Label8
        Left = 3
        Top = 174
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '8'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label818: Label8
        Left = 3
        Top = 294
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '13'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label819: Label8
        Left = 3
        Top = 319
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '14'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label820: Label8
        Left = 2
        Top = 342
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '15'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label821: Label8
        Left = 2
        Top = 368
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '16'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label822: Label8
        Left = 3
        Top = 270
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '12'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label823: Label8
        Left = 3
        Top = 245
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '11'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label824: Label8
        Left = 3
        Top = 222
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '10'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label825: Label8
        Left = 3
        Top = 197
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '9'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label833: Label8
        Left = 3
        Top = 582
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '25'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label834: Label8
        Left = 3
        Top = 559
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '24'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label835: Label8
        Left = 3
        Top = 534
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '23'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label836: Label8
        Left = 3
        Top = 511
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '22'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label837: Label8
        Left = 3
        Top = 486
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '21'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label838: Label8
        Left = 3
        Top = 462
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '20'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label839: Label8
        Left = 3
        Top = 437
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '19'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label840: Label8
        Left = 3
        Top = 414
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '18'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object Label841: Label8
        Left = 3
        Top = 391
        Width = 16
        Height = 19
        Alignment = taRightJustify
        AutoSize = False
        Caption = '17'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TextId = 0
      end
      object CDesc1: Text8Pt
        Left = 21
        Top = 2
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 0
        Text = 'Full Multi Currency'
        TextId = 0
        ViaSBtn = False
      end
      object CSS1: Text8Pt
        Left = 170
        Top = 2
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 1
        TextId = 0
        ViaSBtn = False
      end
      object RS1: Text8Pt
        Tag = 1
        Left = 262
        Top = 2
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 2
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST1: Text8Pt
        Left = 350
        Top = 2
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 3
        TextId = 0
        ViaSBtn = False
      end
      object CDesc2: Text8Pt
        Left = 21
        Top = 26
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 4
        Text = 'Job Costing'
        TextId = 0
        ViaSBtn = False
      end
      object RS2: Text8Pt
        Tag = 1
        Left = 262
        Top = 26
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 5
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST2: Text8Pt
        Left = 350
        Top = 26
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 6
        TextId = 0
        ViaSBtn = False
      end
      object CDesc3: Text8Pt
        Left = 21
        Top = 50
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 7
        Text = 'Report Writer'
        TextId = 0
        ViaSBtn = False
      end
      object CSS3: Text8Pt
        Left = 170
        Top = 50
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 8
        TextId = 0
        ViaSBtn = False
      end
      object RS3: Text8Pt
        Tag = 1
        Left = 262
        Top = 50
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 9
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST3: Text8Pt
        Left = 350
        Top = 50
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 10
        TextId = 0
        ViaSBtn = False
      end
      object CSS2: Text8Pt
        Left = 170
        Top = 26
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 11
        TextId = 0
        ViaSBtn = False
      end
      object Cdesc4: Text8Pt
        Left = 21
        Top = 74
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 12
        Text = 'DLL Toolkit'
        TextId = 0
        ViaSBtn = False
      end
      object CSS4: Text8Pt
        Left = 170
        Top = 74
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 13
        TextId = 0
        ViaSBtn = False
      end
      object RS4: Text8Pt
        Tag = 1
        Left = 262
        Top = 74
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 14
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST4: Text8Pt
        Left = 350
        Top = 74
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 15
        TextId = 0
        ViaSBtn = False
      end
      object Cdesc5: Text8Pt
        Left = 21
        Top = 98
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 16
        Text = 'TeleSales'
        TextId = 0
        ViaSBtn = False
      end
      object CSS5: Text8Pt
        Left = 170
        Top = 98
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 17
        TextId = 0
        ViaSBtn = False
      end
      object RS5: Text8Pt
        Tag = 1
        Left = 262
        Top = 98
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 18
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST5: Text8Pt
        Left = 350
        Top = 98
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 19
        TextId = 0
        ViaSBtn = False
      end
      object CDesc6: Text8Pt
        Left = 21
        Top = 122
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 20
        Text = 'Account Stock Analysis'
        TextId = 0
        ViaSBtn = False
      end
      object CSS6: Text8Pt
        Left = 170
        Top = 122
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 21
        TextId = 0
        ViaSBtn = False
      end
      object RS6: Text8Pt
        Tag = 1
        Left = 262
        Top = 122
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 22
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST6: Text8Pt
        Left = 350
        Top = 122
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 23
        TextId = 0
        ViaSBtn = False
      end
      object CDesc7: Text8Pt
        Left = 21
        Top = 146
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 24
        Text = 'eBusiness Module'
        TextId = 0
        ViaSBtn = False
      end
      object CSS7: Text8Pt
        Left = 170
        Top = 146
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 25
        TextId = 0
        ViaSBtn = False
      end
      object RS7: Text8Pt
        Tag = 1
        Left = 262
        Top = 146
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 26
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST7: Text8Pt
        Left = 350
        Top = 146
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 27
        TextId = 0
        ViaSBtn = False
      end
      object CDesc8: Text8Pt
        Left = 21
        Top = 170
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 28
        Text = 'Paperless Module'
        TextId = 0
        ViaSBtn = False
      end
      object CSS8: Text8Pt
        Left = 170
        Top = 170
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 29
        TextId = 0
        ViaSBtn = False
      end
      object RS8: Text8Pt
        Tag = 1
        Left = 262
        Top = 170
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 30
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST8: Text8Pt
        Left = 350
        Top = 170
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 31
        TextId = 0
        ViaSBtn = False
      end
      object CDesc9: Text8Pt
        Left = 21
        Top = 194
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 32
        Text = 'OLE Save Functions'
        TextId = 0
        ViaSBtn = False
      end
      object CSS9: Text8Pt
        Left = 170
        Top = 194
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 33
        TextId = 0
        ViaSBtn = False
      end
      object RS9: Text8Pt
        Tag = 1
        Left = 262
        Top = 194
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 34
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST9: Text8Pt
        Left = 350
        Top = 194
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 35
        TextId = 0
        ViaSBtn = False
      end
      object CDesc10: Text8Pt
        Left = 21
        Top = 218
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 36
        Text = 'Commitment Accounting'
        TextId = 0
        ViaSBtn = False
      end
      object CSS10: Text8Pt
        Left = 170
        Top = 218
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 37
        TextId = 0
        ViaSBtn = False
      end
      object RS10: Text8Pt
        Tag = 1
        Left = 262
        Top = 218
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 38
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST10: Text8Pt
        Left = 350
        Top = 218
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 39
        TextId = 0
        ViaSBtn = False
      end
      object CDesc11: Text8Pt
        Left = 21
        Top = 242
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 40
        Text = 'Trade Counter'
        TextId = 0
        ViaSBtn = False
      end
      object CSS11: Text8Pt
        Left = 170
        Top = 242
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 41
        TextId = 0
        ViaSBtn = False
      end
      object RS11: Text8Pt
        Tag = 1
        Left = 262
        Top = 242
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 42
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST11: Text8Pt
        Left = 350
        Top = 242
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 43
        TextId = 0
        ViaSBtn = False
      end
      object CDesc12: Text8Pt
        Left = 21
        Top = 266
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 44
        Text = 'Lite Works Order Processing'
        TextId = 0
        ViaSBtn = False
      end
      object CSS12: Text8Pt
        Left = 170
        Top = 266
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 45
        TextId = 0
        ViaSBtn = False
      end
      object RS12: Text8Pt
        Tag = 1
        Left = 262
        Top = 266
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 46
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST12: Text8Pt
        Left = 350
        Top = 266
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 47
        TextId = 0
        ViaSBtn = False
      end
      object Cdesc13: Text8Pt
        Left = 21
        Top = 290
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 48
        Text = 'Pro Works Order Processing'
        TextId = 0
        ViaSBtn = False
      end
      object CSS13: Text8Pt
        Left = 170
        Top = 290
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 49
        TextId = 0
        ViaSBtn = False
      end
      object RS13: Text8Pt
        Tag = 1
        Left = 262
        Top = 290
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 50
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST13: Text8Pt
        Left = 350
        Top = 290
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 51
        TextId = 0
        ViaSBtn = False
      end
      object CDesc14: Text8Pt
        Left = 21
        Top = 315
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 52
        Text = 'SentiMail'
        TextId = 0
        ViaSBtn = False
      end
      object CSS14: Text8Pt
        Left = 170
        Top = 315
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 53
        TextId = 0
        ViaSBtn = False
      end
      object RS14: Text8Pt
        Tag = 1
        Left = 262
        Top = 315
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 54
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST14: Text8Pt
        Left = 350
        Top = 315
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 55
        TextId = 0
        ViaSBtn = False
      end
      object CDesc15: Text8Pt
        Left = 21
        Top = 339
        Width = 147
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 56
        Text = 'Enhanced User Profile'
        TextId = 0
        ViaSBtn = False
      end
      object CSS15: Text8Pt
        Left = 170
        Top = 339
        Width = 90
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 57
        TextId = 0
        ViaSBtn = False
      end
      object RS15: Text8Pt
        Tag = 1
        Left = 262
        Top = 339
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 58
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST15: Text8Pt
        Left = 350
        Top = 339
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 59
        TextId = 0
        ViaSBtn = False
      end
      object CDesc16: Text8Pt
        Left = 21
        Top = 363
        Width = 146
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 60
        Text = 'CIS/RCT Module'
        TextId = 0
        ViaSBtn = False
      end
      object CSS16: Text8Pt
        Left = 170
        Top = 363
        Width = 89
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 61
        TextId = 0
        ViaSBtn = False
      end
      object RS16: Text8Pt
        Tag = 1
        Left = 262
        Top = 363
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 62
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST16: Text8Pt
        Left = 350
        Top = 363
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 63
        TextId = 0
        ViaSBtn = False
      end
      object CDesc17: Text8Pt
        Left = 21
        Top = 388
        Width = 145
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 64
        Text = 'JC Applications & Valuations'
        TextId = 0
        ViaSBtn = False
      end
      object CSS17: Text8Pt
        Left = 170
        Top = 388
        Width = 88
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 65
        TextId = 0
        ViaSBtn = False
      end
      object RS17: Text8Pt
        Tag = 1
        Left = 262
        Top = 388
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 66
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST17: Text8Pt
        Left = 350
        Top = 388
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 67
        TextId = 0
        ViaSBtn = False
      end
      object CDesc18: Text8Pt
        Left = 21
        Top = 413
        Width = 144
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 68
        Text = 'Full Stock Control'
        TextId = 0
        ViaSBtn = False
      end
      object CSS18: Text8Pt
        Left = 170
        Top = 413
        Width = 87
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 69
        TextId = 0
        ViaSBtn = False
      end
      object RS18: Text8Pt
        Tag = 1
        Left = 262
        Top = 413
        Width = 86
        Height = 22
        Color = clWhite
        EditMask = '>cccccccccc;0; '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        MaxLength = 10
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 70
        OnExit = RS1Exit
        TextId = 0
        ViaSBtn = False
      end
      object ST18: Text8Pt
        Left = 350
        Top = 413
        Width = 85
        Height = 22
        TabStop = False
        Color = clBtnFace
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 11
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 71
        TextId = 0
        ViaSBtn = False
      end
    end
  end
  object SBSPanel1: TSBSPanel
    Left = 0
    Top = 222
    Width = 462
    Height = 41
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 1
    AllowReSize = False
    IsGroupBox = False
    TextId = 0
    object CanCP1Btn: TButton
      Tag = 1
      Left = 329
      Top = 12
      Width = 80
      Height = 21
      Cancel = True
      Caption = '&Cancel'
      ModalResult = 2
      TabOrder = 3
      OnClick = OkCP1BtnClick
    end
    object OkCP1Btn: TButton
      Tag = 1
      Left = 244
      Top = 12
      Width = 80
      Height = 21
      Caption = '&OK'
      ModalResult = 1
      TabOrder = 2
      OnClick = OkCP1BtnClick
    end
    object RBtn1: TButton
      Tag = 1
      Left = 65
      Top = 12
      Width = 80
      Height = 21
      Caption = '&Reset'
      Enabled = False
      ModalResult = 1
      TabOrder = 0
      OnClick = RBtn1Click
    end
    object PBtn1: TButton
      Tag = 1
      Left = 148
      Top = 12
      Width = 80
      Height = 21
      Caption = '&Print'
      ModalResult = 1
      TabOrder = 1
      OnClick = PBtn1Click
    end
  end
end
