object SetVATRate: TSetVATRate
  Left = 274
  Top = 230
  HelpContext = 280
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = 'Set VAT Rates'
  ClientHeight = 274
  ClientWidth = 545
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 14
  object SBSBackGroup2: TSBSBackGroup
    Left = 244
    Top = -1
    Width = 207
    Height = 142
    TextId = 0
  end
  object Label82: Label8
    Left = 271
    Top = 20
    Width = 76
    Height = 14
    Caption = '&Last Tax Return'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label83: Label8
    Left = 264
    Top = 50
    Width = 83
    Height = 14
    Caption = 'Tax Return every'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label81: Label8
    Left = 258
    Top = 80
    Width = 89
    Height = 14
    Caption = 'Current Tax Period'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label84: Label8
    Left = 288
    Top = 110
    Width = 59
    Height = 14
    Caption = 'Tax Scheme'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label816: Label8
    Left = 394
    Top = 50
    Width = 35
    Height = 14
    Caption = 'months'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object sbgVAT100XML: TSBSBackGroup
    Left = 244
    Top = 145
    Width = 207
    Height = 123
    Caption = 'VAT100 XML Submission Settings'
    TextId = 0
  end
  object lblVAT100XMLUserId: Label8
    Left = 250
    Top = 164
    Width = 54
    Height = 14
    HelpContext = 2224
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'User Id'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object lblVAT100XMLPwd: Label8
    Left = 250
    Top = 190
    Width = 54
    Height = 14
    HelpContext = 2224
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Password'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object lblVAT100XMLConfirm: Label8
    Left = 251
    Top = 211
    Width = 47
    Height = 14
    HelpContext = 2224
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Confirm'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object lblVAT100XMLPwd2: Label8
    Left = 250
    Top = 223
    Width = 54
    Height = 14
    HelpContext = 2224
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Password'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object lblSenderType: Label8
    Left = 250
    Top = 243
    Width = 54
    Height = 14
    HelpContext = 2224
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Type'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object OkCP1Btn: TButton
    Tag = 1
    Left = 457
    Top = 4
    Width = 80
    Height = 21
    Caption = '&OK'
    Enabled = False
    ModalResult = 1
    TabOrder = 9
    OnClick = OkCP1BtnClick
  end
  object CanCP1Btn: TButton
    Tag = 1
    Left = 457
    Top = 28
    Width = 80
    Height = 21
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 10
    OnClick = OkCP1BtnClick
  end
  object OHBtn: TButton
    Tag = 1
    Left = 457
    Top = 117
    Width = 80
    Height = 21
    Caption = '&Output History'
    Enabled = False
    TabOrder = 13
    OnClick = IHBtnClick
  end
  object IHBtn: TButton
    Tag = 1
    Left = 457
    Top = 93
    Width = 80
    Height = 21
    Caption = '&Input History'
    Enabled = False
    TabOrder = 12
    OnClick = IHBtnClick
  end
  object CPBtn: TButton
    Tag = 1
    Left = 457
    Top = 69
    Width = 80
    Height = 21
    Caption = 'Close &Period'
    Enabled = False
    TabOrder = 11
    OnClick = CPBtnClick
  end
  object ScrollBox1: TScrollBox
    Left = 5
    Top = 5
    Width = 234
    Height = 262
    HorzScrollBar.Visible = False
    TabOrder = 0
    object Label85: Label8
      Left = -7
      Top = 21
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'S'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label86: Label8
      Left = -7
      Top = 44
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'E'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label87: Label8
      Left = -7
      Top = 68
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Z'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label88: Label8
      Left = -7
      Top = 92
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = '1'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label89: Label8
      Left = -7
      Top = 116
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = '2'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label810: Label8
      Left = 1
      Top = 142
      Width = 20
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = '3/A'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label811: Label8
      Left = 2
      Top = 165
      Width = 19
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = '4/D'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label813: Label8
      Left = -5
      Top = 1
      Width = 32
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Code'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label812: Label8
      Left = 39
      Top = 1
      Width = 66
      Height = 14
      Alignment = taCenter
      AutoSize = False
      Caption = 'Description'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label814: Label8
      Left = 129
      Top = 2
      Width = 44
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Rate '
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label815: Label8
      Left = 181
      Top = 2
      Width = 32
      Height = 14
      AutoSize = False
      Caption = 'Goods'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label817: Label8
      Left = -7
      Top = 189
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = '5'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label818: Label8
      Left = -7
      Top = 212
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = '6'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label819: Label8
      Left = -7
      Top = 236
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = '7'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label820: Label8
      Left = -7
      Top = 260
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = '8'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label821: Label8
      Left = -7
      Top = 284
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = '9'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label822: Label8
      Left = -1
      Top = 307
      Width = 20
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'T'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label823: Label8
      Left = 1
      Top = 331
      Width = 19
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'X'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label824: Label8
      Left = -1
      Top = 452
      Width = 20
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'R'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label826: Label8
      Left = -7
      Top = 427
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'G'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label828: Label8
      Left = -7
      Top = 403
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'F'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label829: Label8
      Left = -7
      Top = 379
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'C'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label830: Label8
      Left = -7
      Top = 356
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'B'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label825: Label8
      Left = -7
      Top = 475
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'W'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object Label827: Label8
      Left = -7
      Top = 499
      Width = 26
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Y'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TextId = 0
    end
    object DR0: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 18
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 1
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object CDesc0: Text8Pt
      Tag = 1
      Left = 23
      Top = 18
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 0
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object GC0: TBorCheck
      Tag = 1
      Left = 193
      Top = 20
      Width = 14
      Height = 20
      Caption = 'GC0'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 2
      TextId = 0
    end
    object CDesc1: Text8Pt
      Tag = 1
      Left = 23
      Top = 42
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 3
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR1: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 42
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 4
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC1: TBorCheck
      Tag = 1
      Left = 193
      Top = 42
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 5
      TextId = 0
    end
    object CDesc2: Text8Pt
      Tag = 1
      Left = 23
      Top = 66
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 6
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR2: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 66
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 7
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC2: TBorCheck
      Tag = 1
      Left = 193
      Top = 66
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 8
      TextId = 0
    end
    object CDesc3: Text8Pt
      Tag = 1
      Left = 23
      Top = 90
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 9
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR3: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 90
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 10
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC3: TBorCheck
      Tag = 1
      Left = 193
      Top = 90
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 11
      TextId = 0
    end
    object CDesc4: Text8Pt
      Tag = 1
      Left = 23
      Top = 114
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 12
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR4: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 114
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 13
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC4: TBorCheck
      Tag = 1
      Left = 193
      Top = 114
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 14
      TextId = 0
    end
    object CDEsc5: Text8Pt
      Tag = 1
      Left = 23
      Top = 138
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 15
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR5: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 138
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 16
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC5: TBorCheck
      Tag = 1
      Left = 193
      Top = 138
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 17
      TextId = 0
    end
    object CDesc6: Text8Pt
      Tag = 1
      Left = 23
      Top = 162
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 18
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR6: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 162
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 19
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC6: TBorCheck
      Tag = 1
      Left = 193
      Top = 162
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 20
      TextId = 0
    end
    object Cdesc7: Text8Pt
      Tag = 1
      Left = 23
      Top = 186
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 21
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR7: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 186
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 22
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object DR8: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 210
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 25
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object CDesc8: Text8Pt
      Tag = 1
      Left = 23
      Top = 210
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 24
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object Cdesc9: Text8Pt
      Tag = 1
      Left = 23
      Top = 234
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 27
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR9: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 234
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 28
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object Cdesc10: Text8Pt
      Tag = 1
      Left = 23
      Top = 258
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 30
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR10: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 258
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 31
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object Cdesc11: Text8Pt
      Tag = 1
      Left = 23
      Top = 282
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 33
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR11: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 282
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 34
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object CDesc12: Text8Pt
      Tag = 1
      Left = 23
      Top = 305
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 36
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR12: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 305
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 37
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object CDesc13: Text8Pt
      Tag = 1
      Left = 23
      Top = 329
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 39
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR13: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 329
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 40
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC11: TBorCheck
      Tag = 1
      Left = 193
      Top = 282
      Width = 14
      Height = 20
      Caption = 'GC11'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 35
      TextId = 0
    end
    object GC12: TBorCheck
      Tag = 1
      Left = 193
      Top = 305
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 38
      TextId = 0
    end
    object GC13: TBorCheck
      Tag = 1
      Left = 193
      Top = 329
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 41
      TextId = 0
    end
    object GC10: TBorCheck
      Tag = 1
      Left = 193
      Top = 258
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 32
      TextId = 0
    end
    object GC9: TBorCheck
      Tag = 1
      Left = 193
      Top = 234
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 29
      TextId = 0
    end
    object GC8: TBorCheck
      Tag = 1
      Left = 193
      Top = 210
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 26
      TextId = 0
    end
    object GC7: TBorCheck
      Tag = 1
      Left = 193
      Top = 188
      Width = 14
      Height = 20
      Caption = 'GC0'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 23
      TextId = 0
    end
    object CDesc18: Text8Pt
      Tag = 1
      Left = 23
      Top = 449
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 54
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR18: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 449
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 55
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC18: TBorCheck
      Tag = 1
      Left = 193
      Top = 448
      Width = 14
      Height = 20
      Caption = 'GC18'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 56
      TextId = 0
    end
    object DR17: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 425
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 52
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object CDesc17: Text8Pt
      Tag = 1
      Left = 23
      Top = 425
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 51
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object CDesc16: Text8Pt
      Tag = 1
      Left = 23
      Top = 401
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 48
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR16: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 401
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 49
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object DR15: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 377
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 46
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC15: TBorCheck
      Tag = 1
      Left = 193
      Top = 377
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 47
      TextId = 0
    end
    object GC16: TBorCheck
      Tag = 1
      Left = 193
      Top = 401
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 50
      TextId = 0
    end
    object GC17: TBorCheck
      Tag = 1
      Left = 193
      Top = 425
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 53
      TextId = 0
    end
    object CDesc15: Text8Pt
      Tag = 1
      Left = 23
      Top = 377
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 45
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object CDesc14: Text8Pt
      Tag = 1
      Left = 23
      Top = 353
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 42
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR14: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 353
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 43
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC14: TBorCheck
      Tag = 1
      Left = 193
      Top = 355
      Width = 14
      Height = 20
      Caption = 'GC0'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 44
      TextId = 0
    end
    object CDesc19: Text8Pt
      Tag = 1
      Left = 23
      Top = 473
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 57
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR19: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 473
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 58
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC19: TBorCheck
      Tag = 1
      Left = 193
      Top = 473
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 59
      TextId = 0
    end
    object CDesc20: Text8Pt
      Tag = 1
      Left = 23
      Top = 497
      Width = 93
      Height = 22
      AutoSize = False
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      ParentShowHint = False
      ReadOnly = True
      ShowHint = True
      TabOrder = 60
      OnEnter = CDesc0Enter
      TextId = 0
      ViaSBtn = False
    end
    object DR20: TCurrencyEdit
      Tag = 1
      Left = 119
      Top = 497
      Width = 69
      Height = 22
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      Lines.Strings = (
        '0.67%-')
      ParentFont = False
      ReadOnly = True
      TabOrder = 61
      WantReturns = False
      WordWrap = False
      OnEnter = CDesc0Enter
      AutoSize = False
      BlockNegative = False
      BlankOnZero = False
      DisplayFormat = '###,###,##0.00% ;###,###,##0.00%-'
      ShowCurrency = False
      TextId = 0
      Value = -0.666666
    end
    object GC20: TBorCheck
      Tag = 1
      Left = 193
      Top = 497
      Width = 14
      Height = 20
      Caption = 'BorCheck1'
      CheckColor = clWindowText
      Color = clBtnFace
      Enabled = False
      ParentColor = False
      TabOrder = 62
      TextId = 0
    end
  end
  object EqF: Text8Pt
    Left = 352
    Top = 77
    Width = 68
    Height = 22
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 3
    Text = 'Oct/1996'
    TextId = 0
    ViaSBtn = False
  end
  object TSF: TSBSComboBox
    Tag = 1
    Left = 352
    Top = 107
    Width = 70
    Height = 22
    HelpContext = 290
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    ParentFont = False
    TabOrder = 4
    OnExit = TSFExit
    Items.Strings = (
      'Normal'
      'Cash Accounting')
    MaxListWidth = 0
    ReadOnly = True
  end
  object TRE: TCurrencyEdit
    Tag = 1
    Left = 352
    Top = 46
    Width = 38
    Height = 22
    Color = clWhite
    Ctl3D = True
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '1-')
    MaxLength = 2
    ParentCtl3D = False
    ParentFont = False
    ReadOnly = True
    TabOrder = 2
    WantReturns = False
    WordWrap = False
    OnExit = LTRChange
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0 ;###,###,##0-'
    DecPlaces = 0
    ShowCurrency = False
    TextId = 0
    Value = -0.666666
  end
  object LTR: TEditDate
    Tag = 1
    Left = 352
    Top = 16
    Width = 68
    Height = 22
    AutoSelect = False
    Color = clWhite
    EditMask = '00/00/0000;0;'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 1
    OnExit = LTRChange
    Placement = cpAbove
  end
  object edtVAT100UserId: Text8Pt
    Left = 308
    Top = 161
    Width = 134
    Height = 22
    HelpContext = 2224
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 12
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 5
    TextId = 0
    ViaSBtn = False
  end
  object edtVAT100Password: Text8Pt
    Left = 308
    Top = 187
    Width = 134
    Height = 22
    HelpContext = 2224
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    PasswordChar = '*'
    ShowHint = True
    TabOrder = 6
    TextId = 0
    ViaSBtn = False
  end
  object edtVAT100PasswordConfirmation: Text8Pt
    Left = 308
    Top = 213
    Width = 134
    Height = 22
    HelpContext = 2224
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    PasswordChar = '*'
    ShowHint = True
    TabOrder = 7
    TextId = 0
    ViaSBtn = False
  end
  object cbVAT100SenderType: TComboBox
    Left = 308
    Top = 239
    Width = 134
    Height = 22
    HelpContext = 2224
    Style = csDropDownList
    ItemHeight = 14
    TabOrder = 8
    Items.Strings = (
      'Individual'
      'Company'
      'Agent'
      'Bureau'
      'Partnership'
      'Trust'
      'Employer'
      'Government'
      'Acting in Capacity'
      'Other ')
  end
  object SubmissionsBtn: TButton
    Tag = 1
    Left = 457
    Top = 149
    Width = 80
    Height = 21
    HelpContext = 2225
    Caption = '&Submissions'
    TabOrder = 14
    OnClick = SubmissionsBtnClick
  end
end
