object StkBinNo: TStkBinNo
  Left = 475
  Top = 224
  HelpContext = 1036
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Add Bin Record'
  ClientHeight = 264
  ClientWidth = 383
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 13
  object SBSPanel1: TSBSBackGroup
    Left = 6
    Top = 2
    Width = 371
    Height = 46
    TextId = 0
  end
  object Label88: Label8
    Left = 11
    Top = 21
    Width = 43
    Height = 14
    Caption = 'Bin Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label89: Label8
    Left = 172
    Top = 21
    Width = 79
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Picking Priority'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object SBSPanel2: TSBSBackGroup
    Left = 6
    Top = 50
    Width = 371
    Height = 179
    TextId = 0
  end
  object Label810: Label8
    Left = 21
    Top = 116
    Width = 33
    Height = 14
    Caption = 'In Doc.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object CurrLab1: Label8
    Left = 226
    Top = 99
    Width = 45
    Height = 14
    Caption = 'Currency'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label87: Label8
    Left = 293
    Top = 99
    Width = 70
    Height = 14
    Caption = 'Unit Cost Price'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object CurrLab2: Label8
    Left = 226
    Top = 143
    Width = 45
    Height = 14
    Caption = 'Currency'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label85: Label8
    Left = 288
    Top = 143
    Width = 75
    Height = 14
    Caption = 'Unit Sales Price'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label811: Label8
    Left = 12
    Top = 161
    Width = 42
    Height = 14
    Caption = 'Out Doc.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label812: Label8
    Left = 18
    Top = 78
    Width = 33
    Height = 14
    Caption = 'In Date'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label82: Label8
    Left = 169
    Top = 60
    Width = 40
    Height = 14
    Caption = 'Orig.Qty'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label81: Label8
    Left = 247
    Top = 60
    Width = 44
    Height = 14
    Caption = 'Available'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object CapLab: Label8
    Left = 318
    Top = 60
    Width = 42
    Height = 14
    Caption = 'Capacity'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object InLocLab: Label8
    Left = 174
    Top = 99
    Width = 35
    Height = 14
    Caption = 'In Locn'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object OutLocLab: Label8
    Left = 171
    Top = 143
    Width = 44
    Height = 14
    Caption = 'Out Locn'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label83: Label8
    Left = 60
    Top = 184
    Width = 62
    Height = 14
    AutoSize = False
    Caption = 'Use by Date'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UseLab: Label8
    Left = 188
    Top = 184
    Width = 61
    Height = 14
    Alignment = taRightJustify
    AutoSize = False
    Caption = 'Use'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    Visible = False
    TextId = 0
  end
  object Label84: Label8
    Left = 138
    Top = 184
    Width = 44
    Height = 14
    AutoSize = False
    Caption = 'UoM'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label86: Label8
    Left = 261
    Top = 183
    Width = 79
    Height = 14
    AutoSize = False
    Caption = 'Auto Pick Mode'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label813: Label8
    Left = 345
    Top = 184
    Width = 20
    Height = 14
    AutoSize = False
    Caption = 'Tag'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object OkCP1Btn: TButton
    Tag = 1
    Left = 110
    Top = 237
    Width = 80
    Height = 21
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 19
    OnClick = CanCP1BtnClick
  end
  object CanCP1Btn: TButton
    Left = 193
    Top = 237
    Width = 80
    Height = 21
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 20
    OnClick = CanCP1BtnClick
  end
  object SNoF: TExMaskEdit
    Tag = 1
    Left = 57
    Top = 17
    Width = 109
    Height = 22
    HelpContext = 1466
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 0
    OnEnter = BNoFEnter
    OnExit = SNoFExit
    TextId = 0
    ViaSBtn = False
    OnMaskError = SNoFMaskError
    OnSetFocusBack = SNoFSetFocusBack
  end
  object BNoF: Text8Pt
    Tag = 1
    Left = 256
    Top = 17
    Width = 109
    Height = 22
    HelpContext = 1467
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 1
    OnExit = BNoFExit
    TextId = 0
    ViaSBtn = False
  end
  object InF: Text8Pt
    Tag = 1
    Left = 57
    Top = 115
    Width = 109
    Height = 22
    HelpContext = 1472
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 6
    TextId = 0
    ViaSBtn = False
  end
  object OutF: Text8Pt
    Tag = 1
    Left = 57
    Top = 159
    Width = 109
    Height = 22
    HelpContext = 1475
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 10
    TextId = 0
    ViaSBtn = False
  end
  object ODF: TEditDate
    Tag = 1
    Left = 57
    Top = 75
    Width = 81
    Height = 22
    HelpContext = 1468
    AutoSelect = False
    Color = clWhite
    EditMask = '00/00/0000;0;'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 2
    Placement = cpAbove
    AllowBlank = True
  end
  object InCF: TSBSComboBox
    Tag = 1
    Left = 222
    Top = 115
    Width = 53
    Height = 22
    HelpContext = 1474
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 8
    ExtendedList = True
    MaxListWidth = 90
    ReadOnly = True
    Validate = True
  end
  object UCF: TCurrencyEdit
    Tag = 1
    Left = 280
    Top = 115
    Width = 85
    Height = 22
    HelpContext = 1474
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    ParentFont = False
    ReadOnly = True
    TabOrder = 9
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object OutCF: TSBSComboBox
    Tag = 1
    Left = 222
    Top = 159
    Width = 53
    Height = 22
    HelpContext = 1477
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 12
    ExtendedList = True
    MaxListWidth = 90
    ReadOnly = True
    Validate = True
  end
  object USF: TCurrencyEdit
    Tag = 1
    Left = 280
    Top = 159
    Width = 85
    Height = 22
    HelpContext = 1477
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    ParentFont = False
    ReadOnly = True
    TabOrder = 13
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object OQF: TCurrencyEdit
    Tag = 1
    Left = 141
    Top = 75
    Width = 75
    Height = 22
    HelpContext = 1469
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    ParentFont = False
    ReadOnly = True
    TabOrder = 3
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object AQF: TCurrencyEdit
    Left = 219
    Top = 75
    Width = 75
    Height = 22
    HelpContext = 1470
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    ParentFont = False
    ReadOnly = True
    TabOrder = 4
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object CQF: TCurrencyEdit
    Tag = 1
    Left = 299
    Top = 75
    Width = 65
    Height = 22
    HelpContext = 1471
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    ParentFont = False
    TabOrder = 5
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object LocInF: Text8Pt
    Tag = 1
    Left = 169
    Top = 115
    Width = 50
    Height = 22
    HelpContext = 1473
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 7
    OnExit = LocInFExit
    TextId = 0
    ViaSBtn = False
  end
  object LocOutF: Text8Pt
    Tag = 1
    Left = 169
    Top = 159
    Width = 50
    Height = 22
    HelpContext = 1476
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 11
    OnExit = LocInFExit
    TextId = 0
    ViaSBtn = False
  end
  object UBF1: TEditDate
    Tag = 1
    Left = 57
    Top = 199
    Width = 75
    Height = 22
    HelpContext = 1478
    AutoSelect = False
    Color = clWhite
    EditMask = '00/00/0000;0;'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 14
    Placement = cpAbove
    AllowBlank = True
  end
  object UQF: TCurrencyEdit
    Tag = 1
    Left = 189
    Top = 199
    Width = 65
    Height = 22
    HelpContext = 1486
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    ParentFont = False
    TabOrder = 16
    Visible = False
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object UOMF: Text8Pt
    Tag = 1
    Left = 136
    Top = 199
    Width = 50
    Height = 22
    HelpContext = 1479
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 15
    OnExit = LocInFExit
    TextId = 0
    ViaSBtn = False
  end
  object PmCBF: TSBSComboBox
    Tag = 1
    Left = 257
    Top = 199
    Width = 85
    Height = 22
    HelpContext = 1480
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 17
    Items.Strings = (
      'Normal'
      'Hold/Lock Bin'
      'Quarantine Bin'
      'Pick by Tag No.')
    MaxListWidth = 90
    ReadOnly = True
    Validate = True
  end
  object TagF: TCurrencyEdit
    Tag = 1
    Left = 344
    Top = 199
    Width = 26
    Height = 22
    HelpContext = 1481
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0 ')
    MaxLength = 2
    ParentFont = False
    ReadOnly = True
    TabOrder = 18
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0 ;###,###,##0-'
    DecPlaces = 0
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
end
