object StkQtyRec: TStkQtyRec
  Left = 421
  Top = 227
  HelpContext = 122
  ActiveControl = QDTF
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Quantity Break'
  ClientHeight = 300
  ClientWidth = 269
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  Visible = True
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 14
  object SBSPanel1: TSBSBackGroup
    Left = 5
    Top = 2
    Width = 259
    Height = 262
    TextId = 0
  end
  object Label81: Label8
    Left = 34
    Top = 45
    Width = 55
    Height = 14
    Caption = 'Stock Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object QFLab: Label8
    Left = 38
    Top = 71
    Width = 51
    Height = 14
    Caption = 'Qty - From'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object QTLab: Label8
    Left = 175
    Top = 70
    Width = 11
    Height = 14
    Caption = 'To'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label84: Label8
    Left = 20
    Top = 19
    Width = 68
    Height = 14
    Caption = 'Discount Type'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label86: Label8
    Left = 64
    Top = 97
    Width = 25
    Height = 14
    Alignment = taRightJustify
    Caption = 'Band'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label85: Label8
    Left = 44
    Top = 125
    Width = 45
    Height = 14
    Alignment = taRightJustify
    Caption = 'Unit Price'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label87: Label8
    Left = 46
    Top = 151
    Width = 42
    Height = 14
    Caption = 'Discount'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label88: Label8
    Left = 21
    Top = 179
    Width = 68
    Height = 14
    Caption = 'Discount (Val)'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label89: Label8
    Left = 13
    Top = 205
    Width = 75
    Height = 14
    Caption = 'Mark-Up/Margin'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label82: Label8
    Left = 34
    Top = 70
    Width = 55
    Height = 14
    Caption = 'Stock Desc'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label812: Label8
    Left = 165
    Top = 238
    Width = 15
    Height = 14
    Alignment = taRightJustify
    Caption = 'to :'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label83: Label8
    Left = 194
    Top = 152
    Width = 10
    Height = 14
    Caption = '%'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label810: Label8
    Left = 194
    Top = 205
    Width = 10
    Height = 14
    Caption = '%'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object OkCP1Btn: TButton
    Tag = 1
    Left = 53
    Top = 274
    Width = 80
    Height = 21
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 14
    OnClick = CanCP1BtnClick
  end
  object CanCP1Btn: TButton
    Tag = 1
    Left = 137
    Top = 274
    Width = 80
    Height = 21
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 15
    OnClick = CanCP1BtnClick
  end
  object QFF: TCurrencyEdit
    Tag = 1
    Left = 93
    Top = 67
    Width = 65
    Height = 22
    HelpContext = 135
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '1-')
    MaxLength = 13
    ParentFont = False
    ReadOnly = True
    TabOrder = 3
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.-'
    ShowCurrency = False
    TextId = 0
    Value = -0.666666
  end
  object QTF: TCurrencyEdit
    Tag = 1
    Left = 191
    Top = 67
    Width = 64
    Height = 22
    HelpContext = 135
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.67-')
    MaxLength = 13
    ParentFont = False
    ReadOnly = True
    TabOrder = 4
    WantReturns = False
    WordWrap = False
    OnExit = QTFExit
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = -0.666666
  end
  object QBF: TSBSComboBox
    Tag = 1
    Left = 93
    Top = 94
    Width = 64
    Height = 22
    HelpContext = 123
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    ParentFont = False
    TabOrder = 5
    OnEnter = QBFEnter
    Items.Strings = (
      'A'
      'B'
      'C'
      'D'
      'E'
      'F'
      'G'
      'H')
    MaxListWidth = 0
    ReadOnly = True
    Validate = True
  end
  object QUPF: TCurrencyEdit
    Tag = 1
    Left = 149
    Top = 120
    Width = 106
    Height = 22
    HelpContext = 124
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '-0.67')
    MaxLength = 12
    ParentFont = False
    ReadOnly = True
    TabOrder = 7
    WantReturns = False
    WordWrap = False
    OnEnter = QUPFEnter
    OnKeyPress = QUPFKeyPress
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00'
    ShowCurrency = False
    TextId = 0
    Value = -0.666666
  end
  object QDF: TCurrencyEdit
    Tag = 1
    Left = 93
    Top = 148
    Width = 99
    Height = 22
    HelpContext = 125
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.67-')
    MaxLength = 6
    ParentFont = False
    ReadOnly = True
    TabOrder = 8
    WantReturns = False
    WordWrap = False
    OnEnter = QDFEnter
    OnExit = QDFExit
    OnKeyPress = QUPFKeyPress
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '##0.00;##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = -0.666666
  end
  object QVF: TCurrencyEdit
    Tag = 1
    Left = 93
    Top = 175
    Width = 99
    Height = 22
    HelpContext = 126
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.67-')
    MaxLength = 13
    ParentFont = False
    ReadOnly = True
    TabOrder = 9
    WantReturns = False
    WordWrap = False
    OnEnter = QVFEnter
    OnKeyPress = QUPFKeyPress
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = -0.666666
  end
  object QMF: TCurrencyEdit
    Tag = 1
    Left = 93
    Top = 202
    Width = 99
    Height = 22
    HelpContext = 127
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.67-')
    MaxLength = 9
    ParentFont = False
    ReadOnly = True
    TabOrder = 10
    WantReturns = False
    WordWrap = False
    OnEnter = QMFEnter
    OnKeyPress = QUPFKeyPress
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = -0.666666
  end
  object QBCurrF: TSBSComboBox
    Tag = 1
    Left = 93
    Top = 120
    Width = 53
    Height = 22
    HelpContext = 40165
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 6
    OnEnter = QBCurrFEnter
    ExtendedList = True
    MaxListWidth = 90
    ReadOnly = True
    Validate = True
  end
  object QSCF: Text8Pt
    Left = 93
    Top = 42
    Width = 121
    Height = 22
    HelpContext = 120
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 1
    OnExit = QSCFExit
    TextId = 0
    ViaSBtn = False
  end
  object QSDF: Text8Pt
    Left = 93
    Top = 67
    Width = 162
    Height = 22
    HelpContext = 120
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 2
    OnExit = QSCFExit
    TextId = 0
    ViaSBtn = False
  end
  object I1TransDateF: TEditDate
    Tag = 1
    Left = 93
    Top = 234
    Width = 69
    Height = 22
    HelpContext = 1575
    AutoSelect = False
    Color = clWhite
    EditMask = '00/00/0000;0;'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 12
    Placement = cpAbove
    AllowBlank = True
  end
  object I2TransDateF: TEditDate
    Tag = 1
    Left = 181
    Top = 234
    Width = 68
    Height = 22
    HelpContext = 1575
    AutoSelect = False
    Color = clWhite
    EditMask = '00/00/0000;0;'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 13
    Placement = cpAbove
    AllowBlank = True
  end
  object UDF: TBorCheckEx
    Left = 9
    Top = 235
    Width = 81
    Height = 20
    Caption = 'Effect Dates'
    Color = clBtnFace
    ParentColor = False
    TabOrder = 11
    TabStop = True
    TextId = 0
    OnClick = UDFClick
  end
  object QDTF: TComboBox
    Tag = 1
    Left = 93
    Top = 16
    Width = 162
    Height = 22
    HelpContext = 121
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    ParentFont = False
    TabOrder = 0
    OnClick = QDTFClick
  end
end
