object StkSerNo: TStkSerNo
  Left = 319
  Top = 190
  HelpContext = 1036
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Add Serial/Batch Number'
  ClientHeight = 263
  ClientWidth = 383
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 13
  object SBSPanel1: TSBSBackGroup
    Left = 6
    Top = 2
    Width = 371
    Height = 46
    TextId = 0
  end
  object Label88: Label8
    Left = 17
    Top = 19
    Width = 36
    Height = 14
    Caption = 'Ser No.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label89: Label8
    Left = 230
    Top = 19
    Width = 47
    Height = 14
    Caption = 'Batch No.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object SBSPanel2: TSBSBackGroup
    Left = 6
    Top = 50
    Width = 371
    Height = 175
    TextId = 0
  end
  object Label810: Label8
    Left = 21
    Top = 79
    Width = 33
    Height = 14
    Caption = 'In Doc.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object CurrLab1: Label8
    Left = 226
    Top = 62
    Width = 45
    Height = 14
    Caption = 'Currency'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label87: Label8
    Left = 293
    Top = 62
    Width = 70
    Height = 14
    Caption = 'Unit Cost Price'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object CurrLab2: Label8
    Left = 226
    Top = 106
    Width = 45
    Height = 14
    Caption = 'Currency'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label85: Label8
    Left = 288
    Top = 106
    Width = 75
    Height = 14
    Caption = 'Unit Sales Price'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label811: Label8
    Left = 12
    Top = 124
    Width = 42
    Height = 14
    Caption = 'Out Doc.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label812: Label8
    Left = 11
    Top = 167
    Width = 42
    Height = 14
    Caption = 'Out Date'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label82: Label8
    Left = 170
    Top = 149
    Width = 40
    Height = 14
    Caption = 'Orig.Qty'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label81: Label8
    Left = 242
    Top = 149
    Width = 44
    Height = 14
    Caption = 'Available'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object UseLab: Label8
    Left = 334
    Top = 149
    Width = 19
    Height = 14
    Caption = 'Use'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    Visible = False
    TextId = 0
  end
  object InLocLab: Label8
    Left = 174
    Top = 62
    Width = 35
    Height = 14
    Caption = 'In Locn'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object OutLocLab: Label8
    Left = 171
    Top = 107
    Width = 44
    Height = 14
    Caption = 'Out Locn'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label83: Label8
    Left = 224
    Top = 195
    Width = 62
    Height = 14
    AutoSize = False
    Caption = 'Use by Date'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object Label84: Label8
    Left = 11
    Top = 195
    Width = 43
    Height = 14
    Caption = 'Bin Code'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TextId = 0
  end
  object OkCP1Btn: TButton
    Tag = 1
    Left = 109
    Top = 233
    Width = 80
    Height = 21
    Caption = '&OK'
    ModalResult = 1
    TabOrder = 16
    OnClick = CanCP1BtnClick
  end
  object CanCP1Btn: TButton
    Left = 192
    Top = 233
    Width = 80
    Height = 21
    Cancel = True
    Caption = '&Cancel'
    ModalResult = 2
    TabOrder = 17
    OnClick = CanCP1BtnClick
  end
  object SNoF: Text8Pt
    Tag = 1
    Left = 57
    Top = 17
    Width = 141
    Height = 22
    HelpContext = 1037
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 0
    OnExit = SNoFExit
    TextId = 0
    ViaSBtn = False
  end
  object BNoF: Text8Pt
    Tag = 1
    Left = 280
    Top = 17
    Width = 85
    Height = 22
    HelpContext = 1037
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 1
    OnEnter = BNoFEnter
    OnExit = BNoFExit
    TextId = 0
    ViaSBtn = False
  end
  object InF: Text8Pt
    Tag = 1
    Left = 57
    Top = 78
    Width = 109
    Height = 22
    HelpContext = 1038
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 2
    TextId = 0
    ViaSBtn = False
  end
  object OutF: Text8Pt
    Tag = 1
    Left = 57
    Top = 122
    Width = 109
    Height = 22
    HelpContext = 1039
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 6
    TextId = 0
    ViaSBtn = False
  end
  object ODF: TEditDate
    Tag = 1
    Left = 57
    Top = 164
    Width = 81
    Height = 22
    HelpContext = 1044
    AutoSelect = False
    Color = clWhite
    EditMask = '00/00/0000;0;'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 10
    Placement = cpAbove
    AllowBlank = True
  end
  object InCF: TSBSComboBox
    Tag = 1
    Left = 222
    Top = 78
    Width = 53
    Height = 22
    HelpContext = 1040
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 4
    ExtendedList = True
    MaxListWidth = 90
    ReadOnly = True
    Validate = True
  end
  object UCF: TCurrencyEdit
    Tag = 1
    Left = 280
    Top = 78
    Width = 85
    Height = 22
    HelpContext = 1040
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 13
    ParentFont = False
    ReadOnly = True
    TabOrder = 5
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object OutCF: TSBSComboBox
    Tag = 1
    Left = 222
    Top = 122
    Width = 53
    Height = 22
    HelpContext = 1043
    Style = csDropDownList
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    MaxLength = 3
    ParentFont = False
    TabOrder = 8
    ExtendedList = True
    MaxListWidth = 90
    ReadOnly = True
    Validate = True
  end
  object USF: TCurrencyEdit
    Tag = 1
    Left = 280
    Top = 122
    Width = 85
    Height = 22
    HelpContext = 1043
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 13
    ParentFont = False
    ReadOnly = True
    TabOrder = 9
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object OQF: TCurrencyEdit
    Tag = 1
    Left = 148
    Top = 164
    Width = 65
    Height = 22
    HelpContext = 1045
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 13
    ParentFont = False
    ReadOnly = True
    TabOrder = 11
    WantReturns = False
    WordWrap = False
    OnEnter = OQFEnter
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object AQF: TCurrencyEdit
    Left = 224
    Top = 164
    Width = 65
    Height = 22
    HelpContext = 1045
    TabStop = False
    Color = clBtnFace
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    ParentFont = False
    ReadOnly = True
    TabOrder = 12
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object UQF: TCurrencyEdit
    Tag = 1
    Left = 300
    Top = 164
    Width = 65
    Height = 22
    HelpContext = 1045
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    Lines.Strings = (
      '0.00 ')
    MaxLength = 13
    ParentFont = False
    TabOrder = 13
    Visible = False
    WantReturns = False
    WordWrap = False
    AutoSize = False
    BlockNegative = False
    BlankOnZero = False
    DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
    ShowCurrency = False
    TextId = 0
    Value = 1E-10
  end
  object LocInF: Text8Pt
    Tag = 1
    Left = 169
    Top = 78
    Width = 50
    Height = 22
    HelpContext = 1041
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 3
    OnExit = LocInFExit
    TextId = 0
    ViaSBtn = False
  end
  object LocOutF: Text8Pt
    Tag = 1
    Left = 169
    Top = 122
    Width = 50
    Height = 22
    HelpContext = 1042
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 7
    OnExit = LocInFExit
    TextId = 0
    ViaSBtn = False
  end
  object UBF1: TEditDate
    Tag = 1
    Left = 290
    Top = 192
    Width = 75
    Height = 22
    HelpContext = 1046
    AutoSelect = False
    Color = clWhite
    EditMask = '00/00/0000;0;'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ReadOnly = True
    TabOrder = 15
    Placement = cpAbove
    AllowBlank = True
  end
  object BCF1: Text8Pt
    Tag = 1
    Left = 57
    Top = 192
    Width = 109
    Height = 22
    HelpContext = 1038
    CharCase = ecUpperCase
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 10
    ParentFont = False
    ParentShowHint = False
    ReadOnly = True
    ShowHint = True
    TabOrder = 14
    OnExit = BCF1Exit
    TextId = 0
    ViaSBtn = False
  end
end
