object TxLine: TTxLine
  Left = 422
  Top = 198
  HelpContext = 7
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  ClientHeight = 605
  ClientWidth = 641
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsMDIChild
  KeyPreview = True
  OldCreateOrder = True
  Position = poDefault
  Scaled = False
  Visible = True
  OnActivate = FormActivate
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnDeactivate = FormDeactivate
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 14
  object PageControl1: TPageControl
    Left = 1
    Top = 1
    Width = 640
    Height = 600
    ActivePage = DE3Page
    TabIndex = 2
    TabOrder = 0
    OnChange = PageControl1Change
    OnChanging = PageControl1Changing
    object DE1Page: TTabSheet
      Caption = 'Data Entry'
      object Id1Panel: TSBSPanel
        Left = 0
        Top = 2
        Width = 404
        Height = 214
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 0
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object Id1ItemLab: Label8
          Left = 10
          Top = 12
          Width = 19
          Height = 14
          Caption = 'Item'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id1UPLab: Label8
          Left = 260
          Top = 42
          Width = 34
          Height = 14
          Caption = 'U/Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id1DiscLab: Label8
          Left = 252
          Top = 75
          Width = 42
          Height = 14
          Caption = 'Discount'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id1LTotLab: Label8
          Left = 269
          Top = 107
          Width = 22
          Height = 14
          Caption = 'Total'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id1QtyLab: Label8
          Left = 87
          Top = 12
          Width = 17
          Height = 14
          Caption = 'Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object Id1ItemF: Text8Pt
        Tag = 1
        Left = 34
        Top = 10
        Width = 39
        Height = 22
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 1
        TextId = 0
        ViaSBtn = False
      end
      object Id1QtyF: TCurrencyEdit
        Tag = 1
        Left = 108
        Top = 10
        Width = 88
        Height = 22
        HelpContext = 247
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        WantReturns = False
        WordWrap = False
        OnEnter = Id3PQtyFEnter
        OnExit = Id3PQtyFExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id1SBox: TScrollBox
        Left = 8
        Top = 38
        Width = 238
        Height = 131
        HorzScrollBar.Visible = False
        BorderStyle = bsNone
        Ctl3D = False
        ParentCtl3D = False
        TabOrder = 3
        object Id1Desc1F: Text8Pt
          Tag = 1
          Left = 1
          Top = 1
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          Text = '12345678901234567890123456789012345'
          OnKeyPress = Id1Desc1FKeyPress
          TextId = 0
          ViaSBtn = False
        end
        object Id1Desc2F: Text8Pt
          Tag = 1
          Left = 1
          Top = 22
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 1
          OnKeyPress = Id1Desc1FKeyPress
          TextId = 0
          ViaSBtn = False
        end
        object Id1Desc3F: Text8Pt
          Tag = 1
          Left = 1
          Top = 43
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 2
          OnKeyPress = Id1Desc1FKeyPress
          TextId = 0
          ViaSBtn = False
        end
        object Id1Desc4F: Text8Pt
          Tag = 1
          Left = 1
          Top = 64
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          OnKeyPress = Id1Desc1FKeyPress
          TextId = 0
          ViaSBtn = False
        end
        object Id1Desc5F: Text8Pt
          Tag = 1
          Left = 1
          Top = 85
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 4
          OnKeyPress = Id1Desc1FKeyPress
          TextId = 0
          ViaSBtn = False
        end
        object Id1Desc6F: Text8Pt
          Tag = 1
          Left = 1
          Top = 106
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 5
          TextId = 0
          ViaSBtn = False
        end
      end
      object Id1UPriceF: TCurrencyEdit
        Tag = 1
        Left = 296
        Top = 42
        Width = 100
        Height = 22
        HelpContext = 268
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 4
        WantReturns = False
        WordWrap = False
        OnExit = Id3UPriceFExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id1LTotF: TCurrencyEdit
        Tag = 2
        Left = 296
        Top = 105
        Width = 100
        Height = 22
        HelpContext = 248
        TabStop = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 6
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id1DiscF: Text8Pt
        Tag = 1
        Left = 296
        Top = 74
        Width = 100
        Height = 22
        HelpContext = 269
        AutoSize = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 5
        OnEnter = Id3DiscFoldEnter
        OnExit = Id3DiscFoldExit
        TextId = 0
        ViaSBtn = False
      end
      object OkCP1Btn: TButton
        Tag = 1
        Left = 441
        Top = 223
        Width = 80
        Height = 21
        HelpContext = 278
        Caption = '&OK'
        ModalResult = 1
        TabOrder = 7
        OnClick = CanCP1BtnClick
      end
      object CanCP1Btn: TButton
        Tag = 1
        Left = 526
        Top = 223
        Width = 80
        Height = 21
        HelpContext = 279
        Cancel = True
        Caption = '&Cancel'
        ModalResult = 2
        TabOrder = 8
        OnClick = CanCP1BtnClick
      end
    end
    object De2Page: TTabSheet
      Caption = 'Data Entry'
    end
    object DE3Page: TTabSheet
      Caption = 'Data Entry'
      object Id3Panel3: TSBSPanel
        Left = 0
        Top = 324
        Width = 432
        Height = 153
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 7
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object UDF1L: Label8
          Left = 7
          Top = 14
          Width = 48
          Height = 14
          Caption = 'UD Field 1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF3L: Label8
          Left = 218
          Top = 14
          Width = 48
          Height = 14
          Caption = 'UD Field 3'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF2L: Label8
          Left = 6
          Top = 38
          Width = 48
          Height = 14
          Caption = 'UD Field 2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object UDF4L: Label8
          Left = 218
          Top = 38
          Width = 48
          Height = 14
          Caption = 'UD Field 4'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblUdf5: Label8
          Left = 7
          Top = 74
          Width = 48
          Height = 14
          Caption = 'UD Field 5'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblUdf8: Label8
          Left = 218
          Top = 74
          Width = 48
          Height = 14
          Caption = 'UD Field 8'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblUdf6: Label8
          Left = 7
          Top = 100
          Width = 48
          Height = 14
          Caption = 'UD Field 6'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblUdf9: Label8
          Left = 218
          Top = 100
          Width = 48
          Height = 14
          Caption = 'UD Field 9'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblUdf7: Label8
          Left = 7
          Top = 126
          Width = 48
          Height = 14
          Caption = 'UD Field 7'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblUdf10: Label8
          Left = 218
          Top = 126
          Width = 54
          Height = 14
          Caption = 'UD Field 10'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object bevUDFs: TBevel
          Left = 6
          Top = 61
          Width = 418
          Height = 3
        end
      end
      object Id3Panel: TSBSPanel
        Left = 0
        Top = 2
        Width = 252
        Height = 214
        BevelInner = bvRaised
        BevelOuter = bvLowered
        Caption = 'Id3Panel'
        TabOrder = 0
        AllowReSize = False
        IsGroupBox = False
        TextId = 0
        object Id3SCodeLab: Label8
          Left = 7
          Top = 12
          Width = 43
          Height = 14
          Caption = 'Stk Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object id3LocLab: Label8
          Left = 183
          Top = 11
          Width = 27
          Height = 14
          Alignment = taRightJustify
          Caption = 'Locn '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object Id3SCodeF: Text8Pt
        Tag = 1
        Left = 52
        Top = 10
        Width = 127
        Height = 22
        Hint = 
          'Double click to drill down|Double clicking or using the down but' +
          'ton will drill down to the record for this field. The up button ' +
          'will search for the nearest match.'
        HelpContext = 256
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 1
        OnDblClick = Id3SCodeFDblClick
        OnEnter = Id3SCodeFEnter
        OnExit = Id3SCodeFExit
        TextId = 0
        ViaSBtn = False
        ShowHilight = True
      end
      object Id3SBox: TScrollBox
        Left = 8
        Top = 38
        Width = 241
        Height = 131
        HorzScrollBar.Visible = False
        BorderStyle = bsNone
        Ctl3D = False
        ParentCtl3D = False
        TabOrder = 3
        OnExit = Id3SBoxExit
        object Id3Desc1F: Text8Pt
          Tag = 1
          Left = 1
          Top = 1
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 0
          Text = '12345678901234567890123456789012345'
          OnKeyPress = Id3Desc1FKeyPress
          TextId = 0
          ViaSBtn = False
        end
        object Id3Desc2F: Text8Pt
          Tag = 1
          Left = 1
          Top = 22
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 1
          OnKeyPress = Id1Desc1FKeyPress
          TextId = 0
          ViaSBtn = False
        end
        object Id3Desc3F: Text8Pt
          Tag = 1
          Left = 1
          Top = 43
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 2
          OnKeyPress = Id1Desc1FKeyPress
          TextId = 0
          ViaSBtn = False
        end
        object Id3Desc4F: Text8Pt
          Tag = 1
          Left = 1
          Top = 64
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 3
          OnKeyPress = Id1Desc1FKeyPress
          TextId = 0
          ViaSBtn = False
        end
        object Id3Desc5F: Text8Pt
          Tag = 1
          Left = 1
          Top = 85
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 4
          OnKeyPress = Id1Desc1FKeyPress
          TextId = 0
          ViaSBtn = False
        end
        object Id3Desc6F: Text8Pt
          Tag = 1
          Left = 1
          Top = 106
          Width = 236
          Height = 22
          HelpContext = 235
          Color = clWhite
          Ctl3D = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 50
          ParentCtl3D = False
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 5
          TextId = 0
          ViaSBtn = False
        end
      end
      object Id3LocF: Text8Pt
        Tag = 1
        Left = 207
        Top = 11
        Width = 38
        Height = 22
        HelpContext = 274
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 2
        OnEnter = Id3LocFEnter
        OnExit = Id3LocFExit
        TextId = 0
        ViaSBtn = False
      end
      object scrMultiBuy: TScrollBox
        Left = 0
        Top = 220
        Width = 432
        Height = 99
        HelpContext = 8003
        HorzScrollBar.Visible = False
        BevelKind = bkTile
        BorderStyle = bsNone
        TabOrder = 6
        Visible = False
        object lblMultiBuy: TLabel
          Left = 8
          Top = 5
          Width = 233
          Height = 14
          HelpContext = 8003
          Caption = 'The following Multi-Buy discounts are available:-'
        end
      end
      object pnlService: TPanel
        Left = 2
        Top = 178
        Width = 248
        Height = 25
        HelpContext = 8052
        BevelOuter = bvNone
        TabOrder = 4
        object lblServiceTo: TLabel
          Left = 159
          Top = 4
          Width = 9
          Height = 14
          HelpContext = 8052
          Caption = 'to'
        end
        object chkService: TBorCheck
          Tag = 1
          Left = 5
          Top = 1
          Width = 73
          Height = 18
          HelpContext = 8052
          Align = alRight
          Caption = 'EC Service'
          CheckColor = clWindowText
          Color = clBtnFace
          ParentColor = False
          TabOrder = 0
          TabStop = True
          TextId = 0
          OnClick = chkServiceClick
          OnMouseUp = chkServiceMouseUp
        end
        object dtServiceStart: TEditDate
          Tag = 1
          Left = 84
          Top = 1
          Width = 69
          Height = 22
          HelpContext = 8052
          AutoSelect = False
          Color = clWhite
          EditMask = '00/00/0000;0;'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 1
          Placement = cpAbove
        end
        object dtServiceEnd: TEditDate
          Tag = 1
          Left = 175
          Top = 1
          Width = 69
          Height = 22
          HelpContext = 8052
          AutoSelect = False
          Color = clWhite
          EditMask = '00/00/0000;0;'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          TabOrder = 2
          Placement = cpAbove
        end
      end
      object pnlWebExtensions: TPanel
        Left = 0
        Top = 485
        Width = 432
        Height = 80
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 18
        Visible = False
        object Label4: TLabel
          Left = 5
          Top = 13
          Width = 51
          Height = 14
          Alignment = taRightJustify
          Caption = 'Reference'
        end
        object Label5: TLabel
          Left = 5
          Top = 43
          Width = 52
          Height = 14
          Alignment = taRightJustify
          Caption = 'Receipt No'
        end
        object Label6: TLabel
          Left = 194
          Top = 13
          Width = 73
          Height = 14
          Alignment = taRightJustify
          Caption = 'PostCode From'
        end
        object Label87: Label8
          Left = 207
          Top = 40
          Width = 60
          Height = 14
          Alignment = taRightJustify
          Caption = 'PostCode To'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object edtReference: Text8Pt
          Tag = 1
          Left = 60
          Top = 8
          Width = 121
          Height = 22
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 20
          ParentFont = False
          ParentShowHint = False
          ShowHint = True
          TabOrder = 0
          TextId = 0
          ViaSBtn = False
        end
        object edtFromPostCode: Text8Pt
          Tag = 1
          Left = 274
          Top = 8
          Width = 121
          Height = 22
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 15
          ParentFont = False
          ParentShowHint = False
          ShowHint = True
          TabOrder = 2
          TextId = 0
          ViaSBtn = False
        end
        object edtReceiptNo: Text8Pt
          Tag = 1
          Left = 60
          Top = 40
          Width = 121
          Height = 22
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 20
          ParentFont = False
          ParentShowHint = False
          ShowHint = True
          TabOrder = 1
          TextId = 0
          ViaSBtn = False
        end
        object edtToPostCode: Text8Pt
          Tag = 1
          Left = 274
          Top = 40
          Width = 121
          Height = 22
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 15
          ParentFont = False
          ParentShowHint = False
          ShowHint = True
          TabOrder = 3
          TextId = 0
          ViaSBtn = False
        end
      end
      object pnlValues: TPanel
        Left = 256
        Top = 2
        Width = 373
        Height = 214
        BevelInner = bvRaised
        BevelOuter = bvLowered
        TabOrder = 5
        object Id3PQLab: Label8
          Left = 11
          Top = 13
          Width = 43
          Height = 14
          Caption = 'Pack Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3QtyLab: Label8
          Left = 37
          Top = 36
          Width = 17
          Height = 14
          Caption = 'Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3UPLab: Label8
          Left = 20
          Top = 62
          Width = 34
          Height = 14
          Caption = 'U/Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3DiscLab: Label8
          Left = 12
          Top = 87
          Width = 42
          Height = 14
          Caption = 'Discount'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3LTotLab: Label8
          Left = 31
          Top = 112
          Width = 22
          Height = 14
          Caption = 'Total'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblOtherDiscounts: Label8
          Left = 13
          Top = 138
          Width = 85
          Height = 14
          Caption = 'Other Discounts:-'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblMBDiscount: Label8
          Left = 10
          Top = 163
          Width = 44
          Height = 14
          Alignment = taRightJustify
          Caption = 'Multi-Buy'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object lblTransDiscount: Label8
          Left = 26
          Top = 187
          Width = 28
          Height = 14
          Alignment = taRightJustify
          Caption = 'Trans'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label81: Label8
          Left = 194
          Top = 14
          Width = 45
          Height = 14
          Caption = 'Job Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label82: Label8
          Left = 196
          Top = 39
          Width = 42
          Height = 14
          Caption = 'Analysis'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object VATCCLab3: Label8
          Left = 177
          Top = 64
          Width = 61
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = '/CC/Dep'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label85: Label8
          Left = 196
          Top = 88
          Width = 42
          Height = 14
          Caption = 'GL Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Id3CostLab: Label8
          Left = 199
          Top = 138
          Width = 34
          Height = 14
          Alignment = taRightJustify
          Caption = 'Cost__'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label83: Label8
          Left = 193
          Top = 163
          Width = 44
          Height = 14
          Caption = 'Line type'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object DelDateLab: Label8
          Left = 187
          Top = 188
          Width = 50
          Height = 14
          Alignment = taRightJustify
          Caption = 'Deliv. Date'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Bevel1: TBevel
          Left = 173
          Top = 10
          Width = 3
          Height = 196
        end
        object Id5JCodeF: Text8Pt
          Tag = 1
          Left = 241
          Top = 9
          Width = 123
          Height = 22
          Hint = 
            'Double click to drill down|Double clicking or using the down but' +
            'ton will drill down to the record for this field. The up button ' +
            'will search for the nearest match.'
          HelpContext = 465
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 6
          OnEnter = Id3UPriceFEnter
          OnExit = Id5JCodeFExit
          TextId = 0
          ViaSBtn = False
          Link_to_Job = True
          ShowHilight = True
        end
        object Id5JAnalF: Text8Pt
          Tag = 1
          Left = 241
          Top = 34
          Width = 123
          Height = 22
          HelpContext = 466
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 7
          OnEnter = Id3UPriceFEnter
          OnExit = Id5JAnalFExit
          TextId = 0
          ViaSBtn = False
        end
        object Id3DepF: Text8Pt
          Tag = 1
          Left = 325
          Top = 59
          Width = 39
          Height = 22
          HelpContext = 272
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 10
          OnEnter = Id3UPriceFEnter
          OnExit = Id1CCFExit
          TextId = 0
          ViaSBtn = False
        end
        object Id3CCF: Text8Pt
          Tag = 1
          Left = 284
          Top = 59
          Width = 39
          Height = 22
          HelpContext = 272
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 9
          OnEnter = Id3UPriceFEnter
          OnExit = Id1CCFExit
          TextId = 0
          ViaSBtn = False
        end
        object Id3VATF: TSBSComboBox
          Tag = 1
          Left = 241
          Top = 59
          Width = 41
          Height = 22
          HelpContext = 249
          Style = csDropDownList
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ItemHeight = 14
          MaxLength = 1
          ParentFont = False
          TabOrder = 8
          OnClick = Id3VATFClick
          OnDropDown = Id3VATFDropDown
          OnEnter = Id3VATFEnter
          OnExit = Id3VATFExit
          AllowChangeInExit = True
          ExtendedList = True
          MaxListWidth = 75
          ReadOnly = True
          Validate = True
        end
        object Id3NomF: Text8Pt
          Tag = 1
          Left = 241
          Top = 84
          Width = 82
          Height = 22
          HelpContext = 275
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 11
          OnEnter = Id3UPriceFEnter
          OnExit = Id3NomF2Exit
          TextId = 0
          ViaSBtn = False
        end
        object Id3LTF: TSBSComboBox
          Tag = 1
          Left = 241
          Top = 159
          Width = 57
          Height = 22
          HelpContext = 276
          Style = csDropDownList
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ItemHeight = 14
          MaxLength = 40
          ParentFont = False
          TabOrder = 15
          ExtendedList = True
          MaxListWidth = 75
          ReadOnly = True
          Validate = True
        end
        object GLDescF: Text8Pt
          Left = 191
          Top = 109
          Width = 173
          Height = 22
          HelpContext = 275
          TabStop = False
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ReadOnly = True
          ShowHint = True
          TabOrder = 12
          TextId = 0
          ViaSBtn = False
        end
        object edtMultiBuy: Text8Pt
          Tag = 1
          Left = 58
          Top = 159
          Width = 97
          Height = 22
          HelpContext = 8004
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ShowHint = True
          TabOrder = 4
          OnEnter = edtMultiBuyEnter
          OnExit = edtMultiBuyExit
          TextId = 0
          ViaSBtn = False
        end
        object edtTransDiscount: Text8Pt
          Tag = 1
          Left = 58
          Top = 184
          Width = 97
          Height = 22
          HelpContext = 8005
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ParentShowHint = False
          ShowHint = True
          TabOrder = 5
          OnEnter = edtTransDiscountEnter
          OnExit = edtMultiBuyExit
          TextId = 0
          ViaSBtn = False
        end
        object Id3DiscF: Text8Pt
          Tag = 1
          Left = 58
          Top = 84
          Width = 97
          Height = 22
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 13
          ParentFont = False
          ParentShowHint = False
          ShowHint = True
          TabOrder = 3
          OnEnter = Id3DiscFoldEnter
          OnExit = Id3DiscFoldExit
          TextId = 0
          ViaSBtn = False
        end
        object Id3DelF: TEditDate
          Tag = 1
          Left = 241
          Top = 184
          Width = 77
          Height = 22
          HelpContext = 273
          AutoSelect = False
          Color = clWhite
          EditMask = '00/00/0000;0;'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 10
          ParentFont = False
          ReadOnly = True
          TabOrder = 16
          OnEnter = Id3DelFDeleteEnter
          OnExit = Id3DelFDeleteExit
          Placement = cpAbove
        end
        object Id3CostF: TCurrencyEdit
          Tag = 1
          Left = 241
          Top = 134
          Width = 123
          Height = 22
          HelpContext = 277
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 13
          WantReturns = False
          WordWrap = False
          OnEnter = Id3CostFDeleteMeEnter
          OnExit = Id3CostFDeleteMeExit
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object Id3LTotF: TCurrencyEdit
          Tag = 2
          Left = 58
          Top = 109
          Width = 97
          Height = 22
          HelpContext = 248
          TabStop = False
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          Lines.Strings = (
            '0.67-')
          ParentFont = False
          ReadOnly = True
          TabOrder = 14
          WantReturns = False
          WordWrap = False
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object Id3PQtyF: TCurrencyEdit
          Tag = 1
          Left = 58
          Top = 9
          Width = 76
          Height = 22
          HelpContext = 267
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          MaxLength = 13
          ParentFont = False
          ReadOnly = True
          TabOrder = 0
          WantReturns = False
          WordWrap = False
          OnEnter = Id3PQtyFEnter
          OnExit = Id3PQtyFExit
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object Id3QtyF: TCurrencyEdit
          Tag = 1
          Left = 58
          Top = 34
          Width = 76
          Height = 22
          HelpContext = 247
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          MaxLength = 13
          ParentFont = False
          ReadOnly = True
          TabOrder = 1
          WantReturns = False
          WordWrap = False
          OnEnter = Id3PQtyFEnter
          OnExit = Id3PQtyFExit
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
        object Id3UPriceF: TCurrencyEdit
          Tag = 1
          Left = 58
          Top = 59
          Width = 97
          Height = 22
          HelpContext = 268
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          Lines.Strings = (
            '0.67-')
          MaxLength = 13
          ParentFont = False
          ReadOnly = True
          TabOrder = 2
          WantReturns = False
          WordWrap = False
          OnEnter = Id3UPriceFEnter
          OnExit = Id3UPriceFExit
          AutoSize = False
          BlockNegative = False
          BlankOnZero = False
          DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
          ShowCurrency = False
          TextId = 0
          Value = -0.666666
        end
      end
      object LUD1F: Text8Pt
        Tag = 1
        Left = 60
        Top = 332
        Width = 150
        Height = 22
        HelpContext = 283
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 8
        OnExit = LUD1FExit
        TextId = 0
        ViaSBtn = False
        OnEntHookEvent = LUD1FEntHookEvent
      end
      object LUD2F: Text8Pt
        Tag = 1
        Left = 60
        Top = 357
        Width = 150
        Height = 22
        HelpContext = 283
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 9
        OnExit = LUD1FExit
        TextId = 0
        ViaSBtn = False
        OnEntHookEvent = LUD1FEntHookEvent
      end
      object LUD3F: Text8Pt
        Tag = 1
        Left = 274
        Top = 332
        Width = 150
        Height = 22
        HelpContext = 283
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 10
        OnExit = LUD1FExit
        TextId = 0
        ViaSBtn = False
        OnEntHookEvent = LUD1FEntHookEvent
      end
      object LUD4F: Text8Pt
        Tag = 1
        Left = 274
        Top = 357
        Width = 150
        Height = 22
        HelpContext = 283
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 11
        OnExit = LUD1FExit
        TextId = 0
        ViaSBtn = False
        OnEntHookEvent = LUD1FEntHookEvent
      end
      object edtUdf5: Text8Pt
        Tag = 1
        Left = 60
        Top = 394
        Width = 150
        Height = 22
        HelpContext = 283
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 12
        OnExit = LUD1FExit
        TextId = 0
        ViaSBtn = False
        OnEntHookEvent = LUD1FEntHookEvent
      end
      object edtUdf6: Text8Pt
        Tag = 1
        Left = 60
        Top = 420
        Width = 150
        Height = 22
        HelpContext = 283
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 13
        OnExit = LUD1FExit
        TextId = 0
        ViaSBtn = False
        OnEntHookEvent = LUD1FEntHookEvent
      end
      object edtUdf7: Text8Pt
        Tag = 1
        Left = 60
        Top = 446
        Width = 150
        Height = 22
        HelpContext = 283
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 14
        OnExit = LUD1FExit
        TextId = 0
        ViaSBtn = False
        OnEntHookEvent = LUD1FEntHookEvent
      end
      object edtUdf10: Text8Pt
        Tag = 1
        Left = 274
        Top = 446
        Width = 150
        Height = 22
        HelpContext = 283
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 17
        OnExit = LUD1FExit
        TextId = 0
        ViaSBtn = False
        OnEntHookEvent = LUD1FEntHookEvent
      end
      object edtUdf9: Text8Pt
        Tag = 1
        Left = 274
        Top = 420
        Width = 150
        Height = 22
        HelpContext = 283
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 16
        OnExit = LUD1FExit
        TextId = 0
        ViaSBtn = False
        OnEntHookEvent = LUD1FEntHookEvent
      end
      object edtUdf8: Text8Pt
        Tag = 1
        Left = 274
        Top = 394
        Width = 150
        Height = 22
        HelpContext = 283
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        MaxLength = 30
        ParentFont = False
        ParentShowHint = False
        ReadOnly = True
        ShowHint = True
        TabOrder = 15
        OnExit = LUD1FExit
        TextId = 0
        ViaSBtn = False
        OnEntHookEvent = LUD1FEntHookEvent
      end
    end
    object DE4Page: TTabSheet
      HelpContext = 494
      Caption = 'Qty/Pick'
      object SBSPanel7: TSBSPanel
        Left = 254
        Top = 4
        Width = 351
        Height = 61
        Caption = 'Total Quantities To Date'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        AllowReSize = False
        IsGroupBox = True
        TextId = 0
        object Label831: Label8
          Left = 42
          Top = 18
          Width = 43
          Height = 14
          Caption = ' Ordered'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label833: Label8
          Left = 125
          Top = 18
          Width = 45
          Height = 14
          Caption = 'Delivered'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label834: Label8
          Left = 200
          Top = 18
          Width = 55
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Written Off'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object Label835: Label8
          Left = 282
          Top = 18
          Width = 58
          Height = 14
          Caption = 'Outstanding'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object SBSPanel8: TSBSPanel
        Left = 284
        Top = 75
        Width = 321
        Height = 51
        Caption = 'Pick/Write Off - This Time'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        AllowReSize = False
        IsGroupBox = True
        TextId = 0
        object Label836: Label8
          Left = 183
          Top = 28
          Width = 47
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Write Off'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
        object PickLab: Label8
          Left = 18
          Top = 27
          Width = 41
          Height = 14
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Pick'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          TextId = 0
        end
      end
      object Id4QOF: TCurrencyEdit
        Tag = 2
        Left = 263
        Top = 36
        Width = 80
        Height = 22
        HelpContext = 479
        TabStop = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id4QDF: TCurrencyEdit
        Tag = 2
        Left = 348
        Top = 36
        Width = 80
        Height = 22
        HelpContext = 479
        TabStop = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 3
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id4QWF: TCurrencyEdit
        Tag = 2
        Left = 433
        Top = 36
        Width = 80
        Height = 22
        HelpContext = 479
        TabStop = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 4
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id4QOSF: TCurrencyEdit
        Tag = 2
        Left = 518
        Top = 36
        Width = 80
        Height = 22
        HelpContext = 479
        TabStop = False
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        ParentFont = False
        ReadOnly = True
        TabOrder = 5
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object ID4QPTF: TCurrencyEdit
        Tag = 1
        Left = 348
        Top = 98
        Width = 80
        Height = 22
        HelpContext = 480
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        MaxLength = 13
        ParentFont = False
        ReadOnly = True
        TabOrder = 6
        WantReturns = False
        WordWrap = False
        OnEnter = ID4QPTFEnter
        OnExit = ID4QPTFExit
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
      object Id4QWTF: TCurrencyEdit
        Tag = 1
        Left = 518
        Top = 98
        Width = 80
        Height = 22
        HelpContext = 480
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Lines.Strings = (
          '0.67-')
        MaxLength = 13
        ParentFont = False
        ReadOnly = True
        TabOrder = 7
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = -0.666666
      end
    end
    object IntrastatPage: TTabSheet
      Caption = 'Intrastat'
      ImageIndex = 4
      object lblIntrastatInstructions: TLabel
        Left = 8
        Top = 8
        Width = 575
        Height = 14
        Caption = 
          'Use this section to override the Default Intrastat Settings take' +
          'n from the Transaction Header, Trader, and Stock records.'
      end
      object lblCommodityCode: TLabel
        Left = 32
        Top = 54
        Width = 112
        Height = 14
        Alignment = taRightJustify
        Caption = 'Commodity/TARIC Code'
      end
      object lblStockUnits: TLabel
        Left = 34
        Top = 79
        Width = 110
        Height = 14
        Alignment = taRightJustify
        Caption = 'Stock Units in SSD Unit'
      end
      object lblLineUnitWeight: TLabel
        Left = 43
        Top = 103
        Width = 101
        Height = 14
        Alignment = taRightJustify
        Caption = 'Line Unit Weight (Kg)'
      end
      object lblGoodsToCountry: TLabel
        Left = 59
        Top = 128
        Width = 85
        Height = 14
        Alignment = taRightJustify
        Caption = 'Goods to Country'
      end
      object lblNoTc: TLabel
        Left = 120
        Top = 180
        Width = 24
        Height = 14
        Alignment = taRightJustify
        Caption = 'NoTc'
      end
      object lblSSDUplift: TLabel
        Left = 96
        Top = 206
        Width = 48
        Height = 14
        Alignment = taRightJustify
        Caption = 'SSD Uplift'
      end
      object chkOverrideIntrastat: TCheckBox
        Left = 8
        Top = 28
        Width = 209
        Height = 17
        Caption = 'Override Intrastat Settings on this Line'
        TabOrder = 0
        OnClick = chkOverrideIntrastatClick
      end
      object edtStockUnits: TCurrencyEdit
        Left = 152
        Top = 76
        Width = 61
        Height = 21
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'ARIAL'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        ParentFont = False
        TabOrder = 2
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object edtLineUnitWeight: TCurrencyEdit
        Left = 152
        Top = 100
        Width = 61
        Height = 21
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'ARIAL'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        ParentFont = False
        TabOrder = 3
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object chkCountry: TRadioButton
        Left = 152
        Top = 128
        Width = 61
        Height = 17
        Caption = 'Country'
        Checked = True
        TabOrder = 4
        TabStop = True
        OnClick = chkCountryClick
      end
      object chkQRCode: TRadioButton
        Left = 152
        Top = 152
        Width = 425
        Height = 17
        Caption = 
          'Special Code QR - Consumable Goods Delivered to Vessel / Aircraf' +
          't'
        TabOrder = 6
        OnClick = chkQRCodeClick
      end
      object edtSSDUplift: TCurrencyEdit
        Left = 152
        Top = 202
        Width = 61
        Height = 21
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'ARIAL'
        Font.Style = []
        Lines.Strings = (
          '0.00 ')
        ParentFont = False
        TabOrder = 8
        WantReturns = False
        WordWrap = False
        AutoSize = False
        BlockNegative = False
        BlankOnZero = False
        DisplayFormat = '###,###,##0.00 ;###,###,##0.00-'
        ShowCurrency = False
        TextId = 0
        Value = 1E-10
      end
      object cbIntrastatCountry: TSBSComboBox
        Left = 216
        Top = 124
        Width = 281
        Height = 22
        Style = csDropDownList
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        ParentFont = False
        TabOrder = 5
        MaxListWidth = 0
      end
      object cbNoTc: TSBSComboBox
        Left = 152
        Top = 176
        Width = 345
        Height = 22
        Style = csDropDownList
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 14
        ParentFont = False
        TabOrder = 7
        MaxListWidth = 0
      end
      object edtCommodityCode: TMaskEdit
        Left = 152
        Top = 51
        Width = 78
        Height = 22
        EditMask = '9999999999;1; '
        MaxLength = 10
        TabOrder = 1
        Text = '          '
      end
    end
  end
end
