object ContactEditorFrm: TContactEditorFrm
  Left = 695
  Top = 283
  HelpContext = 8101
  BorderStyle = bsDialog
  Caption = 'Role Editor'
  ClientHeight = 357
  ClientWidth = 574
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poMainFormCenter
  Scaled = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 14
  object Label1: TLabel
    Left = 46
    Top = 11
    Width = 27
    Height = 14
    Alignment = taRightJustify
    Caption = 'Name'
  end
  object Label2: TLabel
    Left = 34
    Top = 35
    Width = 39
    Height = 14
    Alignment = taRightJustify
    Caption = 'Job Title'
  end
  object Label3: TLabel
    Left = 24
    Top = 59
    Width = 49
    Height = 14
    Alignment = taRightJustify
    Caption = 'Telephone'
  end
  object Label4: TLabel
    Left = 55
    Top = 83
    Width = 18
    Height = 14
    Alignment = taRightJustify
    Caption = 'Fax'
  end
  object Label5: TLabel
    Left = 6
    Top = 107
    Width = 68
    Height = 14
    Alignment = taRightJustify
    Caption = 'Email Address'
  end
  object Label6: TLabel
    Left = 368
    Top = 8
    Width = 27
    Height = 14
    Caption = 'Roles'
  end
  object pnlOwnAddress: TPanel
    Left = 8
    Top = 152
    Width = 355
    Height = 177
    BevelOuter = bvNone
    Enabled = False
    TabOrder = 1
    object lblAddress1: TLabel
      Left = 2
      Top = 11
      Width = 63
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Line 1'
      Enabled = False
    end
    object lblPostCode: TLabel
      Left = 16
      Top = 131
      Width = 49
      Height = 14
      Alignment = taRightJustify
      Caption = 'Post Code'
      Enabled = False
    end
    object lblCountry: TLabel
      Left = 27
      Top = 156
      Width = 38
      Height = 14
      Alignment = taRightJustify
      Caption = 'Country'
      Enabled = False
    end
    object lblAddress2: TLabel
      Left = 2
      Top = 35
      Width = 63
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Line 2'
      Enabled = False
    end
    object lblAddress3: TLabel
      Left = 2
      Top = 59
      Width = 63
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Line 3'
      Enabled = False
    end
    object lblAddress4: TLabel
      Left = 2
      Top = 83
      Width = 63
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'Town'
      Enabled = False
    end
    object lblAddress5: TLabel
      Left = 2
      Top = 107
      Width = 63
      Height = 14
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'County'
      Enabled = False
    end
    object lstCountry: TSBSComboBox
      Tag = 1
      Left = 72
      Top = 152
      Width = 279
      Height = 22
      HelpContext = 111
      Style = csDropDownList
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clNavy
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ItemHeight = 14
      MaxLength = 3
      ParentFont = False
      TabOrder = 0
      ExtendedList = True
      MaxListWidth = 220
      Validate = True
    end
    object edtContactAddr1: Text8Pt
      Left = 72
      Top = 8
      Width = 279
      Height = 22
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 1
      TextId = 0
      ViaSBtn = False
      GDPREnabled = True
    end
    object edtContactAddr2: Text8Pt
      Left = 72
      Top = 32
      Width = 279
      Height = 22
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 2
      TextId = 0
      ViaSBtn = False
      GDPREnabled = True
    end
    object edtContactAddr3: Text8Pt
      Left = 72
      Top = 56
      Width = 279
      Height = 22
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 3
      TextId = 0
      ViaSBtn = False
      GDPREnabled = True
    end
    object edtContactAddr4: Text8Pt
      Left = 72
      Top = 80
      Width = 279
      Height = 22
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 4
      TextId = 0
      ViaSBtn = False
      GDPREnabled = True
    end
    object edtContactAddr5: Text8Pt
      Left = 72
      Top = 104
      Width = 279
      Height = 22
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 30
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 5
      TextId = 0
      ViaSBtn = False
      GDPREnabled = True
    end
    object edtContactPostCode: Text8Pt
      Left = 72
      Top = 128
      Width = 145
      Height = 22
      Enabled = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      MaxLength = 20
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 6
      TextId = 0
      ViaSBtn = False
      GDPREnabled = True
    end
  end
  object btnCancel: TButton
    Left = 486
    Top = 332
    Width = 80
    Height = 21
    Cancel = True
    Caption = 'Cancel'
    TabOrder = 4
    OnClick = btnCancelClick
  end
  object btnOk: TButton
    Left = 396
    Top = 332
    Width = 80
    Height = 21
    Caption = 'OK'
    TabOrder = 3
    OnClick = btnOkClick
  end
  object chkHasOwnAddress: TCheckBox
    Left = 8
    Top = 136
    Width = 145
    Height = 17
    Caption = 'Contact has own address'
    TabOrder = 0
    OnClick = chkHasOwnAddressClick
  end
  object rolesList: TCheckListBox
    Left = 366
    Top = 24
    Width = 201
    Height = 302
    BevelInner = bvLowered
    BevelOuter = bvNone
    ItemHeight = 14
    TabOrder = 2
    OnDblClick = rolesListDblClick
  end
  object edtContactName: Text8Pt
    Left = 80
    Top = 8
    Width = 279
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 45
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 5
    TextId = 0
    ViaSBtn = False
    GDPREnabled = True
  end
  object edtContactJobTitle: Text8Pt
    Left = 80
    Top = 32
    Width = 279
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 6
    TextId = 0
    ViaSBtn = False
    GDPREnabled = True
  end
  object edtContactTelephone: Text8Pt
    Left = 80
    Top = 56
    Width = 279
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 7
    TextId = 0
    ViaSBtn = False
    GDPREnabled = True
  end
  object edtContactFax: Text8Pt
    Left = 80
    Top = 80
    Width = 279
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 30
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 8
    TextId = 0
    ViaSBtn = False
    GDPREnabled = True
  end
  object edtContactEmail: Text8Pt
    Left = 80
    Top = 104
    Width = 279
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 100
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    TabOrder = 9
    TextId = 0
    ViaSBtn = False
    GDPREnabled = True
  end
  object EnterToTab1: TEnterToTab
    ConvertEnters = True
    OverrideFont = True
    Version = 'TEnterToTab v1.02 for Delphi 6.01'
    Left = 330
    Top = 129
  end
end
