object fNomLine: TfNomLine
  Left = 0
  Top = 0
  Width = 603
  Height = 23
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  ParentFont = False
  PopupMenu = pmLine
  TabOrder = 0
  object Shape1: TShape
    Left = 3
    Top = 22
    Width = 114
    Height = 1
    Pen.Color = clGray
  end
  object Shape2: TShape
    Left = 122
    Top = 22
    Width = 63
    Height = 1
    Pen.Color = clGray
  end
  object _CC: TShape
    Left = 190
    Top = 22
    Width = 43
    Height = 1
    Pen.Color = clGray
  end
  object _Dept: TShape
    Left = 238
    Top = 22
    Width = 43
    Height = 1
    Pen.Color = clGray
  end
  object Shape5: TShape
    Left = 457
    Top = 22
    Width = 70
    Height = 1
    Pen.Color = clGray
  end
  object Shape6: TShape
    Left = 286
    Top = 22
    Width = 70
    Height = 1
    Pen.Color = clGray
  end
  object lGrossAmount: TLabel
    Left = 580
    Top = 3
    Width = 21
    Height = 14
    Alignment = taRightJustify
    Caption = '0.00'
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlue
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    PopupMenu = pmLine
  end
  object edDesc: TEdit
    Tag = 1
    Left = 3
    Top = 3
    Width = 114
    Height = 18
    HelpContext = 2060
    BorderStyle = bsNone
    Color = clWhite
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 55
    ParentFont = False
    PopupMenu = pmLine
    TabOrder = 0
    OnEnter = EditEnter
  end
  object edGLCode: TEdit
    Tag = 2
    Left = 122
    Top = 3
    Width = 63
    Height = 18
    HelpContext = 2061
    BorderStyle = bsNone
    Color = clWhite
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    PopupMenu = pmLine
    ShowHint = True
    TabOrder = 1
    OnEnter = EditEnter
    OnExit = edGLCodeExit
  end
  object edCC: TEdit
    Tag = 3
    Left = 190
    Top = 3
    Width = 43
    Height = 18
    HelpContext = 2062
    BorderStyle = bsNone
    Color = clWhite
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    PopupMenu = pmLine
    ShowHint = True
    TabOrder = 2
    OnEnter = edCCEnter
    OnExit = edFieldExit
  end
  object edDept: TEdit
    Tag = 4
    Left = 238
    Top = 3
    Width = 43
    Height = 18
    HelpContext = 2063
    BorderStyle = bsNone
    Color = clWhite
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    PopupMenu = pmLine
    ShowHint = True
    TabOrder = 3
    OnEnter = edDeptEnter
    OnExit = edFieldExit
  end
  object cmbVATCode: TComboBox
    Tag = 6
    Left = 361
    Top = 0
    Width = 91
    Height = 22
    HelpContext = 2065
    BevelInner = bvNone
    BevelOuter = bvNone
    Style = csDropDownList
    Color = clWhite
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    ItemHeight = 14
    ParentFont = False
    PopupMenu = pmLine
    TabOrder = 5
    OnChange = AmountChanged
    OnEnter = EditEnter
    OnExit = cmbVATCodeExit
  end
  object edNetAmount: TNumEdit
    Tag = 5
    Left = 286
    Top = 3
    Width = 70
    Height = 18
    HelpContext = 2064
    AutoSize = False
    BevelInner = bvNone
    BevelOuter = bvNone
    BorderStyle = bsNone
    Color = clWhite
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 15
    ParentFont = False
    PopupMenu = pmLine
    TabOrder = 4
    Text = '0'
    OnChange = edNetAmountChange
    OnEnter = EditEnter
    OnExit = edFieldExit
    EditAlignment = alRight
    PermitNegatives = False
    PermitDecimals = True
    DecimalPlaces = 2
  end
  object edVATAmount: TNumEdit
    Tag = 7
    Left = 457
    Top = 3
    Width = 70
    Height = 18
    HelpContext = 2066
    AutoSize = False
    BevelInner = bvNone
    BevelOuter = bvNone
    BorderStyle = bsNone
    Color = clWhite
    Enabled = False
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 15
    ParentFont = False
    PopupMenu = pmLine
    TabOrder = 6
    Text = '0'
    OnChange = AmountChanged
    OnEnter = EditEnter
    EditAlignment = alRight
    PermitNegatives = False
    PermitDecimals = True
    DecimalPlaces = 2
  end
  object pmLine: TPopupMenu
    OnPopup = pmLinePopup
    Left = 528
    object Undo1: TMenuItem
      Caption = 'Undo'
      OnClick = Undo1Click
    end
    object N2: TMenuItem
      Caption = '-'
    end
    object Cut1: TMenuItem
      Caption = 'Cut'
      OnClick = Cut1Click
    end
    object Copy1: TMenuItem
      Caption = 'Copy'
      OnClick = Copy1Click
    end
    object Paste1: TMenuItem
      Caption = 'Paste'
      OnClick = Paste1Click
    end
    object Delete1: TMenuItem
      Caption = 'Delete'
      OnClick = Delete1Click
    end
    object N1: TMenuItem
      Caption = '-'
    end
    object DeleteLine1: TMenuItem
      Caption = 'Delete Line'
      OnClick = DeleteLine1Click
    end
  end
end
