object frmedDealers: TfrmedDealers
  Left = 0
  Top = 0
  Width = 586
  Height = 582
  Background.Fixed = False
  HandleTabs = False
  SupportedBrowsers = [brIE, brNetscape6]
  DesignLeft = 287
  DesignTop = 70
  object cbParent: TIWComboBox
    Left = 144
    Top = 80
    Width = 226
    Height = 21
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ItemsHaveValues = False
    NoSelectionText = ' '
    RequireSelection = True
    ScriptEvents = <>
    UseSize = True
    DoSubmitValidation = True
    Editable = True
    TabOrder = 0
    ItemIndex = -1
    Sorted = True
  end
  object lblParent: TIWLabel
    Left = 24
    Top = 84
    Width = 46
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Parent:'
  end
  object cbDealerType: TIWComboBox
    Left = 144
    Top = 138
    Width = 226
    Height = 21
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ItemsHaveValues = False
    NoSelectionText = ' '
    RequireSelection = True
    ScriptEvents = <>
    OnChange = edFilterDealerSubmit
    UseSize = True
    DoSubmitValidation = True
    Editable = True
    TabOrder = 1
    ItemIndex = 0
    Items.Strings = (
      'Dealer'
      'Distributor')
    Sorted = True
  end
  object lblDealerType: TIWLabel
    Left = 24
    Top = 142
    Width = 114
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Dealership Type:'
  end
  object cbSuspended: TIWCheckBox
    Left = 144
    Top = 387
    Width = 105
    Height = 21
    ZIndex = 0
    Caption = 'Suspended'
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    DoSubmitValidation = True
    Style = stNormal
    TabOrder = 2
    Checked = False
  end
  object bnSaveChanges: TIWButton
    Left = 144
    Top = 425
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Save Changes'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 3
    OnClick = bnSaveChangesClick
  end
  object bnReturnAdmin: TIWButton
    Left = 144
    Top = 466
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Return to Admin'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 4
    OnClick = bnReturnAdminClick
  end
  object bnReturnMain: TIWButton
    Left = 260
    Top = 466
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Return to Main'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 5
    OnClick = bnReturnMainClick
  end
  object edDealerName: TIWEdit
    Left = 144
    Top = 52
    Width = 241
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edDealerName'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 6
    PasswordPrompt = False
  end
  object lblDealerName: TIWLabel
    Left = 24
    Top = 56
    Width = 92
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Dealer Name:'
  end
  object lblhdrDealers: TIWLabel
    Left = 20
    Top = 16
    Width = 60
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = [fsBold]
    Caption = 'Dealers'
  end
  object bnCancel: TIWButton
    Left = 260
    Top = 425
    Width = 109
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Cancel'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 7
    OnClick = bnCancelClick
  end
  object memoDealer: TIWMemo
    Left = 25
    Top = 223
    Width = 287
    Height = 154
    ZIndex = 0
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    RawText = False
    ReadOnly = False
    Required = False
    TabOrder = 8
    WantReturns = False
    FriendlyName = 'IWMemo1'
  end
  object lblDealerNotes: TIWLabel
    Left = 24
    Top = 203
    Width = 91
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Dealer Notes:'
  end
  object edEmail: TIWEdit
    Left = 144
    Top = 166
    Width = 241
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edDealerName'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 9
    PasswordPrompt = False
  end
  object lblEmail: TIWLabel
    Left = 24
    Top = 170
    Width = 89
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Dealer Email:'
  end
  object cbActive: TIWCheckBox
    Left = 260
    Top = 387
    Width = 105
    Height = 21
    ZIndex = 0
    Caption = 'Active'
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    DoSubmitValidation = True
    Style = stNormal
    TabOrder = 10
    Checked = True
  end
  object bnFilterDealer: TIWButton
    Left = 430
    Top = 78
    Width = 55
    Height = 25
    ZIndex = 0
    ButtonType = btButton
    Caption = 'Filter'
    Color = clBtnFace
    DoSubmitValidation = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    TabOrder = 11
    OnClick = edFilterDealerSubmit
  end
  object edFilterDealer: TIWEdit
    Left = 376
    Top = 80
    Width = 32
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edDealerName'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 12
    OnSubmit = edFilterDealerSubmit
    PasswordPrompt = False
  end
  object cbContainsDealer: TIWCheckBox
    Left = 490
    Top = 82
    Width = 85
    Height = 21
    ZIndex = 0
    Caption = 'Contains'
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    ScriptEvents = <>
    DoSubmitValidation = True
    Style = stNormal
    TabOrder = 13
    Checked = False
  end
  object lblDealerCode: TIWLabel
    Left = 25
    Top = 112
    Width = 88
    Height = 16
    ZIndex = 0
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    Caption = 'Dealer Code:'
  end
  object edDealerCode: TIWEdit
    Left = 144
    Top = 108
    Width = 241
    Height = 21
    ZIndex = 0
    BGColor = clNone
    DoSubmitValidation = True
    Editable = True
    Font.Color = clNone
    Font.Enabled = True
    Font.Size = 10
    Font.Style = []
    FriendlyName = 'edDealerCode'
    MaxLength = 0
    ReadOnly = False
    Required = False
    ScriptEvents = <>
    TabOrder = 14
    PasswordPrompt = False
  end
end
