object frmBase: TfrmBase
  Left = 485
  Top = 363
  BorderStyle = bsSingle
  BorderWidth = 2
  ClientHeight = 313
  ClientWidth = 475
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 14
  object AdvPg: TAdvToolBarPager
    Left = 0
    Top = 0
    Width = 475
    Height = 28
    CanMove = True
    Caption.Indent = 5
    CaptionButtons = []
    TabGroups = <>
    TabSettings.EndMargin = 0
    PageLeftMargin = 0
    PageRightMargin = 0
    TabOrder = 0
  end
end
