object fCode: TfCode
  Left = 0
  Top = 0
  Width = 423
  Height = 38
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  ParentFont = False
  TabOrder = 0
  object lName: TLabel
    Left = 64
    Top = 12
    Width = 29
    Height = 14
    Alignment = taRightJustify
    Caption = 'lName'
  end
  object Shape1: TShape
    Left = 8
    Top = 37
    Width = 409
    Height = 1
    Pen.Color = clSilver
  end
  object edCode1: TCurrencyEdit
    Left = 104
    Top = 8
    Width = 33
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    MaxLength = 3
    ParentFont = False
    TabOrder = 0
    WantReturns = False
    WordWrap = False
    OnExit = edCodeExit
    AutoSize = False
    BlankOnZero = False
    DisplayFormat = '###'
    ShowCurrency = False
    TextId = 0
  end
  object edCode2: TCurrencyEdit
    Left = 144
    Top = 8
    Width = 33
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    MaxLength = 3
    ParentFont = False
    TabOrder = 1
    WantReturns = False
    WordWrap = False
    OnExit = edCodeExit
    AutoSize = False
    BlankOnZero = False
    DisplayFormat = '###'
    ShowCurrency = False
    TextId = 0
  end
  object edCode3: TCurrencyEdit
    Left = 184
    Top = 8
    Width = 33
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    MaxLength = 3
    ParentFont = False
    TabOrder = 2
    WantReturns = False
    WordWrap = False
    OnExit = edCodeExit
    AutoSize = False
    BlankOnZero = False
    DisplayFormat = '###'
    ShowCurrency = False
    TextId = 0
  end
  object edCode4: TCurrencyEdit
    Left = 224
    Top = 8
    Width = 33
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    MaxLength = 3
    ParentFont = False
    TabOrder = 3
    WantReturns = False
    WordWrap = False
    OnExit = edCodeExit
    AutoSize = False
    BlankOnZero = False
    DisplayFormat = '###'
    ShowCurrency = False
    TextId = 0
  end
  object edCode5: TCurrencyEdit
    Left = 264
    Top = 8
    Width = 33
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    MaxLength = 3
    ParentFont = False
    TabOrder = 4
    WantReturns = False
    WordWrap = False
    OnExit = edCodeExit
    AutoSize = False
    BlankOnZero = False
    DisplayFormat = '###'
    ShowCurrency = False
    TextId = 0
  end
  object edCode6: TCurrencyEdit
    Left = 304
    Top = 8
    Width = 33
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    MaxLength = 3
    ParentFont = False
    TabOrder = 5
    WantReturns = False
    WordWrap = False
    OnExit = edCodeExit
    AutoSize = False
    BlankOnZero = False
    DisplayFormat = '###'
    ShowCurrency = False
    TextId = 0
  end
  object edCode7: TCurrencyEdit
    Left = 344
    Top = 8
    Width = 33
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    MaxLength = 3
    ParentFont = False
    TabOrder = 6
    WantReturns = False
    WordWrap = False
    OnExit = edCodeExit
    AutoSize = False
    BlankOnZero = False
    DisplayFormat = '###'
    ShowCurrency = False
    TextId = 0
  end
  object edCode8: TCurrencyEdit
    Left = 384
    Top = 8
    Width = 33
    Height = 22
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'ARIAL'
    Font.Style = []
    MaxLength = 3
    ParentFont = False
    TabOrder = 7
    WantReturns = False
    WordWrap = False
    OnExit = edCodeExit
    AutoSize = False
    BlankOnZero = False
    DisplayFormat = '###'
    ShowCurrency = False
    TextId = 0
  end
end
