@echo off

del e:\develop\entrprse\*.dcu > NUL
del x:\entrprse\custom\*.dcu > NUL
del x:\entrprse\custom\dummy\*.dcu > NUL
del x:\entrprse\custom\standard\*.dcu > NUL
del x:\entrprse\custom\vathook\*.dcu > NUL
del x:\entrprse\formdes2\*.dcu > NUL
del x:\entrprse\multcomp\*.dcu > NUL
del x:\entrprse\ole\*.dcu > NUL
del "x:\entrprse\r&d\*.dcu" > NUL
del x:\entrprse\repwrt\*.dcu > NUL
del x:\entrprse\register\*.dcu > NUL
del x:\sbslib\win\win32\*.dcu > NUL
del x:\sbslib\win\win32\rprint3\D2\*.dcu > NUL
del x:\sbslib\win\excommon\*.dcu > NUL
